@startuml
!include ../style.puml

Class AnalysePasswordCommand LOGIC_COLOR_T1{
--
+execute(Model model) : CommandResult
 ~ getRequiredAnalysers() : List<Analyser> analysers
}

Class Password MODEL_COLOR_T1
    Interface Analyser MODEL_COLOR {
    ----
    + analyse(List<Password> p) : List<Result> r
    }
together {
    Class DictionaryAnalyser MODEL_COLOR_T1

    Class SimilarityAnalyser MODEL_COLOR_T1

    Class SequenceAnalyser  MODEL_COLOR_T1

    Class StrengthAnalyser  MODEL_COLOR_T1

    Class UniqueAnalyser  MODEL_COLOR_T1

    Class KeyboardAnalyser  MODEL_COLOR_T1
}

Class "{abstract}\nResult" as Result MODEL_COLOR {
# password : Password
# description : ResultOutcome
---
+ {abstract} getGreaterDetail : String
+ toString() : String
}

Class "<<enumeration>>\nResultOutcome" MODEL_COLOR {
      PASS
      FAIL
      WEAK
      MODERATE
      STRONG
    }

together {

    Class DictionaryResult MODEL_COLOR_T1 {
    - matches : List<DictionaryMatch>
    }

    Class SimilarityResult MODEL_COLOR_T1{
    - matches : List<SimilarityMatch>
    }

    Class SequenceResult MODEL_COLOR_T1 {
    - matches : List<SequenceMatch>
    }
    Class StrengthResult MODEL_COLOR_T1

    Class UniqueResult MODEL_COLOR_T1 {
    - matches : List<UniqueMatch>
    }

    Class KeyboardResult MODEL_COLOR_T1 {
    - matches : List<KeyboardMatch>
    }
}


Class AnalysisReport MODEL_COLOR_T1 {
-reportBuilder : StringBuilder
- reports: Hashmap<Analyser, List<Result>>
----
- write(Analyser a,Result r): void
}

AnalysePasswordCommand .> Password : retrieves
AnalysePasswordCommand .down.> Analyser : retrieves

Analyser "*" .right.> "*" Password : analyses
(Analyser, Password) .. Result

KeyboardAnalyser .up.|> Analyser
DictionaryAnalyser .up.|> Analyser
SimilarityAnalyser .up.|> Analyser
UniqueAnalyser .up.|> Analyser
SequenceAnalyser .up.|> Analyser
StrengthAnalyser .up.|> Analyser
UniqueAnalyser -[hidden]up- SimilarityAnalyser
SequenceAnalyser -[hidden]up UniqueAnalyser
StrengthAnalyser -[hidden]up SequenceAnalyser
SimilarityAnalyser -[hidden]up DictionaryAnalyser

Password -[hidden]down-> AnalysisReport : writes
AnalysisReport "1"-left->"*" Result : writes
AnalysisReport "1"-left->"6" Analyser

Result -[hidden]left-> "<<enumeration>>\nResultOutcome"
KeyboardResult  -up-|> Result
DictionaryResult  -up-|> Result
SimilarityResult -up-|> Result
SequenceResult  -up-|> Result
UniqueResult -up-|> Result
StrengthResult  -up-|> Result
SimilarityResult -[hidden]up- SequenceResult
UniqueResult -[hidden]up- DictionaryResult
StrengthResult -[hidden]up- DictionaryResult


show members

skinparam classFontColor #000000
skinparam classAttributeIconSize 0
@enduml
