@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR



package UI.itinerary <<Rectangle>> {
object ":ListView" as DiaryGallery
object ":ListCell" as DiaryGalleryCard
Class HiddenOutside #FFFFFF
}

package Model.itinerary <<Rectangle>> {
object ":Event" as PhotoList
object ":Inventory" as Photo
}


HiddenOutside --> DiaryGallery

DiaryGallery *-down-> "*" DiaryGalleryCard
DiaryGallery -right-> "1" PhotoList
PhotoList -down-> "*" Photo
DiaryGalleryCard -right-> "1" Photo

@enduml
