@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Command <<Rectangle>> {
    Class "{abstract}\nCommand" as Command
    Class UndoCommand
    Class RedoCommand
}

UndoCommand -up-|> Command
RedoCommand -up-|> Command

class Command {
    void execute(model)
}

class RedoCommand {
int numberOfTries
}

@enduml
