@startuml
skinparam classAttributeIconSize 0

interface Model

Model <|.. ModelManager
ModelManager ..> "1" HistoryManager
HistoryManager ..> Model
HistoryManager ..> "2" CommandDeque
CommandDeque o-- "*" Command
Command ..> Model

class HistoryManager {
-CommandDeque executedCommands
-CommandDeque inverselyExecutedCommands
+rollback(Model)
+commit(Model)
}

@enduml