@startuml
skinparam classAttributeIconSize 0

interface Model

ModelManager .up.|> Model
ModelManager .left.> "1" HistoryManager
HistoryManager .up.> Model
HistoryManager .down.> "2" CommandDeque
CommandDeque o-right-> "*" Command
Command .up.> Model

class HistoryManager {
-CommandDeque executedCommands
-CommandDeque inverselyExecutedCommands
+rollback(Model)
+commit(Model)
}

@enduml
