@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0
skinparam classAttributeFontColor #FFFFFFF

Package HistoryManager <<Rectangle>> {
    Class HistoryManager
    Class CommandDeque
}

Interface Model <<interface>>
Class ModelManager
Class "{abstract}\nCommand" as Command

ModelManager .up.|> Model
ModelManager .left.> "1" HistoryManager
HistoryManager .up.> Model
HistoryManager .down.> "2" CommandDeque
CommandDeque o-right-> "*" Command
Command .up.> Model

class HistoryManager {
-executedCommands: CommandDeque
-inverselyExecutedCommands: CommandDeque
+rollback(Model): boolean
+commit(Model): boolean
}

@enduml
