@startuml
!include ../style2.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package FinanceTracker <<Rectangle>> {
    Class FinanceTracker
    Class MonthlyLimit
    Class PurchaseList
    Class InstallmentList
    Class Purchase
    Class PurchaseDescription
    Class PurchaseMoneySpent
    Class LocalDate
    Class Installment
    Class InstallmentDescription
    Class InstallmentMoneyPaid
    Class MonthlyLimit
}

FinanceTracker *--> "1" PurchaseList
FinanceTracker *--> "1" InstallmentList
FinanceTracker *--> "0...1" MonthlyLimit

PurchaseList o--> "*" Purchase
Purchase *-left-> "1" PurchaseDescription
Purchase *--> "1" PurchaseMoneySpent
Purchase *--> "1" LocalDate

InstallmentList o--> "*" Installment
Installment *--> "1" InstallmentDescription
Installment *-right-> "1" InstallmentMoneyPaid

@enduml
