package seedu.moolah.ui.statistics;

import java.util.logging.Logger;

import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;

import seedu.moolah.commons.core.LogsCenter;
import seedu.moolah.ui.panel.Panel;
import seedu.moolah.ui.panel.PanelName;


/**
 * Panel containing the PieChart generated by a statistics command.
 */
public class StatsPanel extends Panel {

    public static final PanelName PANEL_NAME = new PanelName("Statistics");
    private static final String FXML = "StatsPanel.fxml";
    private final Logger logger = LogsCenter.getLogger(StatsPanel.class);

    @FXML
    private StackPane titlePlaceHolder;

    @FXML
    private StackPane statisticsHolder;


    public StatsPanel(Region statistics, String title) {
        super(FXML);

        titlePlaceHolder.setMinHeight(0);
        titlePlaceHolder.getChildren().add(new Label(title));

        statisticsHolder.getChildren().add(statistics);
    }

    //again standardise the notation of category, categorical and total

    //what do I do with methods of the same erasure? Add boolean or should I just rearrange?

    @Override
    public void view() {
        getRoot().setVisible(true);
        getRoot().setDisable(false);
    }

    @Override
    public void hide() {
        getRoot().setVisible(false);
        getRoot().setDisable(true);
    }
}

