@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddTimetableCommandParser" as AddTimetableCommandParser LOGIC_COLOR
participant "a:AddTimetableCommand" as AddTimetableCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":TimetableVisualization" as TimetableVisualization LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addTimetable 1 n/NUSMODS_URL")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addTimetable 1 n/NUSMODS_URL")
activate AddressBookParser

create AddTimetableCommandParser
AddressBookParser -> AddTimetableCommandParser
activate AddTimetableCommandParser

AddTimetableCommandParser --> AddressBookParser
deactivate AddTimetableCommandParser

AddressBookParser -> AddTimetableCommandParser : parse("1 n/NUSMODS_URL")
activate AddTimetableCommandParser

create AddTimetableCommand
AddTimetableCommandParser -> AddTimetableCommand
activate AddTimetableCommand

AddTimetableCommand --> AddTimetableCommandParser : a
deactivate AddTimetableCommand

AddTimetableCommandParser --> AddressBookParser : a
deactivate AddTimetableCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTimetableCommandParser -[hidden]-> AddressBookParser
destroy AddTimetableCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddTimetableCommand : execute()
activate AddTimetableCommand

create TimetableVisualization
AddTimetableCommand -> TimetableVisualization
activate TimetableVisualization

TimetableVisualization --> AddTimetableCommand
deactivate TimetableVisualization

AddTimetableCommand -> TimetableVisualization : visualize()
activate TimetableVisualization

TimetableVisualization --> AddTimetableCommand
deactivate TimetableVisualization
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTimetableCommandParser -[hidden]-> AddressBookParser
destroy TimetableVisualization

AddTimetableCommand -> Model : setPerson()
activate Model

Model --> AddTimetableCommand
deactivate Model

create CommandResult
AddTimetableCommand -> CommandResult
activate CommandResult

CommandResult --> AddTimetableCommand : result
deactivate CommandResult

AddTimetableCommand --> LogicManager : result
deactivate AddTimetableCommand

[<--LogicManager
deactivate LogicManager
@enduml
