@startuml

start

:User executes a findprob command;

if () then ([command is valid])
	:Instantiate a FindCommand with a corresponding predicate;
	:Execute FindCommand;
	:Update UI with filtered problem list;
else ([else])
	:Throw an exception;
	:Update UI to notify the user;
endif

stop

@enduml
