#!/bin/bash

echo -e "\n================ Running pre-push checks ================"

./gradlew clean checkstyleMain checkstyleTest test asciidoctor

# Store the last exit code in a variable
RESULT=$?

if [ $RESULT -eq 0 ]
then
    echo -e "\n================ Pre-push checks: PASSED ================\n"
else
    echo -e "\n================ Pre-push checks: FAILED ================"
fi

# Return exit code to determine if push passes
exit $RESULT
