@startuml
start
:User executes tag command;

if () then ([Valid])
    :Initialise TagCommand;
    if () then ([Some Tag(s) don't exist])
        :Add specified Tag to the set without duplicates;
        if () then ([Transaction is an Expense])
            :Initialise Expense with updated Tag set;
        else ([Transaction is an Income])
            :Initialise Income with updated Tag set;
        endif
        :Replace original in transaction list;
    else ([All Tag(s) already exist])
    :Show warning for duplicates;
    endif
else ([Invalid])
    :ParseException;
endif
stop
@enduml
