@startuml
!include ../style.puml

skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T1
skinparam classBackgroundColor LOGIC_COLOR_T1
skinparam classBorderColor Black
skinparam classFontColor Black
show members

class AliasCommand {
+{static} COMMAND_WORD: String
+{static} MESSAGE_USAGE: String
+{static} MESSAGE_SUCCESS: String
#validate(model: Model)
#execute(model: Model): CommandResult
}

abstract class "{abstract}\nUndoableCommand"

AliasCommand -up-|> "{abstract}\nUndoableCommand"
AliasCommand -right-> "1" Alias: toAdd
AliasCommand ..> Model
AliasCommand ..> UserPrefs
AliasCommand ..> CommandResult
AliasCommand .left.> CommandException: throws

@enduml