@startuml
skinparam linetype ortho

(*) -> "parse input"
if "[begins with command word?]" then
---> [yes] parse as command
    if "[parsed without error]" then
    ---> [yes] "return command"
    -->  (*1)
    else
    --> [no] "throw exception" as error
    endif
else
--> [no] "parse as alias"
    if "[begins with alias?]" then
    --> [yes] "replace alias in input with saved input"
    --> "parse input"
    else
    --> [no] error
    --> (*2)


'
'if (begins with command word?) then (yes)
'    :parse input as command;
'else (no)
'    if (begins with alias) then (yes)
'        :replace alias in user \ninput with saved input;
'
'    else (no)
'        :throw exception;
'
'
'endif
':a;

@enduml
