@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

JsonAdaptedProblemSearchRule .right.> JsonAdaptedNameContainsKeywordsPredicate
JsonAdaptedProblemSearchRule .right.> JsonAdaptedAuthorMatchesKeywordsPredicate
JsonAdaptedProblemSearchRule .right.> JsonAdaptedDescriptionContainsKeywordsPredicate
JsonAdaptedProblemSearchRule .right.> JsonAdaptedSourceMatchesKeywordsPredicate
JsonAdaptedProblemSearchRule .right.> JsonAdaptedDifficultyIsInRangePredicate
JsonAdaptedProblemSearchRule .right.> JsonAdaptedTagIncludesKeywordsPredicate

JsonAdaptedNameContainsKeywordsPredicate -[hidden]down- JsonAdaptedAuthorMatchesKeywordsPredicate
JsonAdaptedAuthorMatchesKeywordsPredicate -[hidden]down- JsonAdaptedDescriptionContainsKeywordsPredicate
JsonAdaptedDescriptionContainsKeywordsPredicate -[hidden]down- JsonAdaptedSourceMatchesKeywordsPredicate
JsonAdaptedSourceMatchesKeywordsPredicate -[hidden]down- JsonAdaptedDifficultyIsInRangePredicate
JsonAdaptedDifficultyIsInRangePredicate -[hidden]down- JsonAdaptedTagIncludesKeywordsPredicate
@enduml
