@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Package Storage <<Rectangle>> {
    Interface Storage <<Interface>>
    Interface UserPrefsStorageComponent <<Interface>>
    Interface HistoryManagerStorageComponent <<Interface>>
    Interface CcaTrackerStorageComponent <<Interface>>
    Interface CoursePlannerStorageComponent <<Interface>>
    Interface FinanceTrackerStorageComponent <<Interface>>
    Interface PlannerStorageComponent <<Interface>>
}

Storage -up-|> UserPrefsStorageComponent
Storage -up-|> HistoryManagerStorageComponent
Storage -up-|> CcaTrackerStorageComponent
Storage -up-|> CoursePlannerStorageComponent
Storage -up-|> FinanceTrackerStorageComponent
Storage -up-|> PlannerStorageComponent

@enduml
