@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include <office/Users/administrator>
!include ../style.puml

Package " "<<Rectangle>>{
    Class GUI UI_COLOR
    Class DiaryParser LOGIC_COLOR
    Class DiaryCommand LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class DiaryModel MODEL_COLOR
    Class Commons LOGIC_COLOR_T2
    Class "Log Center" as Logs UI_COLOR_T1
    Class "Test Driver\nJunit Test" as Test MODEL_COLOR_T4
}

Class "<$user>\nUser" as User MODEL_COLOR_T2
Class "<$administrator>\nDeveloper" as Developer MODEL_COLOR_T2
Class "<$documents>\nJson File" as File UI_COLOR_T1

User -right-> GUI
GUI -right-> DiaryParser
DiaryParser -right-> DiaryCommand
DiaryCommand -down-> DiaryModel
DiaryModel -right-> Storage
DiaryModel -up-> GUI


Storage .up.> Commons
DiaryParser .up.> Commons
GUI .up.> Commons

Logs -right- Commons
Storage .right.>File
Developer <-right-> Test
Test -up-> DiaryModel




@enduml
