@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class PhotoList
class Photo
class LocalDateTime
class Path
class String

Class HiddenOutside #FFFFFF
DiaryEntry -right-> "1 " PhotoList
PhotoList *-down-> "*" Photo

Photo *--> "  1" LocalDateTime : Date Taken <
Photo *---> "          1" Path : Image File Path <
Photo *--> "                                                        1 " String : description <

@enduml
