@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class PhotoList
class Photo
class LocalDateTime
class Path
class String

PhotoList *-down-> "*" Photo

Photo *---> "1" LocalDateTime : date taken <
Photo *---> "1" Path : image file path <
Photo *---> "1" String : description <

@enduml
