@startuml
!include ../style.puml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Parser LOGIC_COLOR
    Class Command #345678
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Commons LOGIC_COLOR_T2
    Class Hidden #FFFFFF
    Class HiddenUI #FFFFFF
    Class HiddenModel #FFFFFF


}
Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1
User --> UI
UI -down-> Parser
Parser -right-> Command
Command -right-> Model
Command ..up..> Commons
Model -right-> Storage


Storage .right.>File
@enduml
