package com.dukeacademy.solution.models;

import java.util.Optional;

/**
 * Represents output generated by programs ran by the application.
 */
public class ProgramOutput {
    private String output;
    private Optional<RuntimeError> error;

    public ProgramOutput() {
        this.output = "";
        this.error = Optional.empty();
    }

    public String getOutput() {
        return this.output;
    }

    public Optional<RuntimeError> getRuntimeError() {
        return this.error;
    }

    public void append(String output) {
        this.output += output;
    }

    public void appendNewLine(String output) {
        this.output += output + "\n";
    }

    public static ProgramOutput getErroredProgramOutput(String errorMessage) {
        ProgramOutput output = new ProgramOutput();
        output.error = Optional.of(new RuntimeError(errorMessage));
        return output;
    }
}
