package com.dukeacademy.solution.models;

/**
 * Represents output generated by programs ran by the application.
 */
public class ProgramOutput {
    private String output;

    public ProgramOutput() {
        this.output = "";
    }

    public String getOutput() {
        return this.output;
    }

    public void append(String output) {
        this.output += output;
    }

    public void appendNewLine(String output) {
        this.output += output + "\n";
    }
}
