package com.dukeacademy.solution.models;

import java.util.Optional;

/**
 * Represents output generated by programs ran by the application.
 */
public class ProgramOutput {
    private String output;
    private RuntimeError error;

    private ProgramOutput() {
        this.output = "";
    }

    private ProgramOutput(String output, RuntimeError error) {
        this.output = output;
    }

    public String getOutput() {
        return this.output;
    }

    public Optional<RuntimeError> getRuntimeError() {
        return Optional.ofNullable(this.error);
    }

    public ProgramOutput append(String output) {
        String newOutput = this.output += output;
        return new ProgramOutput(newOutput, this.error);
    }

    public ProgramOutput append(ProgramOutput output) {
        return this.append(output.getOutput());
    }

    public ProgramOutput appendNewLine(String output) {
        String newOutput = this.output += output + "\n";
        return new ProgramOutput(newOutput, this.error);
    }

    public ProgramOutput appendNewLine(ProgramOutput output) {
        return this.appendNewLine(output.getOutput());
    }

    public static ProgramOutput getEmptyProgramOutput() {
        return new ProgramOutput();
    }

    public static ProgramOutput getErroredProgramOutput(String errorMessage) {
        ProgramOutput output = new ProgramOutput();
        output.error = new RuntimeError(errorMessage);
        return output;
    }
}
