@startuml
hide circle

class UiPart<Region>


class PanelName {
    {static} CURRENT_PANEL: PanelName
}

class PlaceholderPanel {
    messageToDisplay: String
}

class SinglePanelView {
    -panelNameToPanelMap : HashMap<PanelName, Panel>
    -currentPanel : Panel
    viewPanel(PanelName) : void
    getCurrentPanel() : Panel
}

interface PanelManager <<interface>> {
    setPanel(PanelName, Panel) : void
    hasPanel(PanelName) : boolean
    getPanel(PanelName) : Panel
    removePanel(PanelName) : Panel
}

abstract "{abstract}\nPanel" {
    hide() : void
    view() : void
}


PanelManager <|.. SinglePanelView
UiPart <|-- SinglePanelView
UiPart <|-- "{abstract}\nPanel"
"{abstract}\nPanel" <|-- PlaceholderPanel 
SinglePanelView o--> "*" "{abstract}\nPanel"
SinglePanelView o--> "*" PanelName
@enduml