@startuml

!include ../style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package "Transactions List" {
    class transaction1 as "__:Income__" {
        <color:#white>Description: "Bursary"
        <color:#white>Value: 500
        <color:#white>Date: dd/mm/yyyy
        <color:#white>Remark: "Awarded for doing well in school"
    }
    class transaction2 as "__:Expense__" {
        <color:#white>Description: "Laksa"
        <color:#white>Value: 3.50
        <color:#white>Date: dd/mm/yyyy
    }
}

transaction1 -[hidden]left- transaction2
show members
@enduml
