@startuml
start
:User executes add transaction command;

if () then ([Invalid input])
    :Throw ParseException;
else ([Valid input])
    if () then ([Transaction is an Expense])
        :Initialize AddExpenseCommandParser;
        :Initialize Expense;
        :Initialize AddExpenseCommand;
    else ([Transaction is an Income])
        :Initialize AddIncomeCommandParser;
        :Initialize Income;
        :Initialize AddIncomeCommand;
    endif
        :Add to transaction list;
endif
stop
@enduml
