@startuml
start
:User inputs a valid command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([else])
    if () then ([else])
    :System displays error message;
    else ([is Approved Command])
    :Command is Created;
    endif
else ([isLoggedIn])
:Command is Created;
endif
stop
@enduml
