@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":AchievementsLogicManager" as AchievementsLogicManager LOGIC_COLOR
participant ":Supplier" as Supplier LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":StatisticsModelManager" as StatisticsModelManager MODEL_COLOR
end box

box Ui UI_COLOR_T1
participant ":AddressBookCard" as AddressBookCard UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":AddressBookLogicManager" as AddressBookLogicManager LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":AddressBookModelManager" as AddressBookModelManager MODEL_COLOR
end box

[-> AchievementsLogicManager : getStatisticsView()
activate AchievementsLogicManager

AchievementsLogicManager -> Supplier : get()
activate Supplier
create StatisticsModelManager

Supplier -> StatisticsModelManager
activate StatisticsModelManager
return

Supplier -> AchievementsLogicManager : StatisticsModel
deactivate Supplier

AchievementsLogicManager -> StatisticsModelManager : getStatisticsView()
activate StatisticsModelManager

StatisticsModelManager -> AddressBookCard : AddressBookCard.make()
activate AddressBookCard

AddressBookCard -> AddressBookLogicManager : getTotalPersons()
activate AddressBookLogicManager

AddressBookLogicManager -> AddressBookModelManager : getTotalPersons()
activate AddressBookModelManager

AddressBookModelManager -> AddressBookLogicManager : totalPersons
deactivate AddressBookModelManager

AddressBookLogicManager -> AddressBookCard : totalPersons
deactivate AddressBookLogicManager

AddressBookCard -> StatisticsModelManager : addressBookCard
deactivate AddressBookCard

StatisticsModelManager -> AchievementsLogicManager : addressBookCard
deactivate StatisticsModelManager

[<- AchievementsLogicManager : statisticsView
deactivate AchievementsLogicManager

@enduml
