@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class HiddenOutside #FFFFFF

namespace Address {
namespace Model {
namespace Person {
Class Person
}
}
}

namespace Model {
Class ModelManager
Interface Model <<Interface>>{
}
}


namespace Achievements {
namespace Model {
Interface StatisticsModel <<Interface>>
Class StatisticsModelManager
}
}


Interface ObservableList <<Interface>>
Interface Supplier <<Interface>>
HiddenOutside ..> Model.Model

''''''''''MODEL''''''''''
''''''''''Model
Model.ModelManager .up.|> Model.Model
''''''''''Model Interface
Model.Model .down.> Achievements.Model.StatisticsModel :supplies >
Model.Model .right.>Supplier
''''''''''ModelManager Constructor
''' composition or aggregation?
Model.ModelManager ..> "1" Achievements.Model.StatisticsModel


''''''''''ACHIEVEMENTS''''''''''
''''''''''StatisticsModel Interface
Achievements.Model.StatisticsModelManager .up.|> Achievements.Model.StatisticsModel
''''''''''StatisticsModel Manager
Achievements.Model.StatisticsModelManager o--> ObservableList
Achievements.Model.StatisticsModelManager --> "*" Address.Model.Person.Person
''''''''''''''''''''''''''''''''

@enduml
