@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class HiddenOutside #FFFFFF

namespace XYZ {
namespace Model {
Class XYZModel
namespace Util {
Interface XYZStatistics <<Interface>>
}
}
namespace Logic {
Class XYZLogic LOGIC_COLOR
}
}

namespace Achievements {
namespace Model {
Interface StatisticsModel <<Interface>>
Class StatisticsModelManager
}
namespace UI {
class XYZCard UI_COLOR
}
}


Interface ObservableList <<Interface>>


''''''''''ACHIEVEMENTS''''''''''
''''''''''StatisticsModel Interface
Achievements.Model.StatisticsModelManager .up.|> Achievements.Model.StatisticsModel
Achievements.Model.StatisticsModelManager o-down-> "1" XYZ.Model.Util.XYZStatistics

XYZ.Logic.XYZLogic .up.|> XYZ.Model.Util.XYZStatistics



''''''''''StatisticsModel Manager
Achievements.Model.StatisticsModel ..> ObservableList
Achievements.Model.StatisticsModel ..> Node
Achievements.Model.StatisticsModelManager ..> ObservableList
Achievements.Model.StatisticsModelManager ..> Node
Achievements.Model.StatisticsModelManager ..> Achievements.UI.XYZCard
Achievements.UI.XYZCard ..> XYZ.Model.Util.XYZStatistics

XYZ.Logic.XYZLogic o--> XYZ.Model.XYZModel
'Achievements.Model.StatisticsModelManager -->
''''''''''''''''''''''''''''''''

@enduml
