@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CatalogParser" as CatalogParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
'participant ":Book" as Book MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add t/Animal Farm a/George")
activate LogicManager

LogicManager -> CatalogParser : parseCommand("add t/Animal Farm a/George")
activate CatalogParser

create AddCommandParser
CatalogParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> CatalogParser
deactivate AddCommandParser

CatalogParser -> AddCommandParser : parse("t/Animal Farm a/George")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

AddCommandParser --> CatalogParser : a
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> CatalogParser
destroy AddCommandParser

CatalogParser --> LogicManager : a
deactivate CatalogParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : addBook()
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
