@startuml
!include style.puml

!define MODEL_COLOR #BD2032
!define MODEL_COLOR_T1 #F97181
!define MODEL_COLOR_T2 #E41F36
!define MODEL_COLOR_T3 #7B000E
!define MODEL_COLOR_T4 #51000A

!define STORAGE_COLOR #A38300
!define STORAGE_COLOR_T1 #FFE374
!define STORAGE_COLOR_T2 #EDC520
!define STORAGE_COLOR_T3 #806600
!define STORAGE_COLOR_T2 #544400

!define TIMER_COLOR #654321
!define TIMER_COLOR_T1 #D2B48C

!define APPMANAGER_COLOR #00008B
!define APPMANAGER_COLOR_T1 #6495ED

!define PARSERMANAGER_COLOR #A034EB
!define PARSERMANAGER_COLOR_T1 #DFB0FF

!define COMMONS_COLOR #999999
!define COMMONS_COLOR_T1 #CCCCCC

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ParserManager" as ParserManager PARSERMANAGER_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":WordBank" as WordBank MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":StorageManager" as StorageManager STORAGE_COLOR
participant ":JsonWordBankListStorage" as JsonWordBankListStorage STORAGE_COLOR
end box

box Commons COMMONS_COLOR_T1
participant ":JsonUtil" as JsonUtil COMMONS_COLOR
end box

[-> LogicManager : add w/.. m/..
activate LogicManager
LogicManager -> ParserManager : parseCommand("...")

activate ParserManager
ParserManager --> LogicManager : addCommand
deactivate ParserManager

LogicManager -> ModelManager : command.execute(model)
activate ModelManager
ModelManager -> WordBank : hasCard(..)
activate WordBank

WordBank --> ModelManager : false
deactivate WordBank

ModelManager -> WordBank : addCard(..)
note right: Card is added through WordBank's method., so that \ndata is synchronised in Model and UI.
activate WordBank

WordBank --> ModelManager :
deactivate WordBank

ModelManager --> LogicManager : CardCommandResult
deactivate ModelManager

LogicManager -> StorageManager : commandResult.updateStorage(..)
activate StorageManager

StorageManager -> JsonWordBankListStorage : updateWordBank(..)
activate JsonWordBankListStorage

JsonWordBankListStorage -> JsonUtil : saveWordBank(WordBank)
activate JsonUtil

JsonUtil -> JsonUtil : saveJsonFile(..)
JsonUtil --> JsonWordBankListStorage

deactivate JsonUtil

JsonWordBankListStorage --> StorageManager
deactivate JsonWordBankListStorage

StorageManager --> LogicManager
deactivate StorageManager
'ModelManager --> LogicManager
'deactivate ModelManager



[<--LogicManager : CommandResult

@enduml
