@startuml
start
:user enters an add command;
:checks for command validity;
if () then (is valid)
    :checks timestamp field of command;
    if () then (no timestamp inputted)
        :adds expense;
    else (timestamp inputted);
        if () then (timestamp denotes a future date)
            :adds event;
        else (timestamp denotes present or past date);
            :adds expense;
        endif;
    endif;
    :show success message;
else (invalid)
    :show error message;
endif;
stop
@enduml
