@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DukeCooksParser" as DukeCooksParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant ":AddRecordCommandParser" as AddRecordCommandParser LOGIC_COLOR
participant "d:AddRecordCommand" as AddRecordCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add \n health t/glucose * ")
activate LogicManager

LogicManager -> DukeCooksParser : parseCommand("add \n health t/glucose * ")
activate DukeCooksParser

DukeCooksParser -> AddCommandParser : parse("health t/glucose * ")
activate AddCommandParser

AddCommandParser -> AddRecordCommandParser :  parse("t/glucose * ")
activate AddRecordCommandParser

create AddRecordCommand
AddRecordCommandParser -> AddRecordCommand : r
activate AddRecordCommand

AddRecordCommand --> AddRecordCommandParser : d
deactivate AddRecordCommand

AddRecordCommandParser --> AddCommandParser : d
deactivate AddRecordCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddRecordCommandParser -[hidden]-> AddCommandParser
destroy AddRecordCommandParser

AddCommandParser --> DukeCooksParser : d
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> DukeCooksParser
destroy AddCommandParser

DukeCooksParser --> LogicManager : d
deactivate DukeCooksParser

LogicManager -> AddRecordCommand : execute(model)
activate AddRecordCommand

AddRecordCommand -> Model : addRecord(r)
activate Model

Model --> AddRecordCommand
deactivate Model

create CommandResult
AddRecordCommand -> CommandResult
activate CommandResult

CommandResult --> AddRecordCommand
deactivate CommandResult

AddRecordCommand --> LogicManager : result
deactivate AddRecordCommand

[<--LogicManager
deactivate DukeCooksParser
@enduml
