@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR

end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModuleBookParser" as ModuleBookParser LOGIC_COLOR
participant ":LinkCommandParser" as LinkCommandParser LOGIC_COLOR
participant ":AddLinkCommandParser" as AddLinkCommandParser LOGIC_COLOR
participant "a:AddLinkCommand" as AddLinkCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "link:Link" as Link MODEL_COLOR
end box

[-> MainWindow : execute(USER_INPUT)
activate MainWindow

MainWindow --> LogicManager : execute(USER_INPUT)
activate LogicManager

LogicManager -> ModuleBookParser : parseCommand("link ...")
activate ModuleBookParser

create LinkCommandParser
ModuleBookParser -> LinkCommandParser
activate LinkCommandParser

LinkCommandParser --> ModuleBookParser
deactivate LinkCommandParser

ModuleBookParser -> LinkCommandParser : parse("add ... ")
activate LinkCommandParser

create AddLinkCommandParser
LinkCommandParser -> AddLinkCommandParser
activate AddLinkCommandParser

AddLinkCommand --> LinkCommandParser
deactivate AddLinkCommand

LinkCommandParser -> AddLinkCommandParser : parse("add n/LINK_NAME ...")

AddLinkCommandParser --> AddLinkCommandParser : isValidUrl("LINK_URL")
activate AddLinkCommandParser
AddLinkCommandParser -> AddLinkCommandParser
deactivate AddLinkCommandParser

create Link
AddLinkCommandParser -> Link : Link(LINK_NAME, LINK_URL)
activate Link

Link --> AddLinkCommandParser : link
deactivate Link

create AddLinkCommand
AddLinkCommandParser -> AddLinkCommand : AddLinkCommand(INDEX, link)
activate AddLinkCommand

AddLinkCommand --> AddLinkCommandParser : a
deactivate AddLinkCommand

AddLinkCommandParser --> LinkCommandParser: a
deactivate AddLinkCommandParser
AddLinkCommandParser -[hidden]-> LinkCommandParser
destroy AddLinkCommandParser

LinkCommandParser --> ModuleBookParser : a
deactivate LinkCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
LinkCommandParser -[hidden]-> ModuleBookParser
destroy LinkCommandParser

ModuleBookParser --> LogicManager : a
deactivate ModuleBookParser

LogicManager -> AddLinkCommand : execute()
activate AddLinkCommand

ref over AddLinkCommand, Model : add link to module

create CommandResult
AddLinkCommand -> CommandResult
activate CommandResult

CommandResult --> AddLinkCommand
deactivate CommandResult

AddLinkCommand --> LogicManager : CommandResult
deactivate AddLinkCommand

LogicManager -> MainWindow: CommandResult
deactivate LogicManager

MainWindow --> MainWindow: handleShowModule()
activate MainWindow

MainWindow --> LogicManager: getDisplayedModule()
activate LogicManager

LogicManager --> Model: getDisplayedModule()
activate Model

Model -> LogicManager: Module
deactivate Model

LogicManager -> MainWindow: Module
deactivate LogicManager

MainWindow -> MainWindow
deactivate MainWindow

[<- MainWindow: Updated ui
deactivate MainWindow


@enduml
