@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SpendingBookParser" as SpendingBookParser LOGIC_COLOR
participant ":AddReminderCommandParser" as AddReminderCommandParser LOGIC_COLOR
participant "a:AddReminderCommand" as AddReminderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "r:Reminder" as Reminder LOGIC_COLOR
participant "m:ReminderMessage" as ReminderMessage LOGIC_COLOR
participant "deadline:Date" as Date LOGIC_COLOR
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("reminder d/today m/Pay bill")
activate LogicManager

LogicManager -> SpendingBookParser : parseCommand("reminder d/today m/Pay bill")
activate SpendingBookParser

create AddReminderCommandParser
SpendingBookParser -> AddReminderCommandParser
activate AddReminderCommandParser

AddReminderCommandParser --> SpendingBookParser
deactivate AddReminderCommandParser

SpendingBookParser -> AddReminderCommandParser : parse("d/today m/Pay bill")
activate AddReminderCommandParser

create Reminder
AddReminderCommandParser -> Reminder
activate Reminder

create ReminderMessage
Reminder -> ReminderMessage
activate ReminderMessage

ReminderMessage --> Reminder : m
deactivate ReminderMessage

create Date
Reminder -> Date
activate Date

Date --> Reminder : deadline
deactivate Date

Reminder --> AddReminderCommandParser : r
deactivate Reminder

create AddReminderCommand
AddReminderCommandParser -> AddReminderCommand : r
activate AddReminderCommand

AddReminderCommand --> AddReminderCommandParser : a
deactivate AddReminderCommand

AddReminderCommandParser --> SpendingBookParser : a
deactivate AddReminderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddReminderCommandParser -[hidden]-> AddReminderCommandParser
destroy AddReminderCommandParser

SpendingBookParser --> LogicManager : a
deactivate SpendingBookParser

LogicManager -> AddReminderCommand : execute()
activate AddReminderCommand

AddReminderCommand -> Model : addReminder(r)
activate Model

Model --> AddReminderCommand
deactivate Model

Create CommandResult
AddReminderCommand -> CommandResult
activate CommandResult

CommandResult --> AddReminderCommand
deactivate CommandResult

AddReminderCommand --> LogicManager : result
deactivate AddReminderCommand

[<--LogicManager
deactivate LogicManager
@enduml
