@startuml
start
:User executes AddReminderCommand;

if() then ([All parameters present])
    if() then ([Valid Date])
        if() then ([Valid Message])
            : Add a new reminder to the current reminder list in the Model;
            : Update User Interface with the newly added reminder;
        else ([else])
            : Show error message for invalid message value;
        endif
    else ([else])
        : Show error message for invalid date value;
    endif
else([else])
    : Show error message for invalid command format;
endif
stop
@enduml
