@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "a:ReminderCommand" as ReminderCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":UserPrefs" as UserPrefs MODEL_COLOR
participant "at:Reminder" as Reminder MODEL_COLOR
end box
[-> LogicManager : execute(reminder)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(reminder)
activate AddressBookParser

create ReminderCommand
AddressBookParser -> ReminderCommand
activate ReminderCommand

opt illegal reminder
    AddressBookParser <-- ReminderCommand : throw CommandException
    LogicManager <-- AddressBookParser : throw CommandException
    [<- LogicManager : throw CommandException
end

ReminderCommand --> AddressBookParser
deactivate ReminderCommand

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> ReminderCommand : execute()
activate ReminderCommand

ReminderCommand -> Model : addReminder(reminder)
activate Model

Model -> UserPrefs : addReminder(reminder)
activate UserPrefs

UserPrefs -> Reminder :addReminder(reminder)
activate Reminder

Reminder --> UserPrefs :at
deactivate Reminder

UserPrefs --> Model :
deactivate UserPrefs

Model --> ReminderCommand
deactivate Model

ReminderCommand --> LogicManager : result
deactivate ReminderCommand

ReminderCommand -[hidden]-> LogicManager : result
destroy ReminderCommand

@enduml
