@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class HiddenOutside #FFFFFF

namespace Model {
Class ModelManager
Interface Model <<Interface>>
Class ReadOnlyUserPrefs
Class UserPrefs

}

namespace Address {
namespace Model {
namespace Person {
Class Person
Class Address
Class Email
Class Name
Class Phone
Class UniquePersonList
}
namespace Tag {
Class Tag
}
namespace Country {
Class Country
}
Interface AddressBookModel <<Interface>>
Class AddressBookModelManager
Interface ReadOnlyAddressBook <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
}
}


Interface ObservableList <<Interface>>
HiddenOutside ..> Model.Model
''''''''''LAYOUT''''''''''
Model.ModelManager .[hidden]down.> Address
''''''''''''''''''''''''''


''''''''''MODEL''''''''''
''''''''''Model
Model.ModelManager .up.|> Model.Model
''''''''''Model Interface
Model.Model .down.> Address.Model.AddressBookModel :gets >
''''''''''ModelManager Constructor
''' composition or aggregation?
Model.ModelManager *--> "1" Address.Model.AddressBookModel
''''''''''UserPrefs
Model.UserPrefs .up.|> Model.ReadOnlyUserPrefs

''''''''''ADDRESS''''''''''
''''''''''AddressBookModel Interface
Address.Model.AddressBookModel .right.> ObservableList
Address.Model.AddressBookModelManager .up.|> Address.Model.AddressBookModel
''''''''''AddressBookModelManager Constructor
Address.Model.AddressBookModelManager ..> Address.Model.ReadOnlyAddressBook
Address.Model.AddressBookModelManager ..>  Model.ReadOnlyUserPrefs
Address.Model.AddressBookModelManager -->"1" Address.Model.Person.Person : filtered list
Address.Model.AddressBookModelManager o--> Model.UserPrefs

''''''''''ReadOnlyAddressBook
Address.Model.ReadOnlyAddressBook ..> Address.Model.AddressBook

''''''''''AddressBook
Address.Model.AddressBook *-- "1" Address.Model.Person.UniquePersonList

''''''''''Person
Address.Model.Person.UniquePersonList o--> "*" Address.Model.Person.Person
Address.Model.Person.Person *--> Address.Model.Person.Name
Address.Model.Person.Person *--> Address.Model.Person.Phone
Address.Model.Person.Person *--> Address.Model.Person.Email
Address.Model.Person.Person *--> Address.Model.Person.Address
Address.Model.Person.Person *--> Address.Model.Person.Remark
Address.Model.Person.Person *--> Address.Model.Country.Country
Address.Model.Person.Person *--> "*" Address.Model.Tag.Tag


@enduml
