@startuml
autoactivate on
!include style2.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":JarvisParser" as JarvisParser LOGIC_COLOR
participant ":AddCourseCommandParser" as AddCourseCommandParser LOGIC_COLOR
participant "c:AddCourseCommand" as AddCourseCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add-course c/CS2102")

LogicManager -> JarvisParser : parseCommand("add-course c/CS2102")

create AddCourseCommandParser
JarvisParser -> AddCourseCommandParser
    return

JarvisParser -> AddCourseCommandParser : parse("c/CS2102")

create AddCourseCommand
AddCourseCommandParser -> AddCourseCommand

return c
return c
return c

LogicManager -> AddCourseCommand : execute()

AddCourseCommand -> Model : addCourse(CS2102)
    |||
    return

|||

create CommandResult
AddCourseCommand -> CommandResult
    return

return result

[<--LogicManager
@enduml
