@startuml
!include style.puml

box UI LOGIC_COLOR_T1
participant ":DashboardWindow" as DashboardWindow LOGIC_COLOR_T1
end box

box Model MODEL_COLOR_T1
participant ":UniqueDashboardList" as UniqueDashboardList MODEL_COLOR_T1
end box

[-> DashboardWindow : executeCommand("add task ...")
activate DashboardWindow

DashboardWindow -> UniqueDashboardList : add(...)
activate UniqueDashboardList

UniqueDashboardList -> UniqueDashboardList : sortDashboard()
activate UniqueDashboardList

return

UniqueDashboardList --> DashboardWindow
deactivate UniqueDashboardList

<-- DashboardWindow : New task added: ...

@enduml
