@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR


package Model <<Rectangle>>{
Class AliasChecker
Class AliasList
Class AliasPair
Class CommandWordAdder
}

AliasList *--down-> "1...*" AliasPair

@enduml
