@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PasswordBookParser" as PasswordBookParser LOGIC_COLOR
participant ":AnalyseCommand" as AnalyseCommand LOGIC_COLOR
participant ":DictionaryAnalyser" as DictionaryAnalyser LOGIC_COLOR
participant "dictionary: Dictionary" as Dictionary LOGIC_COLOR
participant ":DictionaryMatch" as DictionaryMatch LOGIC_COLOR
participant ":DictionaryResult" as DictionaryResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
end box
[-> LogicManager : execute(analyse)
activate LogicManager

LogicManager -> PasswordBookParser : parseCommand(analyse)
activate PasswordBookParser

create AnalyseCommand
PasswordBookParser -> AnalyseCommand
activate AnalyseCommand

AnalyseCommand --> PasswordBookParser
deactivate AnalyseCommand

PasswordBookParser --> LogicManager
deactivate PasswordBookParser

LogicManager -> AnalyseCommand : execute()
activate AnalyseCommand

AnalyseCommand -> AnalyseCommand : getRequiredAnalysers()
activate AnalyseCommand

create Dictionary
AnalyseCommand -> Dictionary
activate Dictionary
Dictionary --> AnalyseCommand : dictionary
deactivate Dictionary

create DictionaryAnalyser
AnalyseCommand -> DictionaryAnalyser
activate DictionaryAnalyser

DictionaryAnalyser --> AnalyseCommand
deactivate DictionaryAnalyser

deactivate AnalyseCommand

loop hasAnalyser
    AnalyseCommand -> DictionaryAnalyser : analyse(passwordList)
    activate DictionaryAnalyser
        loop hasPassword
           DictionaryAnalyser -> DictionaryAnalyser : getAllMatches(password)
           activate DictionaryAnalyser
           DictionaryAnalyser -> Dictionary : getDictionary()
           activate Dictionary
           Dictionary --> DictionaryAnalyser
           deactivate Dictionary

           create DictionaryMatch
           DictionaryAnalyser -> DictionaryMatch
           activate DictionaryMatch
           DictionaryMatch --> DictionaryAnalyser
           deactivate DictionaryMatch
            deactivate DictionaryAnalyser

            create DictionaryResult
            DictionaryAnalyser -> DictionaryResult
            activate DictionaryResult
            DictionaryResult --> DictionaryAnalyser
            deactivate DictionaryResult
                DictionaryAnalyser --> AnalyseCommand
            deactivate DictionaryAnalyser

        end
    end
    AnalyseCommand --> LogicManager
    deactivate AnalyseCommand
[<--LogicManager
deactivate LogicManager
@end
