@startuml
start
:User uses a macro/alias;

repeat
    if (matches alias) then ([true])
        if (currentAlias > previousAlias) then ([true])
            :Apply this alias instead;
        else ([else])
        endif
    else ([else])
    endif
repeat while (more alias exists in table) is ([true])
->[no];
stop
@enduml
