@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

show members

  namespace unrealunity.visit {
    namespace model {
      namespace appointment {
        class unrealunity.visit.model.appointment.Appointment {
            - days : int
            - description : String
            + Appointment()
            + getDays()
            + getDaysString()
            + getDescription()
            + getDescriptionRaw()
            + getType()
            + isSameAppointment()
            + isSameAppointment()
            + setDays()
            + toString()
        }
      }
    }
  }

@enduml
