@startuml
skinparam classAttributeIconSize 0
hide empty members

package model {
Interface Model <<Interface>>
Class ModelManager
Interface ReadOnlyArchiveWrapper
Class ArchiveWrapper
}

package archive {
    Class Archive {
    String archiveName
    }
}

package expense {
    Class ExpenseList
    Class Expense
}



ModelManager .up.|> Model
ArchiveWrapper .up.|> ReadOnlyArchiveWrapper
ModelManager o-right- "1" ArchiveWrapper
Archive -right-|> ExpenseList
ArchiveWrapper *-right- Archive
ExpenseList o-down- "*" Expense

@enduml
