@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":UiLogic" as uilogic UI_LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : Switches tab
activate ui UI_COLOR

ui -[UI_COLOR]> uilogic : execute(uiActionDetails)
activate uilogic UI_LOGIC_COLOR

uilogic -[UI_LOGIC_COLOR]> model : switchTab(index)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> uilogic
deactivate model

uilogic -[UI_LOGIC_COLOR]> storage : saveAlgoBase(algoBase)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
deactivate storage

storage --[STORAGE_COLOR]> uilogic
deactivate storage

uilogic --[UI_LOGIC_COLOR]> ui
deactivate uilogic

ui--[UI_COLOR]> user
deactivate ui
@enduml
