@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as questionsLogic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "delete 1"
activate ui UI_COLOR

ui -[UI_COLOR]> questionsLogic : execute("delete 1")
activate questionsLogic LOGIC_COLOR

questionsLogic -[LOGIC_COLOR]> model : deletePerson(p)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> questionsLogic
deactivate model

questionsLogic -[LOGIC_COLOR]> storage : saveQuestionBank(questionBank)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
deactivate storage

storage --[STORAGE_COLOR]> questionsLogic
deactivate storage

logic --[LOGIC_COLOR]> ui
deactivate questionsLogic

ui--[UI_COLOR]> user
deactivate ui
@enduml
