@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as addressBookLogic LOGIC_COLOR
Participant ":Model" as addressBookModel MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "delete 1"
activate ui UI_COLOR

ui -[UI_COLOR]> addressBookLogic : execute("delete 1")
activate addressBookLogic LOGIC_COLOR

addressBookLogic -[LOGIC_COLOR]> addressBookModel : deletePerson(p)
activate addressBookModel MODEL_COLOR

addressBookModel -[MODEL_COLOR]-> addressBookLogic
deactivate addressBookModel

addressBookLogic -[LOGIC_COLOR]> storage : saveAddressBook(addressBook)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
deactivate storage

storage --[STORAGE_COLOR]> addressBookLogic
deactivate storage

addressBookLogic --[LOGIC_COLOR]> ui
deactivate addressBookLogic

ui--[UI_COLOR]> user
deactivate ui
@enduml
