@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR


user -[USER_COLOR]> ui : "delete 1"
activate ui

ui -> logic : "execute("delete 1")"
activate logic

logic -> model : "deleteEatery()"
activate model
model --> logic
deactivate model

logic -> storage : saveEateryList()
activate storage

storage -> storage : save to file
storage --> logic
deactivate storage

logic --> ui
deactivate logic

ui --> user
deactivate ui
@enduml
