@startuml
!include <office/Concepts/documents>
!include <office/Users/user>

hide circles
hide empty members
skinparam packageStyle rectangle
skinparam shadowing false

package Horo {
    class CommandManager
    class Ics
    class ModelManager
    class NotificationManager
    class StorageManager
    class UiManager
    class UndoRedoManager

    class LogsCenter
    class Main
}

class "<$user>" as User
class "<$documents>" as Documents

CommandManager <..> UiManager

Ics --> ModelManager

ModelManager ..> StorageManager
ModelManager ..> UiManager
ModelManager ..> UndoRedoManager

NotificationManager --> ModelManager

StorageManager --> ModelManager
StorageManager <..> Documents

UndoRedoManager --> ModelManager

User <..> UiManager
@enduml
