@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.


if (Are the driver and task valid?) then ([yes])
else ([no])
 stop
endif

if (Is the task already assigned?) then ([yes])

else ([yes])
    if (Is force assign?) then ([yes])
    : Free that task;
    else ([no])
        stop
    endif
endif

: Check against the driver's schedule;
if (Is the target driver available during the proposed time) then ([yes])
    : assign;
    stop
else ([no])
    if (Was the task changed?) then ([yes])
        : Restore that task;
    else ([no])
endif
stop

@enduml
