@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (Is force assign?) then ([yes])

else ([no])
    : Check against current schedule;
    if (The most optimal time slot?) then ([yes])
    else ([no])
        stop
    endif
endif
if (Within working hours?) then ([yes])
else ([no])
    stop
endif
if (No schedule clash?) then ([yes])
    else ([no])
        stop
endif
stop
@enduml
