@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package AutoComplete {

package Graphs {
Interface Graph <<Interface>>
Class "{abstract}\nAutoCompleteGraph" as AutoCompleteGraph
Class "{abstract}\nGraphBuiltFromModel" as GraphBuiltFromModel
Class "{abstract}\nGraphWithStartNode" as GraphWithStartNode
Class "{abstract}\nGraphWithPreamble}" as GraphWithPreamble
Class "{abstract}\nGraphWithStartNodeAndPreamble}" as GraphWithStartNodeAndPreamble
}

package Edges {
Interface Edge <<Interface>>
Class AutoCompleteEdge
}

package Nodes {
Class "{abstract}\nNode" as Node
Class "{abstract}\nAutoCompleteNode" as AutoCompleteNode
Class EmptyAutoCompleteNode
}

Class AutoCompleteResultGenerator
Interface AutoCompleteResultProvider <<Interface>>
Interface AutoCompleteValueProvider <<Interface>>
Class EmptyProvider
}

AutoCompleteResultGenerator *-right-> "*" AutoCompleteResultProvider

AutoCompleteGraph .up.|> Graph
AutoCompleteGraph .up..|> AutoCompleteResultProvider

GraphBuiltFromModel -up-|> AutoCompleteGraph
GraphWithStartNode -up-|> GraphBuiltFromModel
GraphWithPreamble -up-|> GraphBuiltFromModel
GraphWithStartNodeAndPreamble -up-|> GraphWithStartNode

EmptyProvider .left.|> AutoCompleteResultProvider

AutoCompleteEdge .up.|> Edge
AutoCompleteGraph *--> "*" AutoCompleteEdge

AutoCompleteNode -up-|> Node
AutoCompleteEdge *--> "2" AutoCompleteNode
AutoCompleteNode .up...|> AutoCompleteValueProvider

Graph ...> Node

EmptyAutoCompleteNode -up-|> AutoCompleteNode

@enduml
