@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

'title After command "autotag Help u/stackoverflow.com/questions"

show object fields
package Bookmarks <<rectangle>> {
    object "<u>b1:Bookmark" as Bookmark1 {
        name : CS2103T Website
        url : https://nus-cs2103-ay1920s1.github.io/website/
        tags : School
    }
    object "<u>b3:Bookmark" as Bookmark2 {
        name : PlantUML mix different elements
        url : https://stackoverflow.com/questions/54020731
        tags : Help
    }
}

package AutotagController {
    object "<u>t1:SelectiveBookmarkTagger" as Tagger1 {
         predicate : url contains "stackoverflow.com/questions"
         tag : Help
    }
}

Bookmarks -[hidden]right> AutotagController

Bookmark1 -[hidden]down-> Bookmark2

@end
