@startuml
!include style.puml

participant ":CommandBox" as CommandBox UI_COLOR
participant ":AutoCompletePanelManager" as AutoCompletePanelManager UI_COLOR
participant ":AutoCompletePanel" as AutoCompletePanel UI_COLOR
participant ":AutoCompleteWord" as AutoCompleteWord UI_COLOR
participant ":MatchWordUpdater" as MatchWordUpdater UI_COLOR
participant ":AutoCompleteListHandler" as AutoCompleteListHandler UI_COLOR
participant ":AutoCompleteStorage" as AutoCompleteStorage UI_COLOR
participant "commandTextField:TextField" as CommandTextField UI_COLOR

[-> CommandBox : User presses SHIFT key;
activate CommandBox


CommandBox -> CommandBox : receiveDataFromSender()
 activate CommandBox

 CommandBox -> AutoCompletePanelManager : sendData()
 activate AutoCompletePanelManager

AutoCompletePanelManager -> AutoCompletePanelManager: getSelected()
activate AutoCompletePanelManager

AutoCompletePanelManager -> AutoCompletePanel: getSelected()
activate AutoCompletePanel

AutoCompletePanel --> AutoCompletePanelManager: selectedAutoCompleteWord
deactivate AutoCompletePanel

return selectedAutoCompleteWord

AutoCompletePanelManager -> AutoCompleteWord: getSuggestedWord()
activate AutoCompleteWord

AutoCompleteWord --> AutoCompletePanelManager: textToDisplay
deactivate AutoCompleteWord

AutoCompletePanelManager --> CommandBox: textToDisplay
deactivate AutoCompletePanelManager
return textToDisplay

CommandBox -> CommandTextField : setText(textToDisplay)
activate CommandTextField

CommandTextField --> CommandBox
deactivate CommandTextField

CommandBox -> CommandBox : notifyObserversToChange(KeyCode.SHIFT, textToDisplay);
activate CommandBox

CommandBox -> AutoCompletePanelManager : update(KeyCode.SHIFT, textToDisplay);
activate AutoCompletePanelManager

AutoCompletePanelManager -> AutoCompletePanelManager : updateListView(KeyCode.SHIFT, textToDisplay)
activate AutoCompletePanelManager

AutoCompletePanelManager -> MatchWordUpdater : findMatchedWords(textToDisplay)
activate MatchWordUpdater

MatchWordUpdater -->  AutoCompletePanelManager: matchedWords
deactivate MatchWordUpdater

AutoCompletePanelManager ->  AutoCompleteListHandler: generateList(matchedWords, textToDisplay)
activate AutoCompleteListHandler

ref over AutoCompleteListHandler, AutoCompleteStorage : generating list

AutoCompleteListHandler --> AutoCompletePanelManager: generatedList
deactivate AutoCompleteListHandler

AutoCompletePanelManager -> AutoCompletePanel: setList(generatedList)
activate AutoCompletePanel

AutoCompletePanel --> AutoCompletePanelManager
deactivate AutoCompletePanel
return

AutoCompletePanelManager --> CommandBox
deactivate AutoCompletePanelManager
return

@enduml

