@startuml
start
:User presses TAB;

if () then ([no input])
else ([else])
    if () then ([first word])
    :Use command keywords;
    else ([else])
    if () then ([first word is help])
        :Use command keywords;
    else ([else])
        :Use argument keywords;
    endif
    endif
    :Find search results based on keywords and input;
    if () then ([only one result])
    else ([else])
    :Create a menu;
    :User selects an option in the menu;
    endif
    :Set text to that search result;
endif
stop
@enduml