@startuml
start
:Step 1: User inputs command ;
:Step 2: Ensure no syntax error;
if () then ([No syntax or logic error])
:Step 3: Calculate manpower required by the event;
:Step 4: Create a list of available employees;
:Step 5: Check if supply exceeds demand;
if () then ([supply >= demand])
:Step 6: Allocate employees to the event;
:Step 7: Done;
else ([supply < demand])
endif
else ([Error])
endif
stop
@enduml
