@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

'title Initial State

show object fields
package Bookmarks <<rectangle>> {
    object "<u>b1:Bookmark" as Bookmark1 {
        name : CS2103T Website
        url : https://nus-cs2103-ay1920s1.github.io/website/
        tags : School
    }
    object "<u>b2:Bookmark" as Bookmark2 {
        name : PlantUML mix different elements
        url : https://stackoverflow.com/questions/54020731
        tags :
    }
}

package AutotagController {
}

Bookmarks -[hidden]right> AutotagController

Bookmark1 -[hidden]down-> Bookmark2

@end
