@startuml
start
:User inputs command ;
:Ensure no syntax error or logic error;
if () then ([No logic or syntax error])
:Check that there is an allocated budget to calculate statistics from;
if () then ([A target budget is present])
:Get the current budget;
:Calculate the period to make statistics from \nbased on user input;

if (Both dates are specified) then ([yes])
  :Statistics interval uses specified start and end dates;
elseif (only end date is specified) then ([yes])
  :Statistics interval starts from 1 budget period \nbefore end date till end date;
elseif (only start date is specified) then ([yes])
  :Statistics interval starts from start date\ntill 1 budget period after;
else ([no])
  :both start date and end date not specified;
  :Statistics interval is equal to current budget;
endif
:Calculate the statistics;
else ([No budget is allocated])
    :show no primary budget message;
endif
else ([Error])
    :show invalid command format message;
endif
stop

@enduml