@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MooLahParser" as MooLahParser LOGIC_COLOR
participant ":StatsCommandParser" as StatsCommandParser LOGIC_COLOR
participant "statsCommand:StatsCommand" as StatsCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant "statistics:PieChartStatistics" as Statistics MODEL_COLOR
end box

[-> LogicManager : execute("statsbasic \n sd/01-10-2019 \n ed/01-11-2019")
activate LogicManager

LogicManager -> MooLahParser : parseCommand(statsbasic \n sd/01-10-2019 \n ed/01-11-2019")
activate MooLahParser

create StatsCommandParser
MooLahParser -> StatsCommandParser
activate StatsCommandParser

StatsCommandParser --> MooLahParser
deactivate StatsCommandParser

MooLahParser -> StatsCommandParser : parse("statsbasic \n sd/01-10-2019 \n ed/01-11-2019)
activate StatsCommandParser



ref over StatsCommandParser, StatsCommand : Extract parameters \ncreate StatsCommand


create StatsCommand
StatsCommandParser -> StatsCommand :
activate StatsCommand

StatsCommand --> StatsCommandParser : statsCommand
deactivate StatsCommand

StatsCommandParser --> MooLahParser : statsCommand
destroy StatsCommandParser





MooLahParser --> LogicManager : statsCommand
deactivate MooLahParser

LogicManager -> StatsCommand : run(model)
activate StatsCommand

StatsCommand -> StatsCommand: validate
activate StatsCommand


StatsCommand -> StatsCommand:
deactivate StatsCommand

StatsCommand -> StatsCommand: execute
activate StatsCommand

StatsCommand -> ModelManager : getPrimaryBudget()
activate ModelManager


ModelManager --> StatsCommand : primaryBudget
deactivate ModelManager

create Statistics
StatsCommand -> Statistics : createPieChartStatistics(\n primaryBudget, \n desc)
activate Statistics

ref over StatsCommand, Statistics : Create pie chart statistics


Statistics -> StatsCommand : statistics
deactivate Statistics


StatsCommand -> ModelManager : setStatistic(statistics)
activate ModelManager

ModelManager --> StatsCommand
deactivate ModelManager

StatsCommand --> StatsCommand
deactivate StatsCommand

create CommandResult
StatsCommand -> CommandResult
activate CommandResult

CommandResult --> StatsCommand :
deactivate CommandResult

StatsCommand --> LogicManager : result
destroy StatsCommand

[<--LogicManager : result
deactivate LogicManager




@enduml
