@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Mams *-right-> "1" UniqueStudentList
Mams *-right-> "1" UniqueModuleList
Mams *-right-> "1" UniqueAppealList

UniqueStudentList o-right-> "*"Student
UniqueModuleList o-down-> "*"Module
UniqueAppealList o-down-> "*"Appeal

Student o-up-> "*" Tag

Student *--> Name
Student *--> Credits
Student *--> PrevMods
Student *--> MatricId


@enduml
