@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

WordBank *-down-> "1" UniqueCardList
WordBank *-down-> "1" Name
UniqueTagList *-down-> "*" Tag
UniqueCardList o-down-> Card

Card o-down-> "*" UniqueTagList

Card *--> Id
Card *--> Word
Card *--> Meaning
@enduml
