@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Book --> "*" Genre
Book --> "1" Title
Book --> "1" SerialNumber
Book --> "1" Author
Book -right-> "0..1" Loan
Book --> "1" LoanList : "LoanHistory"
Loan -down[hidden]> Author
@enduml
