@startuml
start
:MooLah launches;
if (primary budget (if any) expired?) then (yes)
    :refresh budget;
else (no)
    :proceed with current period;
endif

:expense is added to MooLah;
if () then (budget list is empty)
    :create default budget;
    :set default budget as primary;
else (budget list is not empty)
    :proceed with current primary budget;
endif

if () then (expense has a budget \n(retrieved from past data))
    :add this expense to corresponding budget;
else (expense has no budget \n(newly added by user))
    :set primary budget as expenses's budget;
    :add expense to primary budget;
endif

:update budget's proportionUsed;
:add expense to expense list;
stop
@enduml
