@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package CalendarWindow <<Rectangle>>{
Class Tab UI_COLOR
Class "{abstract}\nUiPart" as UiPart UI_COLOR
Class CalendarWindow UI_COLOR_T1
Class YearMonth
Class CalendarDateCell
Class DateDisplayGrid
Class CalendarDateStackPane
Class SingleDayEngagementsDisplayWindow
Class EngagementListView
Class EngagementListViewCell
Class Engagement
Class LocalDate
Class PreviousMonthButton
Class CalendarTitle
Class NextMonthButton
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Tab
Tab *-down-> "0...1" CalendarWindow

CalendarWindow *-down-> PreviousMonthButton
CalendarWindow *-down-> CalendarTitle
CalendarWindow *-down-> NextMonthButton
CalendarWindow .up.|> UiPart
CalendarWindow -right-> Logic
CalendarWindow *-down-> YearMonth
CalendarWindow *-down-> DateDisplayGrid
CalendarWindow *-down-> "35" CalendarDateCell

DateDisplayGrid -down-> "35" CalendarDateStackPane

CalendarDateCell .up.|> UiPart
CalendarDateCell *-down-> "1" CalendarDateStackPane
CalendarDateCell *-down-> "*" Engagement
CalendarDateCell *-right-> SingleDayEngagementsDisplayWindow
CalendarDateCell -down-> LocalDate

SingleDayEngagementsDisplayWindow .up.|> UiPart
SingleDayEngagementsDisplayWindow -down-> "1" EngagementListView

EngagementListView -down-> "*" EngagementListViewCell

EngagementListViewCell -down-> "1" Engagement

Engagement .right.> Model

@enduml
