@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Package cap {
Interface ReadOnlyCapLog <<Interface>>
Interface ReadOnlySemesterLog <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class CapLog
Class CapUserPrefs
Class Model
Class ModelCapManager
Class ReadOnlyCapLog
Class ReadOnlySemesterLog
Class ReadOnlyUserPrefs

Package Common {
Class Module
}

Package Person {
Class Title
Class Description
Class ModuleCode
Class Credit
Class Semester
Class Faculty
Class Grade
Class SemesterPeriod
Class AcademicYear
Class NameContainsKeywordPredicate
Class UniqueModuleList
Class UniqueSemesterList
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

CapLog .up.|> ReadOnlyCapLog

ModelCapManager .up.|> Model
Model .right.> ObservableList
ModelCapManager o--> "1" CapLog
ModelCapManager o-left-> "1" CapUserPrefs
CapUserPrefs .up.|> ReadOnlyUserPrefs

ReadOnlyCapLog *--> "1" UniqueModuleList
ReadOnlySemesterLog *--> "1" UniqueSemesterList
UniqueModuleList <--o ObservableList
UniqueModuleList o--> "*" Module
UniqueSemesterList o--> "*" Semester
UniqueSemesterList <--o ObservableList
CapLog o--> Module

Module *--> Title
Module *--> ModuleCode
Module *--> Description
Module *--> Credit
Module *--> Semester
Module *--> Faculty
Module *--> Grade
Semester *--> SemesterPeriod
Semester *--> AcademicYear

ModelCapManager o-->"1" Module : moduleFilteredList
ModelSemesterManager o-->"1" Module : semesterFilteredList
}
}
FindCommand o--> NameContainsKeywordPredicate


@enduml
