@startuml

start
-Display the list of patient's appointments
-Enter edit appointment command
        if() then ([Valid index])
        -find the target appointment

            if() then ([no. of appointments < no. of doctor on duty])
            -Appointment's timing changed
            -Display the patient's all upcoming appointments

            else ([else])
            -Display error message\n to input valid appointment's timing
            endif
        else ([Not valid])
        -Display error message\n to input valid appointment's index
        endif
stop
@enduml
