@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR


Class MainWindow

package Chart <<Rectangle>> {
Class ChartBox
Class StatisticsFormatOptions
Class "{abstract}\nExpenseChart" as ExpenseChart
Class ExpenseTimelineChart
Class ExpenseBreakdownChart


enum StatisticsFormat {
TIMELINE
BREAKDOWN
}
}

package StatisticsGenerator <<Rectangle>> {
Class HiddenChart #FFFFFF
}
Class "{abstract}\nUiPart" as UiPart


MainWindow *-right-> ChartBox
ChartBox -right-> StatisticsFormat
ChartBox *-down-> ExpenseChart
ChartBox -down-> StatisticsFormatOptions
ExpenseTimelineChart -up-|> ExpenseChart
ExpenseBreakdownChart -up-|> ExpenseChart
ExpenseTimelineChart *-> StatisticsGenerator
ExpenseBreakdownChart *-> StatisticsGenerator
ExpenseChart -left-|> UiPart

@enduml
