@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


abstract class ClashCommand
class ClashModCommand
class ClashStudentCommand
class ClashAppealCommand

ClashCommand <|-- ClashModCommand
ClashCommand <|-- ClashStudentCommand
ClashCommand <|-- ClashAppealCommand

@enduml
