@startuml
start
:User executes command    ;

if () then ([command execution is successful]         )
    if () then (
    [command is an
    ReversibleActionPairCommand]          )


        :Purge redundant
        commands in the
           Redo stack           ;

        :Adds the command
        to the undo stack        ;

        :Inform user of
        command result   ;

        :Invoke storage to
        save the current
        state of the model   ;

    else (  [else])
        :Inform user of
        command result   ;
    endif

else (  [else])
    :Inform user that
    an error occurred   ;
endif
stop
@enduml
