@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command saves new
EngagementList state])
    :Purge redunant states;
    :Save EngagementList to
    historyList;
else ([else])
endif
stop
@enduml
