@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (tab name matches) then ([TutorAid executes tab change])
    :UiManager calls MainWindow
    to display fetched tab;
    :MainWindow fills the stage
     with tab information;
stop
else ([end])
stop
@enduml
