@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PasswordBookParser" as PasswordBookParser LOGIC_COLOR
participant ":CopyPasswordCommandParser" as CopyPasswordCommandParser LOGIC_COLOR
participant "c:CopyPasswordValueCommand" as CopyPasswordValueCommand LOGIC_COLOR
participant "c:CopyPasswordUsernameCommand" as CopyPasswordUsernameCommand LOGIC_COLOR
participant "c:CopyPasswordWebsiteCommand" as CopyPasswordWebsiteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Commons LOGIC_COLOR_T2
participant ":ClipboardUtil" as ClipboardUtil LOGIC_COLOR_T1

[-> LogicManager : execute("cp p 1")
activate LogicManager

LogicManager -> PasswordBookParser : parseCommand("cp p 1")
activate PasswordBookParser

create CopyPasswordCommandParser
PasswordBookParser -> CopyPasswordCommandParser
activate CopyPasswordCommandParser

CopyPasswordCommandParser --> PasswordBookParser
deactivate CopyPasswordCommandParser

PasswordBookParser -> CopyPasswordCommandParser : parse("p 1")
activate CopyPasswordCommandParser
opt isCopyPasswordValueCommand
    create CopyPasswordValueCommand
    CopyPasswordCommandParser -> CopyPasswordValueCommand
    activate CopyPasswordValueCommand
    CopyPasswordValueCommand --> CopyPasswordCommandParser
    deactivate CopyPasswordValueCommand
end
opt isCopyPasswordUsernameCommand
    create CopyPasswordUsernameCommand
    CopyPasswordCommandParser -> CopyPasswordUsernameCommand
    activate CopyPasswordUsernameCommand
    CopyPasswordUsernameCommand --> CopyPasswordCommandParser
    deactivate CopyPasswordUsernameCommand
end
opt isCopyPasswordWebsiteCommand
    create CopyPasswordWebsiteCommand
    CopyPasswordCommandParser -> CopyPasswordWebsiteCommand
    activate CopyPasswordWebsiteCommand
    CopyPasswordWebsiteCommand --> CopyPasswordCommandParser
    deactivate CopyPasswordWebsiteCommand
end

CopyPasswordCommandParser --> PasswordBookParser : c
deactivate CopyPasswordCommandParser

CopyPasswordCommandParser -[hidden]-> PasswordBookParser
destroy CopyPasswordCommandParser

PasswordBookParser --> LogicManager : c
deactivate PasswordBookParser

LogicManager -> CopyPasswordValueCommand : execute()
activate CopyPasswordValueCommand

CopyPasswordValueCommand -> Model : getFilteredPasswordList()
activate Model

Model --> CopyPasswordValueCommand : passwordList
deactivate Model

CopyPasswordValueCommand -> ClipboardUtil : copyToClipboard(passwordValue)
activate ClipboardUtil
ClipboardUtil --> CopyPasswordValueCommand
deactivate ClipboardUtil

create CommandResult
CopyPasswordValueCommand -> CommandResult
activate CommandResult

CommandResult --> CopyPasswordValueCommand
deactivate CommandResult

CopyPasswordValueCommand --> LogicManager : result
deactivate CopyPasswordValueCommand

[<--LogicManager
deactivate LogicManager
@enduml
