@startuml

hide CustomProperty methods
hide CliSyntax members
hide ParameterType methods
skinparam classAttributeIconSize 0

class CustomProperty {
    - String fullName
    - Prefix prefix
    - ParameterType parameterType
}

class PropertyBook {
    - {static} PropertyBook instance
    - Set<CustomProperty> customProperties
    - Set<Prefix> defaultPrefixes
    - Set<String> defaultFullNames
    - Set<Prefix> customPrefixes
    - Set<String> customFullNames
    + {static} getInstance()
    + isPrefixUsed(Prefix)
    + isFullNameUsed(String)
    + isFullNameUsedByCustomProperty(String)
    + addCustomProperty(CustomProperty)
    + removeCustomProperty(String)
}

enum ParameterType <<enumeration>> {
    NUMBER
    TEXT
    DATE
}

PropertyBook o-Left-> "*" CustomProperty: tracks >

PropertyBook <.Left. CliSyntax: updates prefixes >

CustomProperty -Down-> "1" ParameterType

@enduml
