@startuml
start
:User executes DeleteReminderCommand;

if() then ([Index present])
    if() then ([Index within bound])
        : Delete the specified reminder from the current reminder list in the model;
        : Update User Interface with the updated reminder list;
    else ([Index out of bound])
        : Show error message for invalid index;
    endif
else([Index absent])
    : Show error message for invalid command format;
endif
stop
@enduml
