@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":DukeCooksParser" as DukeCooksParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":DeletePageCommandParser" as DeletePageCommandParser LOGIC_COLOR
participant "d:DeletePageCommand" as DeletePageCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "index:Index" as Index MODEL_COLOR
participant "diaryName:DiaryName" as DiaryName MODEL_COLOR
end box

[-> DukeCooksParser : parseCommand("delete page 1 \n n/Asian Cuisines")
activate DukeCooksParser

create DeleteCommandParser
DukeCooksParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> DukeCooksParser
deactivate DeleteCommandParser

DukeCooksParser -> DeleteCommandParser : parse("page 1 n/Asian Cuisines")
activate DeleteCommandParser

create DeletePageCommandParser
DeleteCommandParser -> DeletePageCommandParser
activate DeletePageCommandParser

DeletePageCommandParser --> DeleteCommandParser
deactivate DeletePageCommandParser

DeleteCommandParser -> DeletePageCommandParser : parse("1 n/Asian Cuisines")
activate DeletePageCommandParser

create Index
DeletePageCommandParser -> Index : new Index("1")
activate Index

Index --> DeletePageCommandParser : index
deactivate Index

create DiaryName
DeletePageCommandParser -> DiaryName : new DiaryName("Asian Cuisines")
activate DiaryName

DiaryName -> DiaryName : isValidDiaryName()
activate DiaryName

DiaryName --> DiaryName
deactivate DiaryName

DiaryName --> DeletePageCommandParser : diaryName
deactivate DiaryName

create DeletePageCommand
DeletePageCommandParser -> DeletePageCommand : new DeletePageCommand(index, diaryName)
activate DeletePageCommand

DeletePageCommand --> DeletePageCommandParser : d
deactivate DeletePageCommand

DeletePageCommandParser --> DeleteCommandParser : d
deactivate DeletePageCommandParser

DeleteCommandParser --> DukeCooksParser : d
deactivate  DeleteCommandParser

[<--DukeCooksParser : d
deactivate DukeCooksParser

[-> DeletePageCommand : execute()
activate DeletePageCommand

DeletePageCommand -> Model
activate Model

Model --> DeletePageCommand
deactivate Model

DeletePageCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePageCommand
deactivate CommandResult

[<-- DeletePageCommand : result

@enduml