@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SpendingBookParser" as SpendingBookParser LOGIC_COLOR
participant ":ReminderCommandParser" as ReminderCommandParser LOGIC_COLOR
participant ":DeleteReminderCommandParser" as DeleteReminderCommandParser LOGIC_COLOR
participant "d:DeleteReminderCommand" as DeleteReminderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("reminder delete 1")
activate LogicManager

LogicManager -> SpendingBookParser : parseCommand("reminder delete 1")
activate SpendingBookParser

create ReminderCommandParser
SpendingBookParser -> ReminderCommandParser
activate ReminderCommandParser

ReminderCommandParser --> SpendingBookParser
deactivate ReminderCommandParser

SpendingBookParser -> ReminderCommandParser : parse("delete 1")
activate ReminderCommandParser

create DeleteReminderCommandParser
ReminderCommandParser -> DeleteReminderCommandParser
activate DeleteReminderCommandParser

DeleteReminderCommandParser --> ReminderCommandParser
deactivate DeleteReminderCommandParser

ReminderCommandParser -> DeleteReminderCommandParser : parse("1")
activate DeleteReminderCommandParser

create DeleteReminderCommand
DeleteReminderCommandParser -> DeleteReminderCommand
activate DeleteReminderCommand

DeleteReminderCommand --> DeleteReminderCommandParser : d
deactivate DeleteReminderCommand

DeleteReminderCommandParser --> ReminderCommandParser : d
deactivate DeleteReminderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteReminderCommandParser -[hidden]-> ReminderCommandParser
destroy DeleteReminderCommandParser

ReminderCommandParser --> SpendingBookParser : d
deactivate ReminderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ReminderCommandParser -[hidden]-> SpendingBookParser
destroy ReminderCommandParser

SpendingBookParser --> LogicManager : d
deactivate SpendingBookParser

LogicManager -> DeleteReminderCommand : execute()
activate DeleteReminderCommand

DeleteReminderCommand -> Model : deleteReminder(1)
activate Model

Model --> DeleteReminderCommand
deactivate Model

create CommandResult
DeleteReminderCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteReminderCommand
deactivate CommandResult

DeleteReminderCommand --> LogicManager : result
deactivate DeleteReminderCommand

[<--LogicManager
deactivate LogicManager
@enduml
