@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "a:AddAnnotationCommand" as AddAnnotationCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "b:Bookmark" as Bookmark MODEL_COLOR
participant "doc:OfflineDocument" as OfflineDocument MODEL_COLOR
participant "an:Annotation" as Annotation MODEL_COLOR
end box


AddAnnotationCommand -> Bookmark : getRequiredDocCopy(index)
activate Bookmark

Bookmark --> AddAnnotationCommand : doc
deactivate Bookmark

create Annotation
AddAnnotationCommand -> Annotation : Annotation(highlight, note)
activate Annotation

Annotation --> AddAnnotationCommand : an
deactivate Annotation

AddAnnotationCommand -> OfflineDocument : addAnnotation(pid, an)
activate OfflineDocument

OfflineDocument --> AddAnnotationCommand
deactivate OfflineDocument

@enduml
