@startuml
scale 1.5
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MemeParser" as MemeParser LOGIC_COLOR
participant ":MemeDeleteCommandParser" as MemeDeleteCommandParser LOGIC_COLOR
participant "d:MemeDeleteCommand" as MemeDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> MemeParser : parseCommand("delete 1")
activate MemeParser

create MemeDeleteCommandParser
MemeParser -> MemeDeleteCommandParser
activate MemeDeleteCommandParser

MemeDeleteCommandParser --> MemeParser
deactivate MemeDeleteCommandParser

MemeParser -> MemeDeleteCommandParser : parse("1")
activate MemeDeleteCommandParser

create MemeDeleteCommand
MemeDeleteCommandParser -> MemeDeleteCommand
activate MemeDeleteCommand

MemeDeleteCommand --> MemeDeleteCommandParser : d
deactivate MemeDeleteCommand

MemeDeleteCommandParser --> MemeParser : d
deactivate MemeDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
MemeDeleteCommandParser -[hidden]-> MemeParser
destroy MemeDeleteCommandParser

MemeParser --> LogicManager : d
deactivate MemeParser

LogicManager -> MemeDeleteCommand : execute()
activate MemeDeleteCommand

MemeDeleteCommand -> Model : deleteMeme(1)
activate Model

Model --> MemeDeleteCommand
deactivate Model

create CommandResult
MemeDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> MemeDeleteCommand
deactivate CommandResult

MemeDeleteCommand --> LogicManager : result
deactivate MemeDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
