@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NotebookParser" as NotebookParser LOGIC_COLOR
participant ":DeleteStudentCommandParser" as DeleteStudentCommandParser LOGIC_COLOR
participant "d:DeleteStudentCommand" as DeleteStudentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deletestudent 1")
activate LogicManager

LogicManager -> NotebookParser : parseCommand("deletestudent 1")
activate NotebookParser

create DeleteStudentCommandParser
NotebookParser-> DeleteStudentCommandParser
activate DeleteStudentCommandParser

DeleteStudentCommandParser --> NotebookParser
deactivate DeleteStudentCommandParser

NotebookParser-> DeleteStudentCommandParser : parse("1")
activate DeleteStudentCommandParser

create DeleteStudentCommand
DeleteStudentCommandParser -> DeleteStudentCommand
activate DeleteStudentCommand

DeleteStudentCommand --> DeleteStudentCommandParser : d
deactivate DeleteStudentCommand

DeleteStudentCommandParser --> NotebookParser: d
deactivate DeleteStudentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteStudentCommandParser -[hidden]-> NotebookParse
destroy DeleteStudentCommandParser

NotebookParser--> LogicManager : d
deactivate NotebookParse

LogicManager -> DeleteStudentCommand : execute()
activate DeleteStudentCommand

DeleteStudentCommand -> Model : deleteStudent(1)
activate Model

DeleteStudentCommand -> Model : saveState()
Model --> DeleteStudentCommand
deactivate Model

create CommandResult
DeleteStudentCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteStudentCommand
deactivate CommandResult

DeleteStudentCommand --> LogicManager : result
deactivate DeleteStudentCommand

[<--LogicManager
deactivate LogicManager
@enduml
