@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":DeleteIdCommandParser" as DeleteIdCommandParser LOGIC_COLOR
participant "d:DeleteIdCommand" as DeleteIdCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("del t/1")
activate LogicManager

LogicManager -> CommandParser : parseCommand("del t/1")
activate CommandParser

create DeleteIdCommandParser
CommandParser -> DeleteIdCommandParser
activate DeleteIdCommandParser

DeleteIdCommandParser --> CommandParser
deactivate DeleteIdCommandParser

CommandParser -> DeleteIdCommandParser : parse("t/1")
activate DeleteIdCommandParser

create DeleteIdCommand
DeleteIdCommandParser -> DeleteIdCommand : DeleteIdCommand("t/1")
activate DeleteIdCommand

DeleteIdCommand --> DeleteIdCommandParser : d
deactivate DeleteIdCommand

DeleteIdCommandParser --> CommandParser : d
deactivate DeleteIdCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteIdCommandParser -[hidden]-> CommandParser
destroy DeleteIdCommandParser

CommandParser --> LogicManager : d
deactivate CommandParser

LogicManager -> DeleteIdCommand : execute()
activate DeleteIdCommand

DeleteIdCommand -> Model : deleteTask(taskToDelete)
activate Model

Model --> DeleteIdCommand
deactivate Model

create CommandResult
DeleteIdCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteIdCommand
deactivate CommandResult

DeleteIdCommand --> LogicManager : result
deactivate DeleteIdCommand

[<--LogicManager
deactivate LogicManager
@enduml
