@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR
skinparam classAttributeIconSize 0
skinparam classAttributeFontColor #FFFFFF


Class Diary {
 - diaryName : DiaryName
 - pages : Page
 + getDiaryName()
 + getPages()
}

Class DiaryName {
 - fullName : String
 + isValidDiaryName()
}

Class Page {
 - title : Title
 + getTitle()
}

Class Title {
 - fullTitle : String
 + isValidTitle()
}

Diary *-down-> "1" DiaryName : has unique >
Diary *-left-> "*" Page : can contain many >

Page *-down-> "1" Title : has unique

show members
@enduml

