@startuml
scale 3/4
start
:User executes display command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
'Beta syntax also does not support multiple alternate paths, hence multiple
'diamond are used instead.


if () then ([arguments valid])
    if () then ([arguments is "interviewee"])
    :signal TabListener;
    - TabListener signals Main Window
    - Main Window display interviewee tab
    else if () then ([arguments is "interviewer"])
    :signal TabListener;
        - TabListener signals Main Window
        - Main Window display interviewer tab
    else if () then ([arguments is "schedule"])
    :display schedule tab;
    - TabListener signals Main Window
    - Main Window display schedule tab
    endif
else ([arguments invalid])
    : throw invalid command exception;
    - display invalid command to user
endif
stop
@end uml
