@startuml
!include style.puml
skinparam backgroundColor #EEEBDC

skinparam sequence {
	ArrowColor MediumSpringGreen
	LifeLineBorderColor MidnightBlue
	LifeLineBackgroundColor MediumAquaMarine

	ParticipantBorderColor MidnightBlue
	ParticipantBackgroundColor MediumVioletRed
	ParticipantFontName Impact
	ParticipantFontSize 17
	ParticipantFontColor MOTIVATION

}
box Logic LOGIC_COLOR_T1
participant ":DoneTaskCommandParser" as A
participant ":DoneTaskCommand" as B
participant "CommandResult" as D
end box
box Model MODEL_COLOR_T1
participant ":UniqueDashboardList" as C
end box

 -> A: parse(done 1)
activate A

A -> B: DoneTaskCommand(1)
activate B

B -> C: doneDashboard(list)
activate C
C --> B:
destroy C

B -> D: new CommandResult(MESSAGE)
activate D
destroy B

 <- D: feedbackToUser

destroy A

@enduml
