@startuml
title EditReview

start

:User executes ""editreview"" command;
note left
  Arguments should
  contain valid review index,
  review description,
  cost, rating and date
end note

if (is a valid command) then (yes)
    :Parse arguments into a
    ""EditReviewCommand"" object;

    if (any field edited) then (yes)
            :Execute EditReviewCommand;
            note left
                    Edits review
            end note

            :Edits the review;

                :Show success message to the user;
    else (no)
            : Throw an exception;

            : Show error message to the user;
    endif





else (no)
    :Throw an exception;

    :Show error message to the user;
endif

stop

@enduml
