@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":iFridgeParser" as iFridgeParser LOGIC_COLOR
participant ":TemplateListParser" as TemplateListParser LOGIC_COLOR
participant ":TemplateItemParser" as TemplateItemParser LOGIC_COLOR
participant ":EditTemplateItemCommandParser" as EditTemplateItemCommandParser LOGIC_COLOR
participant "e:EditTemplateItemCommand" as EditTemplateItemCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(args1)
activate LogicManager

LogicManager -> iFridgeParser : parseCommand(args1)
activate iFridgeParser

create TemplateListParser
iFridgeParser -> TemplateListParser
activate TemplateListParser

TemplateListParser --> iFridgeParser
deactivate TemplateListParser

iFridgeParser -> TemplateListParser : parseCommand(args2)
activate TemplateListParser

create TemplateItemParser
TemplateListParser -> TemplateItemParser
activate TemplateItemParser

TemplateItemParser --> TemplateListParser
deactivate TemplateItemParser

TemplateListParser -> TemplateItemParser : parse(args3)
activate TemplateItemParser

create EditTemplateItemCommandParser
TemplateItemParser -> EditTemplateItemCommandParser
activate EditTemplateItemCommandParser

EditTemplateItemCommandParser --> TemplateItemParser
deactivate EditTemplateItemCommandParser

TemplateItemParser -> EditTemplateItemCommandParser : parse(args4)
activate EditTemplateItemCommandParser

create EditTemplateItemCommand
EditTemplateItemCommandParser -> EditTemplateItemCommand
activate EditTemplateItemCommand

EditTemplateItemCommand --> EditTemplateItemCommandParser : e
deactivate EditTemplateItemCommand

EditTemplateItemCommandParser --> TemplateItemParser : e
deactivate EditTemplateItemCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditTemplateItemCommandParser -[hidden]-> TemplateItemParser
destroy EditTemplateItemCommandParser

TemplateItemParser --> TemplateListParser : e
deactivate TemplateItemParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TemplateItemParser -[hidden]-> TemplateListParser
destroy TemplateItemParser

TemplateListParser --> iFridgeParser : e
deactivate TemplateListParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TemplateListParser -[hidden]-> iFridgeParser
destroy TemplateListParser

iFridgeParser --> LogicManager : e
deactivate iFridgeParser

LogicManager -> EditTemplateItemCommand : execute()
activate EditTemplateItemCommand

ref over EditTemplateItemCommand, Model : Retrieve and edit specified template, template items and update templateList

EditTemplateItemCommand -> Model: setTemplate(templateToEdit, EditedTemplate)
activate Model

Model --> EditTemplateItemCommand
deactivate Model

EditTemplateItemCommand -> Model: setShownTemplate(editedTemplate)
activate Model

Model --> EditTemplateItemCommand
deactivate Model

create CommandResult
EditTemplateItemCommand -> CommandResult
activate CommandResult

CommandResult --> EditTemplateItemCommand
deactivate CommandResult

EditTemplateItemCommand --> LogicManager : result
deactivate EditTemplateItemCommand

[<--LogicManager
deactivate LogicManager
@enduml
