@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SchedulerParser" as SchedulerParser LOGIC_COLOR
participant ":EmailCommandParser" as EmailCommandParser LOGIC_COLOR
participant "e:EmailCommand" as EmailCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Interviewee" as Interviewee MODEL_COLOR
end box

[-> LogicManager : execute("email ct/timeslot Alice")
activate LogicManager

LogicManager -> SchedulerParser : parseCommand("email ct/timeslot Alice")
activate SchedulerParser

create EmailCommandParser
SchedulerParser -> EmailCommandParser
activate EmailCommandParser

EmailCommandParser --> SchedulerParser
deactivate EmailCommandParser

SchedulerParser -> EmailCommandParser : parse("ct/timeslot Alice")
activate EmailCommandParser

EmailCommandParser -> EmailCommandParser : parseTimeslotCommand(emailArgs)
activate EmailCommandParser

EmailCommandParser -> ParserUtil : <<static>> \n parseName("Alice")
activate ParserUtil

ParserUtil --> EmailCommandParser : name
deactivate ParserUtil

create EmailCommand
EmailCommandParser -> EmailCommand : name
activate EmailCommand

EmailCommand --> EmailCommandParser : e
deactivate EmailCommand

EmailCommandParser --> EmailCommandParser : e
deactivate EmailCommandParser

EmailCommandParser --> SchedulerParser : e
deactivate EmailCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EmailCommandParser -[hidden]-> SchedulerParser
destroy EmailCommandParser

SchedulerParser --> LogicManager : e
deactivate SchedulerParser

LogicManager -> EmailCommand : execute()
activate EmailCommand

EmailCommand -> EmailCommand : executeTimeslotCommand()
activate EmailCommand

EmailCommand -> Model : getUnfilteredIntervieweeList()
activate Model

Model --> EmailCommand : intervieweeList
deactivate Model

loop interviewee in intervieweeList
    EmailCommand -> Interviewee : getName()
    activate Interviewee

    Interviewee --> EmailCommand : name
    deactivate Interviewee

    EmailCommand -> Interviewee : name.equals(intervieweeName)
    activate Interviewee

    Interviewee --> EmailCommand : equality
    deactivate Interviewee

    break equality
        EmailCommand --> EmailCommand : intervieweeToEmail
    end
end

EmailCommand -> Model : emailInterviewee(intervieweeToEmail)
activate Model

Model -> Interviewee : setEmailSent(true)
activate Interviewee

Interviewee --> Model
deactivate Interviewee

Model --> EmailCommand
deactivate Model

create CommandResult
EmailCommand -> CommandResult
activate CommandResult

CommandResult --> EmailCommand
deactivate CommandResult

EmailCommand --> LogicManager : result
deactivate EmailCommand

[<--LogicManager
deactivate LogicManager
@enduml
