@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EnqueueCommandParser" as EnqueueCommandParser LOGIC_COLOR
participant ":ReversibleActionPair" as ReversibleActionPair LOGIC_COLOR
participant "EnqueueCommand" as EnqueueCommand LOGIC_COLOR
participant "DequeueCommand" as DequeueCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("enqueue 001A")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("enqueue 001A")
activate AddressBookParser

create EnqueueCommandParser
AddressBookParser -> EnqueueCommandParser
activate EnqueueCommandParser

EnqueueCommandParser --> AddressBookParser
deactivate EnqueueCommandParser

AddressBookParser -> EnqueueCommandParser : parse("001A")
activate EnqueueCommandParser

EnqueueCommandParser -> ReversibleActionPair
activate ReversibleActionPair

ReversibleActionPair -> EnqueueCommand : EnqueueCommand("001A")
activate EnqueueCommand

EnqueueCommand --> ReversibleActionPair
deactivate EnqueueCommand

ReversibleActionPair -> DequeueCommand : DequeueCommand("001A")
activate DequeueCommand

DequeueCommand --> ReversibleActionPair
deactivate DequeueCommand

ReversibleActionPair --> EnqueueCommandParser : ReversibleActionPair(EnqueueCommand, DequeueCommand)
deactivate ReversibleActionPair

EnqueueCommandParser --> AddressBookParser
deactivate EnqueueCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EnqueueCommandParser -[hidden]-> AddressBookParser
destroy EnqueueCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> EnqueueCommand : execute()
activate EnqueueCommand

EnqueueCommand -> Model : enqueuePatient("001A")
activate Model

Model --> EnqueueCommand
deactivate Model

create CommandResult
EnqueueCommand -> CommandResult
activate CommandResult

CommandResult --> EnqueueCommand
deactivate CommandResult

EnqueueCommand --> LogicManager : result
deactivate EnqueueCommand

[<--LogicManager
deactivate LogicManager
@enduml
