@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Package Entity {
    class Entity
    class Team
    class Participant
    class Mentor

   Participant .up.|> Entity
   Team .up.|> Entity
   Mentor .up.|> Entity
}
@enduml

