@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package EntityList <<Rectangle>> {
    class EntityList
    EntityList *-down-> "1" ObservableList
    EntityList *-down-> "1" UnmodifiableObservableList
}

@enduml
