@startuml
(*) --> "Get Timer"
if "" then
    -->[timer == 0] if "" then
        -->[cards left] ===B1===
        ---> "show card front"
        ---> "request user input"
        ---> "evaluate user input"
        if "" then
            -->[correct] "update score"
            --> "show card back"
        else
            -->[wrong] "show card back"
        endif
        -->===B2===




@enduml