@startuml

class Expense
class Description
class Price
class Timestamp
class Category
class UniqueIdentifier
class Budget

Description "1" <-- Expense
Description "1" <-- Expense
Price "1" <-- Expense
Timestamp "1" <-- Expense
Category "1" <-- Expense
UniqueIdentifier "1" <-- Expense
Budget "1" <.. Expense

class Expense {
getDescription(): Description
getPrice(): Price
getTimestamp(): Timestamp
getUniqueIdentifier(): UniqueIdentifier
getBudgetName(): Description
getCategory(): Category
isSameExpense(e: Expense): boolean
setBudget(b: Budget)
}

@enduml
