@startuml
(*)  --> "check tab name in the tab list"
if "tab name matches" then
    -->[true] "Fetch Tab Information"
    --> "setController of matching tab name"
    --> "Return fetched tab"
    -->(*)
else
    -->[false] (*)
@enduml
