@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":FillCommandParser" as FillCommandParser LOGIC_COLOR
participant "f:FillCommand" as FillCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "fi:FilteredList<Incident>" as FilteredList MODEL_COLOR
participant "updatedIncident:Incident" as Incident MODEL_COLOR
end box

[-> FillCommandParser : parse([args])
activate FillCommandParser

create FillCommand
FillCommandParser -> FillCommand
activate FillCommand

FillCommand --> FillCommandParser
deactivate FillCommand

[<--FillCommandParser : f
deactivate FillCommandParser

[-> FillCommand : execute()
activate FillCommand

destroy FillCommandParser

FillCommand -> Model : getFilteredIncidentList()
activate Model

Model --> FillCommand : fi
deactivate Model

FillCommand -> FilteredList : get([INDEX])
activate FilteredList

FilteredList --> FillCommand : incidentToFill
deactivate FilteredList

create Incident
FillCommand -> Incident
activate Incident

Incident --> FillCommand : updatedIncident
deactivate Incident

FillCommand -> Model : remove(incidentToFill)
activate Model

Model --> FillCommand
deactivate Model

FillCommand -> Model : add(updatedIncident)
activate Model

Model --> FillCommand
deactivate Model

[<-- FillCommand : resultMessage
deactivate FillCommand

destroy FillCommand

@enduml