@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":IncidentManagerParser" as IncidentManagerParser LOGIC_COLOR
participant ":SearchIncidentsCommandParser" as SearchIncidentsCommandParser LOGIC_COLOR
participant "l:SearchIncidentsCommand" as SearchIncidentsCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "filteredIncidents:FilteredList<Incident>" as FilteredList MODEL_COLOR
end box
[-> LogicManager : execute("search op/Alex")
activate LogicManager

LogicManager -> IncidentManagerParser : parseCommand("search op/Alex")
activate IncidentManagerParser

create SearchIncidentsCommandParser
IncidentManagerParser -> SearchIncidentsCommandParser
activate SearchIncidentsCommandParser

SearchIncidentsCommandParser --> IncidentManagerParser
deactivate SearchIncidentsCommandParser

IncidentManagerParser -> SearchIncidentsCommandParser : parse("Alex")
activate SearchIncidentsCommandParser

SearchIncidentsCommandParser -> Model : "Alex"
activate Model
Model --> SearchIncidentsCommandParser : predicate
deactivate Model

create SearchIncidentsCommand
SearchIncidentsCommandParser -> SearchIncidentsCommand : predicate
activate SearchIncidentsCommand

SearchIncidentsCommand --> SearchIncidentsCommandParser : l
deactivate SearchIncidentsCommand

SearchIncidentsCommandParser --> IncidentManagerParser : l
deactivate SearchIncidentsCommandParser

IncidentManagerParser --> LogicManager : l
deactivate IncidentManagerParser
destroy SearchIncidentsCommandParser

LogicManager -> SearchIncidentsCommand : execute()
activate SearchIncidentsCommand

SearchIncidentsCommand -> Model : updatedFilteredIncidentList(predicate)
activate Model

Model -> FilteredList : setPredicate(predicate)
activate FilteredList
 FilteredList --> Model :
deactivate FilteredList

Model --> SearchIncidentsCommand
deactivate Model

SearchIncidentsCommand -> Model : getFilteredIncidentList
activate Model

Model --> SearchIncidentsCommand
deactivate Model

SearchIncidentsCommand -> SearchIncidentsCommand : size()

SearchIncidentsCommand --> LogicManager : commandResult
deactivate SearchIncidentsCommand
SearchIncidentsCommand -[hidden]-> LogicManager : commandResult

[<--LogicManager
deactivate LogicManager
@enduml
