@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

FolderStructure -down-> "1" Folder
FolderStructure -> "*" FolderStructure
@enduml
