@startuml
package ui.game {
    class StartWindow
    class Tab
    class MainWindow
    abstract class UiPart<Region>
    class GameWindow
    class PlayerInformation
    class GameBody
    class MovingWord
}

package game {
    class Player
    class Words
}

UiPart <- Tab
UiPart <|-- MainWindow
UiPart <|- StartWindow
UiPart <|-- GameWindow
UiPart <|-- GameBody
UiPart <|-- PlayerInformation
UiPart <|-- MovingWord

MainWindow *--> Tab
MainWindow ..> StartWindow
StartWindow -right--> "0...1" GameWindow
GameWindow -down--> "1" GameBody
GameWindow -down--> "1" PlayerInformation

MovingWord .down.> Words
GameWindow .down.> Player
GameBody .down.> Player
GameBody .right.> "*" MovingWord
PlayerInformation .down.> Player

@enduml
