@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":PdfCreator" as PdfCreator MODEL_COLOR
participant ":TaskManager" as TaskManager MODEL_COLOR
participant ":PdfWrapperLayout" as PdfWrapperLayout MODEL_COLOR
end box


[-> Model : saveDriverTaskPdf( \n FILEPATH*, 5/11/2019)
note right: FILEPATH*: "./data/DeliveryTasks 2019-11-5".pdf"
activate Model

create PdfCreator
Model -> PdfCreator : new PdfCreator(FILEPATH*)
activate PdfCreator

PdfCreator --> Model
deactivate PdfCreator

Model -> TaskManager : getList()
activate TaskManager

TaskManager --> Model: tasks
deactivate TaskManager

Model -> TaskManager : getDriversFromTasks()
activate TaskManager

TaskManager --> Model: drivers
deactivate TaskManager

Model -> PdfCreator : saveDriverTaskPdf(tasks, drivers, 5/11/2019)
activate PdfCreator

PdfCreator -> PdfCreator ++: createDocument()
PdfCreator --> PdfCreator --: document

PdfCreator -> PdfCreator ++: insertCoverPage(document, 5/11/2019)
PdfCreator --> PdfCreator --

PdfCreator -> PdfCreator ++: insertDriverTask(document, 5/11/2019)

create PdfWrapperLayout
PdfCreator -> PdfWrapperLayout :  new PdfWrapperLayout(document)
activate PdfWrapperLayout

PdfWrapperLayout --> PdfCreator
deactivate PdfWrapperLayout

PdfCreator -> PdfWrapperLayout : populateDocumentWithTasks(tasks, 5/11/2019);
activate PdfWrapperLayout

PdfWrapperLayout --> PdfCreator
deactivate PdfWrapperLayout

PdfCreator --> PdfCreator --

PdfCreator --> Model
deactivate PdfCreator

[<-- Model
deactivate Model

@enduml
