@startuml
title: Activity : Execute Generate Command
start
:User executes generate command;
note left: e.g. "generate lower/false"

if () then ([no prefixes used])
    : Create default configuration;
    note left: GeneratePasswordDescriptor
    else ([else])
    : Create custom configuration;
endif

:System executes command
using given configuration;
note left: LogicManager

repeat
    :Password is generated randomly
    based on configuration;
    note left: GeneratorUtil
repeat while () is (Password does not \n contain all required fields)
->Else;
stop

@enduml
