@startuml
start

:Check user input for prefix;
note left: GeneratePasswordCommandParser

if () then ([no prefixes used])
    : Create GeneratePasswordDescriptor
    with default configuration;
    note left: StorageManager
    else ([else])
    : Create GeneratePasswordDescriptor
    with custom configuration;
endif

:GeneratePasswordCommand is executed
using given configuration;
note left: LogicManager

repeat
    :Password is generated randomly
    based on configuration;
    note left: GeneratorUtil
repeat while (User requirment met?) is (no)
->yes;
stop

@enduml