@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command generates PDF])
    :Execute Report Generator;
    :Generate PDF Report;
else ([command does not generate PDF])
endif
stop
@enduml
