@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command generates PDF])
    :Parse bodyId and signature;
    :Execute Report Generator;
    :Generate PDF report for bodyId
    and add signature;
else ([command does not generate PDF])
endif
stop
@enduml
