@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GenReportCommandParser" as GenReportCommandParser LOGIC_COLOR
participant "g:GenReportCommand" as GenReportCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":ReportGenerator" as Storage STORAGE_COLOR
end box

box iText ITEXT_COLOR
participant ":Document" as Document ITEXT_COLOR_T1
participant ":PdfWriter" as PdfWriter ITEXT_COLOR_T1
end box

[-> LogicManager : execute("genReport B1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("genReport B1")
activate AddressBookParser

create GenReportCommandParser
AddressBookParser -> GenReportCommandParser
activate GenReportCommandParser

GenReportCommandParser --> AddressBookParser
deactivate GenReportCommandParser

AddressBookParser -> GenReportCommandParser : parse("B1")
activate GenReportCommandParser

create GenReportCommand
GenReportCommandParser -> GenReportCommand
activate GenReportCommand

GenReportCommand --> GenReportCommandParser : g
deactivate GenReportCommand

GenReportCommandParser --> AddressBookParser : g
deactivate GenReportCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GenReportCommandParser -[hidden]-> AddressBookParser
destroy GenReportCommandParser

AddressBookParser --> LogicManager : g
deactivate AddressBookParser

LogicManager -> GenReportCommand : execute()
activate GenReportCommand

GenReportCommand -> Storage : generate(body)
activate Storage

create Document
Storage -> Document
activate Document
Document --> Storage
deactivate Document

Storage -> PdfWriter : getInstance(document, new FileOutputStream("Report B00000001.pdf")
PdfWriter --> Storage

Storage -> Storage : addHeader(document, "Mortago Report for B00000001")
activate Storage
Storage -> Document : open()
Document --> Storage
Storage --> Storage
deactivate Storage

Storage -> Storage : addPersonalDetails(document, body)
activate Storage
Storage --> Storage
deactivate Storage

Storage -> Storage : addNokDetails(document, body)
activate Storage
Storage --> Storage
deactivate Storage

Storage -> Storage : addOtherDetails(document, body)
activate Storage
Storage --> Storage
deactivate Storage

Storage -> Storage : addFooter(document, writer)
activate Storage
Storage -> Document : close()
Document --> Storage
Storage -> PdfWriter : close()
PdfWriter --> Storage
Storage --> Storage

Storage --> GenReportCommand
deactivate Storage

create CommandResult
GenReportCommand -> CommandResult
activate CommandResult

CommandResult --> GenReportCommand
deactivate CommandResult

GenReportCommand --> LogicManager : result
deactivate GenReportCommand

[<--LogicManager
deactivate LogicManager
@enduml
