@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Graphs {

Class "{abstract}\n Graph" as Graph
Class "{abstract}\nAutoCompleteGraph" as AutoCompleteGraph
Class "{abstract}\nGraphWithStartNode" as GraphWithStartNode
Class "{abstract}\nGraphWithStartNodeAndPreamble" as GraphWithStartNodeAndPreamble
Class Edge

package Add {
Class AddCustomerGraph
Class AddOrderGraph
Class AddPhoneGraph
Class AddScheduleGraph
}

package Edit {
Class EditCustomerGraph
Class EditOrderGraph
Class EditPhoneGraph
Class EditScheduleGraph
}

package Stats {
Class GenerateStatsGraph
}

package View {
Class ViewScheduleGraph
}

}

AutoCompleteGraph -up|> Graph
GraphWithStartNode -up|> AutoCompleteGraph
GraphWithStartNodeAndPreamble -up|> GraphWithStartNode

Graph *-left> "*" Edge

ViewScheduleGraph --|> GraphWithStartNode
GenerateStatsGraph --|> GraphWithStartNode
AddCustomerGraph --|> GraphWithStartNode
AddPhoneGraph --|> GraphWithStartNode
AddOrderGraph --|> GraphWithStartNode

AddScheduleGraph --|> GraphWithStartNodeAndPreamble
EditCustomerGraph --|> GraphWithStartNodeAndPreamble
EditOrderGraph --|> GraphWithStartNodeAndPreamble
EditScheduleGraph --|> GraphWithStartNodeAndPreamble
EditPhoneGraph --|> GraphWithStartNodeAndPreamble

@enduml
