@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface HistoryManagerStorage <<Interface>>

Class JsonHistoryManagerStorage
Class "{abstract}\nJsonAdaptedCommand"

JsonHistoryManagerStorage .up.|> HistoryManagerStorage
JsonHistoryManagerStorage o-down-> "{abstract}\nJsonAdaptedCommand"
@enduml