@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":HistoryWindow" as HistoryWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
participant ":HistoryCommandParser" as HistoryCommandParser LOGIC_COLOR
participant "command : HistoryCommand" as HistoryCommand LOGIC_COLOR
end box

-> MainWindow : executeCommand("history -h")
activate MainWindow

MainWindow -> Logic: execute("history -h")
activate Logic
Logic -> HistoryCommandParser: parse(" -h")
activate HistoryCommandParser
create HistoryCommand
HistoryCommandParser -> HistoryCommand
activate HistoryCommand
HistoryCommand --> HistoryCommandParser
deactivate HistoryCommand
HistoryCommandParser -> Logic: command
deactivate HistoryCommandParser
Logic -> HistoryCommand : execute(model)
activate HistoryCommand
HistoryCommand -> Logic : commandResult
note right: showHistory and hideOutput\n flags in commandResult\n is set to true.
deactivate HistoryCommand

Logic -> MainWindow: commandResult
deactivate Logic

<- MainWindow: setFeedBackToUser("Displaying history window.")

MainWindow -> HistoryWindow : setHideOutputDisplay(true)
activate HistoryWindow
HistoryWindow --> MainWindow : Command feedbacks\nhidden
deactivate HistoryWindow

MainWindow -> HistoryWindow : show()
activate HistoryWindow
HistoryWindow --> MainWindow : showing history \nwindow
deactivate HistoryWindow

MainWindow -> Logic : getCommandHistory()
activate Logic
Logic -> MainWindow: commandHistory
deactivate Logic

MainWindow -> HistoryWindow: updateHistoryDisplay(commandHistory)
activate HistoryWindow
HistoryWindow --> MainWindow: History display \n updated
deactivate HistoryWindow

<-- MainWindow: history command executed
deactivate MainWindow

destroy HistoryCommandParser
destroy HistoryCommand


@enduml
