@startuml
scale 3/4
start
:User inputs import command;
while () is ([incorrect command format])
    :Shows correct command format and \nprompts user to try again;
endwhile ([correct command format])

if () then ([input file exists])
    :Reads data from specified file;
    if () then ([data is in correct format])

        :Adds data into Model;
    else ([else])
        :Displays error message in UI;
    endif
else ([else])
    :Displays 'FILE_NOT_FOUND'\n error message in UI;
endif
stop
@enduml
