@startuml
start
:User input an import command;
if () then (valid csv)
:parse the rows in the file;
:create a valid Spending list;
  :read a Spending from list;
  :add Spending list to Model;
else (invalid csv)
endif
stop
@enduml
