@startuml
!include style.puml

start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([input is not empty and only single input])
    if () then ([command word exists])
        : Open new InfoWindow displaying the command information;
        else([else])
        endif
    else([else])
endif
stop
@enduml
