@startuml
!include style.puml

participant ":MainApp" as MainApp MODEL_COLOR_T1

box Storage STORAGE_COLOR_T1
participant "<<class>>\n:TestStorage" as TestStorage STORAGE_COLOR
end box

box UI UI_COLOR_T1
participant "<<class>>\n:DialogManager" as DialogManager UI_COLOR
end box

box Logic LOGIC_COLOR_T
end box

box Model MODEL_COLOR_T
end box

[-> MainApp : start(primaryStage)
activate MainApp

MainApp -> TestStorage : isUserExist()
activate TestStorage

TestStorage --> MainApp : userExists
deactivate TestStorage

alt user does not exist
    MainApp -> DialogManager : showCreatePasswordDialog()
    activate DialogManager

    DialogManager --> MainApp : password
    deactivate DialogManager

    MainApp -> TestStorage : initPassword(password)
    activate TestStorage
    deactivate TestStorage

else user exists
    loop password is incorrect
        MainApp -> DialogManager : showValidatePasswordDialog()
        activate DialogManager

        DialogManager --> MainApp : password
        deactivate DialogManager

        MainApp -> TestStorage : testPassword(password)
        activate TestStorage

        TestStorage --> MainApp : isCorrect
        deactivate TestStorage
    end

end

MainApp -> MainApp : initWithPassword(password)
activate MainApp

@enduml
