@startuml

start
:User executes Display command;
if () then ([Valid Type and Index]          )
    :Locate target projection;
    :Display target projection from current user state;
    :Display success message;
else (          [else])
    :Display error message;
endif
stop

@enduml
