@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam classAttributeIconSize 0
show members

class InterviewSlotVertex {
    -item: InterviewSlot
    -partner: IntervieweeVertex
}

class InterviewSlot {
    -interviewer: Interviewer
    -slot: Slot
}

InterviewSlotVertex o-right-"1" InterviewSlot

@enduml
