@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ITEM_COLOR_T4
skinparam classBackgroundColor ITEM_COLOR

package Item {
class ItemBuilder
class Item {
    - Task : task
    - Event : event
    - Reminder : reminder
    - Priority : priority
    - Hashset<Tag> : tags
    - ItemDescription : itemDescription

}
class Task
class Event
class Reminder
class Task
class Tag
ItemBuilder .right.> Item: creates >
Item "0..1  " .up.-o Task
Item "   0..1" .up.--o Event
Item "\n\n0..1" .up.-o Reminder
enum Priority {
  HIGH
  MEDIUM
  LOW
}
Item " 1" .left.--* ItemDescription
Item "1" .left.--* Priority
Item "                          \n\n*" .up.---o Tag
@enduml
