@startuml
'!include ../../plantuml-styles/plantuml-ae.iuml

skinparam Shadowing false
skinparam ArrowFontStyle normal
skinparam ArrowFontName Courier
skinparam ArrowFontSize 10


title Use Case diagram for itinerary\n

actor User
actor :Summary\nSystem: as Summary
actor Calendar

note top of Calendar #white
"The calendar and itinerary work in tandem,
with the calendar giving a visual representation
of the events in the itinerary event list."
end note

rectangle "Event List in itinerary" {
  Calendar -left- (Update visually upon inputting event)

  User -right- (Add event)
  User -right- (Delete event)
  User -right- (Edit event)
  User -right- (Search event)

  Summary -right- (Calculate stats)
  (Itinerary events in event list\nstatistics to user) <. (Calculate stats): include

  (Add event) -left- (Update visually upon inputting event)
  (Delete event) -left- (Update visually upon inputting event)
  (Edit event) -left- (Update visually upon inputting event)

  (Calculate stats) -[hidden]up- (Search event)
  (Delete event) -[hidden]up- (Add event)
  (Edit event) -[hidden]up- (Delete event)
  (Search event) -[hidden]up- (Edit event)
}

Calendar -[hidden]down-> User
Summary -[hidden]up-> User


'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml