@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Package Model <<Rectangle>>{
Class Model
Class Predicate
Class EventList

Package Event {
Class Event
Class Title
Class Date
Class Time
Class Location
Class Description
}

Model --> "1" Event : filtered list
Model --> "1" Predicate
Predicate --> Event

Itinerary *--> "1" EventList : Generates >
EventList o--> "*" Event
Event *-->"1" Title
Event *-->"1" Date
Event *-->"1" Time
Event *-->"1" Location
Event *-->"1" Description

@enduml
