@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Ledger <<Rectangle>>{

Class Ledger
Package Transaction {
Interface LedgerOperation <<Interface>>

Class Transaction <<abstract>>

Class Amount

Package {
Class Split
Class LendMoney
Class Payment
Class ReceiveMoney

}

Class UniquePersonList

}
}

Class HiddenOutside #FFFFFF

'UniquePersonList
UniquePersonList ---"*" Person

Transaction ---"1" Amount
Transaction ---"1" Date

'ledger operation
Ledger o--> LedgerOperation
Ledger --- UniquePersonList
Split .up.|> LedgerOperation
Payment .up.|> LedgerOperation
LendMoney .up.|> Payment
ReceiveMoney .up.|> Payment

Split --> Transaction
Split --- LendMoney
Payment --> Transaction


@enduml
