@startuml
!include style.puml

skinparam MinClassWidth 0
skinparam ParticipantPadding 0

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SaveNusParser" as SaveNusParser LOGIC_COLOR
participant ":PreferenceCommandParser" as PreferenceCommandParser LOGIC_COLOR
participant "d:LikeCommand" as LikeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":UserRecommendations" as UserRecommendations MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR
participant ":JsonRecsStorage" as JsonRecsStorage STORAGE_COLOR
participant ":JsonSR" as JsonSR STORAGE_COLOR
participant ":JsonAR" as JsonAR STORAGE_COLOR
end box

legend top
Legend:
* CS: categorySet
* TS: tagSet
* LS: locationSet
* JsonSR: JsonSerializableRecs
* JsonAR: JsonAdaptedRecs
end legend

[-> LogicManager : execute("like c/Thai")
activate LogicManager

LogicManager -> SaveNusParser : parseCommand("like c/Thai")
activate SaveNusParser

create PreferenceCommandParser
SaveNusParser -> PreferenceCommandParser
activate PreferenceCommandParser

PreferenceCommandParser --> SaveNusParser
deactivate PreferenceCommandParser

SaveNusParser -> PreferenceCommandParser : parse("c/Thai", true)
activate PreferenceCommandParser

create LikeCommand
PreferenceCommandParser -> LikeCommand
activate LikeCommand

LikeCommand --> PreferenceCommandParser : d
deactivate LikeCommand

PreferenceCommandParser --> SaveNusParser : d
deactivate PreferenceCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
PreferenceCommandParser -[hidden]-> SaveNusParser
destroy PreferenceCommandParser

SaveNusParser --> LogicManager : d
deactivate SaveNusParser

LogicManager -> LikeCommand : execute()
activate LikeCommand

LikeCommand -> Model : addLikes(CS, TS, LS)
activate Model

Model --> UserRecommendations : addLikes(CS, TS, LS)
activate UserRecommendations

UserRecommendations --> Model
deactivate UserRecommendations

Model --> LikeCommand
deactivate Model

create CommandResult
LikeCommand -> CommandResult
activate CommandResult

CommandResult --> LikeCommand
deactivate CommandResult

LikeCommand --> LogicManager : result
deactivate LikeCommand

LogicManager -> Storage : saveRecs(model.getRecommendationSystem().getUserRecommendations())
activate Storage

Storage -> JsonRecsStorage : saveRecs(recs)
activate JsonRecsStorage

create JsonSR
JsonRecsStorage -> JsonSR
activate JsonSR

create JsonAR
JsonSR -> JsonAR
activate JsonAR

JsonAR --> JsonSR
deactivate JsonAR

JsonSR --> JsonRecsStorage
deactivate JsonSR

JsonRecsStorage --> Storage
deactivate JsonRecsStorage

Storage --> LogicManager
deactivate Storage

[<--LogicManager
deactivate LogicManager
@enduml
