@startuml
!include style.puml

start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Categories, tags and locations are valid])
    if () then ([Categories, tags and locations are not present in dislikes])
        :Add categories, tags and locations to UserRecommendations;
        :Save UserRecommendations to storage;
    else ([else])
    endif
else ([else])
endif
stop

@enduml
