@startuml

start
:user enters list command;
:identify parameter of list command;
if (no parameter?) then (yes)
    :display all persons;
elseif (is patient?) then (yes)
    :update list to show
        all patients;
elseif (is donor?) then (yes)
    :update list to show
        all donors;
elseif (is doctor?) then (yes)
    :update list to show
          all doctors;
else (invalid parameter)
    :display error message;
endif
stop
@enduml
