@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":IncidentManagerParser" as IncidentManagerParser LOGIC_COLOR
participant "l:ListIncidentsCommand" as ListIncidentsCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "filteredIncidents:FilteredList<Incident>" as FilteredList MODEL_COLOR
end box
[-> LogicManager : execute("list-i")
activate LogicManager

LogicManager -> IncidentManagerParser : parseCommand("list-i")
activate IncidentManagerParser

create ListIncidentsCommand
IncidentManagerParser -> ListIncidentsCommand : (PREDICATE_SHOW_ALL_INCIDENTS)
activate ListIncidentsCommand

ListIncidentsCommand --> IncidentManagerParser
deactivate ListIncidentsCommand

IncidentManagerParser --> LogicManager : l
deactivate IncidentManagerParser

LogicManager -> ListIncidentsCommand : execute()
activate ListIncidentsCommand

ListIncidentsCommand -> ListIncidentsCommand : handleAllIncidents()
activate ListIncidentsCommand

ListIncidentsCommand -> Model : updateFilteredIncidentList(PREDICATE_SHOW_ALL_INCIDENTS)
activate Model

Model -> FilteredList : setPredicate(PREDICATE_SHOW_ALL_INCIDENTS)
activate FilteredList
 FilteredList --> Model :
deactivate FilteredList

Model --> ListIncidentsCommand
deactivate Model

ListIncidentsCommand -> ListIncidentsCommand : MESSAGE_ALL_INCIDENTS_LISTED
deactivate ListIncidentsCommand

ListIncidentsCommand --> LogicManager : resultMessage
deactivate ListIncidentsCommand
ListIncidentsCommand -[hidden]-> LogicManager : resultMessage
destroy ListIncidentsCommand

[<--LogicManager
deactivate LogicManager
@enduml
