@startuml
!include style.puml
show members
left to right direction
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam ObjectAttributeFontSize 12

object "__loanRecords:LoanRecords__" as LoanRecords
object "__:Loan__" as Loan {
    renewCount = 0
    remainingFineAmount = 0
    paidFineAmount = 0
}
object "__loanId:LoanId__" as LoanId {
    value = "L000123"
}
object "__bookSerialNumber:SerialNumber__" as SerialNumber {
    value = "B00456"
}
object "__borrowerId:BorrowerId__" as BorrowerId {
    value = "K0789"
}
object "__startDate:LocalDate__" as startDate {
    year = 2019
    month = 10
    day = 10
}
object "__dueDate:LocalDate__" as dueDate {
    year = 2019
    month = 10
    day = 24
}
object "__:Book__" as Book
object "__:Borrower__" as Borrower
object "__currentLoanList:LoanList__" as currentLoanList
object "__returnedLoanList:LoanList__" as returnedLoanList

LoanRecords --> Loan
LoanRecords --> LoanId
Book --> Loan
Book --> SerialNumber
Borrower --> currentLoanList
Borrower --> returnedLoanList
currentLoanList --> Loan
returnedLoanList -[hidden]-> Loan
Borrower --> BorrowerId
Loan -> LoanId
Loan --> SerialNumber
Loan --> BorrowerId
Loan --> startDate
Loan --> dueDate

@enduml
