@startuml
start
:User enters input;
if () then ([Input is valid - includes tutorial name, module code, week, student name])
  :Marks attendance of student;
  :Feedback to user: success;
else ([Input does not include student name])
  :Pointer initializes at first student in specified tutorial;
  repeat
    :Prompts user to confirm attendance of student;
    if () then ([User inputs yes])
      :Marks attendance of student;
    else ([User inputs no or irrelevant command])
      :Does not mark attendance of student;
    endif
    :Points to next student;
  repeatWhile ([Has next student?]) is ([yes])
  ->no;
endif
stop
@enduml
