@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Match a Specific Patient

package ORGANice {
    class Patient1 as "__p1:Patient__"
    class Patient2 as "__p2:Patient__"
    class Donor1 as "__d1:Donor__"
    class Donor2 as "__d2:Donor__"
}

show object fields
package listOfMatches {
    object "<u>md1:MatchedDonor" as MatchedPatient1 {
        donor : d1
        successRate : 100
    }

    object "<u>md2:MatchedDonor" as MatchedPatient2 {
        donor : d2
        successRate : 66.67
    }
}

Patient1 -[hidden]right-> Patient2
Patient2 -[hidden]right-> Donor1
Donor1 -[hidden]right-> Donor2

ORGANice -[hidden]down-> listOfMatches
@end
