@startuml
start
:User likes a meme by index;

if () then ([User presses ENTER])
    :Weme updates the \nlike count of the \nmeme at the index \nonce;
else ([User presses [UP])
    repeat
    :Weme updates the \nlike count of the \nmeme at the index;
    repeat while () is ([User continues pressing [UP])
endif

stop
@enduml
