@startuml
start
:User enters meme creation mode;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:User adds text;

repeat
if () then ([User wants to add text])
    :User adds text;
else if () then ([User wants to edit text])
    :User edits text;
else ([User wants to delete text])
    :User deletes text;
endif
repeat while () is ([finished?])

:Weme generates new Meme, applying all text entered by the user;
stop
@enduml
