@startuml
start

:Prompt user for merge;
:User executes command;

while (has unprompted different fields)
    :prompt next merge;
    if () then (["yes" or ""])

    :update field;

    else (["no"])

    :skip merge;

    endif
endwhile
stop
@enduml
