@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ReferenceId <<Interface>>

Class AddressBook
Class ReadOnlyAddressBook
Class AppointmentBook
Class ReadOnlyAppointmentBook
Class Model
Class ModelManager

Class Tag

Package UserPrefs {
Class UserPrefs
Class ReadOnlyUserPrefs
}

Package Person {
Class Person
Class Address
Class Email
Class Name
Class Phone
Class PersonReferenceId
}

Package Events {
Class Event
Class Timing
Class DateTime
Class Status
}

Package Queue {
Class QueueManager
Class QueueList
Class Room
}

Package common {
Interface Identical <<Interface>>
}

}

Class HiddenOutside #FFFFFF
HiddenOutside .down-> Model

AddressBook .up.|> ReadOnlyAddressBook
AddressBook --> Person

AppointmentBook .up.|> ReadOnlyAppointmentBook
AppointmentBook --> Event

UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager .up.-|> Model

ReferenceId .-|> Identical
PersonReferenceId .up.|> ReferenceId

Person .up.-|> Identical
Person *.-|> ReferenceId
Person *-down-> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *-left-> "*" Tag

Timing *--> DateTime
Timing -[hidden]right-> Status

Event .up.|> Identical
Event *.--|> ReferenceId
Event *--> Timing
Event *--> Status

Room .-|> Identical
Room *---|> "* ... 1" ReferenceId : Doctor
Room *---|> "* ... 1" ReferenceId : Patient


QueueManager *-down-> "1" QueueList
QueueManager *---> "*" Room
QueueList *.---|> ReferenceId

ModelManager -left--> "1" AddressBook : staff
ModelManager -left--> "1" AddressBook : patients
ModelManager -down--> "1" AppointmentBook : Appointments
ModelManager -down--> "1" AppointmentBook : StaffDutyRoster
ModelManager -right--> "1" UserPrefs
ModelManager ---> QueueManager

Person -[hidden]up----> Identical
Identical -[hidden]right----> ReferenceId
ReferenceId -[hidden]right-> Events


@enduml
