@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package CoursePlanner <<Rectangle>> {
    Class CoursePlanner
    Class UniqueCourseList
    Class Course
    Class CourseText

    Class Title
    Class CourseCode
    Class CourseCredit
    Class Faculty
    Class Description
    Class PrereqTree
    Class Preclusion
    Class FulfillRequirements
}

Course *-left-> "1" Title
Course *--> "1" CourseCode
Course *--> "1" CourseCredit
Course *--> "1" Faculty
Course *--> "1" Description
Course *--> "0..1" PrereqTree
Course *--> "0..1" Preclusion
Course *-right-> "0..1" FulfillRequirements
UniqueCourseList o--> "*" Course
CoursePlanner *--> "1" UniqueCourseList
CoursePlanner *--> "1" CourseText
@enduml
