@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFoodList <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class FoodList
Class ReadOnlyFoodList
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Food {
Class Food
Class FoodName
Class Calorie
Class Gi
Class Sugar
Class Fat
Class FoodType
Class UniqueFoodList
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FoodList .up.|> ReadOnlyFoodList

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" FoodList
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FoodList *--> "1" UniqueFoodList
UniqueFoodList o--> "*" Food
Food *--> FoodName
Food *--> Calorie
Food *--> Gi
Food *--> Sugar
Food *--> Fat
Food *--> FoodType

Calorie -down-|> NutritionValue
Gi -down-|> NutritionValue
Sugar -down-|> NutritionValue
Fat -down-|> NutritionValue


ModelManager -->"1" Food : filtered list
@enduml
