@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyMark <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Mark
Class ReadOnlyMark
Class VersionedMark
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class VersionedMark.MarkStateRecord

Package FolderStructure {
Class FolderStructure
}

Package Reminder {
'Class ReminderAssociation #FFFFFF
}

Package Autotag {
'Class AutotagController #FFFFFF
}

Package Bookmark {
Class HiddenB1 #FFFFFF
Class HiddenB2 #FFFFFF
}

Package Annotation {
Class A #FFFFFF
}

Package Predicates {
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .left.> ObservableList
ModelManager o-left-> "1" VersionedMark
ModelManager o-right-> "1" UserPrefs
ModelManager -down--> Bookmark : filtered list of >
'ModelManager --> "1" Url : < currently viewed online in
'ModelManager --> "1" Bookmark : < currently viewed offline in

UserPrefs .up.|> ReadOnlyUserPrefs

Mark .right.|> ReadOnlyMark
VersionedMark -down-|> Mark
VersionedMark *-left "*" VersionedMark.MarkStateRecord : contains >
VersionedMark.MarkStateRecord *-down> ReadOnlyMark

Mark *--> Bookmark
Mark *-right-> "1" FolderStructure
Mark *--> Reminder
Mark *--> Autotag

FolderStructure -[hidden]left-> Autotag
Autotag -[hidden]left-> Reminder

'UniqueBookmarkList o--> Bookmark
Bookmark -left-> Tag
Bookmark --> Annotation

HiddenB1 -[hidden]right-> HiddenB2

'should I show this?
'Reminder --> Url
Reminder -right-> Bookmark

Autotag --> Tag
Autotag -down-> Predicates

@enduml
