@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Package Model <<Rectangle>>{
Interface ObservableList <<Interface>>
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface Identical <<Interface>>
Interface ReferenceId <<Interface>>

Class AddressBook
Class ReadOnlyAddressBook
Class AppointmentBook
Class ReadOnlyAppointmentBook
Class Model
Class ModelManager

Class UniqueTagList
Class Tag

Package UserPrefs {
Class UserPrefs
Class ReadOnlyUserPrefs
}

Package UniqueList {
Class UniqueTreeList
Class UniqueElementList
Class UniquePersonList
}

Package Person {
Class Person
Class Address
Class Email
Class Name
Class Phone
Class UniquePersonList
Class PersonReferenceId
Class PatientReferenceId
Class StaffReferenceId
}

Package Events {
Class Appointment
Class DutyShift
Class Event
Class Timing
Class DateTime
Class Status
}

Package Queue {
Class QueueManager
Class QueueList
Class Room
}

}

Class HiddenOutside #FFFFFF
HiddenOutside .down-> Model

AddressBook .up.|> ReadOnlyAddressBook

AppointmentBook .up.|> ReadOnlyAppointmentBook

UserPrefs .up.|> ReadOnlyUserPrefs

Model .right.> ObservableList
ModelManager .up.-|> Model

AddressBook *-> "1" UniquePersonList
AddressBook *-> "1" UniqueTagList
UniqueTagList --> "*" Tag
AppointmentBook *--down-> "1" UniqueElementList : UniqueElementList<Appointment>
AppointmentBook *-down-> Appointment

UniqueTreeList *-> Identical
UniqueElementList *-down> UniqueTreeList
UniquePersonList -down-> "*" Person
UniquePersonList *-up> "1" UniqueElementList : UniqueElementList<Person>

ReferenceId .-|> Identical
PersonReferenceId .up.|> ReferenceId
PatientReferenceId *.up-> PersonReferenceId
StaffReferenceId *.left-> PersonReferenceId

Person .up.-|> Identical
Person *.-|> ReferenceId
Person *-down-> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *-left-> "*" Tag


Appointment *-down-> Event
Appointment *.-right|> "1" ReferenceId : Doctor
DutyShift *-> Event

Timing *--> DateTime
Timing -[hidden]right-> Status

Event .up.|> Identical
Event *.--|> ReferenceId
Event *--> Timing
Event *--> Status

Room .-|> Identical
Room *.---|> ReferenceId

QueueManager -up-> UniqueElementList : UniqueElementList<Room>
QueueManager *-down-> QueueList
QueueManager *-down-> Room
QueueList *.---|> ReferenceId


ModelManager -left--> "1" AddressBook : staff
ModelManager -left--> "1" AddressBook : patients
ModelManager -down--> "1" AppointmentBook : Appointments
ModelManager -down--> "1" AppointmentBook : StaffDutyRoster
ModelManager -right--> "1" UserPrefs

Person -[hidden]up----> Identical
Identical -[hidden]right----> ReferenceId
ReferenceId -[hidden]right-> Events
UniqueList -[hidden]down----> Identical


@enduml
