@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyPlanner <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Planner
Class ReadOnlyPlanner
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Field\n {
Class Address
Class H1 #FFFFFF
Class Name
}

Package ItineraryItem {
    Abstract Class ItineraryItem
    Package Activity {
    Class Activity
    Class UniqueActivityList
    }

    Package Accommodation {
    Class Accommodation
    Class UniqueAccommodationList
    }
}

Package Day {
Class ActivityWithTime
Class Day
Class Timetable
Class Itinerary
}

Package Contact {
Class Contact
Class Email
Class Phone
Class UniqueContactList
}
Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Planner .up.|> ReadOnlyPlanner

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Planner
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Planner *--> UniqueAccommodationList
Planner *--> UniqueContactList
Planner *--> UniqueActivityList
Planner *--> Itinerary

ItineraryItem *-->  Name
ItineraryItem *-[hidden]-> Name
ItineraryItem *-[hidden]-> Name
ItineraryItem *--> Address
ItineraryItem *--> "0..1  \n" Contact
ItineraryItem *-[hidden]-> Contact
ItineraryItem *-up-> "\n        *" Tag
ItineraryItem <|-- Accommodation
ItineraryItem <|-[hidden]- Accommodation

ItineraryItem <|-- Activity

UniqueActivityList o--> "         *" Activity
UniqueAccommodationList o--> "        *" Accommodation

UniqueContactList o--> "*" Contact

Contact *-->  Name
Contact *-[hidden]->  Phone
Contact *-[hidden]->  Phone
Contact *-->  Phone
Contact *-[hidden]-> "0..1" Email
Contact *-[hidden]-> "0..1" Email
Contact *--> "0..1" Email
Contact *-[hidden]-> "0..1" Address
Contact *-[hidden]-> "0..1" Address
Contact *--> "0..1" Address

Contact *-up-> "*" Tag


Itinerary o--> " *" Day
Day *--> Timetable
Timetable o--> " *" ActivityWithTime

Name -[hidden]right-> H1

@enduml
