@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":ViewCommand" as ViewCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "tml:TrackedModuleList" as TrackedModuleList MODEL_COLOR
participant "aml:TrackedModuleList" as ArchivedModuleList MODEL_COLOR
end box

activate ViewCommand

ViewCommand -> Model : getFilteredModuleList()
activate Model

Model --> ViewCommand : tml
deactivate Model

ViewCommand -> TrackedModuleList : Find matching module
activate TrackedModuleList

TrackedModuleList --> ViewCommand : Module
deactivate TrackedModuleList

opt module not found

    ViewCommand -> Model : getFilteredArchivedModuleList()
    activate Model
    Model --> ViewCommand : aml
    deactivate Model

    ViewCommand -> ArchivedModuleList : Find matching module
    activate ArchivedModuleList

    ArchivedModuleList --> ViewCommand : Module
    deactivate ArchivedModuleList
end

@enduml
