@startuml

interface NotesLogic {
    setNoteSubmissionChannel(channel)
    getAllNotesList()
    addNoteWithSketch(note, sketch)
    addNote(note)
    saveNoteFromSubmissionChannel()
    replaceNote(oldNote, newNote)
    getSelectedNote()
    selectNote(id)
    deleteNote(id)
}

@enduml
