@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":AddCommand" as AddCommand LOGIC_COLOR
participant "notifCommand:NotifCommand" as NotifCommand LOGIC_COLOR
end box

participant "ses:ScheduledExecutorService" as ScheduledExecutorService LOGIC_COLOR

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
participant "notif:Notif" as Notif MODEL_COLOR
end box

-> AddCommand :AddCommand(body)
create AddCommand
activate AddCommand
<-- AddCommand
deactivate AddCommand

-> AddCommand :execute()
activate AddCommand
    AddCommand -> Model :addEntity(body)
    activate Model
    Model --> AddCommand
    deactivate Model

    create Notif
    AddCommand -> Notif :Notif(body)
    activate Notif
    Notif --> AddCommand :notif
    deactivate Notif

    create ScheduledExecutorService
    create NotifCommand

    AddCommand -> NotifCommand :NotifCommand(notif, NOTIF_PERIOD, NOTIF_TIME_UNIT)
    activate NotifCommand
    NotifCommand --> AddCommand :notifCommand
    deactivate NotifCommand

    AddCommand -> NotifCommand :execute(model)
    activate NotifCommand
        NotifCommand -> Notif :getAlert()
        activate Notif
        Notif --> NotifCommand :alert
        deactivate Notif

        NotifCommand -> NotifCommand :startSesChangeBodyStatus()
        activate NotifCommand
        NotifCommand -> ScheduledExecutorService :schedule(alert, NOTIF_PERIOD, NOTIF_TIME_UNIT)
        activate ScheduledExecutorService
        ScheduledExecutorService --> NotifCommand

        deactivate NotifCommand
        deactivate ScheduledExecutorService


        NotifCommand -> NotifCommand :startSesChangeBodyStatusUi()
        activate NotifCommand
        ref over NotifCommand, ScheduledExecutorService : Runnable changeUI
        NotifCommand -> ScheduledExecutorService :schedule(changeUI, NOTIF_PERIOD, NOTIF_TIME_UNIT)
        activate ScheduledExecutorService
        ScheduledExecutorService --> NotifCommand

        deactivate ScheduledExecutorService

        deactivate NotifCommand

    NotifCommand --> AddCommand
    deactivate NotifCommand


deactivate AddCommand


@enduml
