@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface CustomerDatabaseStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonCustomerDatabaseStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> CustomerDatabaseStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonCustomerDatabaseStorage .left.|> CustomerDatabaseStorage
JsonCustomerDatabaseStorage .down.> JsonSerializableCustomerDatabaseStorage
JsonSerializableCustomerDatabaseStorage .right.> JsonSerializableCustomer
JsonSerializableCustomer .right.> JsonAdaptedTag
@enduml
