@startuml
start
:User logs Transaction;
if() then ([In Transaction])

:Income statement appended to Transaction list;
:BankAccount handles amount from Income;

else([Out Transaction])

:Expenditure statement appended to Transaction list;
:BankAccount handles amount from Expenditure;

endif

if() then ([In Transaction])

else([Out Transaction])
:Check if transaction has similar categories and is within the same time period as any Budget entries;

if(Within time period and similar categories) then ([yes])
:Budget's remaining amount to deduct from Transaction's amount;


else([no])

endif

endif

:Transaction appended to Transaction List;

stop
@enduml

