@startuml
!include style.puml
skinparam arrowThickness 1.3
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

show members
hide empty members

Package WordBankList <<Rectangle>>{
Interface ReadOnlyWordBankList <<Interface>> {
getFilteredWordBankList()
getWordBankFromName(String)
hasBankName(String)
}

class WordBankList {
   +addWordBank(ReadOnlyWordBank)
   +removeWordBank(WordBank)
}
Class UniqueWordBankList

WordBankList .left.|> ReadOnlyWordBankList
WordBankList o-down-> "1" UniqueWordBankList
UniqueWordBankList --> WordBank

show members
hide empty members

Package WordBank <<Rectangle>>{
Interface ReadOnlyWordBank <<Interface>> {
getName()
getCard(Index)
getCardList()
}

class WordBank {
   -name: String
   +addCard(Card)
   +removeCard(Card)
   +setCard(Card, Card)
   +hasCard(Card)
   +resetData(ReadOnlyWordBank)
}
Class UniqueCardList
Class Card


WordBank .left.|> ReadOnlyWordBank
WordBank o-down-> "1" UniqueCardList
UniqueCardList -down-> Card

show members
hide empty members

Package Card <<Rectangle>>{
Class Card {
- id: String
- tags: Set<Tag>
}
Class Word
Class Meaning
}

Card o--> "1" Word
Card o--> "1" Meaning

Meaning *-LEFT[hidden]-> Word
@enduml

