@startuml
:User executes command;
:UniversalParser parses command;

if () then ([command is universal command])
    :Return universal command;
else ([else])
    if () then ([current context is customer])
        :CustomerParser parses command;
    else ([current context is editing])
        split
            :hi;
        split again
            :do;
        end split
    endif
endif

:Executes command;
stop
@enduml