@startuml
:User executes command;
:UniversalParser parses command;

if () then ([command is universal command])
    :Return universal command;
else ([else])
    if () then ([current context is editing])
        :EditingParser parses command;
    else ([else])
        :ContextParser parses command;
        :Return context command;
    endif
endif

:Executes command;
stop
@enduml
