@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Participant {
    Participant .up.|> Entity
    Participant *-down-> Phone
    Participant *-down-> Email
}
@enduml
