@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor white

Package Password {
Class Password
Class PasswordValue
Class PasswordDescription
Class Username
Class UniquePasswordList
Class Website
Class PasswordModifiedAt
Class PasswordExpiredAt
Enum "<<enumeration>>\nExpiryMode" as ExpiryMode
}
show members
Enum ExpiryMode {
HEALTHY
EXPIRING
EXPIRED
}

Class PasswordValue {
value:String
getNonEncryptedPasswordValue()
getEncryptedPasswordValue()
}

Class PasswordDescription {
value:String
}

Class Username {
value:String
}

Class PasswordExpiredAt {
value: Date
}

Class Website {
value: String
}

Class PasswordModifiedAt {
value: Date
}

Class Password {
updateExpiry()
getNonEncryptedPasswordValue()
}

PasswordBook *--> "1" UniquePasswordList

UniquePasswordList o--> "*" Password
Password *--> "*" Tag

Password *--> PasswordValue
Password *--> PasswordDescription
Password *--> Username
Password *--> "0...1" Website
Password *--> PasswordModifiedAt
Password *--> PasswordExpiredAt
Password *--> ExpiryMode
ExpiryMode .-left-> PasswordExpiredAt
@enduml
