@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DeliverymenParser" as DeliverymenParser LOGIC_COLOR
participant "c:PayListCommand" as PayListCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":DeliverymenDatabase" as DeliverymenDatabase MODEL_COLOR
participant ":UniqueDeliverymenList" as UniqueDeliverymenList MODEL_COLOR
participant ":Deliveryman" as Deliveryman MODEL_COLOR
participant ":Analyzer" as Analyzer MODEL_COLOR
end box
[-> LogicManager : execute(paylist)
activate LogicManager

LogicManager -> DeliverymenParser : parseCommand(undo)
activate DeliverymenParser

create PayListCommand
DeliverymenParser -> PayListCommand
activate PayListCommand

PayListCommand --> DeliverymenParser : c
deactivate PayListCommand

DeliverymenParser --> LogicManager : c
deactivate DeliverymenParser

LogicManager -> PayListCommand : execute()
activate PayListCommand

PayListCommand -> Model : getPayList()
activate Model

Model -> DeliverymenDatabase : getDeliverymen()
activate DeliverymenDatabase

DeliverymenDatabase -> UniqueDeliverymenList : getDeliverymen()
activate UniqueDeliverymenList

UniqueDeliverymenList -> Deliveryman : getRecord()
activate Deliveryman

Deliveryman --> UniqueDeliverymenList : r:Record
deactivate Deliveryman

UniqueDeliverymenList --> DeliverymenDatabase : r:Record
deactivate UniqueDeliverymenList

DeliverymenDatabase -> Analyzer : plsAnalyzeThisRecord(r)
activate Analyzer

Analyzer --> DeliverymenDatabase: isEligible:Boolean(ok,bro)
deactivate Analyzer

DeliverymenDatabase -> DeliverymenDatabase: p.addToListIfEligible()
activate DeliverymenDatabase

DeliverymenDatabase --> DeliverymenDatabase
deactivate DeliverymenDatabase

DeliverymenDatabase --> Model : p:List
deactivate DeliverymenDatabase

Model --> PayListCommand: p:List
deactivate Model

PayListCommand --> LogicManager : result
deactivate PayListCommand
PayListCommand -[hidden]-> LogicManager : result
destroy PayListCommand

[<--LogicManager
deactivate LogicManager
@enduml
