@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant ":DeliverymenDatabase" as DeliverymenDatabase MODEL_COLOR
participant ":StatusManager" as StatusManager MODEL_COLOR
participant ":StatisticsManager" as StatisticsManager MODEL_COLOR
participant ":Analyzer" as Analyzer MODEL_COLOR
participant ":RecordCard" as RecordCard MODEL_COLOR
end box

[-> DeliverymenDatabase : analyzeDeliverymanStatus()
activate DeliverymenDatabase

DeliverymenDatabase -> StatusManager : getStatusLists()
activate StatusManager

StatusManager --> DeliverymenDatabase : statusLists: List[]
deactivate StatusManager

DeliverymenDatabase -> StatisticsManager : analyze(statusLists)
activate StatisticsManager

create RecordCard
StatisticsManager -> RecordCard : createRecordCard()
activate RecordCard

RecordCard --> StatisticsManager : emptyCard: RecordCard
deactivate RecordCard

StatisticsManager -> Analyzer : analyze(emptyCard)
activate Analyzer

Analyzer -> Analyzer : computeStatistics()
activate Analyzer

Analyzer -> RecordCard : editCard()
activate RecordCard

RecordCard --> Analyzer : editedCard: RecordCard
deactivate RecordCard

Analyzer --> Analyzer : editedCard
deactivate Analyzer

Analyzer --> StatisticsManager : editedCard
deactivate Analyzer

StatisticsManager --> DeliverymenDatabase : editedCard
deactivate StatisticsManager

[<--DeliverymenDatabase : editedCard
deactivate DeliverymenDatabase
@enduml
