@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "p:ScheduledPriorityCommand" as ScheduledPriorityCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "timer:Timer" as Timer MODEL_COLOR
participant ":TimerTask" as Task MODEL_COLOR
participant "result:TaskList" as VisualList MODEL_COLOR
participant ":Runnable" as Runnable MODEL_COLOR
end box
[-> LogicManager : execute(priority 30.min.later)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(priority 30.min.later)
activate AddressBookParser

create ScheduledPriorityCommand
AddressBookParser -> ScheduledPriorityCommand
activate ScheduledPriorityCommand

ScheduledPriorityCommand --> AddressBookParser
deactivate ScheduledPriorityCommand

AddressBookParser --> LogicManager : p
deactivate AddressBookParser

LogicManager -> ScheduledPriorityCommand : execute()
activate ScheduledPriorityCommand

ScheduledPriorityCommand -> Model : scheduleOffPriorityMode(LocalDateTime)
activate Model

create Timer
Model -> Timer : new Timer()
activate Timer
Timer --> Model
deactivate Timer

create Task
Model -> Task : new TimerTask()
activate Task

Task --> Model
deactivate Task

Model -> Timer : schedule(TimerTask, LocalDateTime)
activate Timer
deactivate Model

ScheduledPriorityCommand -> Model : togglePriorityMode()
activate Model

Model -> Model: toggleOnPriorityMode()
activate Model
create VisualList
Model -> VisualList : new TaskList()
activate VisualList
VisualList --> Model: result
deactivate VisualList

deactivate Model
Model -> ScheduledPriorityCommand: CommandResult
deactivate Model

ScheduledPriorityCommand --> LogicManager: CommandResult
destroy ScheduledPriorityCommand

[<--LogicManager : CommandResult
deactivate LogicManager

Timer -> Task : run()
activate Task

Task -> Model : toggleOffPriorityMode()
activate Model
destroy Task
Model -> Timer : cancel()
destroy Timer


create Runnable
Model -> Runnable : new Runnable()
activate Runnable
Runnable --> Model
deactivate Runnable

Model -> Runnable : run()
activate Runnable
loop
Runnable -> VisualList : add(Item)
activate VisualList
deactivate VisualList
end
destroy Runnable

deactivate Model

@enduml
