@startuml

interface ProgramExecutor {
    + CompletableFuture<ProgramOutput> : executeProgram(ClassFile program, ProgramInput input)
}

class ProgramOutput {
    + String : getOutput()
    + Optional<RuntimeError> : getRuntimeError()
    + ProgramOutput : append(String string)
    + ProgramOutput : appendNewLine(String string)
    + {static} ProgramOutput : getEmptyProgramOutput()
    + {static} ProgramOutput : getErroredProgramOutput(String errorMessage)
}

class ProgramInput {
    + String : getInput()
}

ProgramExecutor -> ProgramOutput
ProgramExecutor -> ProgramInput

@enduml
