@startuml

interface ProgramSubmissionLogic {
    getTestResultObservable()
    getCurrentQuestionObservable()
    setCurrentQuestion()
    submitUserProgram(userProgram)
    setUserProgramSubmissionChannel(channel)
    submitUserProgramFromSubmissionChannel()
    closeProgramSubmissionLogicManager()
}

@enduml
