@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ProjectCommandParser" as ProjectCommandParser LOGIC_COLOR
participant "p:ProjectCommand" as ProjectCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":ReadOnlyBankAccount" as ReadOnlyBankAccount MODEL_COLOR
participant "dc:DateComparator" as DateComparator MODEL_COLOR
participant "pr:Projection" as Projection MODEL_COLOR

end box

[-> LogicManager : execute("project d/22112019")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("project d/22112019")
activate AddressBookParser

create ProjectCommandParser
AddressBookParser -> ProjectCommandParser
activate ProjectCommandParser

ProjectCommandParser --> AddressBookParser
deactivate ProjectCommandParser

AddressBookParser -> ProjectCommandParser : parse("d/22112019")
activate ProjectCommandParser

create ProjectCommand
ProjectCommandParser -> ProjectCommand : 22112019
activate ProjectCommand

ProjectCommand --> ProjectCommandParser : p
deactivate ProjectCommand

ProjectCommandParser --> AddressBookParser : p
deactivate ProjectCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ProjectCommandParser -[hidden]-> AddressBookParser
destroy ProjectCommandParser

AddressBookParser --> LogicManager : p
deactivate AddressBookParser

LogicManager -> ProjectCommand : execute()
activate ProjectCommand

ProjectCommand -> Model : getBankAccount()
activate Model

Model --> ProjectCommand : ReadOnlyBankAccount
deactivate Model

create DateComparator
ProjectCommand --> DateComparator
activate DateComparator

DateComparator --> ProjectCommand
deactivate DateComparator

ProjectCommand --> ReadOnlyBankAccount : getSortedTransactionHistory(dc)
activate ReadOnlyBankAccount

ReadOnlyBankAccount --> ProjectCommand : th
deactivate ReadOnlyBankAccount

create Projection
ProjectCommand --> Projection : th, 22112019
activate Projection

Projection --> ProjectCommand
deactivate Projection

create CommandResult
ProjectCommand -> CommandResult :pr
activate CommandResult

CommandResult --> ProjectCommand
deactivate CommandResult

ProjectCommand --> LogicManager : result
deactivate ProjectCommand

[<--LogicManager
deactivate LogicManager
@enduml
