@startuml

interface QuestionsLogic {
    getAllQuestionsList()
    getAllFilteredQuestionsList()
    filterQuestionsList(predicate)
    addQuestion(question)
    getQuestion(id)
    setQuestion(id, question)
    replaceQuestion(oldQuestion, newQuestion)
    deleteAllQuestions()
    getSelectedQuestion()
    selectQuestion(id)
}

@enduml
