@startuml
!include ClassDiagramstyle.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class QuizResult {
quizTime: String
result: Boolean
getAnswer(): Answer
getQuestionBody(): QuestionBody
getSubject(): Subject
getDifficulty(): Difficulty
getQuizTime(): String
getResult(): Boolean
isWithinDate(LocalDate start, LocalDate end): boolean
}

class Answer {
answer: String
isValidAnswer(String test): boolean
}
class QuestionBody {
body: String
isValidQuestionBody(String test): boolean
}
class Subject {
subject: String
isValidSubject(String test): boolean
}
class Difficulty {
difficulty: String
isValidDifficulty(String test): boolean
}

QuizResult *--> "1" Answer
QuizResult *--> "1" QuestionBody
QuizResult *--> "1" Subject
QuizResult *--> "1" Difficulty

@enduml
