@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":CommandBox" as CommandBox UI_COLOR
participant ":ResultDisplay" as ResultDisplay UI_COLOR
end box


box Logic LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
participant ":AlfredParser" as AlfredParser LOGIC_COLOR
participant ":RemoveCommandAllocator" as RemoveCommandAllocator LOGIC_COLOR
participant ":RemoveParticipantCommandParser" as RemoveParticipantCommandParser LOGIC_COLOR
participant "c:RemoveParticipantCommand" as RemoveParticipantCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box


[-> MainWindow : 'remove participant P-100 T-2'
activate LogicManager

MainWindow -> CommandBox : handleCommandEntered()
activate CommandBox

CommandBox -> Logic : execute("remove participant P-100 T-2")
activate Logic

Logic -> AlfredParser : parseCommand("remove participant P-100 T-2")
activate AlfredParser

create RemoveCommandAllocator
AlfredParser -> RemoveCommandAllocator
activate RemoveCommandAllocator

RemoveCommandAllocator --> AlfredParser
deactivate RemoveCommandAllocator

AlfredParser -> RemoveCommandAllocator : allocate("participant P-100 T-2")
activate RemoveCommandAllocator

create RemoveParticipantCommandParser
RemoveCommandAllocator -> RemoveParticipantCommandParser
activate RemoveParticipantCommandParser

RemoveParticipantCommandParser --> RemoveCommandAllocator
deactivate RemoveParticipantCommandParser

RemoveCommandAllocator -> RemoveParticipantCommandParser : parse("P-100 T-2")
activate RemoveParticipantCommandParser

create RemoveParticipantCommand
RemoveParticipantCommandParser -> RemoveParticipantCommand
activate RemoveParticipantCommand

RemoveParticipantCommand --> RemoveParticipantCommandParser : c
deactivate RemoveParticipantCommand

RemoveParticipantCommandParser --> RemoveCommandAllocator : c
deactivate RemoveParticipantCommandParser

RemoveCommandAllocator --> AlfredParser : c
deactivate RemoveCommandAllocator

AlfredParser --> Logic : c
deactivate AlfredParser


Logic -> RemoveParticipantCommand : execute()
activate RemoveParticipantCommand

RemoveParticipantCommand -> Model
activate Model


Model --> RemoveParticipantCommand
deactivate Model

RemoveParticipantCommand --> Logic : commandResult
deactivate AssignCommand

Logic --> CommandBox : commandResult
deactivate Logic

CommandBox --> MainWindow
deactivate CommandBox

MainWindow -> ResultDisplay : setFeedBackToUser(CommandResult)
activate ResultDisplay

ResultDisplay --> MainWindow
deactivate ResultDisplay

[<--MainWindow
deactivate MainWindow
@enduml
