@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":SavePdfCommandParser" as SavePdfCommandParser LOGIC_COLOR
participant "p:SavePdfCommand" as SavePdfCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(savepdf)
activate LogicManager

LogicManager -> CommandParser : parseCommand(savepdf)
activate CommandParser
note right: savepdf's FULL COMMAND: "savepdf pdf/summary dt/5/11/2019"

create SavePdfCommandParser
CommandParser -> SavePdfCommandParser : SavePdfCommandParser()
activate SavePdfCommandParser

SavePdfCommandParser --> CommandParser
deactivate SavePdfCommandParser

CommandParser -> SavePdfCommandParser : parse(savepdf)
activate SavePdfCommandParser

create SavePdfCommand
SavePdfCommandParser -> SavePdfCommand : SavePdfCommand(\n"summary", 5/11/2019)
activate SavePdfCommand

SavePdfCommand --> SavePdfCommandParser : p
deactivate SavePdfCommand

SavePdfCommandParser --> CommandParser : p
deactivate SavePdfCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
SavePdfCommandParser -[hidden]-> CommandParser
destroy SavePdfCommandParser

CommandParser --> LogicManager : p
deactivate CommandParser

LogicManager -> SavePdfCommand : execute()
activate SavePdfCommand


note right : FILEPATH*: "./data/DeliveryTasks 2019-11-05.pdf"
SavePdfCommand -> Model : generateTaskSummaryPdf(\nFILEPATH*, 5/11/2019)
activate Model

Model --> SavePdfCommand
deactivate Model

create CommandResult
SavePdfCommand -> CommandResult
activate CommandResult

CommandResult --> SavePdfCommand
deactivate CommandResult

SavePdfCommand --> LogicManager : result
deactivate SavePdfCommand

[<--LogicManager
deactivate LogicManager

@enduml
