@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command saves Mark])
    :Purge redundant states;
    :Save Mark and the
    corresponding record to
    markStateRecords;
else ([else])
endif
stop
@enduml
