@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
participant ":SaveNusParser" as SaveNusParser LOGIC_COLOR
participant ":SaveCommandParser" as SaveCommandParser LOGIC_COLOR
participant ":CommandWordParser" as CommandWordParser LOGIC_COLOR
participant "d:SaveCommand" as SaveCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Wallet" as Wallet MODEL_COLOR
participant ":SavingsAccount" as SavingsAccount MODEL_COLOR
participant ":CurrentSavings" as CurrentSavings MODEL_COLOR
participant ":SavingsHistory" as SavingsHistory MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR
participant ":JsonSavingsAccountStorage" as JsonSavingsAccountStorage STORAGE_COLOR
participant ":JsonSavingsStorage" as JsonSavingsStorage STORAGE_COLOR
end box

[-> Logic : execute("save 10.00")
activate Logic

Logic -> Model : getAliasList()
activate Model
Model --> Logic : AliasList aliasList

deactivate Model
Logic -> SaveNusParser : parseCommand(aliasList, "save 10.00")
activate SaveNusParser

create CommandWordParser
SaveNusParser -> CommandWordParser
activate CommandWordParser
CommandWordParser --> SaveNusParser
deactivate CommandWordParser
SaveNusParser -> CommandWordParser : : parseWord(aliasList, matcher.group("commandWord"))
activate CommandWordParser
CommandWordParser --> SaveNusParser : commandWord
deactivate CommandWordParser

create SaveCommandParser
SaveNusParser -> SaveCommandParser
activate SaveCommandParser
SaveCommandParser --> SaveNusParser
deactivate SaveCommandParser
SaveNusParser -> SaveCommandParser : parse("10.00")
activate SaveCommandParser

create SaveCommand
SaveCommandParser -> SaveCommand
activate SaveCommand

SaveCommand --> SaveCommandParser : d
deactivate SaveCommand

SaveCommandParser --> SaveNusParser : d
deactivate SaveCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SaveCommandParser -[hidden]-> SaveNusParser
destroy SaveCommandParser

SaveNusParser --> Logic : d
deactivate SaveNusParser

Logic -> SaveCommand : execute()
activate SaveCommand

SaveCommand -> Model : depositInSavings(Savings savings)
activate Model
Model -> Model : deductFromWallet(Savings savings)
activate Model
Model -> Wallet : deductFromWallet(Savings savings)
activate Wallet
Wallet --> Model
deactivate Wallet
Model --> Model
deactivate Model

Model -> SavingsAccount : addToSavings(Savings savings)
activate SavingsAccount
SavingsAccount -> CurrentSavings : setCurrentSavings(Money newAmount)
activate CurrentSavings
CurrentSavings --> SavingsAccount
deactivate CurrentSavings
SavingsAccount --> Model
deactivate SavingsAccount

Model -> SavingsHistory : addToHistory(Savings savings)
activate SavingsHistory
SavingsHistory --> Model
deactivate SavingsHistory
'Hidden arrow for neatness of diagram.
Model -[hidden]-> SaveCommand
Model --> SaveCommand
deactivate Model

create CommandResult
SaveCommand -> CommandResult
activate CommandResult

CommandResult --> SaveCommand
deactivate CommandResult

SaveCommand --> Logic : result
deactivate SaveCommand

Logic -> Storage : saveSavingsAccount(model.getSavingsAccount())
activate Storage

Storage -> JsonSavingsStorage : saveSavingsAccount(ReadOnlySavingsAccount savingsAccount)
activate JsonSavingsAccountStorage
JsonSavingsStorage --> Storage
deactivate JsonSavingsAccountStorage
Storage --> Logic
deactivate Storage

Logic -> Storage : saveSavingsHistory(mode.getSavingsHistory())
activate Storage
Storage -> JsonSavingsStorage : saveSavingsHistory(ReadOnlySavingsHistory savingsHistory)
activate JsonSavingsStorage
JsonSavingsStorage --> Storage
deactivate JsonSavingsStorage
Storage --> Logic

[<--Logic
deactivate Logic

@enduml
