@startuml

!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package Model <<Rectangle>> {
    Interface ReadOnlySavingsAccount <<Interface>>
    Class CurrentSavings
    Class SavingsAccount
    Class Money
}
SavingsAccount ..|> ReadOnlySavingsAccount
SavingsAccount *--> "1" CurrentSavings
CurrentSavings *--> "1" Money

@enduml
