@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package Model <<Rectangle>> {
    Interface ReadOnlySavingsAccount <<Interface>>
    Class Savings
    Class Withdrawal
    Class SavingsAccount
    Class SavingsHistory
    Class AccountMoney
    Class Amount
    Class TimeStamp
}
SavingsAccount .up.|> ReadOnlySavingsAccount
SavingsAccount *--> "1" SavingsHistory
SavingsHistory o--> "0..*" Savings
SavingsHistory o--> "0..*" Withdrawal

Savings *--> "1" AccountMoney
Withdrawal *--> "1" AccountMoney

AccountMoney *--> "1" Amount
AccountMoney *--> "1" TimeStamp

@enduml
