@startuml ScheduleConflict
!include style.puml

title __Schedule Conflict__
actor User USER_COLOR
participant "__:Ui__" as Ui UI_COLOR
participant "__:Logic__" as Logic LOGIC_COLOR
participant "__:Model__" as Model MODEL_COLOR

User -[USER_COLOR]> Ui: schedule n/cardio d/12/12/2012
activate Ui UI_COLOR

Ui -[UI_COLOR]> Logic: execute("n/cardio d/12/12/2012")
activate Logic LOGIC_COLOR

Logic -[LOGIC_COLOR]> Model: hasSchedule(schedule)
activate Model MODEL_COLOR

Model --[MODEL_COLOR]> Logic: true
deactivate Model

Logic --[LOGIC_COLOR]> Ui: CommandResult("Schedule Conflict")
deactivate Logic

Ui -[UI_COLOR]> Ui: showResolveWindow()
activate Ui UI_COLOR_T1
return
Ui --[UI_COLOR]> User

@enduml
