@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":IncidentManagerParser" as IncidentManagerParser LOGIC_COLOR
participant "l:ListIncidentsCommand" as ListIncidentsCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedIncidentManager" as VersionedIncidentManager MODEL_COLOR
end box
[-> LogicManager : execute(incidents)
activate LogicManager

LogicManager -> IncidentManagerParser : parseCommand(incidents)
activate IncidentManagerParser

create ListIncidentsCommand
IncidentManagerParser -> ListIncidentsCommand
activate ListIncidentsCommand

ListIncidentsCommand --> IncidentManagerParser
deactivate ListIncidentsCommand

IncidentManagerParser --> LogicManager : l
deactivate IncidentManagerParser

LogicManager -> ListIncidentsCommand : execute()
activate ListIncidentsCommand

ListIncidentsCommand -> Model : updatedFilteredIncidentList(PREDICATE_SHOW_ALL_INCIDENTS)
activate Model

Model -> VersionedIncidentManager : setPredicate(PREDICATE_SHOW_ALL_INCIDENTS)
activate VersionedIncidentManager

VersionedIncidentManager --> Model :
deactivate VersionedIncidentManager

Model --> ListIncidentsCommand
deactivate Model

ListIncidentsCommand --> LogicManager : commandResult
deactivate ListIncidentsCommand
ListIncidentsCommand -[hidden]-> LogicManager : commandResult
destroy ListIncidentsCommand

[<--LogicManager
deactivate LogicManager
@enduml
