@startuml
start
:User executes a settings
command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([settings command parsed successfully]           )
    :Executes settings
    command                 ;
    :Changes state of model  ;
    :Updated settings is
    saved to
    plusworksettings.json  ;
else ([else])
    :Throws ParseException;
endif
stop
@enduml
