@startuml
start
:User executes sort command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid fields present])
    :Determine sort order in parser based on given fields;
    :Update Model based on the sort order;
else ([missing or invalid fields])
    :Display error message;
endif
stop
@enduml
