@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor #32a89d

package Sort <<Rectangle>> {
    Class CustomSorter
    Class DefaultComparator
    Class FieldComparator
    Class FoodComparator
}

CustomSorter *--> "1" FoodComparator

@enduml
