@startuml
(*)  --> "check input"
If "shares.length  == name.length?" then
--> [Yes] "set user's share to 0"
--> "create split"
--> (*)
else
    if "share size is 1 more than name?"
    --> [yes] "user's share is the first"
    --> "create split"
    else
    --> "throw error"
    endif
Endif
-->(*)
@enduml

