@startuml
start
:User executes Split command;
:SplitCommandParser parses and validates user input;

if() then ([Valid input])

:Creates SplitCommand containing List of shares and people;
:Calculates Amount for each Person;
:Update balance for each Person;
:Update balance for Ledger;
:Commit UserState;

else([else])
:Throw ParseException;
endif

stop

@enduml

