@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":StartCommandParser" as StartCommandParser LOGIC_COLOR
participant "d:StartCommand" as StartCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("start cs2103")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("start cs2103")
activate AddressBookParser

AddressBookParser -> AddressBookParser : parseNormalCommand("start cs2103")
activate AddressBookParser
create StartCommandParser
AddressBookParser -> StartCommandParser
activate StartCommandParser

StartCommandParser --> AddressBookParser
deactivate StartCommandParser

AddressBookParser -> StartCommandParser : parse("cs2103")
activate StartCommandParser

create StartCommand
StartCommandParser -> StartCommand
activate StartCommand

StartCommand --> StartCommandParser : d
deactivate StartCommand

StartCommandParser --> AddressBookParser : d
deactivate StartCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
StartCommandParser -[hidden]-> AddressBookParser
AddressBookParser --> AddressBookParser : d
deactivate AddressBookParser
destroy StartCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> StartCommand : execute()
activate StartCommand

StartCommand -> StartCommand : searchTag("cs2103")
activate StartCommand
StartCommand --> StartCommand
deactivate StartCommand

StartCommand -> Model : initialiseTestModel()
activate Model

Model --> StartCommand
deactivate Model

StartCommand -> AddressBookParser : startTestMode()
activate AddressBookParser
AddressBookParser --> StartCommand
deactivate AddressBookParser

StartCommand -> Model : getTestQuestion()
activate Model
Model --> StartCommand : question
deactivate Model


create CommandResult
StartCommand -> CommandResult
activate CommandResult

CommandResult --> StartCommand
deactivate CommandResult

StartCommand --> LogicManager : result
deactivate StartCommand

[<--LogicManager
deactivate LogicManager
@enduml
