@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":KeyboardFlashCardsParser" as KeyboardFlashCardsParser LOGIC_COLOR
participant ":StartCommandParser" as StartCommandParser LOGIC_COLOR
participant "d:StartCommand" as StartCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("start cs2103")
activate LogicManager

LogicManager -> KeyboardFlashCardsParser : parseCommand("start cs2103")
activate KeyboardFlashCardsParser

KeyboardFlashCardsParser -> KeyboardFlashCardsParser : parseNormalCommand("start cs2103")
activate KeyboardFlashCardsParser
create StartCommandParser
KeyboardFlashCardsParser -> StartCommandParser
activate StartCommandParser

StartCommandParser --> KeyboardFlashCardsParser
deactivate StartCommandParser

KeyboardFlashCardsParser -> StartCommandParser : parse("cs2103")
activate StartCommandParser

create StartCommand
StartCommandParser -> StartCommand
activate StartCommand

StartCommand --> StartCommandParser : d
deactivate StartCommand

StartCommandParser --> KeyboardFlashCardsParser : d
deactivate StartCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
StartCommandParser -[hidden]-> KeyboardFlashCardsParser
KeyboardFlashCardsParser --> KeyboardFlashCardsParser : d
deactivate KeyboardFlashCardsParser
destroy StartCommandParser

KeyboardFlashCardsParser --> LogicManager : d
deactivate KeyboardFlashCardsParser

LogicManager -> StartCommand : execute()
activate StartCommand

StartCommand -> StartCommand : searchTag("cs2103")
activate StartCommand
StartCommand --> StartCommand
deactivate StartCommand

StartCommand -> Model : initialiseTestModel()
activate Model

Model --> StartCommand
deactivate Model

StartCommand -> KeyboardFlashCardsParser : startTestMode()
activate KeyboardFlashCardsParser
KeyboardFlashCardsParser --> StartCommand
deactivate KeyboardFlashCardsParser

StartCommand -> Model : getTestQuestion()
activate Model
Model --> StartCommand : question
deactivate Model


create CommandResult
StartCommand -> CommandResult
activate CommandResult

CommandResult --> StartCommand
deactivate CommandResult

StartCommand --> LogicManager : result
deactivate StartCommand

[<--LogicManager
deactivate LogicManager
@enduml
