@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AppDataParser" as AppDataParser LOGIC_COLOR
participant ":GetStatisticsCommandParser" as GetStatisticsCommandParser LOGIC_COLOR
participant "g:GetStatisticsCommand" as GetStatisticsCommand LOGIC_COLOR
participant "c:CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("stats s/CS2103T")
activate LogicManager

LogicManager -> AppDataParser : parseCommand("stats s/CS2103T")
activate AppDataParser

create GetStatisticsCommandParser
AppDataParser -> GetStatisticsCommandParser
activate GetStatisticsCommandParser

GetStatisticsCommandParser --> AppDataParser
deactivate GetStatisticsCommandParser

AppDataParser -> GetStatisticsCommandParser : parse("stats s/CS2103T")
activate GetStatisticsCommandParser

create GetStatisticsCommand
GetStatisticsCommandParser -> GetStatisticsCommand
activate GetStatisticsCommand

GetStatisticsCommand --> GetStatisticsCommandParser : g
deactivate GetStatisticsCommand

GetStatisticsCommandParser --> AppDataParser : g
deactivate GetStatisticsCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetStatisticsCommandParser -[hidden]-> AppDataParser
destroy GetStatisticsCommandParser

AppDataParser --> LogicManager : g
deactivate AppDataParser

LogicManager -> GetStatisticsCommand : execute()
activate GetStatisticsCommand

create CommandResult
GetStatisticsCommand -> CommandResult
activate CommandResult

CommandResult --> GetStatisticsCommand
deactivate CommandResult

GetStatisticsCommand -> CommandResult : setType(CHART)
activate CommandResult

CommandResult --> GetStatisticsCommand
deactivate CommandResult

GetStatisticsCommand --> LogicManager : c
deactivate GetStatisticsCommand

[<--LogicManager
deactivate LogicManager
@enduml
