//@@author LeonardTay748
@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":StatsWindow" as StatsWindow UI_COLOR
end box

box MODEL MODEL_COLOR_T1
participant ":model" as Model MODEL_COLOR
end box

box JavaFx EXTERNAL_LIBRARY_COLOR_T1
participant ":Scene" as Scene EXTERNAL_LIBRARY_COLOR
participant ":FlowPane" as FlowPane EXTERNAL_LIBRARY_COLOR
participant ":Stage" as Stage EXTERNAL_LIBRARY_COLOR
end box

group sd show statistics
-> StatsWindow : show(model)

                loop for each rating
                activate StatsWindow
                StatsWindow -> Model : updateFilteredFlashCardList(rating)
                activate Model
                StatsWindow <-- Model : ObservableList<FlashCard>
                deactivate Model
                StatsWindow -> Model : size()
                activate Model
                StatsWindow <-- Model : number
                deactivate Model
                end

                StatsWindow -> Model : getPerformance()
                activate Model
                StatsWindow <-- Model : ArrayList<Integer>
                deactivate Model

                StatsWindow -> Model : getTestStats()
                activate Model
                StatsWindow <-- Model : stats[]
                deactivate Model

                StatsWindow -> FlowPane : FlowPane()
                activate FlowPane
                StatsWindow <-- FlowPane : root
                deactivate FlowPane


                StatsWindow -> Scene : Scene(root)
                activate Scene
                StatsWindow <-- Scene : scene
                deactivate Scene

                StatsWindow -> Stage : setScene(scene)
                activate Stage
                StatsWindow <-- Stage :
                deactivate Stage

                <-- StatsWindow :
                deactivate StatsWindow
end

@enduml
