@startuml
start
:User executes stats command;
:Check input;

if () then ([input is valid])
    :Filter quizResults list;
    :Hide notes and
    tasks panels;
    :Display statistics;
else ([else])
    :Exception thrown;
endif
stop
@enduml
