@startuml
skinparam classAttributeIconSize 0

package Statistic <<Rectangle>> {
    class Statistic
    class StatsFactory
    StatsFactory - Statistic : creates >
}

class StatsFactory {
    -ObservableList<Exercise> exercises
    -String chart
    -String category
    -Date startDate
    -Date endDate
    +generateStatistics() : Statistic
}

class Statistic {
    -String category
    -String chart
    -Date startDate
    -Date endDate
    -ArrayList<String> properties
    -ArrayList<Double> values
    -double total
    -double average
    +resetData() : void
}

@enduml
