@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":StatsPieChart" as StatsPieChart UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
end box

[-> MainWindow : executeCommand("stats s/CS2103T")
activate MainWindow

MainWindow -> Logic : execute("stats s/CS2103T")
activate Logic

Logic --> MainWindow : commandResult
deactivate Logic

MainWindow -> MainWindow : showStats(commandResult.getType())
activate MainWindow

create StatsPieChart
MainWindow -> StatsPieChart : StatsPieChart()
activate StatsPieChart

StatsPieChart --> MainWindow : statsPieChart
deactivate StatsPieChart

MainWindow -> StatsPieChart : setMouseover()
activate StatsPieChart

StatsPieChart --> MainWindow
deactivate StatsPieChart
'Hidden arrow to position the destroy marker below the end of the activation bar.
StatsPieChart -[hidden]-> MainWindow
destroy StatsPieChart

MainWindow --> MainWindow
deactivate MainWindow

[<--MainWindow
deactivate MainWindow
@enduml
