@startuml
!include style.puml

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":SellerManagerParser" as abp LOGIC_COLOR
Participant ":StatsCommandParser" as ecp LOGIC_COLOR
Participant "command:StatsCommand" as ec LOGIC_COLOR
Participant "statsPayload:StatsPayload" as sp LOGIC_COLOR
Participant "commandResult:CommandResult" as cr LOGIC_COLOR


[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create ecp
abp -> ecp
abp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: startingDate, endingDate, statisticType, UiChange

ec --> ecp --
ecp --> abp --: command
abp --> logic --: command

logic -> ec ++: execute, model
create sp
ec -> sp ++: startingDate, endingDate, statisticType
sp --> ec --: statsPayload

ec -> cr ++: StatsPayload, UiChange
cr -> ec --: commandResult
ec -> logic --: commandResult

<- logic :commandResult


@enduml
