@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface UserStateStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonUserStateStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> UserStateStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonUserStateStorage .left.|> UserStateStorage
JsonUserStateStorage .down.> JsonSerializableUserState
JsonSerializableUserState .down.> JsonAdaptedBankAccountOperations
JsonSerializableUserState .left.> JsonSerializableBudget
JsonSerializableUserState .right.> JsonAdaptedLedgerStorage
JsonSerializableUserState .down.> JsonAdaptedProjection
JsonAdaptedBankAccountOperations .left.> JsonAdaptedCategory
JsonAdaptedLedgerStorage .right.> JsonAdaptedLedgerOperations
JsonAdaptedLedgerOperations .down.> JsonAdaptedPerson
JsonSerializableBudget ...> JsonAdaptedCategory

@enduml
