@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface FlashcardListStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonFlashcardListStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> FlashcardListStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonFlashcardListStorage .left.|> FlashcardListStorage
JsonFlashcardListStorage .down.> JsonSerializableFlashcardListStorage
JsonSerializableFlashcardListStorage .right.> JsonSerializableFlashcard
JsonSerializableFlashcardList .right.> JsonAdaptedTag
@enduml
