@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AddressBookStorage <<Interface>>
Interface EventBookStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonAddressBookStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> AddressBookStorage
StorageManager o--> EventBookStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonAddressBookStorage .left.|> AddressBookStorage
JsonAddressBookStorage .down.> JsonSerializableAddressBookStorage
JsonSerializableAddressBookStorage .down.> JsonSerializableEmployee
JsonSerializableEmployee .down.> JsonAdaptedTag

JsonEventBookStorage .left.|> EventBookStorage
JsonEventBookStorage .down.> JsonSerializableEventBookStorage
JsonSerializableEventBookStorage .down.> JsonSerializableEvent
JsonSerializableEvent .down.> JsonAdaptedTag
@enduml
