/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'T1 through T4 are shades of the original color from lightest to darkest

!define UI_COLOR #148f77
!define UI_COLOR_T1 #c0f0d2

!define LOGIC_COLOR #1f69ad
!define LOGIC_COLOR_T1 #b0d5f7

!define MODEL_COLOR #621c78
!define MODEL_COLOR_T1 #e6bdf2

!define MAIN_COLOR #AB1313
!define MAIN_COLOR_T1 #F5C1C1

!define STORAGE_COLOR #e67f25
!define STORAGE_COLOR_T1 #f5c8a2

!define COMMONS_COLOR #5f9ca3
!define COMMONS_COLOR_T1 #bcdfe3

!define USER_COLOR #000000

!define ITEXT_COLOR #F9E79F
!define ITEXT_COLOR_T1 #F1C40F

skinparam BackgroundColor #FFFFFFF

skinparam Shadowing false

skinparam Class {
    FontColor #FFFFFF
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #FFFFFF
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #FFFFFF
    FontName Arial
}

skinparam Participant {
    FontColor #FFFFFFF
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
