@startuml
skinparam activityShape rectangle

start
:Entered suggest command;
:check if suggest type is valid;
if() then ([Valid suggest type])

if() then ([suggest type == "basic"])
    :updates list to show basic exercises;
else ([suggest type == "possible"])
    if() then ([valid arguments])
        :Form predicate;
        :updates list to show exercises with matching predicate;
    else ([Invalid arguments])
        :show invalid arguments message;
    endif
    endif
else ([Invalid suggest type])
    :show invalid suggest type message;
endif
-> Program resumes;
stop
@enduml
