@startuml
package ui {
    class TabPanel
    class MainWindow {
        fetchTabInformation(tabName:String): Tab
    }
    class Tab
    abstract class UiPart<Region>
}

package logic.parser {
    class TabCommandParser
    interface Parser
    class TypeeParser
}

package logic.commands {
    class TabCommand
    abstract class Command
    class CommandResult
}

UiPart <|-- Tab
UiPart <|-- TabPanel
UiPart <|-- MainWindow
MainWindow *--> Tab
MainWindow *--> TabPanel
Parser <|.. TabCommandParser
Parser <|.. TypeeParser
TypeeParser ..> TabCommandParser
Command <|-- TabCommand
TabCommandParser ..> TabCommand
TabCommand ..> CommandResult
MainWindow ..> TypeeParser
CommandResult .. MainWindow
@enduml
