@startuml
!include ClassDiagramStyle.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class TaskForNote
class TaskForQuestion



abstract class Task {
    - isDone : boolean = false
    - date : LocalDate
    - time : LocalTime
    + {abstract} toString() : String
}

class TaskForNote {
    - note : Note
    + toString() : String
}

class TaskForQuestion {
    - question : Question
    + toString() : String
}

Task <|-- TaskForNote
Task <|-- TaskForQuestion

@enduml
