@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MemeCreationParser" as MemeCreationParser LOGIC_COLOR
participant "c:TemplateAddTextCommand" as TemplateAddTextCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box UI UI_COLOR_T1
participant ":MemeCreationPanel" as MemeCreationPanel UI_COLOR
end box

activate MainWindow
MainWindow -> LogicManager : execute(add text)
activate LogicManager

LogicManager -> MemeCreationParser : parseCommand(add text)
activate MemeCreationParser

create TemplateAddTextCommand
MemeCreationParser -> TemplateAddTextCommand
activate TemplateAddTextCommand

TemplateAddTextCommand --> MemeCreationParser
deactivate TemplateAddTextCommand

MemeCreationParser --> LogicManager : c
deactivate MemeCreationParser

LogicManager -> TemplateAddTextCommand : execute()
activate TemplateAddTextCommand

create CommandResult
TemplateAddTextCommand -> CommandResult
activate CommandResult
CommandResult ---> TemplateAddTextCommand
deactivate CommandResult
TemplateAddTextCommand -> LogicManager : r
deactivate TemplateAddTextCommand

LogicManager -> MainWindow : r
deactivate LogicManager

MainWindow -> CommandResult : getText()
activate CommandResult
CommandResult -> MainWindow : t
deactivate CommandResult

MainWindow -> CommandResult : getPosition()
activate CommandResult
CommandResult -> MainWindow : p
deactivate CommandResult

MainWindow -> MemeCreationPanel : addText(t, p)
activate MemeCreationPanel
MemeCreationPanel -> MainWindow
deactivate MemeCreationPanel

deactivate MainWindow
@enduml
