@startuml
'(*)  --> "User executes command"
start
:User executes command;
if () then ([toggle panel])
'--> [Yes] "Handle toggle panel"
''--> "Toggle specific panel"
    :Toggle specific panel;
    if () then ([panel to toggle already shown in main panel])
            :Throw new CommandException;
        else ([else])
            if () then ([all panels are toggled off])
                :Toggle entire side panel off;
            else ([else])
            endif
        endif
else ([else])
endif
stop

@enduml
