@startuml
(*)  --> "User executes command"
if "toggle panel" then
--> [Yes] "Handle toggle panel"
--> "Toggle specific panel"
    if "no panel is visible or managed" then
        --> [Yes] "Toggle entire side panel"
        --> (*)
        else
        --> [No] (*)
     endif
else
--> [No] (*)
endif

@enduml
