@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AlfredParser" as AlfredParser LOGIC_COLOR
participant ":TopTeamsCommandParser" as TopTeamsCommandParser LOGIC_COLOR
participant "l:topKRandomCommand" as topKRandomCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("getTop 3 tb/moreParticipants random")
activate LogicManager


LogicManager -> AlfredParser : parseCommand("getTop 3 tb/moreParticipants random")
activate AlfredParser

create TopTeamsCommandParser
AlfredParser -> TopTeamsCommandParser
activate TopTeamsCommandParser

TopTeamsCommandParser --> AlfredParser
deactivate TopTeamsCommandParser

AlfredParser -> TopTeamsCommandParser : parse(" 3 tb/moreParticipants random")
activate TopTeamsCommandParser

create topKRandomCommand
TopTeamsCommandParser -> topKRandomCommand
activate topKRandomCommand

topKRandomCommand --> TopTeamsCommandParser : l
deactivate topKRandomCommand

TopTeamsCommandParser --> AlfredParser : l
deactivate TopTeamsCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
TopTeamsCommandParser -[hidden]-> AlfredParser
destroy TopTeamsCommandParser

AlfredParser --> LogicManager : l
deactivate AlfredParser

LogicManager -> topKRandomCommand : execute()
activate topKRandomCommand

topKRandomCommand -> Model : setTopKRandom(3, comparators, subjectName)
activate Model

Model -> Model : setSimpleLeaderboard(comparators, subjectName)
activate Model

Model --> Model
deactivate Model

Model --> topKRandomCommand
deactivate Model

create CommandResult
topKRandomCommand -> CommandResult
activate CommandResult

CommandResult --> topKRandomCommand
deactivate CommandResult

topKRandomCommand --> LogicManager : result
deactivate topKRandomCommand

[<--LogicManager
deactivate LogicManager
@enduml
