@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":UiManager" as UiManager UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
participant ":TranspiredEventsWindow" as TranspiredEventsWindow UI_COLOR
end box

box LOGIC LOGIC_COLOR_T1
participant ":Timekeeper" as Timekeeper LOGIC_COLOR
participant ":LogicManager" as LogicManager LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
end box

[-> UiManager : start(primaryStage)
activate UiManager

par
    loop every 0.05 seconds
        UiManager -> Timekeeper : updateTime()
        activate Timekeeper
    end
    else
    loop every 2 seconds
        UiManager -> MainWindow : handleTranspiredEvents()
        activate MainWindow

        MainWindow -> Timekeeper : getTranspiredEvents()

        Timekeeper -> MainWindow : transpiredEvents
        deactivate Timekeeper

        activate LogicManager
        loop events in transpiredEvents
            MainWindow -> LogicManager : deleteTranspiredEvent
            create TranspiredEventsWindow
            MainWindow -> TranspiredEventsWindow : show(event)
            activate TranspiredEventsWindow
            alt user presses yes
            TranspiredEventsWindow -> TranspiredEventsWindow : addExpenseFromEvent()
            activate TranspiredEventsWindow
            TranspiredEventsWindow -> LogicManager : addExpenseFromEvent(event)
            deactivate TranspiredEventsWindow
            else user presses no
            TranspiredEventsWindow -> TranspiredEventsWindow : ignore()
            end
            TranspiredEventsWindow --> MainWindow : void
            destroy TranspiredEventsWindow
        end
    end
end
@enduml
