@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include <office/Users/administrator>
!include style.puml

Package " "<<Rectangle>>{
    Class GUI UI_COLOR
    Class "Main Window" as MainWin UI_COLOR_T2
    Class "Logic\nManager" as LM LOGIC_COLOR
    Class "Logic\nXYZ" as LXYZ LOGIC_COLOR_T2
    Class "Storage\nManager" as SM STORAGE_COLOR
    Class "Storage\nXYZ" as SXYZ STORAGE_COLOR_T2
    Class "Page\nManager" as PM MODEL_COLOR_T2
    Class "Page\nXYZ" as PXYZ MODEL_COLOR_T3
    Class "Model\nManager" as MM MODEL_COLOR_T2
    Class "Model\nXYZ" as MXYZ MODEL_COLOR_T3
    Class Main MODEL_COLOR_T1
    Class Commons LOGIC_COLOR_T2
    Class "Log Center" as Logs UI_COLOR_T1
    Class "User Pref\nStorage" as UPS STORAGE_COLOR_T3
    Class "User Pref\nModel" as UPM MODEL_COLOR_T4
}

Class "<$user>\nUser" as User MODEL_COLOR_T2
Class "<$documents>\nJson File\nXYZ" as File UI_COLOR_T1

Main -down-> GUI
Main -down-> LM
Main -down-> SM
Main -down-> MM

User -> GUI

GUI -down-> MainWin
MainWin -down-> PM
PM -down-> PXYZ
PXYZ -up-> LXYZ

LM -down-> LXYZ
LXYZ -down-> MXYZ
LXYZ -down-> SXYZ

SM -down-> UPS

MM -down-> UPM

LXYZ .down.> Commons
Main .down.> Commons
Logs -up- Commons


SXYZ .left.> File
UPS .right.> File

@enduml
