@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class BalanceBar
Class ResultDisplay
Class TransactionListPanel
Class ExpenseCard
class IncomeCard
Class StatusBarFooter
Class CommandBox
Class ColouredLabelFactory
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down--> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" TransactionListPanel
MainWindow *-down-> "1" BalanceBar
MainWindow *-down-> "1" StatusBarFooter


TransactionListPanel *-down-> "*" ExpenseCard
TransactionListPanel *-down-> "*" IncomeCard
ExpenseCard -down-> ColouredLabelFactory
IncomeCard -down-> ColouredLabelFactory


MainWindow -left-|> UiPart
StatusBarFooter ---|> UiPart
ResultDisplay -right-|> UiPart
CommandBox -down--|> UiPart
BalanceBar -down-|> UiPart
TransactionListPanel -down--|> UiPart
ExpenseCard ---|> UiPart
IncomeCard --|> UiPart
HelpWindow ---|> UiPart

TransactionListPanel ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
BalanceBar -[hidden]left- ResultDisplay
ExpenseCard -[hidden]left- UiManager

Model -[hidden]-|> UiPart
MainWindow -[hidden]-|> UiPart
@enduml
