@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class StatusBarFooter
Class CommandBox

package Panels <<Rectangle>> {
Class "{abstract}\nPanelComponent" as PanelComponent
'Class NoteListPanel
'Class NoteCard
'Class QuestionListPanel
'Class QuestionListCard
'Class QuizQuestionListPanel
'Class QuizQuestionListCard
'Class TaskListPanel
'Class TaskListCard
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow *-down-> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> StatusBarFooter
MainWindow *-down--> Panels

'MainWindow *-down-> NoteListPanel
'MainWindow *-down-> QuestionListPanel
'MainWindow *-down-> QuizQuestionListPanel
'MainWindow *-down-> TaskListPanel


'NoteListPanel -down-> NoteCard
'QuestionListPanel -down-> QuestionListCard
'QuizQuestionListPanel -down-> QuizQuestionListCard
'TaskListPanel -down-> TaskListCard

MainWindow --|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

PanelComponent --|> UiPart
'NoteListPanel ---|> PanelComponent
'NoteCard ---|> PanelComponent
'QuestionListPanel ---|> PanelComponent
'QuestionListCard ---|> PanelComponent
'QuizQuestionListPanel ---|> PanelComponent
'QuizQuestionListCard ---|> PanelComponent
'TaskListPanel ---|> PanelComponent
'TaskListCard ---|> PanelComponent

'NoteCard ...> Model
'QuestionListCard ...> Model
'QuizQuestionListCard ...> Model
'TaskListCard ...> Model
Panels ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
StatusBarFooter -[hidden]left- Panels

@enduml
