@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\n UiPart  " as UiPart
Class UiManager
Class MainWindow
Class StudyPlanTagPanel
Class SemesterListPanel
Class SemesterCard
Class ModuleCard
Class ModulePill
Class ResultDisplay
Class CommandBox
class TagListPanel
class ModuleListPanel
class SimpleSemesterListPanel
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager --> MainWindow
MainWindow *--> CommandBox
MainWindow *--> StudyPlanTagPanel
MainWindow *--> SemesterListPanel
MainWindow *--> ResultDisplay

SemesterListPanel --> SemesterCard

SemesterCard --> ModuleCard
SemesterCard --> ModulePill

ResultDisplay --> TagListPanel
ResultDisplay --> ModuleListPanel
ResultDisplay --> SimpleSemesterListPanel

MainWindow --|> UiPart

ResultDisplay --|> UiPart
StudyPlanTagPanel --|> UiPart
CommandBox --|> UiPart
SemesterListPanel --|> UiPart
SemesterCard --|> UiPart
ModuleCard --|> UiPart
ModulePill --|> UiPart
TagListPanel --|> UiPart
ModuleListPanel --|> UiPart
SimpleSemesterListPanel --|> UiPart

SemesterCard ..> Model
ModuleCard ..> Model
ModulePill ..> Model
UiManager --> Logic
MainWindow --> Logic

ModuleListPanel -[hidden]left-> SimpleSemesterListPanel
TagListPanel -[hidden]left-> SimpleSemesterListPanel


ResultDisplay -[hidden]right-> StudyPlanTagPanel
StudyPlanTagPanel -[hidden]right-> CommandBox
CommandBox -[hidden]right-> SemesterListPanel

@enduml
