@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "undo"

package ModelHistory{
    package PastModels {
        class State1 as "__m0:ModelChanges__"
    }

    package FutureModels {
        class State3 as "__m2:ModelChanges__"
    }
}

class Pointer as "Changes to revert undo." #FFFFF

Pointer -up-> State3
@end
