@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "sort start ascending"

package States <<rectangle>> {
    class State1 as "__el0:EngagementList__"
    class State2 as "__el1:EngagementList__"
    class State3 as "__el2:EngagementList__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State2
@end
