@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "undo"

package States <<rectangle>> {
    class State1 as "__gt0:GuiltTrip__"
    class State2 as "__gt1:GuiltTrip__"
    class State3 as "__gt2:GuiltTrip__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State2
@end
