@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "newpatient -id S9482963D -name John Doe"

package "CommandHistory" {
    class add1 as "RegisterPatientCommand    "
    class cancel1 as "unregisterPatientCommand    "

    class add2 as "EnqueueCommand    "
    class cancel2 as "DequeueCommand    "

    class add3 as "RegisterPatientCommand    "
    class cancel3 as "UnregisterPatientCommand    "

    class State1 as "__action0:ReversibleActionPairCommand____"
    class State2 as "__action1:ReversibleActionPairCommand____"
    class State3 as "__action2:ReversibleActionPairCommand____"
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

State1 -up-> add1
State1 -up-> cancel1
add1 -[hidden]down-> cancel1
cancel1 -[hidden]right-> cancel2

State2 -up-> add2
State2 -up-> cancel2
add2 -[hidden]down-> cancel2
cancel2 -[hidden]right-> cancel3

State3 -up-> add3
State3 -up-> cancel3
add3 -[hidden]down-> cancel3

@end
