@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "set lp/7"

package CommandHistory <<rectangle>> {
    class Command1 as "__c0:Command__"
    class Command2 as "__c2:Command__"
}

Command1 -[hidden]right-> Command2

class Pointer as "Current Command" #FFFFF

Pointer -up-> Command2
note right on link: Command c1 deleted.

@end
