@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "app-redo"

package history {
    object hr4 {
        command = "pat-delete 3"
        patientBook
        appointmentBook
    }
}

package redoStack {
    object hr3 {
        command = "visit-start 1"
        patientBook
        appointmentBook
    }
}

history -[hidden]right> redoStack

show members

@end
