@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":Parser" as Parser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
participant "UndoState" as UndoState LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":HistoryManager" as HistoryManager MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> Parser : parseInput(undo)
activate Parser

create UndoState
Parser -> UndoState
activate UndoState
UndoState --> Parser
Parser --> LogicManager

LogicManager -> Parser : makeCommand()
Parser -> UndoState : buildCommand()

create UndoCommand
UndoState -> UndoCommand
activate UndoCommand

UndoCommand --> UndoState
deactivate UndoCommand

UndoState -> Parser : u
deactivate UndoState
UndoState -[hidden]-> Parser : result
destroy UndoState

Parser --> LogicManager : u
deactivate Parser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoEngagementList()
activate Model

Model -> HistoryManager : undo()
activate HistoryManager
HistoryManager -> HistoryManager :isUndoable()
HistoryManager -> HistoryManager :resetData(ReadOnlyEngagementList)
HistoryManager --> Model :
deactivate HistoryManager

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
