@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "pat-delete 3"

package history {
    object hr0 {
        command = "pat-delete 3"
        patientBook
        appointmentBook
    }
}

package redoStack {

}

history -[hidden]> redoStack

show members

@end
