@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "redo"

package ModelHistory{
    package PastModels {
        class State1 as "__m0:ModelChanges__"
        class State2 as "__m3:ModelChanges__"

        State1 -[hidden]up-> State2
    }

    package FutureModels {}
}

@end
