@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor LightSkyBlue

title After command "removemod CS1101s y1s1"

package States <<rectangle>> {
    class State1 as "__mp0:VersionedModulePlanner__"
    class State2 as "__mp1:VersionedModulePlanner__"
    class State3 as "__mp2:VersionedModulePlanner__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State3
@end
