@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package States <<rectangle>> {
    package State3 {
        class State3.1 as "__gl2:GroceryList__"
        class State3.2 as "__wl2:WasteList__"
    }
    package State2 {
        class State2.1 as "__gl1:GroceryList__"
        class State2.2 as "__wl1:WasteList__"
    }
    package State1 {
        class State1.1 as "__gl0:GroceryList__"
        class State1.2 as "__wl0:WasteList__"
    }
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
State1.1 -[hidden]down-> State1.2
State2.1 -[hidden]down-> State2.2
State3.1 -[hidden]down-> State3.2

hide State2
hide State3

class Pointer as "Current State" #FFFFF
Pointer -down-> State1
@end
