@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MainParser" as MainParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedUserState" as VersionedUserState MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> MainParser : parseCommand(undo)
activate MainParser

create UndoCommand
MainParser -> UndoCommand
activate UndoCommand

UndoCommand --> MainParser
deactivate UndoCommand

MainParser --> LogicManager : u
deactivate MainParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoUserState()
activate Model

Model -> VersionedUserState : undo()
activate VersionedUserState

VersionedUserState -> VersionedUserState :resetData(ReadOnlyUserState)
VersionedUserState --> Model :
deactivate VersionedUserState

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
