@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

package history {
    object hr5 {
        command = "pat-clear"
        patientBook
        appointmentBook             .
    }
    object hr4 {
        command = "pat-delete 3"
        patientBook
        appointmentBook
    }
}

package redoStack {

}

history -[hidden]right> redoStack

hr4 -[hidden]up-> hr5

show members

@end
