@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "add t/Animal Farm"

package CommandHistory <<rectangle>> {
    class Command1 as "__c0:Command__"
    class Command2 as "__c1:Command__"
}

Command1 -[hidden]right-> Command2

class Pointer as "Current Command" #FFFFF

Pointer -up-> Command2
@end
