@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager   " as LogicManager LOGIC_COLOR
participant ":SystemCommandParser   " as Parser LOGIC_COLOR
participant "u:UndoCommand  " as UndoCommand LOGIC_COLOR
participant ":CommandHistory  " as CommandHistory LOGIC_COLOR

participant "action2:RegisterPatientCommand      " as ActionPair LOGIC_COLOR
participant "i2:UnregisterPatientCommand    " as UnregisterPatientCommand LOGIC_COLOR

participant "result : CommandResult   " as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> Parser : parseCommand("undo")
activate Parser

create UndoCommand
Parser -> UndoCommand
activate UndoCommand

UndoCommand --> Parser
deactivate UndoCommand

Parser --> LogicManager : u
deactivate Parser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> CommandHistory : performUndo()
activate CommandHistory

CommandHistory -> ActionPair : undo()
activate ActionPair

ActionPair -> UnregisterPatientCommand : execute()
activate UnregisterPatientCommand

UnregisterPatientCommand -> Model : deletePatient()
activate Model

return

create CommandResult
UnregisterPatientCommand -> CommandResult
activate CommandResult
return

UnregisterPatientCommand --> ActionPair : result
deactivate UnregisterPatientCommand

ActionPair --> CommandHistory : result
deactivate ActionPair

CommandHistory --> UndoCommand : result
deactivate CommandHistory

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
