@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "clear"

package States <<rectangle>> {
    class State1 as "__sb0:SpendingBook__"
    class State2 as "__sb1:SpendingBook__"
    class State3 as "__sb3:SpendingBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State3
note right on link: State sb2 deleted.
@end
