@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "undo"

package "CommandHistory" {
    class add1 as "RegisterPatientCommand    "
    class cancel1 as "unregisterPatientCommand    "

    class add2 as "EnqueueCommand    "
    class cancel2 as "DequeueCommand    "


    class State1 as "__action0:ReversibleActionPairCommand____"
    class State2 as "__action1:ReversibleActionPairCommand____"

    class Hidden4 as "__action:ReversibleActionPairCommand____"
    }

package "commandRedoHistory" {
    class add3 as "RegisterPatientCommand    "
    class cancel3 as "UnregisterPatientCommand    "

    class State3 as "__action2:ReversibleActionPairCommand____"

    class Hidden5 as "__action:ReversibleActionPairCommand____"
    class Hidden6 as "__action:ReversibleActionPairCommand____"
}

class TopOfUndoStack as " Top Of Undo Stack    " #FFFFF
class TopOfRedoStack as " Top Of Redo Stack    " #FFFFF

State1 -[hidden]right-> State2
State2 -[hidden]right-> Hidden4

State3 -[hidden]right-> Hidden5
Hidden5 -[hidden]right-> Hidden6

State1 -up-> add1
State1 -up-> cancel1
add1 -[hidden]down-> cancel1
cancel1 -[hidden]right-> cancel2

State2 -up-> add2
State2 -up-> cancel2
add2 -[hidden]down-> cancel2

State3 -up-> add3
State3 -up-> cancel3
add3 -[hidden]down-> cancel3


add3 -[hidden]up--> State1
Hidden5 -[hidden]up--> State2
Hidden6 -[hidden]up--> Hidden4

hide Hidden4
hide Hidden5
hide Hidden6

TopOfUndoStack -up-> State2
TopOfRedoStack -up-> State3

@end
