@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UnregisterPatientCommandParser" as UnregisterPatientCommandParser LOGIC_COLOR
participant "u:UnregisterPatientCommand" as UnregisterPatientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

create UnregisterPatientCommandParser
AddressBookParser -> UnregisterPatientCommandParser
activate UnregisterPatientCommandParser

UnregisterPatientCommandParser --> AddressBookParser
deactivate UnregisterPatientCommandParser

AddressBookParser -> UnregisterPatientCommandParser : parse("1")
activate UnregisterPatientCommandParser

create UnregisterPatientCommand
UnregisterPatientCommandParser -> UnregisterPatientCommand
activate UnregisterPatientCommand

UnregisterPatientCommand --> UnregisterPatientCommandParser : u
deactivate UnregisterPatientCommand

UnregisterPatientCommandParser --> AddressBookParser : u
deactivate UnregisterPatientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy UnregisterPatientCommandParser

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UnregisterPatientCommand : execute()
activate UnregisterPatientCommand

UnregisterPatientCommand -> Model : deletePerson(1)
activate Model

Model --> UnregisterPatientCommand
deactivate Model

create CommandResult
UnregisterPatientCommand -> CommandResult
activate CommandResult

CommandResult --> UnregisterPatientCommand
deactivate CommandResult

UnregisterPatientCommand --> LogicManager : result
deactivate UnregisterPatientCommand

[<--LogicManager
deactivate LogicManager
@enduml
