@startuml
(*) --> load question
If "Is it the end of the deck?" then
--> [No] "user attempts question"
--> "mark question"
If "Is the user correct?" then
--> [Yes] "add one to result"
--> "next question"
--> "load question"
else
--> [No] "next question"
Endif
else
--> [Yes] "review mistakes or reattempt questions"
Endif
-->(*)
@enduml