@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":StorageManager" as StorageManager STORAGE_COLOR
participant ":CommandStorage" as CommandStorage STORAGE_COLOR
end box

[-> LogicManager : getNextCommand()
activate LogicManager

LogicManager -> StorageManager : getNextCommand()
activate StorageManager

StorageManager -> CommandStorage : getNextCommand()
activate CommandStorage

StorageManager <-- CommandStorage : command
deactivate CommandStorage

LogicManager <-- StorageManager : command
deactivate StorageManager

<-- LogicManager : command
deactivate LogicManager

@enduml
