@startuml
!include style.puml

start
:User executes useGroceryCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([unit types are consistent])
    if () then ([units are consistent])
    else([else])
        :Convert units;
    endif
        :Execute Reduction;
else([else])
    :Throw InvalidUnitException;
endif
stop
@enduml
