@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":ViewDriverTaskCommandParser" as ViewDriverTaskCommandParser LOGIC_COLOR
participant "v:ViewDriverTaskCommand" as ViewDriverTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("viewD 2")
activate LogicManager

LogicManager -> CommandParser : parseCommand("viewD 2")
activate CommandParser

create ViewDriverTaskCommandParser
CommandParser -> ViewDriverTaskCommandParser
activate ViewDriverTaskCommandParser

ViewDriverTaskCommandParser --> CommandParser
deactivate ViewDriverTaskCommandParser

CommandParser -> ViewDriverTaskCommandParser : parse("2")
activate ViewDriverTaskCommandParser

create ViewDriverTaskCommand
ViewDriverTaskCommandParser -> ViewDriverTaskCommand
activate ViewDriverTaskCommand

ViewDriverTaskCommand --> ViewDriverTaskCommandParser : v
deactivate ViewDriverTaskCommand

ViewDriverTaskCommandParser --> CommandParser : v
deactivate ViewDriverTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewDriverTaskCommandParser -[hidden]-> CommandParser
destroy ViewDriverTaskCommandParser

CommandParser --> LogicManager : v
deactivate CommandParser

LogicManager -> ViewDriverTaskCommand : execute()
activate ViewDriverTaskCommand

ViewDriverTaskCommand -> Model : ViewDriverTask(2)
activate Model

Model --> ViewDriverTaskCommand
deactivate Model

create CommandResult
ViewDriverTaskCommand -> CommandResult
activate CommandResult

CommandResult --> ViewDriverTaskCommand
deactivate CommandResult

ViewDriverTaskCommand --> LogicManager : result
deactivate ViewDriverTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
