@startuml
loop for All Categories in CategoryList
StatisticsManager -[#DarkRed]> Category: getCategoryFromCategoryList()
activate Category
Category --> StatisticsManager #DarkRed: c
deactivate Category

StatisticsManager -[#DarkOrange]> StatisticsManager: calculateTotalAmountForCategory(MonthListToCalculate, c)
activate StatisticsManager #DarkOrange
StatisticsManager -[#DarkOrange]> StatisticsManager: totalAmountCalculated
deactivate StatisticsManager #DarkOrange
StatisticsManager -[#DarkRed]> CategoryStatistics: createCategoryStatistics(c, totalAmountCalculated)
activate CategoryStatistics
CategoryStatistics --> StatisticsManager #DarkRed: s
deactivate CategoryStatistics
end
@enduml