@startuml
!include style.puml
skinparam arrowThickness 1.3
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

show members
hide empty members

Package WordBank <<Rectangle>>{
Interface ReadOnlyWordBank <<Interface>> {
+getName()
+getCardList()
}

class WordBank {
   -name: String
   +getName()
   +getCardList()
   +hasCard(Card)
   +removeCard(Card)
   +resetData(Card)
   +setCard(ReadOnlyWordBank)
}
Class UniqueCardList
Class Card
}

WordBank .left.|> ReadOnlyWordBank
WordBank o-down-> "1" UniqueCardList
UniqueCardList -down-> "*" Card
@enduml
