@startuml
start
:User executes command;

:Search command creates new \n      SearchEventDescriptor;

:Execute filterEvents method;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

repeat
if () then ([Event matches attributes \nin SearchEventDescriptor])
    :Insert matched Event into new filtered event list;
else ([else])
endif
repeat while () is (more event?)

:Return newly filtered event list as result;

stop
@enduml
