@startuml

left to right direction

class Task {
    + {final} id: Id
    + {final} problem: Problem
    + {final} isDone: boolean
    + {final} dueDate: LocalDate
    + equals(Object other): boolean
    + getAuthor(): Author
    + getDescription(): Description
    + getDifficulty(): Difficulty
    + getDueDate(): LocalDate
    + getId(): Id
    + getIsDone(): boolean
    + getName(): Name
    + getProblem(): Problem
    + getRemark(): Remark
    + getStatusIcon(): String
    + getSource(): Source
    + getTags(): Set<Tag>
    + getWebLink(): WebLink
    + hashCode(): int
    + isSameTask(Task other): boolean
    + toString(): String
    + updateDueDate(LocalDate): Task
    + updateProblem(Problem): Task
    + updateStatus(boolean): Task
}

@enduml
