= Olivia Yu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: IchiFund

'''

== Overview

The purpose of this portfolio is to document my contributions to IchiFund, a software engineering project under CS2103T Software Engineering module in the National University of Singapore (NUS).

IchiFund is a command-line interface (CLI) application for personal finance management.
It is designed to be an all-in-one application for finance management,
allowing the financially conscious Computer Science (CS) undergraduate to
manage transactions, set budgets and analyse expenditure with ease and convenience.

My role was to design and implement the analytics feature of the application.

== Summary of contributions

* *Major enhancement*: Developed the `Model`, `Logic` and `Ui` components of the analytics feature of IchiFund.
** What it does: This feature provides deeper insights into users' incomes and expenditures, allowing users to take control of their personal finances.
** Justification: This feature enhances IchiFund significantly because users are given a clear and concise overview of their incomes and expenditures over time and across categories using the `expenditure`, `income`, `balance` and `breakdown` commands. Without this feature, the data would be too cluttered and minimally effective at best in achieving the application's goal of easy and convenient finance management.
** Highlights: This feature affects commands to be added in future. It required an in-depth analysis of design alternatives. Notably, the implementation was challenging as it required a thorough understanding of the existing Address Book (Level 3) (AB3) infrastructure and an overhaul of the existing code base due to the lack of similarity between existing and intended components.

* *Minor enhancement*:
** `catrank` command: This command allows users to view their expenditure category ranking chart.
** `mthrank` command: This command allows users to view their expenditure ranking chart by month.
** `exprank` command: This commands allows users view their expenditure ranking chart.

* *Code contributed*: Click https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=Alaete[here] to view the code I have contributed.

* *Other contributions*:

** Project management:
*** Helped manage the issue tracker
*** Helped review and merge pull requests
** Enhancements to existing features:
*** Updated User Guide remove AB3 references and to be more user-friendly: https://github.com/AY1920S1-CS2103T-W12-4/main/pull/156[#156]
** Documentation:
*** Updated placeholder image: https://github.com/AY1920S1-CS2103T-W12-4/main/pull/158[#158]
*** Updated the User Guide and Developer Guide
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/AY1920S1-CS2103T-T09-2/main/issues/180[#180], https://github.com/AY1920S1-CS2103T-T09-2/main/issues/181[#181], https://github.com/AY1920S1-CS2103T-T09-2/main/issues/182[#182], https://github.com/AY1920S1-CS2103T-T09-2/main/issues/183[#183], https://github.com/AY1920S1-CS2103T-T09-2/main/issues/184[#184], https://github.com/AY1920S1-CS2103T-T09-2/main/issues/185[#185])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=overviewanalytics]

include::../UserGuide.adoc[tag=catrankanalytics]

include::../UserGuide.adoc[tag=mthrankanalytics]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=overviewanalytics]

include::../DeveloperGuide.adoc[tag=expenditureanalytics]

include::../DeveloperGuide.adoc[tag=balanceanalytics]

== PROJECT: IchiFund

'''
