= Abhinav Ramnath - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:experimental:

== Introduction
This project portfolio documents my contributions to a software engineering group project taken in my sophomore year in the National University of Singapore. For this project, my team and I worked together to build
a desktop application, +Work, targeted at NUS students who are project leaders.

=== About the Project
+Work is a project management tool with a graphical user interface (GUI) that helps project leaders to manage their projects details. +Work uses a command line interface (CLI) to operate, in other words, users mainly interact with +Work by typing specific commands and pressing the enter key. +
The main features of +Work include; managing tasks, managing members, managing inventory, generating statistics, generating PDF reports and finding optimal meeting times for members.

=== Important Symbols
Shown below are a few symbols that will appear in this document, along with their significance.
[TIP]
Information listed here can help users of +Work save time when using the application.

[NOTE]
Information listed here should be noted by users to help them improve their experience.

[IMPORTANT]
Information listed here is essential to users. They need to understand this in order for +Work to work optimally.

== Summary of Contributions
This section serves to summarise my major contributions to the project as well other noteworthy contributions such as project management.

=== Enhancements

* *Major enhancement one*: I added the ability for users to *customise the appearance* of +Work to suit their viewing preferences.
** What it does: This feature allows the user to toggle the theme of the entire application between light and dark. Also, it allows the user to toggle the
display of task deadlines format of the app between 24hr and 12hr.
** Justification: This feature improves the current product as +Work can adapt to users viewing preferences. Furthermore, as +Work scales to `v2.0` and beyond, it would be easier for users and developers alike to
handle the increasing complexity additional features may bring.
** Highlights: As of the latest release, this enhancement affects any command that deals with time sensitive data. It required an in-depth analysis of design alternatives. +
The implementation was moderately difficult as I was able to adapt the integration of the
`UserSettings` component based on existing components. The more difficult aspect was to design the component in such a way where it would be easy to extend its functionality
in the event more user settings are to be added. I tried to incorporate as much of the OOP principles as possible so as to
make the feature more robust.
** Credits: I adapted some code that does responsive highlighting for the settings panel in +Work from a course mate.

* *Major enhancement two*: I added a *project dashboard* to +Work that helps users see important information when the application opens.
** What it does: This feature allows the user to view their tasks based on their current completion status. Furthermore, users can view their upcoming deadlines as well as any upcoming project meetings.
** Justification: This feature improves the current product as students decide which tasks demand their attention so that they can remain on track for their project. Furthermore, they can prepare for upcoming meetings more efficiently.
** Highlights: The dashboard is responsive to changes in task status, deadlines and any project meetings. The implementation was relatively simple as I was also responsible for integrating task management into the project.

* *Minor enhancement*: I added cosmetic improvements to +Work's dashboard so as to make it more appealing to students.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=ambhinav&tabRepo=AY1920S1-CS2103T-T12-1%2Fmain%5Bmaster%5D[Functional code]] [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=ambhinav&tabRepo=AY1920S1-CS2103T-T12-1%2Fmain%5Bmaster%5D[Test code]]

=== Other Contributions

** Project management:
*** Managed releases `v1.1`, `v1.2.1` and `v1.4` (3 releases) on GitHub
*** Tracked and helped to fix bugs found during developer testing using GitHub issues (Issue https://github.com/AY1920S1-CS2103T-T12-1/main/issues/82[#82])
*** Added additional tests to the repository to bump coverage up from 37% to 39% (Pull request https://github.com/AY1920S1-CS2103T-T12-1/main/pull/166[#166])
** Enhancements to the application:
*** Created a modular framework in `Ui` to make it easier for teammates to add different user views for their respective features (Pull request https://github.com/AY1920S1-CS2103T-T12-1/main/pull/51[#51])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com/AY1920S1-CS2103T-T12-1/main/pull/152[#152]
** Community:
*** Reviewed pull requests made by teammates to the repository on GitHub (with non-trivial review comments): https://github.com/AY1920S1-CS2103T-T12-1/main/pull/55[#55]
*** Reported bugs and suggestions for other teams in the module (examples:  https://github.com/ambhinav/ped/issues/6[1], https://github.com/ambhinav/ped/issues/5[2], https://github.com/ambhinav/ped/issues/3[3])
** Tools:
*** Added the test coverage tool Coveralls to the team repository (Pull request https://github.com/AY1920S1-CS2103T-T12-1/main/pull/149[#149])

== Contributions to the User Guide

The following is an excerpt taken from the User Guide of +Work. I wrote instructions to help users customise their preferences using the
settings feature.

include::../UserGuide.adoc[tag=settings]

== Contributions to the Developer Guide

The following is an excerpt taken from the Developer Guide of +Work, showing additions I have made to explain the technical
aspects of the settings and dashboard feature.

include::../DeveloperGuide.adoc[tag=settings]

include::../DeveloperGuide.adoc[tag=dashboard]
