= Chen Anqi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MooLah

---

== Overview

This Project Portfolio documents my contributions to MooLah, a student project for a Software
Engineering module. In teams of five, we were tasked with developing the seedu project "AddressBook - Level 3"
to a product of our own choice. Our team decided to morph it to a hassle-free expense tracker - MooLah.

Expense tracking is an inherently troublesome task, because it includes managing
multiple budgets, monitoring complicated statistics, and anticipating future spending.
MooLah aims to streamline this process by providing a user-friendly desktop Command-Line Interface (CLI) solution. MooLah is written in Java, and has about 23 kLoC. It improves efficiency of expense tracking through autocomplete and prefix suggestions.
With a natural language time parser, MooLah accepts more intuitive and flexible time input. The robust budgeting feature
help users cultivate healthy spending habits. With powerful statistics, users can visualize their expenditure in
graphical forms. Besides, the menu feature is specially tailored to students in National University of Singapore,
allowing them to record an expense in school canteens directly from preset menus. Furthermore, MooLah's support for undo-redo
creates a seamless user experience. All these solid and well-developed features make MooLah a perfect personal financial assistant.

== Summary of Contributions
My main role in the team was to develop the budgeting feature. The following is a summary of my
contributions to this feature.

* *Major Enhancement*: added *the ability to track expenses under different budgets, and manage multiple budgets*. +
The budgeting feature is a significant enhancement to MooLah. Users need a tool to help them monitor their expenditure and avoid overspending.
This is especially relevant to our main target users - university students, most of whom do not have a stable income.
The budgeting feature enables users to be more controlled with their own expenses, grow healthy saving habits,
and cultivate good financial management skills to prepare for the future.
** What It Does:
(i) Allows users to monitor spending through a budget progress bar and receive timely notifications when total expenditure hits
important thresholds.
(ii) Allows users to add, modify, delete, and clear budgets.
(iii) Allows users to switch primary budget.
(iv) Allows users to view expenses in a past budgeting period.
** Highlights:
The budgeting feature involves adjustments to the existing model, logic, storage and UI components.
I developed ten budgeting-related commands, added utility classes such as `Percentage`, `BudgetPeriod` and `BudgetWindow`,
and wrote unit tests for all, achieving 100% lines coverage for my part.
One highlight is `BudgetWindow#normalize()`, which shifts the budgeting period to another anchored by a specific date.
While developing this method, it was necessary for me to take into account marginal cases such as February, leap year, and months with 30 days,
and constantly fix emerging bugs to ensure good functionality.
Besides, to make sure budgeting integrates well with undo-redo, I must check through every command to make sure all
undo-redo changes are immediately reflected both on GUI and in storage files. Considering that undo revolves
around `Model`, I need to ensure a deep copy of the budget is made upon every single modification of existing budgets in
the model, which was challenging and time-consuming to debug.

* *Minor Enhancement*: added two commands (`EditExpenseFromBudgetCommand` & `DeleteExpenseFromBudgetCommand`) that allow
users to *edit or delete expenses directly from the budget panel, without having to switch to general expense list first*.

* *Code Contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=anqichen9856&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=anqichen9856&tabRepo=AY1920S1-CS2103T-T11-1%2Fmain%5Bmaster%5D[Functional code]] [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=anqichen9856&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=anqichen9856&tabRepo=AY1920S1-CS2103T-T11-1%2Fmain%5Bmaster%5D[Test code]]

* *Other Contributions*:

** Project Management:
*** Managed issues on GitHub, set up various labels, and assigned team members to corresponding issues
*** Set up milestones with suitable deadlines and wrapped up regularly, closing resolved issues and moving unresolved ones to next milestone
*** Managed releases `v1.1`, `v1.2.1`, `v1.3.0`, `v1.3.1` (4 releases) on GitHub

** Refactor:
*** Replaced all traces of "address book" (from parameter names, class names, javadoc comments and tests in the code base) with "moolah" (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/123[#123])
*** Organized commands, parsers and UI components into different packages according to their features in both main and test directories (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/126[#126])
*** Changed the package "seedu.address" to "seedu.moolah" in both main and test directories (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/253[#253])
*** Changed output jar name from "addressbook.jar" to "moolah.jar" in Gradle build file (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/155[#155])
*** Created an app icon for MooLah (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/126[#126])

** Enhancements to existing features:
*** Updated the GUI to adopt a more elegant and harmonic color scheme with purple and yellow (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/166[#166])
*** Adjusted font colors on GUI to a darker one, increasing contrast against background and improving readability (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/245[#245])
*** Populated SampleDataUtil class with various budgets and expenses so that MooLah has sufficient data upon first launch (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/156[#156])

** Documentation:
*** Improved introduction section of the User Guide (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/259[#259])
*** Transferred user stories from GitHub issues to Developer Guide and formatted them in table form for better readability (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/53[#53])
*** Updated Gradle configuration (site name, etc.) and URLs in User Guide and Developer Guide to suit MooLah project site (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/43[#43], https://github.com/AY1920S1-CS2103T-T11-1/main/pull/54[#54])
*** Updated About Us, Contact Us, and README to match Project MooLah (PR https://github.com/AY1920S1-CS2103T-T11-1/main/pull/51[#51], https://github.com/AY1920S1-CS2103T-T11-1/main/pull/56[#56])

** Community:
*** Reviewed PRs of peer teams with non-trivial review comments (examples: https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/28[#28])
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/AY1920S1-CS2103T-F11-1/main/issues/234[#234], https://github.com/AY1920S1-CS2103T-F11-1/main/issues/224[#224], https://github.com/AY1920S1-CS2103T-F11-1/main/issues/230[#230])

** Tools:
*** Set up Netlify to the team repo, which facilitated previewing changes to documentation files if the PR contains updates to documentation.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=budget]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide.
They showcase my ability to write technical documentation and the technical depth of
my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=budget]
