= Bernice Chio Hui Yin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MORTAGO

---

== 1. Introduction

This document serves to note down my contributions to Mortago, our team’s product for our Software Engineering project.

Our team consists of five computer science undergraduates undertaking CS2103T Software Engineering module. We were tasked with enhancing a basic Command Line Interface (CLI) desktop address book application for our Software Engineering project. We chose to morph it into a mortuary management system called Mortago.

Mortago is a desktop application used for managing mortuaries efficiently. It is primarily used for keeping records of entries into the mortuary.

The user keys in commands using a CLI, and views the command results on a Graphical User Interface (GUI) created with JavaFX. Mortago was built upon a given base code provided by the SE-EDU team. It is written in Java, and has about 20kLoC.

Here are the main features of Mortago:

1.	Generate Report
2.	View Alerts
3.	View Dashboard
4.	View Statistics
5.	Undo and Redo

== 2. Summary of contributions

This section provides the overall view of my contributions to Mortago. All my pull requests (PRs) can be found https://github.com/AY1920S1-CS2103T-T13-2/main/pulls?q=is%3Apr+assignee%3Abernicechio+is%3Aclosed[here].

*2.1. Major Enhancements*

I have contributed 3 supportive enhancements for Mortago’s main feature Generate PDF. Generate PDF automatically generates reports with the specified command.

* *2.1.1. Major enhancement 1:* added the ability to create a PDF document which contains reports for all bodies in the mortuary
** *What it does:* This enhancement allows the manager to automatically generate all full reports for all bodies in a PDF document.
** *Justification:* This enhancement provides convenience for the manager to generate reports for all bodies using a single command.
** *Highlights:* //TODO This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** *Credits:* The https://github.com/itext/itext7[iText Library] is heavily used in this feature to facilitate generating a PDF file in Java.

* *2.1.2. Major enhancement 2:* added the ability to create a PDF document which serves as the report for a specific body
** *What it does:* This enhancement allows the manager to automatically generate a single full report containing details of a specific body in a PDF document.
** *Justification:* In the event that the details of a specific body has been updated, this enhancement provides flexibility for the manager to generate an updated report for the specific body.
** *Highlights:* //TODO This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** *Credits:* The https://github.com/itext/itext7[iText Library] is heavily used in this feature to facilitate generating a PDF file in Java.

* *2.1.3. Major enhancement 3:* added the ability to create a PDF document which contains a tabular view for all bodies in the mortuary
** *What it does:* This enhancement allows the manager to have a brief overview of all the bodies in a PDF document.
** *Justification:* This enhancement highlights key information of each body to the manager so that the manager need not go through every full body report.
** *Highlights:* //TODO This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** *Credits:* The https://github.com/itext/itext7[iText Library] is heavily used in this feature to facilitate generating a PDF file in Java.

*2.2. Minor enhancement*: morphed `list` command to allow the manager to list all bodies, workers and fridges in the application.

*2.3. Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=bernicechio&tabRepo=AY1920S1-CS2103T-T13-2%2Fmain%5Bmaster%5D[via RepoSense]]

*2.4. Other contributions*:

** Project management: Remove non-existing developers photos from `docs/images` folder (Pull request https://github.com/AY1920S1-CS2103T-T13-2/main/pull/130[#130])
** Enhancements to existing features: wrote additional tests for existing features to increase coverage to 82.5% (Pull request https://github.com/AY1920S1-CS2103T-T13-2/main/pull/71[#71])
** Documentation:
*** made cosmetic tweaks to existing contents of the Developer Guide (Commits https://github.com/AY1920S1-CS2103T-T13-2/main/commit/02abc4c16450c0f627eb0401e210a4e82e883dc6[1], https://github.com/AY1920S1-CS2103T-T13-2/main/commit/8a189ab2262d3e28a64f05fbc4f7f09fca6f6bca[2], https://github.com/AY1920S1-CS2103T-T13-2/main/commit/c22ec137fdfa00f9530a22d4b319910c0158e338[3])
*** updated existing diagrams of the Developer Guide (Commits https://github.com/AY1920S1-CS2103T-T13-2/main/commit/8b76f96a6ad08418029ffdba1a758731b236417f[4], https://github.com/AY1920S1-CS2103T-T13-2/main/commit/4be6223dcb76d48eab6502a3acdfab235bf44307[5], https://github.com/AY1920S1-CS2103T-T13-2/main/commit/6783630e1eb4544992d759481874f159fac10ffc[6], https://github.com/AY1920S1-CS2103T-T13-2/main/commit/a553c727fcb7099a1383d808fe6577ea8ca541e3[7]) (//TODO Pull request https://github.com[#200])
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S1-CS2103T-T13-2/main/pull/9[#9], https://github.com/AY1920S1-CS2103T-T13-2/main/pull/31[#31], https://github.com/AY1920S1-CS2103T-T13-2/main/pull/47[#47], https://github.com/AY1920S1-CS2103T-T13-2/main/pull/63[#63], https://github.com/AY1920S1-CS2103T-T13-2/main/pull/102[#102]
*** Contributed to forum discussions (Issue: https://github.com/nus-cs2103-AY1920S1/forum/issues/89[#89])
*** //TODO Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
** Tools:
*** Integrated a third party library (iText) to the project (https://github.com[#42])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=report]

include::../UserGuide.adoc[tag=reports]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=genpdf]

include::../DeveloperGuide.adoc[tag=genpdf]

---
