= Bertrand Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]

== Project: PalPay

== Overview

This portfolio documents my contributions to PalPay, a software engineering project under the module,
CS2103T Software Engineering. My Team and I was tasked to morph an existing software application into a functional application to better suit our intended target issues and audiences.

PalPay is a financial tracking applications activated through a Command-Line-Interface (CLI). Our intended target audience being computing students who lacked a centralized platform for financial management and planning.

For the project, my main role was to develop the Transaction feature.
This feature represents the fundamental user logging and tracking feature which other features of this application subsequently depends on.


== Summary of contributions

* *Code contributed*: https://ay1920s1-cs2103t-w12-3.github.io/publish-RepoSense/#search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=dingyuchen&tabRepo=AY1920S1-CS2103T-W12-3%2Fmain%5Bmaster%5D[RepoSense]

* *Major enhancement*: Implemented the `Transactions` tab and the features subsumed under it.

** What it does: Allows users to input and log their expenditure and income statements. PalPay will also display an overall transaction balance to give users an overall sensing of their financial habits.

** Justification: This feature fulfils the primary goal of the application which is to provide users a platform to store and log all their financial statements in a fast and intuitive manner.

** Highlights: This feature requires constant integration with all existing major features of PalPay (i.e. `out` Transaction to affect `budget` if certain conditions are met). This requires constant cross-examination with other features and reimplementation of the code base to ensure optimal functionality. This also requires a broad familiarity with the entire code base at all points during the development phase.

* *Minor enhancement*:
** Implemented and handled code base throughout for Update feature and `UpdateTransactionDescriptor` to function with all different major features.
** Handled parser checks for the `Amount` variable for incorrect or potentially program-breaking cases. (i.e. Maximum parsed amount can only contain a value of 999,999)

* *Other contributions*:

** Project management:
*** Managed issue tracker of the group's repository
*** Handled external team bug catches. (Issues :
https://github.com/AY1920S1-CS2103T-W12-3/main/issues/176[#176],
https://github.com/AY1920S1-CS2103T-W12-3/main/issues/166[#166],
https://github.com/AY1920S1-CS2103T-W12-3/main/issues/151[#151],
https://github.com/AY1920S1-CS2103T-W12-3/main/issues/145[#145],
https://github.com/AY1920S1-CS2103T-W12-3/main/issues/132[#132],
https://github.com/AY1920S1-CS2103T-W12-3/main/issues/109[#109])

*** Reviewed and merged pull requests. (Pull requests:
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/251[#251],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/234[#234],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/147[#147],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/122[#122],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/101[#101],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/79[#79])


** Enhancements to existing features:

*** Comprehensive Unit and Integration Tests (Pull requests:
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/211[#211],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/99[#99])

*** Refactored `Name` model object to `Description` model object (Pull requests:
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/111[#111])

*** Implemented and integrated `Update` class (Pull requests:
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/211[#211],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/108[#108],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/101[#101])


** Documentation:
*** Reformatted the User Guide for a more sequential flow.
*** Wrote the details for the following commands in the User Guide.
**** In
**** Out
**** Update
**** Delete
*** Created UML diagrams to help in the explanation of `in / out`, `update` and `delete` commands in the Developer Guide.
*** Included **Aspect** cases under **Design Considerations** in the Developer Guide.

** Community:
*** Reported bugs and suggestions for other teams in the module. (Examples:
https://github.com/AY1920S1-CS2103T-T13-1/main/issues/223[T13-1 #223],
https://github.com/AY1920S1-CS2103T-T13-1/main/issues/222[T13-1 #222],
https://github.com/AY1920S1-CS2103T-T13-1/main/issues/221[T13-1 #221],
https://github.com/AY1920S1-CS2103T-T13-1/main/issues/220[T13-1 #220],
https://github.com/AY1920S1-CS2103T-T13-1/main/issues/219[T13-1 #219],
https://github.com/AY1920S1-CS2103T-T13-1/main/issues/216[T13-1 #216])

== Contributions to the User Guide


|===
|_Given below are snippets of sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=out]

include::../UserGuide.adoc[tag=update]

== Contributions to the Developer Guide

|===
|_Given below are snippets of sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=transaction]

include::../DeveloperGuide.adoc[tag=update]


