= Daryl Koh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Budget Buddy

This portfolio provides a detailed report of my contributions to
*Budget Buddy*.

== Overview

Students taking part in this project were tasked to either enhance or morph a simple CLI-based address book application.
We decided to create a finances tracker, *Budget Buddy*, for NUS Computing Students, to both address the need by students to
manage their finances, as well as customise the application's features to suit our users as much as possible,
leveraging on their familiarity with typing and using a CLI.

Budget Buddy is a finances tracker designed around the needs and habits of NUS School of Computing students.
Interaction is mainly through a Command Line Interface (CLI), and results are displayed via a Graphical User Interface (GUI) powered by JavaFX.

Budget Buddy can keep track of transactions across separate accounts, so that users can clearly and conveniently organise their spending.
The application can also keep track of loans that users have made, addressing the habit of our users often borrowing money
from one another, but having trouble remembering exactly who owes money to them, and how much they owe.

Going above and beyond the basic functions that many other trackers have, Budget Buddy also has the ability to run Scripts
and Rules that users have created. These scripts and rules can then carry out custom actions as defined by the users,
who should have some experience with writing code. By capitalising on their programming know-how to create a truly personalised experience,
Budget Buddy distinguishes itself from other finance trackers out there.

== Project Role

My role was mainly to implement Transactions within Budget Buddy. Transactions formed the core of Budget Buddy's finances
tracking, and I implemented the functionality to add, edit and delete Transactions from the finances tracker.

The following sections will elaborate further on my contributions regarding this feature, as well as any other contributions
that I have made.

== Summary of contributions

|===
|The following section summarizes my contributions to Budget Buddy.
|===


=== Major enhancement
Added functionality to add, edit and remove transactions, as well as to list, sort and filter them.

* Function: Transactions provide the ability for users to record their day-to-day spending. The ability
to delete and edit Transactions allows users to correct mistakes in finances recording, or retroactively
update past finances.

* Purpose: Transactions form the core of the functionality of Budget Buddy. Users will be using it
to record their transactions daily, as well as use the sorting and filtering functions to get a clear
view of their spending habits and trends.

* Challenges: Implementing Transactions on their own was a straightforward task, but the difficulties arose
with making sure it integrated well with the rest of the functions of Budget Buddy. One example was another
enhancement I made to the GUI for showing the active account, and implementing the corresponding logic. The full details
are explained below, as a minor enhancement.

=== Minor enhancement
Make manipulating transactions more intuitive when integrated with accounts, by implementing logic to determine the active account.

* Function: Because transactions are never manipulated in isolation in Budget Buddy, the Accounts containing them need to be
taken care of as well. This feature provided the logic to keep track of the active account, so that transaction commands
would not always need to have a specified account, helping Budget Buddy feel more user-friendly and intuitive.

* Purpose: Transactions are the core feature of Budget Buddy, and hence they should be as user-friendly and intuitive to
manipulate as possible.

* Challenges: Implementing a responsive GUI for Transactions proved to be a challenge, as this was our first time
working with JavaFX. It was challenging to think about how to provide a intuitive user experience as well, while maintaining
a logical flow to manipulating transactions.

=== Code contributed
* [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=cambrian-dk[Click here for the RepoSense Report]]

=== Other contributions

* GUI Enhancements:
** Implemented responsive GUI for Active account: Pull request https://github.com/AY1920S1-CS2103T-W13-4/main/pull/194[#194]
* Bug fixes:
** Fixed bugs reported regarding Transactions during PE Dry run: Pull request https://github.com/AY1920S1-CS2103T-W13-4/main/pull/166[#166]
* Documentation:
** Made contributions to the User Guide/Developer Guide as shown below
* Community:
** PRs reviewed with non-trivial comments:
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/34[#34]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=transactions]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=transactions]

include::../DeveloperGuide.adoc[tag=activeAccount]

