= Chen Su - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Module Appeal Management System (MAMS)

---

== Overview

The Module Appeal Management System (MAMS) is a desktop app that aims to combine Command Line Interface (CLI) style commands
with a triple-pane GUI for easy navigation of appeals, module information, and student particulars. This app is particularly
aimed towards *module appeal administrators who prefer to work through their heavy backload of module appeals without ever having to
leave the comfort of the keyboard for their mouse*. The MAMS system can quickly bring up entire lists of students, appeals, and modules for
side-by-side comparison, with specific display commands to view the expanded details of any particular object in question. The MAMS system also provides
a suite of commands for resolving appeals, overriding MC limits, and leaving special notes on students.

The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 20 kLoC.

[NOTE]
This portfolio was adapted from the AddressBook - Level 3 project.

== Summary of contributions

* *Major enhancement 1*: added *the ability to check clashes for various cases*
** What it does: allows the admin to check timetable clash between 2 modules or in a student's current timetable;
Provides a shortcut for the admin to retrieve information on timetable clash in appeals requesting to add or drop modules.
** Justification: Checking timetable clash is one of the most important checks that an admin needs to perform before he/she decides to approve or reject an appeal.
This feature improves the user experience significantly because it provides a convenient way for the admin who needs to perform such checks constantly.
** Highlights: There are a few types of checks can be performed. Therefore, the user inputs for this command can take various forms and are highly flexible.
An in-depth analysis of design alternatives is required to deal with these variations.

* *Major enhancement 2*: enhanced the find command that allows the user to ...
** What it does:
** Justification:
** Highlights: This enhancement affects existing commands and commands to be added in future.
provide shorcuts...

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Helped to manage releases `v1.3` on GitHub
*** issue trackers
** Enhancements to existing `find` features:
*** Wrote tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** First draft of User Guide to aodc
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=clash]

include::../UserGuide.adoc[tag=find]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=logic]

include::../DeveloperGuide.adoc[tag=clash]

include::../DeveloperGuide.adoc[tag=find]

