= Cheong Siu Hong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NurseTraverse

---

== Overview

NurseTraverse is a desktop application designed to help community nurses manage all the data they may need, including visit management, appointment scheduling, and importing and exporting of patient data.
The user interacts with the app using a CLI (Command Line Interface) enhanced with an autocomplete functionality and ability to undo and redo commands. The app has a GUI created with JavaFX and is written in Java.
NurseTraverse is built by me and 4 other students.

== Summary of contributions

* *Major enhancement*: added *the function to export and import patient data.*
** What it does:
*** Exporting features: allows the user to export patient data into a comma separated values (CSV) file. Patient data can be exported all at once, or selectively by index.
*** Importing features: allows the user to import patient data from a CSV file. Imported patient data can either be used to replace all existing patient data or be merged with existing patient data.
** Justification: This feature improves the functionality of the product by facilitating convenient data sharing.
To add data for a few patients, there is no longer a need to use the add command multiple times, which can be a hassle. Example use cases:
*** A freshly trained nurse has been assigned her first set of patients. The patients' data can be passed to the nurse in the CSV format and imported in one go.
*** A (few) patient(s) has been transferred from the care of one nurse to another. The relevant patient data can be exported, passed to the other nurse, and imported.
*** An archive of patient data has to be kept for records purposes. The export feature allows for a "snapshot" of all patient data to be saved easily.
** Highlights: This feature was implementation with Jackson's `dataformat.csv` library. The library is full of functions but is not exactly well documented, and thus the implementation took significant research and experimentation.
The final implementation with this library is such that the export and import functionality can easily be extended to include additional data fields in the future, using Jackson's `Annotation` feature.
Apart the CSV parsing aspect, coding the data interaction for reading and writing patients to the address book had its challenges as well, due to the potential (buggy) interactions with the data from other features.
** Credits: link:https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-csv[Jackson Dataformat CSV], along with the existing Jackson annotations in AB3 used for JSON processing.

* *Code contributed*: My contributed code can be found link:https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=cheongsiuhong[here]. Use the filters to sort functional and test code as needed.

* *Other contributions*:

** Project management:
*** Opened milestones and user stories issues.
*** Managed milestones `v1.0` and `v1.1`.
** Documentation:
*** Created the product README
*** Sanitized irrelevant aspects of the User Guide and Developer Guide : https://github.com[#200]
** Community:
*** PRs reviewed (with non-trivial review comments) or approved:
https://github.com/AY1920S1-CS2103-F10-1/main/pull/66[#66],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/74[#74],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/75[#75],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/76[#76],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/95[#95],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/108[#108],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/109[#109],
and everything else link:https://github.com/AY1920S1-CS2103-F10-1/main/pulls?q=is%3Apr+reviewed-by%3Acheongsiuhong+is%3Aclosed[here]
*** Reported bugs (example: https://github.com/AY1920S1-CS2103-F10-1/main/issues/103[#103])
and another severe bug reported offline fixed in https://github.com/AY1920S1-CS2103-F10-1/main/pull/120[#120]
** Tools:
*** Integrated coveralls to the project.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../userguide/ImportExport.adoc[]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../devguide/ImportExport.adoc[]
