= Choong Yong Xin - Project Portfolio for MoneyGoWhere
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== About the Project

MoneyGoWhere is a finance application built by my team and I as part of a Software Engineering Project.
It was morphed from a basic command line interface Address Book.
MoneyGoWhere is a personal finance application targeted at students at the National University of Singapore (NUS).
It is designed to help students to keep track of all their spending and their related information such as date, cost and tags.
Notable features include allowing users to set budget goals, view statistics, set reminders for bills and export their data to a .csv file.

=== My Role

My  role was to implement the statistics and graph features.
The following sections will illustrate these features in greater detail.

Below are a few icons and formatting which will be used in this document.

[NOTE]
Important information that should be noted.

[TIP]
Tips that can help you better navigate the application.

`test`: Command to be executed or a component, class or object in the architecture of the application.

====
Additional useful information for this section.
====


== Summary of contributions

This section shows a summary of contributions I have made for the project.

* *Major enhancement*: I implemented the *statistics feature*.

** What it does: It allows the user to view their spending in the form of a pie-chart which organises the user's expenditure based on tags.
** Justification: This feature enhances the product significantly as it enables users to view their spending in the form of figures which is more reader-friendly.
Furthermore, it allows users to be more informed of their spending habits as they are now aware of where they have spent most of their money on, enabling them to reflect on their spending habits.
** Highlights: This enhancement required an in-depth understanding of the software architecture as it involves multiple components of the application.

* *Minor enhancement*: I implemented the *graph feature*.
** What it does: It organises the user's expenditure based on date, allowing users to view their daily expenditure based on a date range provided.
** Justification: It enables users to view how much they spend daily and also enable them to analyze trends in their spending amount over a particular period of time.
This helps them to better analyze their spending habits.
** Highlights: This enhancement also required an in-depth understanding of the software architecture as it involves multple components of the application.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=choongyx[Collated code]]
* *Other contributions*:

** Project management:
*** Helped track issues on the team repository using labels, milestones and project card

** Enhancements to existing features:
*** Refactored and modified existing class `Address` to `Cost` to fit the needs of our application
(Pull requests https://github.com/AY1920S1-CS2103T-F13-3/main/pull/61[#61],
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/67[#67],
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/71[#71])

** Documentation:
*** Vetted and formatted the entire User Guide after individual contributions by team members (Pull request https://github.com/AY1920S1-CS2103T-F13-3/main/pull/101[#101])
*** Reviewed team member's documentations (Pull requests
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/80[#80],
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/85[#85],
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/98[#98])
*** Updated Quick Start section and created a set of symbols/legends for User Guide (Pull requests https://github.com/AY1920S1-CS2103T-F13-3/main/pull/50/files[#50], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/101[#101])
*** Collated and updated profiles for all members of the team (Pull request https://github.com/AY1920S1-CS2103T-F13-3/main/pull/7/files[#7])
*** Updated Setting Up, Documentation, Testing and DevOps sections of Developer Guide (Pull request https://github.com/AY1920S1-CS2103T-F13-3/main/pull/244/files[#244])

** Community:
*** PRs reviewed with non-trivial review comments (Pull requests
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/62[#62],
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/70[#70],
https://github.com/AY1920S1-CS2103T-F13-3/main/pull/81[#81])
*** Conducted manual testing, reported bugs and offered suggestions for our team
(Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/issues/128[1],
https://github.com/AY1920S1-CS2103T-F13-3/main/issues/122[2],
https://github.com/AY1920S1-CS2103T-F13-3/main/issues/125[3])
*** Conducted manual testing, reported bugs and offered suggestions for other teams in the class
(Examples: https://github.com/AY1920S1-CS2103T-T10-1/main/issues/246[1],
https://github.com/AY1920S1-CS2103T-T10-1/main/issues/242[2],
https://github.com/AY1920S1-CS2103T-T10-1/main/issues/244[3])

== Contributions to the User Guide

Given below are sections I contributed to the User Guide for the Statistics feature and Graph feature.
They showcase my ability to write documentation targeting end-users.

include::../UserGuide.adoc[tag=statistics]

include::../UserGuide.adoc[tag=graph]

== Contributions to the Developer Guide

Given below are sections on the implementation of the Statistics feature and Graph feature I have worked on.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project.

include::../DeveloperGuide.adoc[tag=statistics]
include::../DeveloperGuide.adoc[tag=graph]


