= Kheng Yau Dong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Scheduler

---

== Overview

Scheduler is a desktop application which is used to automate the process of scheduling interviews.
Its main feature is matching interviewees with interview time slots to generate an interview timetable.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added the **ability to schedule interview**
** What it does: allows the user to schedule interviews for the interviewees using the imported interviewer
availability and interviewee details.
** Justification: This feature is the central feature behind the idea of the entire Scheduler application which is to schedule interviews
automatically so that the user do not have to manually schedule interviews and thus reduce their workload significantly.
** Highlights: The scheduling feature uses an algorithm which tries to maximise the number of interviewees who are allocated
with an interview slot. Please refer to the developer guide for more information regarding the algorithm.
** Credits:

* *Minor enhancement*: Created a data structure which model a schedule timetable as can be seen in the application. The data structure
is used to link multiple features together, such as adding an interviewer and displaying it on the ui.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases v1.0-v1.4 (4 releases) on GitHub.
** Enhancements to existing features:
** Documentation:
** Community:
** Tools:

== Contributions to the User Guide
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::

include::../DeveloperGuide.adoc[tag=dataencryption]

