= Lee Wei Ren Matthew - Project Portfolio (NurseTraverse)
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NurseTraverse

---

== Overview

NurseTraverse is a desktop application designed to help community nurses manage all the data they may need, including visit management, appointment scheduling, and importing and exporting of patient data.
The user interacts with the app using a CLI (Command Line Interface) enhanced with an autocomplete functionality and ability to undo and redo commands. The app has a GUI created with JavaFX and is written in Java.
NurseTraverse is built by me and 4 other students.

NOTE: This PPP may exceed the page limit as the URLs are not printed properly.

== Summary of contributions

* *Major enhancement*: added *the ability to manage visits*
** What it does: allows the user to manage their visits to their patients. They can create their own "checklist" of things to do for each patient, record said data during a visit and view data from previous visits.
** Justification: This feature has been identified as a required feature by user stories https://github.com/AY1920S1-CS2103-F10-1/main/issues/5[#5], https://github.com/AY1920S1-CS2103-F10-1/main/issues/6[#6] and https://github.com/AY1920S1-CS2103-F10-1/main/issues/25[#25] and will provide significant value-add by allowing users to manage visit data directly.
** Highlights: This enhancement adds a new feature for the user. From a design perspective, it was challenging as there was a need to make the use cases and commands usable and efficient while keeping the workload manageable. The implementation too was challenging as it is a rather big feature involving changes to existing commands and the creation of new commands.
** Credits: No code or ideas were referenced to outside of this application (beyond code that already exists within _Address Book 3_).

* *Code contributed*: Code contributed can be found via references in the following issues:
(v1.2: Issue https://github.com/AY1920S1-CS2103-F10-1/main/issues/62[#62],
v1.3: Issue https://github.com/AY1920S1-CS2103-F10-1/main/issues/53[#53],
Bug Hunting: Issue https://github.com/AY1920S1-CS2103-F10-1/main/issues/182[#182])

* *Other contributions*:
** Project management:
*** Setup initial https://github.com/AY1920S1-CS2103-F10-1/main/projects/1[Project Management Board]
*** Setup https://github.com/AY1920S1-CS2103-F10-1/main/pull/94[v1.2.1 release], v1.4 Issues for team (See issues #182-#186)
*** Helped coordinate team and help teammates debug code (offline, no documentation)
** Enhancements to existing features:
*** Modified relative to absolute indexing for Person list, find and edit (Pull Request https://github.com/AY1920S1-CS2103-F10-1/main/pull/69[#69]) which was required for this feature and some other features e.g. Appointment Management
*** Updated the GUI color scheme (See https://github.com/AY1920S1-CS2103-F10-1/main/pull/77[#77])
*** Added tabbing system to main window (See https://github.com/AY1920S1-CS2103-F10-1/main/pull/77[#77]) which was required for multiple features e.g. Appointment Management
** Documentation:
*** Setup initial User Guide to guide direction of project: (Pull Requests https://github.com/AY1920S1-CS2103-F10-1/main/pull/36[#36], https://github.com/AY1920S1-CS2103-F10-1/main/pull/37[#37])
** Community:
*** Pull Requests reviewed with non-trivial review comments or reviewed to approve:
https://github.com/AY1920S1-CS2103-F10-1/main/pull/66[#66],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/67[#67],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/71[#71],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/72[#72],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/73[#73],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/87[#87],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/91[#91],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/105[#105],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/112[#112],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/112[#112],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/197[#197],
*** Contributed to discussions (in Pull Request(s)
https://github.com/AY1920S1-CS2103-F10-1/main/pull/42[#42]
and offline/Telegram discussions)
*** Setup example Milestone issue format (https://github.com/AY1920S1-CS2103-F10-1/main/issues/53[#53])
** Tools:
*** Helped in setting up team repo
*** Helped in integrating Travis
*** Integrated Netlify, Coveralls and Codacy to the team repo

The full list of PRs by me (which includes all the PRs for https://github.com/AY1920S1-CS2103-F10-1/main/pull/104[refactoring], updating documentation, impromptu bug fixes and more) can be found https://github.com/AY1920S1-CS2103-F10-1/main/pulls?q=is%3Apr+author%3Acrazoter[here], and the full list of issues by me can be found https://github.com/AY1920S1-CS2103-F10-1/main/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Acrazoter+[here]. You can find my RepoSense Report https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=crazoter&tabRepo=AY1920S1-CS2103-F10-1%2Fmain%5Bmaster%5D[here]. Please note that the page count for this webpage is inaccurate as it displays all the URLs.

== Contributions to the User Guide

|===
|_Below are sections I contributed to the User Guide (non-exhaustive to keep within the page limit). They showcase my ability to write documentation targeting end-users. For more examples you can refer to the Visit portion of the UG._
|===

//include::../userguide/Visit.adoc[]

include::../userguide/VisitHowTo.adoc[]

//include::../userguide/Security.adoc[]

== Contributions to the Developer Guide

|===
|_Below are sections I contributed to the Developer Guide (non-exhaustive to keep within the page limit). They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../devguide/VisitsManagement.adoc[]
