= Erwin Chan Guo Xin - Project Portfolio
:site-section: AboutUs
:imagesdir: ../images
:stylesdir: ../stylesheets
:sectnums:
:note-caption: :information_source:

=== Introduction

The purpose of this portfolio is to record my contribution to our software engineering project. This project
is part of a software engineering module that I took during my second year in NUS. This project was done in a group of
five, consisting of Shawn, Dominique, Jeun Hoe and Jun Hup who are also second year computer science students. The
duration of this project spanned over a period of 6 weeks.

We were tasked to optimize or morph a basic command line interface (CLI) desktop addressbook application for this
project. We decided to morph the application into a team management application called Athletick which caters to
time-based sports. This application enables coaches or captains to manage their team by recording attendance for
training sessions as well as track the performances of their athletes. One of the constraints set for this project is
that the primary input to the application has to be CLI as it is meant for users who can type fast and prefer typing
over the use of mouse.

//image

The following is a list of our main features:

* Recording of attendance
* Recording of performance
* Viewing of attendance and performance on calendar
* Viewing of athlete's profile
* Undoing and redoing of commands

My role was to design and implement the feature that allows users to view the profile of an athlete. The following
sections will elaborate more on this feature which includes relevant documentation from the user and developer guides.

Note the following symbols and formatting used in this document:

[horizontal]
NOTE:: This symbol indicates important information
`command`:: A grey highlight indicates a command that can be executed.

=== Summary of contributions
This section shows a summary of my contributions to the team project.

*Enhancement added:* I added the ability to view an athlete's profile.

* What it does: The `select` command allows users to view the profile of an individual athlete.

* Justification: There will be occasions when users would like to track the progress of an athlete. The
`select` command
 allows them to view personal information such as the name, phone number and email address. The attendance rate and
 performance of the athlete is also displayed so that it is easier to monitor instead of looking at the attendance and
 performance of all the athletes.

 * Highlights: This feature works with other features such as `find` or `filter` which reduces the need to
 go through the list when looking for a specific athlete. For this feature there were many design alternatives to
 consider as there are many ways it could be implemented to display all the information. The current choice of design
 was used because it was in line with the other features my group mates had implemented. I felt that the implementation
 was quite challenging because it requires a certain knowledge on how to use JavaFX and SceneBuilder which were used to
 design the graphical user interface (GUI). With no prior experience, the learning curve was steep. As our need for
 the design became more specific, more advanced techniques were required which made it more challenging.

*Code contributed:* Please click these links to see a sample of my code: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=changuo79&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=ChangUo79&tabRepo=AY1920S1-CS2103T-T12-3%2Fmain%5Bmaster%5D[RepoSense Code Dashboard]]

*Other contributions*

* Project management

* Enhancements to existing features
** Updated `add` and `edit` command to allow addition of images for an athlete's profile by adding a prefix
`i/FILENAME.png`. (Pull request https://github.com/AY1920S1-CS2103T-T12-3/main/pull/75[#75])

* Documentation
** Updated developer guide to standardise the style and formatting.

* Community
** Reported bugs and gave some feedback on what could be improved (example:
https://github.com/ChangUo79/ped/issues/4[4],
https://github.com/ChangUo79/ped/issues/5[5],
https://github.com/ChangUo79/ped/issues/6[6])
** Reviewed pull requests (With non-trivial review comments):
https://github.com/AY1920S1-CS2103T-T12-3/main/pull/69[#69],
https://github.com/AY1920S1-CS2103T-T12-3/main/pull/75[#75]

=== Contributions to the user guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::..\UserGuide.adoc[tag=select]

==== FAQ

include::..\UserGuide.adoc[tag=FAQ]

=== Contributions to the developer guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

==== Select feature

include::..\DeveloperGuide.adoc[tag=select]

include::..\DeveloperGuide.adoc[tag=photo]

