= Evelyne Juliet - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: iFridge

---

== Overview

iFridge is a desktop grocery management application. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has a lot of code.

== Summary of contributions

* *Major enhancement*: added *the ability to undo/redo previous commands* for grocery list, shopping list, and template list command.
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives.
The implementation too was challenging as it required changes to existing commands
and undo/redo implementation needs to be adjusted to the different types of list and its properties.

* *Minor enhancement*: added a *reminder default command* which serves as an iFridge settings.
** What it does: Saves the user preference on the default number of days used to determine whether a grocery item is expiring soon or not.
** Justification: This is used in color coding grocery list and waste list based on expiry dates,
as well as for reminder command to check reminders for expiring food when no specific number of days is specified.
** Highlights: This enhancement adds more convenience to users as they can set their preference on color coding conditions
for grocery list and waste list which will be saved even when the app is closed and reused when the app is reopened.
It also gives the impression that the app can be personalized based on their preference as changes can be seen directly in the
user interface.

* *Code contributed*: The samples of my functional and test code can be viewed https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=evelynejuliet[here].

* *Other contributions*:

** Project management:
//*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
//** Enhancements to existing features:
//*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
//*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com/AY1920S1-CS2103-F10-2/main/pull/30[#30]
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/zhangxuan97/ped/issues/3[1], https://github.com/zhangxuan97/ped/issues/13[2], https://github.com/zhangxuan97/ped/issues/6[3])
** Tools:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=reminderdefaultcommand]

include::../UserGuide.adoc[tag=commandsummary]

include::../UserGuide.adoc[tag=wastelistfuture]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=reminderdefaultfeature]

include::../DeveloperGuide.adoc[tag=generalundoredofeature]

include::../DeveloperGuide.adoc[tag=groceryundoredofeature]

include::../DeveloperGuide.adoc[tag=shoppingundoredofeature]

include::../DeveloperGuide.adoc[tag=templateundoredofeature]

