= *Clarence Koh - Project Portfolio for $aveNUS*
:site-section: AboutUs
:icons: font
:imagesDir: ../images
:stylesDir: ../stylesheets

== Overview

$aveNUS is a command line interface (CLI) financial planning application that my team and I designed for
CS2103T (Software Engineering) module in School of Computing, National University of Singapore (NUS).

In this project, we morphed the sample address book application into $aveNUS, an application that allows NUS students
to track their financial spending with regards to food purchases. Additionally, the application provides them with
the best food recommendations within their current budget as well as a savings feature to track their savings.

The table below provides a quick summary of the symbols and formatting used in this portfolio.

[width="70%",cols="^15%,85%"]
|===
a| `code` | A grey highlight with monospaced font indicates a command that can be typed into the command box of the application.
a| [.java]#name# | A blue highlight with monospaced font indicates a reference to the codebase. This could be a component, class, method, attribute or file name.
a| icon:check[role="green", size="2x"] | A green tick indicates the expected result that you should see after executing a command in the application.
a| icon:lightbulb-o[role="icon-tip", size="2x"] | A lightbulb indicates tips and tricks that might be useful to the user.
a| icon:info-circle[role="icon-note", size="2x"] | A blue information symbol indicates additional information for that section that is good to know.
a| icon:exclamation-circle[role="icon-important", size="2x"] | A red exclamation mark symbol indicates important pointers to take note.
|===

== Summary of contributions

In this section, I will provide a summary of the contributions I have made to the team project.
THese include features which I have implemented as well as other project-related contributions.

=== Major enhancement: Savings Feature

I have added the Savings feature and all of its related commands.

==== What it does

It allows users to track their saving habits. Users can transfer money from their $aveNUS wallets into their savings account
using the `save` command. In addition, users can transfer money from their savings account and into their $aveNUS wallets
using the `withdraw` command.

Users can then track their savings and withdrawals made from the Savings History Panel of the application's GUI. The savings of a user
is displayed in Green, while the withdrawals are displayed as a negative sum of money, and in red.

==== Justification

In university, students are keen to plan for their lives after they graduate. Students would like to graduate with at least
a certain amount of money in their banks so that they can either pay for their student loans, or return the amount they borrowed
from their parents for paying off their school fees. To do this, they have to start saving from the time they stepped into university.

With the savings feature encompassed into the expenditure tracking application of $aveNUS, the application
serves as a one-stop application for them to efficiently plan their finances when they are in school. The Green display
for the savings added provides a friendlier display to encourage users to save more. The Red display for the withdrawals
made by the user is intentionally harsh, to serve as a warning to the users when they make a withdrawal.

==== Highlights

I had to implement new classes such as `ReadOnlySavingsHistory`, `SavingsHistory`, `ReadOnlySavingsAccount`, `SavingsAccount`
`Savings`, `CurrentSavings` and `SavingsHistoryList`. These classes had to be
implemented across the multiple components within the application architecture to support the Savings
feature, allowing me to better understand the project's architecture.

Storage functionality to keep track of the user's savings and withdrawals, was also implemented in this savings feature,
which allowed me to understanding how data can be saved persistently in a Jackson file.

I also learnt to write unit and integration tests for automated testing within the Savings feature.

It also gave me the opportunity to interact more in depth with the application's GUI, so
as to effectively present the savings history to the user.

=== Other enhancements added: History Retrieval and Restricted Display in Savings History

I assisted my team mate in enhancing his command history feature, allowing users to review the 10 latest
commands that they have typed using the `history` command.

In addition, I conceptualised the restricted viewing of Savings History and added the classes related to the feature.

==== What it does

Users can retrieve the 10 most recently typed commands by using the `history` command.

Users can also view only their savings/withdrawals in the Savings History panel, by using the `show` command that I
have implemented.

==== Justification

The history feature allows the user to conveniently refer to the list of commands he/she typed previously without the hassle of scrolling through his past commands
one by one using the "UP" or "DOWN" arrow. This speeds up input as well, since users can simply copy and paste a command that was typed much earlier.
This is especially useful since this application is a Command-Line application.

On the other hand, the show feature allows the users to view only their savings/withdrawals, thus allowing them to
track for themselves the savings/withdrawals they have made so far and decide if they have been withdrawing too much.

==== Highlights

I had to work closely with my other team members to implement the history feature as we worked on implementing different parts
of it.

The restricted view of the user's savings history also involves the change of certain commands that affects other
commands in the GUI such as the `CommandResult` class, which is used by multiple components within the application.

=== Code contributions

https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=fatclarence&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&until=2019-11-05[Project Code Dashboard]
| https://github.com/AY1920S1-CS2103T-F13-2/main/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Afatclarence+is%3Aclosed[Pull Request]

=== Other contributions

* Project Management:

** Adding users stories to share the goals of our application for the users

** Idealised and conceptualised the addition of the Savings feature

** Managed the integration of code by merging Pull Requests and ensuring compatibility

** Opened issues when enhancements could be made by team members [Issue https://github.com/AY1920S1-CS2103T-F13-2/main/issues/202[#202],
https://github.com/AY1920S1-CS2103T-F13-2/main/issues/140[#140]]

** Opened issues when bugs were found [Issue https://github.com/AY1920S1-CS2103T-F13-2/main/issues/133[#133]]

** Fixed bugs after they were found [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/159[#159],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/297[#297]]

* Enhancements to existing features:

** Updated the GUI by introducting the Savings History Panel and Savings History Cards to enable the
display of the user's savings history. [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/177[#177]]

* Documentation:

** Updated User Guide

*** Added into the User Guide the instructions to use the Savings feature. [PR
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/301[#301]]

*** Update UI images in the User Guide [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/217[#217]]

*** Update other general commands found in the application [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/173[#173]]

** Updated Developer Guide

*** Added into the Developer Guide information regarding the Savings feature. [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/188[#188],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/191[#191], https://github.com/AY1920S1-CS2103T-F13-2/main/pull/320[#320]]

*** Update User Stories and set standard for User Stories formatting. [PR
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/67[#67]]

*** Update other general commands found in the application [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/173[#173]]

** Community:

*** PRs review (with non-trival review comments) [PR
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/323[#323],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/305[#305],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/238[#238],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/179[#179]]

*** Reviewed the Developer Guide of other teams with my team members [
https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/64#pullrequestreview-306988261[Example here]]

== Contributions to the User Guide

This section shows the additions that I have made to the User Guide to provide information about how
the Savings feature works.

|===
| _I wrote the descriptions and commands for the savings feature (including commands for v2.0).
My description of the `save` command is replicated below
while my full write-ups can be found https://github.com/AY1920S1-CS2103T-F13-2/main/blob/master/docs/UserGuide.adoc#savings[here]._
|===

include::../UserGuide.adoc[tag=savings]

|===
| _I also wrote the descriptions for the history command. This is replicated below._
|===

include::../UserGuide.adoc[tag=history]

== Contributions to the Developer Guide

This section shows the additions that I have made to the Developer Guide to show the implementation
and design considerations for the Savings feature.

|===
| _I described the design of the Savings feature and the implementation of commands that allow users
to interact with the Savings feature. My write-up for the `save` command is replicated below while my overview
of the Savings feature can be found
https://github.com/AY1920S1-CS2103T-F13-2/main/blob/master/docs/DeveloperGuide.adoc#savings-feature[here]._

|===

include::../DeveloperGuide.adoc[tag=savings]

