= Felix Ng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CaloFit

---

== Overview

{Introductory statement is as when necessary}

My team of 4 software engineering students and I were tasked with enhancing a basic desktop addressbook application(AddressBook - Level 3) for our Software Engineering project. We chose to morph
it into a calorie tracker cum food database system called CaloFit.

CaloFit is a desktop application for tracking the calories that the user has taken from his or her meals over the course of using the application. +
The user interacts with CaloFit using a Command Line Interface(CLI) that is represented by a box near the top of the application screen. This is where the user can type in their commands and press "Enter" on their keyboards to execute them. +
It has a Graphical User Interface(GUI) created with JavaFX which is the main display that the user sees upon starting up CaloFit.

{Rubric says to list main features, indicated in PPP as a picture, can manually list as well}

My role was to design and write the codes for the report feature. The following sections
illustrate these enhancements in more detail, as well as the relevant documentation I have added to
the user and developer guides in relation to these enhancements.

{A key to the icons and formatting used in the document to be inserted.}

{Stuff not added from PPP guide: what you did to meet task requirements. background info of project scope.}

== Summary of contributions
This section shows a summary of my coding, documentation, and other helpful contributions to the
team project.

* *Major enhancement*: added *the ability to generate a Report*
** What it does: creates a Report that displays the statistics calculated from the user's meal history for that particualar month.
** Justification: This feature gives purpose to the application as the user should be someone who wants to keep track of their calorie intake. By implementing this feature, the user is able to know their calorie intake for the month, as well as other statistics generated from it, whenever they want.
** Highlights: As virtually any form of statistical data can be generated from a user's meal history, the scope of the data calculated and shown to the user is not exhaustive. The statistics chosen to be calculated are decided based on the user stories and use cases that our team has considered and is linked here.
** Credits: {Calculation of statistics}

* *Minor enhancement*: {Maybe include addition of Calorie Class? not really enhanceement/feature tho}

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.2.1`, `v1.3` and `v1.4` (3 releases) on GitHub.
** Enhancements to existing features:
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=report]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=report]
