= Francis Low Siu Yuan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NurseTraverse

---

== Overview

NurseTraverse is a desktop application meant for community nurse to help manage all the data that a community nurse might need. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java.

== Summary of contributions

* *Major enhancement*: added *the ability to autocomplete any command words in application*
** What it does: +
-  Allows the user to easily complete a full command with or without typing. +
-  Guides user in selecting which command to enter next through commands classifications in suggestion panel and command explanations in result box +
** Justification: Nurses and new users may not be familiar with command line input and the different types commands in the application. Thus, having a suggestion panel at the side will greatly enhance user experience, especially for slow typers. Having a guided system will aid nurses in familiarising with the application commands and understanding of the different functions in the system in general.
** Highlights: The implementation of word suggestion is rather tedious since many of the full commands have different formats. For example, "pat-list" do not require any patient index and prefixes but "pat-edit 1 n/ ..." requires both. Thus the implementation of list handlers were changed a few times to fit the objective of providing a better user experience. Logic for checking already matched words in order to change a new set of suggestion words is challenging as well, mainly due to many commands having different formats as mentioned earlier.
** Credits: No outside code or ideas were referenced in the development of these features (beyond code that already exists within Address Book 3).

* *Code contributed*: An overview of contributed code can be found
https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=francislow[here].
- Milestone v1.2: https://github.com/AY1920S1-CS2103-F10-1/main/issues/55[#55]
- Milestone v1.3: https://github.com/AY1920S1-CS2103-F10-1/main/issues/56[#56]
- Milestone v1.4: https://github.com/AY1920S1-CS2103-F10-1/main/issues/61[#61]
- Bug hunting: https://github.com/AY1920S1-CS2103-F10-1/main/issues/183[#183]

* *Other contributions*:

** Project management:
*** Managed release `v1.3` on GitHub
** Documentation:
*** Updated developers guide(appendix A-E) https://github.com/AY1920S1-CS2103-F10-1/main/pull/44[#44]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S1-CS2103-F10-1/main/pull/81[#81], https://github.com/AY1920S1-CS2103-F10-1/main/pull/98[#98]
*** Set up travis CI for the project

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../userguide/AutoComplete.adoc[]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../devguide/Autocomplete.adoc[]
