= Chao Fang How, Gabriel - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NurseTraverse

---

== Overview

NurseTraverse is a desktop application meant for community nurse to help manage all the data that a community nurse
might need. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java.

== Summary of contributions

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one or many at a time. Preceding undo commands can be
reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the
app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth
analysis of design alternatives. The implementation too was challenging as it required detailed handling of the model
state.
** Credits: No outside code or ideas were referenced in the development of these features (beyond code that already
exists within _Address Book 3_).

* *Minor enhancement*: added a history GUI panel that displays previous commands, making it much more convenient to
use the multiple undo command.

* *Code contributed*: An overview of contributed code can be found
https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=gabrielchao[here]. There are filters for
functional and test code. Otherwise, code contributed can be found via references in the following issues:
** Main issue: https://github.com/AY1920S1-CS2103-F10-1/main/issues/59[#59]
** Milestone v1.2: https://github.com/AY1920S1-CS2103-F10-1/main/issues/60[#60]
** Milestone v1.3: https://github.com/AY1920S1-CS2103-F10-1/main/issues/83[#83]
** Milestone v1.4: https://github.com/AY1920S1-CS2103-F10-1/main/issues/203[#203]
** Bug hunting: https://github.com/AY1920S1-CS2103-F10-1/main/pull/197[#197]

* *Other contributions*:

** Project management:
*** Managed release `v1.3.1` on GitHub
*** Helped pinpoint bugs in other code (Issues https://github.com/AY1920S1-CS2103-F10-1/main/issues/84[#84],
https://github.com/AY1920S1-CS2103-F10-1/main/issues/162[#162],
and a severe bug discussed offline and fixed in PR https://github.com/AY1920S1-CS2103-F10-1/main/pull/120[#120])

** Enhancements to existing features:
*** Make name comparison case insensitive (Pull request https://github.com/AY1920S1-CS2103-F10-1/main/pull/197[#197])

** Community:
*** PRs reviewed with non-trivial review comments or reviewed to approve:
https://github.com/AY1920S1-CS2103-F10-1/main/pull/68[#68],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/69[#69],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/77[#77],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/79[#79],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/85[#85],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/91[#91],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/96[#96],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/105[#105],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/120[#120],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/188[#188],
https://github.com/AY1920S1-CS2103-F10-1/main/pull/195[#195]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../userguide/DataUndoRedoHistory.adoc[]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../devguide/UndoRedoHistory.adoc[]
