= Ho Hol Yin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: LiBerry

== Overview
This portfolio aims to highlight my contributions to our team project, 'LiBerry'.

'LiBerry' is a library management system that is designed for small communities with a lack of expertise and
resources to manage a library.

This library management system is able to *manage books* in the library, *register* borrowers,
*loan* and *return* books, as well as *calculate loan periods* and *fines* for any overdue loans. +
{nbsp}

I was in charge of implementing the *Generate loan slip* feature and the *Book* feature.
Additionally, I am responsible for the *code quality and testability* of the team's code base throughout the entire development phase. +
{nbsp}

In this portfolio, I will illustrate my contributions in documenting the user guide and developer guide.
These documentations serve to aid librarians and developers in understanding the features of the software.

== Legend
I have used symbols to give a visual explanation to certain parts of this portfolio. This section aims to explain the meaning behind the usage of these symbols.

TIP: Denotes useful tips.

NOTE: Denotes additional information.

== Summary of contributions
This section shows a summary of my contributions to the team project and will include: +

. Major enhancement - Book feature
. Code contributed
. Other contributions +
{nbsp}

=== *Major enhancement - Book feature*
I am primarily involved the implementation of the book-related core features.
In the Book feature, we have the following sub-features:

** The ability to *add books*
* Allows the librarian to start tracking the movement of books using the system

** The ability to *delete books*.
* Enables the librarian to update the catalog when a book goes missing

** The ability to *display information* about a book.
* Aids the librarian in retrieving more information about a book when a borrower inquires about it +
{nbsp}

I will now share more details about this feature and how it plays a crucial role in 'LiBerry'.

==== What the feature does
This feature allows the librarian to manage the catalog of books in the system using the set of sub-features mentioned above.

==== Justification
This feature is a *must-have* for all library management systems as it provides a foundation for all other higher-level features (such as loaning and renewing books) to work.

==== Highlights
The main difficulty of this feature is the implementation of the ability to *display information of a book*.
This sub-feature requires the use of an `Observer` pattern that observes the loan history of the book.
With every new loan or renew, the info window will be updated.
I have provided a breakdown below as to how this feature achieves the required *depth*, *completeness* and *level of effort*.

* *Depth*: The Book feature is a representation of the cohesive Book component, which supports the ability to:
** *Add* a book to the catalog
** *Delete* a book from the catalog
** *Display information* about a book in the catalog
{nbsp}

* *Completeness*: This feature is cohesively and completely linked to the other core feature such as the Loan feature and the Borrower feature. +
{nbsp}

* *Effort*: Considerable effort was put in to assess the suitability of data structures used to store the books.
Much thought was also put into deciding what information should be displayed in the info window and what is the best way to display these information.

---
=== Code Contributed
The following link shows the analysis of my code contributions:

* https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=hoholyin&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[RepoSense link for Code Contributions]

---

=== *Other contributions*:

==== Project management:
* Managed the release of https://github.com/AY1920S1-CS2103T-F13-1/main/releases/tag/v1.3.1[`v1.3`] on GitHub. +
{nbsp}
* Continually added test cases throughout development phase to ensure consistent code quality. Done through the following Pull Requests:
** https://github.com/AY1920S1-CS2103T-F13-1/main/pull/31[[#31\]]: Refactored `AddressBook3` tests to `LiBerry` tests
** https://github.com/AY1920S1-CS2103T-F13-1/main/pull/206[[#206\]]: Increased test coverage for `UI` components
** https://github.com/AY1920S1-CS2103T-F13-1/main/pull/260[[#260\]]: Increased test coverage for `Delete` and `Book` classes

==== Enhancements to existing features:
These enhancements are done through the following Pull Requests:

* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/147[[#147\]]: Made the `Book` Object immutable in preparation for the undo/redo feature
* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/176[[#176\]]: Added a new `LoanHistory` object in `Book` for to be displayed in the info window
* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/177[[#177\]]: Created a borrower panel in the Graphical User Interface to list books that the borrower has currently loaned
* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/187[[#187\]]: Upgraded `LoanSlipUtil` to allow it to mount multiple loans into a single loan slip

==== Documentation:
The documentations are updated through the following Pull Requests:

* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/148[[#148\]]: Illustrated the `Model` component of the system and its behaviour through class and sequence diagrams
* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/159[[#159\]]: Documented the feature to generate loan slip and its design considerations
* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/162[[#162\]]: Amended Developer Guide based on feedback from tutor

==== Community:
* https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/49/files/22e0d669e265d0f2835df4e4a2d0f15a57b05795[Reviewed] a Pull Request from another group regarding their user stories and UML diagrams
* Contributed a https://github.com/nus-cs2103-AY1920S1/forum/issues/115[tip] in the forum (as a group) on how to check code coverage when running tests
* https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/49/files/22e0d669e265d0f2835df4e4a2d0f15a57b05795[Reported] bugs and suggestions for other teams in the class.

==== Tools:
This tool was added through the following Pull Request:

* https://github.com/AY1920S1-CS2103T-F13-1/main/pull/150[[#150\]]: Integrated a third party library (iText 7) to the project.

== Contributions to the User Guide

This section outlines my contributions to the team's User Guide.
It demonstrates my ability to write documentation for librarians so that they can learn how to: +

. Manage books in their library using the *Book feature*
. Generate loan slips using the *Generate Loan Slip* feature

=== Book feature
The ability to manage books in the system will help librarians track the status of all books with ease.
In the User Guide documentation of the Book feature, I will explain how to use the `add` and `delete` commands.
{nbsp}

include::../UserGuide.adoc[tag=bookRelated]
{nbsp}

=== Generating a loan slip
The done command triggers the generation of a loan slip, which can then be conveniently printed out by the librarian.
In particular, I implemented and documented the loan slip generation feature, allowing librarians to know how to generate a loan slip after serving a borrower.
In the User Guide documentation of this feature, I will cover the following: +

. How the loan slip will be generated when the librarian exits serve mode. +
{nbsp}

include::../UserGuide.adoc[tag=loanSlip]

== Contributions to the Developer Guide

This section highlights my contributions to the Developer Guide.
The following excerpts from the 'LiBerry' Developer Guide demonstrate my ability to aid other developers in understanding about:

. How the Book feature is implemented
. How the loan slip generation feature is implemented

=== Implementation of Book feature

include::../DeveloperGuide.adoc[tag=addBook]

=== Implementation of Generate Loan Slip feature

include::../DeveloperGuide.adoc[tag=printLoanSlip]

---

