= Project Portfolio Page: EzWatchlist
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

This document serves to show the various contributions that I have made in the development of *EzWatchlist* in an understandable manner.

== More About The Project
EzWatchlist is a desktop application that allows users to keep track of movies and tv series that they want to watch or have watched.
It was developed by a group of 5 students from the National University of Singapore taking the Software Engineering module including
myself under the premise that we had to either optimize or morph an existing AddressBook application. We chose the latter. Another
constraint was ensuring that the application had a command-line interface.

=== Main Features
* Adding, editing and deleting Shows
* Keeping track of shows  that are watched
* Online search functionality
* Statistics about user's watchlist

== Summary of Contributions

This section provides a summary of my coding, documentation and other helpful contributions to EzWatchlist.

=== Major Contributions

* Implemented of the *watch* feature for users to keep track of episodes of their tv series and movies watched
** The *watch* feature allows users to update the watch list if the show has been watched
** The watch feature enables users to keep track of shows that they have and have not watched that they can plan
out what they want to watch in the future
** The watch feature also enables users to keep track of the episodes in a TV series that have been watched

=== Minor Contributions

* Updating to the user and developer guides to make them more readable, including the use of diagrams and screenshots of the application
* Updating to EzWatchlist *Contact Us* page
* Writing of tests for EzWatchlist to reduce the possibility of bugs when using EzWatchlist
* Integrating of the features of EzWatchlist to improve the user-experience of the application

View code contributions link: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=jcjjjared&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=jcjjjared&tabRepo=AY1920S1-CS2103T-F13-4%2Fmain%5Bmaster%5D[here]].

== Contributions to User Guide

This section serves to showcase my contributions to the User-Guide, as well as my ability to write
documentation for users in a concise and understandable manner.

include::../UserGuide.adoc[tag=watch]

== Contributions to Developer Guide

This sections showcases my contribution to the EzWatchlist Developer guide for the `watch` function.

include::../DeveloperGuide.adoc[tag=markaswatched]
