= She Jiayu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AlgoBase

== Overview

AlgoBase is a desktop algorithmic problem manager.
The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 20 kLoC.

== Summary of contributions

* *Major enhancement*: implemented *task management feature*
** What it does:
This feature allows the user to keep track of the problems to be done as upcoming tasks
and thus manage his/her progress for each plan.
** Justification:
This feature is the core feature of AlgoBase.
It allows the user to manage the problems to meet different needs,
such as interviews for different companies or different rounds.
By introducing the notion of tasks, user can add more details to the problems
such as due dates and whether each problem has been solved, without modifying the original problem.
This adds significant value to AlgoBase as an algorithmic problem manager.
** Highlights:
This feature is highly coupled with the problem feature and plan feature.
It requires in-depth analysis of all existing features in order to avoid unintended behaviours.
For example, since each task stores a problem, when the corresponding problem is deleted or updated,
all tasks in all plans that are related to this problem need to be updated at the same time.
Moreover, to avoid user mistakes when deleting problems that are used in some tasks,
which may cause additional overhead to bring back the tasks,
a forced mode is introduced to reduce such possibilities.
It involves all main components in AlgoBase, including `Model`, `Logic`, `Storage` and `Ui`.

* *Minor enhancement*: Implemented *data management feature* +
It allows the user to export their data into JSON format and import new data from JSON files.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=jiayushe[View on RepoSense]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.0`, `v1.3.2` and `v1.3.3` (3 releases) on GitHub
** Enhancements to existing features:
*** TBA
** Documentation:
*** TBA
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/65[#65]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/67[#67]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/81[#81]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/90[#90]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/106[#106]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/214[#214]
*** Contributed to forum discussions: TBA
*** Reported bugs and suggestions for other teams in the class:
https://github.com/jiayushe/ped[PE Dry Run]
** Tools:
*** Integrated Github plugins (AppVeyor, Coveralls, Netlify, Traivs) to the team repository

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
include::../UserGuide.adoc[tag=task]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
https://ay1920s1-cs2103t-w11-1.github.io/main/DeveloperGuide.html#task-management-feature[Implementation - Task Management] +
https://ay1920s1-cs2103t-w11-1.github.io/main/DeveloperGuide.html#Design-Ui[Design - UI] +
https://ay1920s1-cs2103t-w11-1.github.io/main/DeveloperGuide.html#Design-Storage[Design - Storage]
include::../DeveloperGuide.adoc[tag=task]

== PROJECT: https://sourceacademy.nus.edu.sg/sourcecast[SourceCast]

An interactive code recorder and player to support e-teaching and e-learning, used in Source Academy,
an immersive experiential learning environment for NUS freshman programming methodology course, CS1101S.

