= Joel Loong - Project Portfolio
:site-section: AboutUs
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:

== Overview

This portfolio documents my contributions to PalPay, a software engineering project under the module,
CS2103T Software Engineering. For this module, we were provided with a working software application which we
could enhance or morph to suit our target audience.

For the project, my main role was

== Summary of contributions

* *Code contributed*: https://ay1920s1-cs2103t-w12-3.github.io/publish-RepoSense/#search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=joloong&tabRepo=AY1920S1-CS2103T-W12-3%2Fmain%5Bmaster%5D[RepoSense]

* *Major enhancement*: Implemented the ability to undo and redo previous commands.

** What it does: Undo command allows the user to undo all previous commands one at a time. Redo command reverses
preceding undo command.

** Justification: It gives users the ability to


** Highlights:

* *Minor enhancement*:

** Placeholder

* *Other contributions*:

** Project management:
*** Managed the biweekly project releases on GitHub.
*** Managed the issue tracker of the group repository.
*** Reviewed and merged pull requests.

** Enhancements to existing features:
*** Wrote comprehensive unit and integration test cases for the application's logic and model.
(Pull requests: https://github.com/AY1920S1-CS2103T-W12-3/main/pull/70[#70],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/114[#114],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/202[#202],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/205[#205])

** Documentation:
*** Reformatted the User Guide for a more sequential flow.
*** Wrote the details for the following commands in the User Guide.
**** View
**** Sort
**** Filter
**** Undo
**** Redo
**** Clear
**** List
**** Help
**** Exit
*** Wrote user stories in the Developer Guide.
*** Created UML diagrams to help in the explanation of view, sort and filter commands in the Developer Guide.

** Community:
*** Reported bugs and suggestions for other teams in the module. (Examples:
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/219[#219],
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/220[#220],
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/222[#222],
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/229[#229])
*** Provided tips and help to other students in the module. (Examples:
https://github.com/nus-cs2103-AY1920S1/forum/issues/70[#70],
https://github.com/nus-cs2103-AY1920S1/forum/issues/79[#79],
https://github.com/nus-cs2103-AY1920S1/forum/issues/110[#110])

** Tools:
*** Managed the initial set up of the group repository on GitHub.
*** Integrated Travis CI, Coveralls, Netlify and RepoSense into the group repository.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users._
|===

Placeholder

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

Placeholder


'''
