= Joel Loong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]

== Project: PalPay

== Overview

This portfolio documents my contributions to PalPay, a software engineering project under the module,
CS2103T Software Engineering. For this module, we were provided with a working software application which we
could enhance or morph to suit our target audience.

PalPay is a student application that effectively tackles the problem of the lack of a centralised platform to
manage their finances. PalPay provides the ability to easily track their expenses and manage their finances.

For the project, my main role was to develop the undo and redo feature for the application. Additionally,
I was tasked to develop the view, sort and filter features.

== Summary of contributions

* *Code contributed*: https://ay1920s1-cs2103t-w12-3.github.io/publish-RepoSense/#search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=joloong&tabRepo=AY1920S1-CS2103T-W12-3%2Fmain%5Bmaster%5D[RepoSense]

* *Major enhancement*: Implemented the ability to undo and redo previous commands.

** What it does: Undo command allows the user to undo all previous commands one at a time. Redo command reverses
preceding undo command.

** Justification: It gives users the ability to easily rectify their mistakes in commands. Hence, it improves
the user experience and a more convenient way of self-correction.


** Highlights: This requires a thorough understanding of the starting infrastructure of the application in other
to make changes to it. This enhancement affects existing commands and commands to be added in future. In addition,
I need to ensure the commands are undoable and redoable, and that there are no conflicts to the existing data
in the application.

* *Minor enhancement*:

** *View* command for users to switch tabs without the need of a mouse to click another tab. This meets the needs
of the target audiences who prefer using the command line.
** *Sort* command for users to sort their lists of transactions in PalPay.
** *Filter* command for users to filter their lists of transactions to reduce the need of scrolling through their lists.


* *Other contributions*:

** Project management:
*** Managed the biweekly project releases on GitHub.
*** Managed the issue tracker of the group repository.
*** Reviewed and merged pull requests.

** Enhancements to existing features:
*** Wrote comprehensive unit and integration test cases for the application's logic and model.
(Pull requests: https://github.com/AY1920S1-CS2103T-W12-3/main/pull/70[#70],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/114[#114],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/202[#202],
https://github.com/AY1920S1-CS2103T-W12-3/main/pull/205[#205])

** Documentation:
*** Reformatted the User Guide for a more sequential flow.
*** Wrote the details for the following commands in the User Guide.
**** View / Sort / Filter / Undo / Redo / Clear / List / Help / Exit
*** Wrote user stories in the Developer Guide.
*** Created UML diagrams to help in the explanation of view, sort and filter commands in the Developer Guide.

** Community:
*** Reported bugs and suggestions for other teams in the module. (Examples:
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/219[#219],
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/220[#220],
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/222[#222],
https://github.com/AY1920S1-CS2103T-T10-3/main/issues/229[#229])
*** Provided tips and help to other students in the module. (Examples:
https://github.com/nus-cs2103-AY1920S1/forum/issues/70[#70],
https://github.com/nus-cs2103-AY1920S1/forum/issues/79[#79],
https://github.com/nus-cs2103-AY1920S1/forum/issues/110[#110])

** Tools:
*** Managed the initial set up of the group repository on GitHub.
*** Integrated Travis CI, Coveralls, Netlify and RepoSense into the group repository.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users._
|===

//include::../UserGuide.adoc[tag=view]

//include::../UserGuide.adoc[tag=sort]

//include::../UserGuide.adoc[tag=filter]

include::../UserGuide.adoc[tag=undo]

//include::../UserGuide.adoc[tag=redo]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=sort]

include::../DeveloperGuide.adoc[tag=undoredo]


'''
