= Jolyn Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Flashmind

---

== Overview

Flashmind is a CLI-based flashcard app designed to help students memorise and revise important content.
It is used mainly for questions that can be answered with a short answer or several MCQ choices.

== Summary of contributions

* *Major enhancement*: added *the ability to start a quiz on a series of flashcards*
** What it does: Allows the user to start a timed quiz on a series of flashcards based on their tags. Users are able to choose one or multiple tags to quiz themselves on.
** Justification: This feature is a great enhancement for users who are looking to memorise content. Instead of just looking at the flashcard, users are able to test themselves in a timed condition and receive feedback from the system on whether their answer is correct.
** Highlights: This enhancement required a holistic understanding of how commands are received. The quiz function required an implementation of quiz mode, which locks certains command and allows a new set of commands to be executed.
** Credits: My teammate, Zhi Wei, helped to implement the timer in the quiz mode.

* *Major enhancement*: added *the ability to add two different types of flashcard: MCQ and ShortAnswer*
** What it does: Allows the user to choose whether they want their flashcard to have MCQ options or simply be a short answer flashcard.
** Justification: This feature enhances the user's learning experiences as flashcards are now more versatile, allowing users to have MCQ options for questions that are harder to remember.
** Highlights: This enhancement required a modification of storage, as well as a refactoring of the code to distinguish between MCQ and Short Answer flashcards.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*:
** Split up the UI to return consecutive flashcards and the result to different displays.


* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=jolynnn8D&tabRepo=AY1920S1-CS2103-T14-3%2Fmain%5Bmaster%5D[Functional code]] [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=jolynnn8D&tabRepo=AY1920S1-CS2103-T14-3%2Fmain%5Bmaster%5D[Test code]]

* *Other contributions*:


** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage
** Documentation:
*** Updated relevant sections of User Guide for all commands in quiz mode: https://github.com/AY1920S1-CS2103-T14-3/main/pull/85[#85]
** Community: //not updated
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools: //not updated
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=quiz]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=logic]


== Contributions to the README
|===
|_Given below are sections I contributed to the README. They showcase my ability to write documentation advertising the project._
|===

//include::../../README.adoc[tag=description]

== PROJECT: Flashmind

---

_{Optionally, you may include other projects in your portfolio.}_
