= *Jon Chua - Project Portfolio for $aveNUS*
:site-section: AboutUs
:icons: font
:imagesDir: ../images
:stylesDir: ../stylesheets

== Overview

$aveNUS is a command line interface (CLI) financial planning application that my team and I designed for
CS2103T (Software Engineering) module in School of Computing, National University of Singapore (NUS).

In this project, we morphed the sample address book application into $aveNUS, an application that allows NUS students
to track their financial spending with regards to food purchases. Additionally, the application provides them with
the best food recommendations within their current budget as well as a savings feature to track their savings.

The table below provides a quick summary of the symbols and formatting used in this portfolio.

[width="70%",cols="^15%,85%"]
|===
a| `code` | Command that can be typed into the command box
ifndef::env-github[]
a| icon:check[role="green", size="2x"] | Success execution of command
a| icon:lightbulb-o[role="icon-tip", size="2x"] | Tips that might be useful
a| icon:info-circle[role="icon-note", size="2x"] | Additional information that is good to know
a| icon:exclamation-circle[role="icon-important", size="2x"] | Important pointers to take note
endif::[]
|===

== Summary of contributions

This section provides a summary of the contributions that I have made to the team project.

=== Major enhancement: Recommendation Feature

I have added a recommendation feature to $aveNUS which displays food items that the user might prefer.

==== What it does

The recommendation feature displays a list of food items that the user might prefer, after taking into account various
factors such as the user's likes and dislikes, current budget and their purchase history.

For example, if the user has purchased Korean food on multiple occasions, the recommendation system will take note and
start to recommend other Korean food that the user might enjoy.

In addition, if the user specifies that they do not like spicy food, the recommendation system will apply a penalty to
spicy food accordingly and the overall recommendations would contain less spicy food.

==== Justification

NUS students might not want to eat the same food on multiple occasions. This feature allows money-conscious students
to discover food matching their palate that they might not have tried before while considering their budget.

==== Highlights

While implementing this feature, I had to implement new commands such as `like`, `dislike`, `removelike` and `removedislike`.
These commands form the backbone of the recommendation system as it allows the user to specify their preferences. The
application can then take into account the user's specified preferences when selecting the food items to recommend,
resulting in more accurate recommendations.

Storage functionality for the user's preferences were also implemented. This means that the user's likes and dislikes
are conveniently saved into their hard disk and persist even after the application is closed and restarted.

Furthermore, I had to link the `Budget` and `PurchaseHistory` class into my recommendation system. It would be useful if
the recommendation system takes into account the user's budget and purchase history. For example, the system filters out
any item that is currently out of the user's budget. Furthermore, it tries not to recommend items that are recently
purchased by the user, assuming that the user wants a variety of foods to enjoy.

In this way, the user benefits from the recommendation system which provides more relevant and accurate recommendations.

=== Other contributions

* Project Management:

** Added user stories as issues on GitHub

** Reviewed pull requests by team members [Examples: https://github.com/AY1920S1-CS2103T-F13-2/main/pull/80[#1],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/99[#2]]

** Opened issues when bugs were found [Issue https://github.com/AY1920S1-CS2103T-F13-2/main/issues/127[#127],
https://github.com/AY1920S1-CS2103T-F13-2/main/issues/171[#171]]

** Fixed bugs after they were found [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/128[#128]]

* Documentation:

** Updated the User Guide

*** Updated README and added badges [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/59[#59],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/63[#63]]

*** Revamped the structure of the User Guide and standardized the structure among team members [PR
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/178[#178]]

** Updated the Developer Guide

*** Standardized the structure among team members [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/178[#178]]

** Community:

*** Reviewed the Developer Guide of other teams [Examples:
https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/64#pullrequestreview-306988261[#1],
https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/64#pullrequestreview-297271318[#2]]

== Contributions to the User Guide

This section shows the contributions that I have made to the recommendation feature of the User Guide.

include::../UserGuide.adoc[tag=recommendations]

== Contributions to the Developer Guide

This section shows the additions that I have made to the recommendation feature of the Developer Guide.

include::../DeveloperGuide.adoc[tag=recommendations1]

The detailed tables documenting the calculation of the recommendation values can be found above at:
<<Getting a list of recommended food items: `recommend`>>

include::../DeveloperGuide.adoc[tag=recommendations2]

