= Kenneth Fung - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Budget Buddy

---

== Overview

Budget Buddy is a desktop application that allows users to track their expenses.
The user interacts with it using a Command-Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX.
It is written in Java, and has about 20 kLoC.

== About the Project

Budget Buddy has a number of features to help users track their expenses and deeply customize their experience while using the app.

As an expense tracker, Budget Buddy provides the ability for users to record and categorize transactions they have made.
Transactions can also be divided into user-created accounts, helping users to isolate transactions for specific events or holidays.
Budget Buddy further allows the user to track loans that they owe others or are owed to them,
helping them remember to pay back or reclaim borrowed money.
Unbalanced group payments can also be split equally by Budget Buddy,
and the resulting debts the user owes or is owed can be recorded as loans automatically.

Budget Buddy also provides features to deeply customize the user experience.
Users can create rules to automate many actions;
for example, they could create a rule that adds a transaction to a specific category if said transaction exceeds a certain amount.
As the target audience comprises of computing students,
Budget Buddy also allows users to utilize their computing know-how to write custom scripts to manipulate the app.
For example, users can write scripts to add huge numbers of transactions,
or scripts to trigger alarms when their expenses have exceeded a certain limit.

My role in the project was to implement all facets regarding the *loans* feature.
Chiefly, I added the ability for the user to add, edit, view and delete loans.
Users can also mark loans as paid or unpaid,
and when viewing their list of loans they can sort or filter the list by amount, date and more.
I was also responsible for implementing the complex algorithm necessary to split and divide an initially unbalanced group payment;
the main challenge in this scenario was to devise an algorithm that worked for any group size and every variation of initial unbalance.

Aside from the implementation of features, I also aided in the delegation of roles among the team,
upholding the quality of project documentation, and ensuring the team remained on task.

== Summary of contributions

* *Major enhancement*: Added *the ability to track loans and split unbalanced group payments equally*
** *What they do*: Tracking loans allows the user to track all the money that they owe/are owed to other people.
Splitting group payments through the app allows the user in avoiding messy miscalculations and over/under-paying their friends.
** *Justification*: This feature improves the product significantly,
as both lending/borrowing money and paying for large items as a group are common occurrences that affect one's expenses,
especially for students.
** *Highlights*: Implementing loan-tracking required an in-depth analysis of design alternatives,
especially regarding the structure of the loan-person relationship.
Building it on top of and mutating the original brownfield project also proved challenging.
Splitting group payments proved difficult due to the need for an accurate yet efficient algorithm.
Great care had to be taken to correctly implement each of the many steps in the complex final result.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=kenneth-fung[RepoSense Report]]

* *Other contributions*:

** Documentation:
*** Updated the User Guide, About Us, Contact and Readme pages to reflect our team taking over the original AddressBook:
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/3[#3]
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/56[#56],
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/60[#60],
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/80[#80],
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/157[#157],
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/178[#178],
https://github.com/AY1920S1-CS2103T-W13-4/main/pull/183[#183]

<<<

== Contributions to the User Guide

|===
|_Given below are a few sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users.
Due to limited space, not all my contributions could be included;
please refer to the full https://ay1920s1-cs2103t-w13-4.github.io/main/UserGuide.html#managing-loans-code-loan-code[User Guide]
to read them in their entirety. I was responsible for the section on *Managing Loans*._
|===

include::../UserGuide.adoc[tag=kenneth-ppp-loan-intro]

<<<

include::../UserGuide.adoc[tag=kenneth-ppp-loan-paid]

include::../UserGuide.adoc[tag=kenneth-ppp-loan-split]

<<<

== Contributions to the Developer Guide

|===
|_Given below are a few sections I contributed to the Developer Guide.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project.
Due to limited space, not all my contributions could be included;
please refer to the full https://ay1920s1-cs2103t-w13-4.github.io/main/DeveloperGuide.html#loans-feature[Developer Guide]
to read them in their entirety. I was responsible for the section detailing the *Loans Feature*._
|===

include::../DeveloperGuide.adoc[tag=kenneth-ppp-loan-class]

<<<

include::../DeveloperGuide.adoc[tag=kenneth-ppp-loan-sequence]
include::../DeveloperGuide.adoc[tag=kenneth-ppp-loan-multi]
include::../DeveloperGuide.adoc[tag=kenneth-ppp-loan-split-1]
include::../DeveloperGuide.adoc[tag=kenneth-ppp-loan-split-2]
