= Kwek Kee En - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ExerHealth

---

== Overview

My team of 4 computer science students were tasked with changing a basic command line application. Our team
decided to morph the application into ExerHealth. **ExerHealth** is a desktop application used for tracking
and scheduling the user's exercises. The application has statistical analysis of exercises users have completed
in the past. Additionally, it also acts as a personal trainer by suggesting different exercises which both
beginners and advanced users can choose from to incorporate into their exercise regimes.
The user interacts with it using a command line interface, and it has a GUI created with JavaFX.

Below is a screenshot of what our desktop application looks like:

**//TODO: Add image of UI**



== Summary of contributions

* *Major enhancement*: added *the ability to search for suggestions*
** What it does: The command `suggest` allows the user to search for suggestions.
** Justification: This feature enables new users to have a starting point in their exercise regime.
This feature also offers experienced users suggestions based on the type of exercises the user wants to do.
** Highlights: This enhancement works well with existing features, such as Custom Properties, and can be expanded on.
It required an in-depth analysis of design alternatives to ensure that future extensions or further enhancements can be smooth.
The implementation too was challenging as it required multiple new predicate and utility classes.

* *Minor enhancement 1*: Added the display panel on the left hand side of the UI to show the respective information after a command is executed.

* *Minor enhancement 2*: Allowed the command box to be automatically focused on upon opening the application so that user does not need to click on the box to start typing.


* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` - `v1.4` (3 releases) on GitHub
*** Wrote additional tests for existing features to increase coverage (Pull requests https://github.com/AY1920S1-CS2103T-T09-2/main/pull/137[#137], https://github.com/AY1920S1-CS2103T-T09-2/main/pull/96[#96])
** Enhancements to existing features:
*** Refactored the GUI (Pull requests https://github.com/AY1920S1-CS2103T-T09-2/main/pull/121[#121]
** Community:
*** PRs reviewed (with non-trivial review comments):  https://github.com/AY1920S1-CS2103T-T09-2/main/pull/114[#114]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=suggest]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=suggest]

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
