= Lew Kai Ming - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Plan²travel

---

== Overview

Plan²travel is a desktop-based travel planning application made to target students, students who want to plan for an overseas trip in particular. The user interacts with it through a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX. This application is written in Java.

This is a software engineering project in which students are tasked to enhance/morph a simple CLI-based address book application. The end result is a travel planning application with focus on students who spend a lot of time on their computer.

Plan²travel aims to assist the user in managing multiple categories of information crucial to planning their itineraries, such as contacts, activities and accommodations. Plan²travel further allows the user to schedule the activities from the list into a time table, giving the user a systematic and well-formatted
view of their itinerary. For more budget-minded users, they are able to use the Optimise feature which optimises the schedule to make it conflict-free and at a low overall cost!

== Summary of contributions

|===
|_This section is a summary of the contributions I have made to the team project._
|===

* *Major enhancement*: added *the ability to add/delete/edit Accommodations/Activities/Contact*
** What it does: allows the user to compile information important to planning an itinerary.
** Justification: This feature improves the product significantly because it allows the user to enter data in a standardised format, making itineraries more readable and manageable.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{The commands were adapted and built upon existing commands from Address Book 3}_

* *Minor enhancement*: added *the ability to optimise a day's schedule*
** What it does: allows the user to optimise a day's schedule by looking for the best way to schedule activities such that there are no conflicts and that the schedule is at the lowest cost. If there are multiple possibilities, the one with the most number of activities would be chosen.
** Justification: This feature improves the product because it allows users to rid the schedule of conflicts with a single command.
** Highlights: This enhancement can be easily extended to allow the user to optimise the schedule besides budget.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=KxxMxxx[RepoSense Report]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=optimise]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=logic]
include::../DeveloperGuide.adoc[tag=optimise]
include::../DeveloperGuide.adoc[tag=userstories]
