= Yoke Kai Xin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

= PROJECT: Mark

---

== Overview

//TODO: change *aims to* to sth else? + make last sentence more concise and shorter
This project portfolio aims to showcase my contributions, as part of my team consisting 5 Year 2 Computer Science students, to our group Software Engineering project, Mark. We were tasked
with enhancing a basic desktop application, https://github.com/nus-cs2103-AY1920S1/addressbook-level3[Address Book (Level 3)], in short AB3, to solve a problem for a specific target group.
AB3 uses a Command Line Interface (CLI) where users type their commands to navigate and use the application.

Given 8 weeks to conceptualise and complete the project implemented in Java, we chose to morph AB3 into a bookmark manager application which we named *Mark*.
Mark aims to improve computing students' productivity by helping them organise their web browsing and note-taking activities. With Mark, computing students can greatly reduce the number of
tabs left open due to various reasons in their web browsers and provides a one-stop platform to allow them to easily pick up their revision through easy navigation and in-built web page
annotation when rushing for time.

Mark has a visually appealing graphical user interface (GUI) to visually guide the users around the application. This is what Mark looks like when you open the application:
//TODO: insert gui pic with well populated data
//caption?

My role was to design and implement the _annotation_ feature so users can conveniently make notes on
important web pages instantly while reading them. This feature uses commands that begin with `annotate` and works on the offline version
of the web pages converted by Mark.

The following sections illustrate my contributions in more detail. The relevant documentation I have added to the User and Developer Guides in relation to this enhancement is also included in this portfolio.

Note the following symbols and formatting used in this document:
//TODO: symbols/glossary list

== Summary of contributions
This section gives a summary of the features I implemented, documentation I did and other parts I contributed to my team project.

=== Major enhancements
I have made 2 major enhancements: adding the annotation functionality and adding the in-built web browser.

==== Added the annotation feature
I added the ability to annotate the offline copy of the web page referred to by a bookmark. Users can not only read their web pages offline,
but they can also make notes on them directly. They can highlight paragraphs and attach notes to paragraphs or add general notes to the document.
//** What it does

* Justification: Users may need to make notes as they are reading through their web pages, for instance when studying. This means it is important for them
to be able to conveniently make notes while they remember what they need to annotate. Rather than having to go through the hassle of opening a new document and storing notes
separately, they can instead annotate directly on the web page the moment they want to add notes or emphasize a piece of information.
This feature keeps their notes together with the content of the web page and makes it easy to get information by taking a glance at the annotated document. If they want to make changes to their
existing annotations, they can also do so easily in just one step.

* Highlights:
* Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

==== Added the web browsing feature
I added the ability to browse web pages on the application. Users can navigate the web using the embedded web view and the address bar.

* Justification: Users no longer need to open a separate web browser window to view their bookmarks. This ensures easy navigation within the application by maintaining focus on the application
rather than on other platforms, which would otherwise make it more troublesome to handle


=== Minor enhancement
In addition to the major enhancements I made, I also created tabs to house the various parts of the user interface that we show to the user.
==== Added tab view

=== Code contributed
 [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
