= Lee Yiyuan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:

== PROJECT: IchiFund

'''

== Overview

This portfolio documents my contributions towards the project, IchiFund, which is part of an introductory software
engineering module, CS2103T. My team (of 5) was tasked to morph or enhance an existing address book software.
Our resulting product, IchiFund, is a desktop finance management application for students to manage transactions, budgets and loans.
It is optimised for students that prefer using a CLI.
My role was to develop the https://ay1920s1-cs2103t-w12-4.github.io/main/UserGuide.html#repeaters[Repeaters] component of the application.

== Summary of contributions

* *Major enhancement*: Developed the `Model`, `Logic`, `Storage`, and `Ui` infrastructure for repeaters.
** Functionality: Provides the foundation on which features related to repeaters, in particular `add`, `edit`, `delete` and `find`, are built.
** Justification: The ability to easily create, read, update and delete repeaters on the GUI of the application depends on properly
establishing the infrastructure for repeaters.
** Highlights: This enhancement demonstrates a deep understanding of the design pattern underlying the existing code.

* *Major enhancement*: Implemented the synchronization of associated transactions whenever the repeaters are updated.
** Functionality: When adding, editing and deleting repeaters, the list of associated transactions are automatically synchronized to the update.
** Justification: Repeated transactions are tedious to handle if they were to be created one by one as separate transactions. With repeaters, the user only need to create, edit and delete a single transactions and all associated transactions will automatically be updated. This greatly reduces the amount of effort needed for users to manage repeated transactions.
** Highlights: This enhancement required the implementation of an additional field in `Transaction` to allow for association between transactions and repeaters. In addition, additional functions were also implemented to synchronize the list of associated transactions whenever a repeater is added, created or deleted. This demonstrates the ability to implement features in conjunction with the work of other developers.

* *Minor enhancement*: Added the ability to edit (PR https://github.com/AY1920S1-CS2103T-W12-4/main/pull/160[#160]), delete (PR https://github.com/AY1920S1-CS2103T-W12-4/main/pull/140[#140]) and find (PR https://github.com/AY1920S1-CS2103T-W12-4/main/pull/243[#243]) repeaters.

* *Code contributed*: Click https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=LeeYiyuan[here] to view the code I have contributed on the CS2103T tP Dashboard.

* *Other contributions*:

** Team:
*** Reported bugs and suggestions for other members in the team (examples:  https://github.com/AY1920S1-CS2103T-W12-4/main/issues/276[276], https://github.com/AY1920S1-CS2103T-W12-4/main/issues/108[108], https://github.com/AY1920S1-CS2103T-W12-4/main/issues/24[24])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=introrep]

include::../UserGuide.adoc[tag=addrep]

include::../UserGuide.adoc[tag=editrep]

include::../UserGuide.adoc[tag=deleterep]

include::../UserGuide.adoc[tag=findrep]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=repeaterintro]

include::../DeveloperGuide.adoc[tag=repeateradd]

include::../DeveloperGuide.adoc[tag=repeateredit]

include::../DeveloperGuide.adoc[tag=repeaterdelete]

include::../DeveloperGuide.adoc[tag=repeaterfind]
