= Lee Liak Ghee - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: SplitWiser

---

== Overview

For our project for our Software Engineering course, my team comprising 5 students (including myself) was given the codebase for a command line desktop application called Address Book, and we were required to morph this given codebase into an application of our choice. We chose to morph the given application into a group expense management app called SplitWiser. This enhanced application enables people to simplify expense and debt tracking in group activities, so that people will know exactly how much to pay each other at the end of the activity.

I was responsible for writing the expense adding feature. This makes my role particularly crucial as the `expense` command is most likely the command that a user interacts with the most. The following sections describe my contributions in greater depth, in addition to the documentation that I also added pertaining to the expense feature.

== Summary of contributions

* *Major enhancement*: Added the ability to add expenses
** *What it does:* The `expense` command allows the user to add expenses to an activity by first specifying who paid and how much, followed by an optional description of the expense, then optionally listing people who were involved in the expense.
** *Justification:* This is important as it gives users the necessary precise control over the people required to pay in each expense. In a real-world group activity scenario, it might not be the case that everyone is involved in every part of the activity that involves money. For example, one might go out for a meal with friends but opt out of buying dessert later. Having such flexibility enables the user to manage a wide range of real-world scenarios.
** *Highlights:* The design of the `expense` command was particularly tricky due to the limitations of a CLI interface. The tough part was in trying to strike a balance between keeping the command simple enough to use yet provide enough flexibility for the user to specify various possible combinations of expense details. We went through various possible designs for the `expense` command and took the user experience into consideration for each case, before finally settling on the way the `expense` command is currently structured.

* *Minor enhancement*: Updated the `edit` command to only work when viewing a contact or activity
** *What it does:* The `edit` command allows the user to modify certain fields of a contact or activity when viewing them. The original Address Book application already had the `edit` command built in, but its behaviour was modified to suit SplitWiser.
** *Justification:* In the original Address Book application, the user was allowed to edit various fields by specifying the index of an item in the visible list, then specifying the respective fields to edit and update. However, this structure is not ideal anymore as our list user interface was updated to not show every field, meaning that the user would not be able to see what exactly was being edited. Thus, the decision was made to enable `edit` only when viewing an item as this reduces the risk of the user making unintentional edits.

* *Minor enhancement*: Added a backend `Context` class that allows for various application contexts and contextual behaviour for various commands
** *What it does:* The `Context` class keeps track of the current application context that the user is in. This `Context` object gets updated upon the execution of each command where necessary.

* *Code contributed*: https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=liakify&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Link to tP dashboard]
* *Other contributions*:

** Documentation:
*** Did the initial revamp of our User Guide: https://github.com/AY1920S1-CS2103T-W11-2/main/pull/39[#39]
*** Updated some UML diagrams for the Developer Guide: https://github.com/AY1920S1-CS2103T-W11-2/main/pull/115[#115], https://github.com/AY1920S1-CS2103T-W11-2/main/pull/198[#198]
** Community:
*** Major PRs reviewed: https://github.com/AY1920S1-CS2103T-W11-2/main/pull/73[#73], https://github.com/AY1920S1-CS2103T-W11-2/main/pull/108[#108], https://github.com/AY1920S1-CS2103T-W11-2/main/pull/124[#124], https://github.com/AY1920S1-CS2103T-W11-2/main/pull/112[#112], https://github.com/AY1920S1-CS2103T-W11-2/main/pull/190[#190]
*** Bug fixes when integrating `settle` (https://github.com/AY1920S1-CS2103T-W11-2/main/pull/190[#190]) and `delete` (https://github.com/AY1920S1-CS2103T-W11-2/main/pull/196[#196]) command

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=expense]

---
include::../UserGuide.adoc[tag=edit]

---
include::../UserGuide.adoc[tag=varexpense]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=expense]

---
include::../DeveloperGuide.adoc[tag=createexpense]
