= Ahmed Bahajjaj - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Incident Management System

'''

== Overview

The Incident Management System is a desktop application used for managing incidents. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major Enhancement*: Implemented *Access Control*
** What it does: Restricts usage of the product to registered users, with additional restrictions depending on user access level.
** Justification: This feature improves the product significantly by implementing basic security controls. Since the product is meant to deal with management of physical resources (vehicles) and sensitive information (incident reports), security controls are necessary for accountability and protection against misuse.
** Highlights: This enhancement affects existing commands and can be easily applied to any commands added in future. It required an in-depth analysis of the product architecture and design alternatives. The implementation too was challenging as it required thorough assessment of loopholes and potential security vulnerabilities.

* *Minor Enhancement*: Implemented *Account Management*
** What it does: Allows users the ability to manage their own account or other accounts if granted privileged access.
** Justification: This feature is necessary for the effective application of access control.
** Highlights: This enhancement required extensive overhauls of existing code, along with in-depth analysis of the GUI design for its implementation.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=madanalogy[View on RepoSense]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.3` (3 releases) on GitHub
** Team tasks:
*** Implemented the Session API for all developers to access account features [https://github.com/AY1920S1-CS2103-T11-1/main/pull/66[#66]]
*** Morphed Person Model to deal with new Account Features [https://github.com/AY1920S1-CS2103-T11-1/main/pull/48[#48]]
*** Refactored Address Book references to Incident Manager [https://github.com/AY1920S1-CS2103-T11-1/main/pull/111[#111]]
** Enhancements to existing features:
*** Improved the GUI to function in varying screen resolutions [https://github.com/AY1920S1-CS2103-T11-1/main/pull/69[#69]]
** Tools:
*** Integrated new Github plugins (Coveralls & Codacy) to the team repo


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=access]

include::../UserGuide.adoc[tag=account]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=accessControl]

include::../DeveloperGuide.adoc[tag=accountManagement]
