= Goh Rui Zhi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Scheduler

---

== Overview
_Scheduler_ automates the tedious process of interview scheduling for organisations. It is designed with convenience in mind,
and apart from the efficient scheduling of interviews, it also empowers user with the ability to import/export timetables and even mass email the interviewees all on the same platform.
The algorithm behind _Scheduler_ ensures the efficient and fair allocation interview slots, effectively minimising human-error.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 20 kLoC.

== Summary of contributions

* *Major enhancements*:
** *Added the ability to import both interviewer's data and interviewee's data.*
*** What it does: Allows the user to conveniently import all interviewers and interviewees data, consisting of
their personal details, as well as, their availabilities.
*** Justification: It is incredibly tedious for the user to make use of the 'add' command to manually add each interviewer and interviewee into Scheduler.
Hence, the automation of this process, which is to import data, is absolutely necessary. It also allows the user to conveniently make changes
in the raw data (CSV file) which allows the flexibility of using formatting tools or automation (VBA) in Microsoft Excel, rather than manually edit the entries
in the application.
*** Highlights: Implementing this feature requires a good understanding of the model and the 'add' feature as it builds upon it.
String processing of the imported data was also tedious and very prone to bugs due to many formatting issues that could happen.

** *Added the ability to export schedules.*
*** What it does: Allows the user to conveniently export the scheduled interview timetables.
*** Justification: Exporting these schedules to an external file allows the flexibility of sharing these timetables
with colleagues/interviewers. It also allows the user to use third party applications (Excel) to touch-up/re-format the data.
 Most importantly, it frees Scheduler of the need to hold the current schedules so that it can be used again to schedule other interviews.

* *Minor enhancement*: Implemented responsive UI for `add`, `delete`, `edit`, `import` and `clear` commands, together with team mate Yau Dong.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=mirozo&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=mirozo&tabRepo=AY1920S1-CS2103-F09-1%2Fmain%5Bmaster%5D[Functional code]]

* *Other contributions*:
** Enhancements to existing features:
*** Designed a way to update Schedules by re-generating the list of schedules solely from a given list of Interviewers. This is the
backbone for the integration between UI and Model after the execution commands that modifies the model e.g. `add`, `delete`,
`edit`, `import` and `clear` commands. The subsequent schedule command's integration with UI also builds upon this method.
Look at section "Updating Schedule List" in Developer's Guide for a better idea of the above.
** Documentation:
*** Did cosmetic tweaks to existing contents of the Developers Guide:
*** Added User Preferences section into User Guide: https://github.com/AY1920S1-CS2103-F09-1/main/pull/164[164]
*** Added User Stories https://github.com/AY1920S1-CS2103-F09-1/main/pull/35[35] and Use Cases https://github.com/AY1920S1-CS2103-F09-1/main/pull/186[186]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S1-CS2103-F09-1/main/pull/161[#161]
*** Handled merge conflicts for team: https://github.com/AY1920S1-CS2103-F09-1/main/pull/78[78] https://github.com/AY1920S1-CS2103-F09-1/main/pull/80[#80]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=import]

include::../UserGuide.adoc[tag=export]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=import]

include::../DeveloperGuide.adoc[tag=export]

