= Benedict Pak - Project Portfolio for MoneyGoWhere
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== About the Project

MoneyGoWhere is a personal finance application targeted at students at the National University of Singapore (NUS), designed by my team and I for our Software Engineering project. It was morphed from a basic command line Address Book. Some notable features include: setting budget goals, viewing statistics, customised searching and sorting, setting reminders for bills, viewing exchange rates, changing the application currency and importing and exporting data from and to a csv file.

My role was to complete find and sort features, and minor features such as natural language date parsing, exchange rate and currency. The sections that follow in this document will elaborate these features in detail. I have also made notable contributions to the User Guide and Developer Guide.

Listed below are some notations that are used throughout the document.

.Legend table
[width="100%",cols="^15%,85%"]
|===
a| *Icon* | *Description*
a| `command` | Command that can be executed
ifndef::env-github[]
a| icon:lightbulb-o[role="icon-tip", size="2x"] | Tips that might be helpful in navigating the application
a| icon:info-circle[role="icon-note", size="2x"] | Important information that should be noted
a| ====
==== | Useful information for a deeper understanding of the command
endif::[]
|===

These icons and their following descriptions enable greater clarity in understanding the document.

== Summary of contributions

This section shows a summary of my contributions to the team project.

* *Major enhancement #1*: Implemented *customisable find* feature
** What it does: It allows users to type `find` to display a range of spending entries based on different attributes.
** Justification: It enables the users to specifically view what they need to know, rather than scrolling through a long general list of spending entries.
** Highlights: This enhancement has good integration with existing commands. It also required in-depth understanding of the underlying codebase.

* *Major enhancement #2*: Implemented *user-defined sort* feature
** What it does: It allows users to type `sort` to re-order the displayed spending entries based on preferred fields.
** Justification: It enables users to customise the order of the information being presented of greater priority, for instance, showing their most expensive purchases first, followed by date of purchase, to allow them to be mindful of their spending.
** Highlights: This enhancement had a challenging design approach. It also required some restructuring of the code base implementation and an in-depth analysis of design alternatives.

* *Minor enhancement #1*: Implemented *natural language date parsing* feature
** What it does: It allows users to enter date formats that are closer to how they are naturally expressed in daily language.
** Justification: It gives users the freedom of choice to enter a variety of dates they want to enter without being restricted to a standard date format.
** Highlights: This enhancement is fundamental to features such as `stats`, `budget` and `reminder`. Implementing this was an extremely arduous task and middleware had to be written to ensure compatibility with the library.
** Credits: *natty* library was used to aid in natural language parsing. However, many modifications were applied in order to allow support for _DD/MM/YYYY_ dates, as it was not implemented by the author.

* *Minor enhancement #2*: Implemented the *exchange rate* and *currency* feature.
** What it does: It allows users to view foreign currency exchange rates, and change their viewing currency.
** Justification: Users can use this feature when they do online shopping and convert currencies as they wish, or use the application overseas.
** Highlights: This enhancement required interaction with the storage and careful handling of existing software architecture.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=nanosync[Collated code]]

== Other contributions

** Project management
*** Created all major milestones on GitHub page
*** Assigned members to issues upon discovery of bugs
*** Reviewed Pull Requests (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/56[#56], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/68[#68], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/95[#95], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/203[#203])

** Enhancements to existing features:
*** Refactored and modified existing classes, including package name `AddressBook` to `SpendingBook` code base to match application needs: (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/73[#73], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/75[#75], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/78[#78])

** Documentation:
*** Cleaned up the User Guide and Developer Guide (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/43[#43], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/106[#106])

** Community:
*** Offered suggestions for other teams in the class (Examples: https://github.com/nus-cs2103-AY1920S1/forum/issues/62[#62], https://github.com/nus-cs2103-AY1920S1/forum/issues/64[#64], https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/111#pullrequestreview-297274115[#111])

** Tools:
*** Integrated Netlify for the team repo to allow continuous deployment of documentation previews
*** Integrated a third party library (Natty) to the project (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/55[#55], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/62[#62], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/69[#69])


== Contributions to the User Guide

Listed below are sections I contributed to the User Guide, which includes Find and Sort section. It showcases my ability to write documentation targeting end-users. For brevity, *flexible date formats* has been omitted and can be found https://ay1920s1-cs2103t-f13-3.github.io/main/UserGuide.html#flexible-date-formats[here].

include::../UserGuide.adoc[tag=find]

include::../UserGuide.adoc[tag=sort]

== Contributions to the Developer Guide

Listed below are sections I contributed to the Developer Guide, which includes the features section for Find and Sort, and the Product Scope section. It showcases my ability to write technical documentation and display the technical depth of my contributions to the project.

include::../DeveloperGuide.adoc[tag=find]

include::../DeveloperGuide.adoc[tag=sort]
