= Benedict Pak - Project Portfolio for MoneyGoWhere
:site-section: AboutUs
:icons: font
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: full
:experimental:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]

== About the Project

MoneyGoWhere is a personal finance application targeted at students at the National University of Singapore (NUS), designed by my team and I for our Software Engineering project. It was morphed from a basic command line Address Book. Some notable features include: setting budget goals, viewing statistics, customised searching and sorting, setting reminders for bills, viewing exchange rates, changing the application currency and importing and exporting data from and to a csv file.

=== My Role

My role was to complete find and sort features, and minor features such as natural language date parsing, exchange rate and changing the application currency. The sections that follow in this document will elaborate these features in detail. I have also made notable contributions to the User Guide and Developer Guide.

Listed in the table below are some notations that are used throughout the document.

.Legend table
[#Legend]
[width="100%",cols="^15%,85%",options="header"]
|===
a| *Icon* | *Description*
a| `command` | Command that can be executed, or a component, class or object in the architecture of the application
a| icon:lightbulb-o[role="icon-tip", size="2x"] | Tips that might be helpful in navigating the application
a| icon:info-circle[role="icon-note blue", size="2x"] | Important information that should be noted
a| ====
==== | Useful information for a deeper understanding of the command
|===

As shown in <<Legend>>, these icons associated to their following descriptions, such as commands, tips, important information and useful information, enable greater clarity in understanding the document. Note that useful information will have text enclosed in its box.

== Summary of contributions

This section shows a summary of my contributions to the team project.

* *Major enhancement #1*: Implemented *customisable find* feature
** What it does: It allows users to type `find` to display a range of spending entries based on different attributes.
** Justification: It enables the users to specifically view what they need to know, rather than scrolling through a long general list of spending entries.
** Highlights: This enhancement has good integration with existing commands. It also required in-depth understanding of the underlying codebase.

* *Major enhancement #2*: Implemented *user-defined sort* feature
** What it does: It allows users to type `sort` to re-order the displayed spending entries based on preferred fields.
** Justification: It enables users to customise the order of the information being presented of greater priority, for instance, showing their most expensive purchases first, followed by date of purchase, to allow them to be mindful of their spending.
** Highlights: This enhancement had a challenging design approach. It also required some restructuring of the code base implementation and an in-depth analysis of design alternatives.

* *Other enhancements*: Implemented *natural language date parsing*, *exchange rate* and *currency* features.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=nanosync[Collated code]]

== Other contributions

** Project management
*** Created all major milestones on GitHub page
*** Assigned members to issues upon discovery of bugs
*** Reviewed Pull Requests (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/56[#56], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/68[#68], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/95[#95], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/203[#203])

** Enhancements to existing features:
*** Refactored and modified existing classes, including package name `AddressBook` to `SpendingBook` code base to match application needs: (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/73[#73], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/75[#75], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/78[#78])

** Documentation:
*** Cleaned up the User Guide and Developer Guide (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/43[#43], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/106[#106])

** Community:
*** Offered suggestions for other teams in the class (Examples: https://github.com/nus-cs2103-AY1920S1/forum/issues/62[#62], https://github.com/nus-cs2103-AY1920S1/forum/issues/64[#64], https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/111#pullrequestreview-297274115[#111])

** Tools:
*** Integrated Netlify for the team repo to allow continuous deployment of documentation previews
*** Integrated a third party library (Natty) to the project (Examples: https://github.com/AY1920S1-CS2103T-F13-3/main/pull/55[#55], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/62[#62], https://github.com/AY1920S1-CS2103T-F13-3/main/pull/69[#69])


== Contributions to the User Guide

Listed below are sections I contributed to the User Guide, which includes the find and sort features and the flexible date formats section. It showcases my ability to write documentation targeting end-users. _For brevity, detailed information for *flexible date formats* can be found in the https://ay1920s1-cs2103t-f13-3.github.io/main/UserGuide.html#flexible-date-formats[User Guide]._


include::../UserGuide.adoc[tag=find]

include::../UserGuide.adoc[tag=sort]

== Contributions to the Developer Guide

Listed below are sections I contributed to the Developer Guide, which includes the features section for Find and Sort, and the Product Scope section. It showcases my ability to write technical documentation and display the technical depth of my contributions to the project.

include::../DeveloperGuide.adoc[tag=find]

include::../DeveloperGuide.adoc[tag=sort]
