= NUStudy project portfolio for Jeremy Tan (Parcly-Taxel)
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Introduction

As part of the CS2103 Software Engineering module at the National University of Singapore,
I was part of a team of five tasked to develop an application from https://github.com/nus-cs2103-AY1920S1/addressbook-level3[a given Java
address book application]. We chose to morph it into NUStudy, an application for
managing lecture notes, questions and revision tasks -- all three things pertinent to the
average university student, regardless of location. Like the original, it has a command line
as its main method of interaction and a JavaFX GUI for display. It has around 5000 lines of code.

This portfolio showcases my contributions to NUStudy: implementing the lecture notes by
retooling the existing _Person_ class, related documentation in the user and developer guides
and management of the Git repository surrounding NUStudy. It also showcases my technical writing skills
and my ability to explain complicated enhancements or modifications to the uninitiated person.

In this portfolio `monospace` indicates command-line input (commands, parameters, etc.)
and _italics_ mark class names.

== Summary of contributions

_retool this to the actual contributions_

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== User guide contributions

|===
|_Given below are sections I contributed to the user guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=lecnote]

== Developer guide contributions

|===
|_Given below are sections I contributed to the developer guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== Other projects

_{Optionally, you may include other projects in your portfolio.}_
