= NUStudy project portfolio for Wang Xueting (ShirleyWangxt)
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Introduction

This project portfolio serves the purpose to showcase my contribution to NUStudy as our software engineering project
and the various skills I have acquired and utilised in the process of development.

=== Project Overview

My team of 4 software engineering students and I were tasked with enhancing a basic command line interface desktop
https://github.com/nus-cs2103-AY1920S1/addressbook-level3[address book application] for our Software Engineering project.
We chose to morph it into a revision flashcard desktop application called *NUStudy*.
This enhanced application enables NUS students to store and manage lecture notes,
practice questions under exam conditions and plan revision tasks effectively.

This is what our project looks like: (todo: graphical user interface)

My role is to design and write the code for question management features. The following sections illustrate
these enhancements in more detail, as well as the relevant documentation I have added to the user and developer guides
in relation to these enhancements.

== Summary of contributions

== User guide contributions

== Developer guide contributions
