= Quek Wei Ping - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MooLah

---

== Overview

This portfolio aims to document my contributions to MooLah

My team of 4 Computer Science students and I were tasked with enhancing a basic Command
Line Interface desktop application AddressBook - Level 3 for our Software Engineering project.
Over 6 weeks, we chose to morph it into a finance tracker application called MooLah. This enhanced application
allows the typical NUS student to manage past expenses with the use of budgets, reminders for
future expenses, helpful statistics and user-friendly input formats. It is written in Java, and has about 27k LoC.
My main developer responsibility in the team consists of the statistics features across every component.


== Summary of contributions

* *Big feature*: I have added *the ability to generate statistics* in MooLah
** What it does: This features consists of a basic summary of expenses, a side-to-side comparison
as well as a trend analysis across different periods of time.
** Justification: This feature improves the product significantly because the lack of analytic tools
to make sense of data is a potential reasons for the problem of poor spending habits to be snowballed.
The inclusion of a statistics feature addresses this directly, with varying levels of depths and
visual representation the user can choose from.
** Highlights: As the feature is closely coupled to the budget features and requires to support other dependencies such as
undo/redo, constant coordination with other developers is required.



* *Code contributed*:(https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=qweiping31415&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Functional Code])

* *Other contributions*:

** Project management:
*** Initiated the renaming of the product to MooLah
*** Reviewed pull requests of team mates
*** Facilitated meetings every Wednesday and Friday and consolidated discussion minutes,
*** Scheduled milestone tasks and ensure that project deliverables are completed on time in the right format.
*** Wrote additional tests for existing features to increase coverage from 52% to 59%
(https://github.com/AY1920S1-CS2103T-T11-1/main/pull/254[#254])



** Enhancements to existing features:
*** Refactored Tag classes from AddressBook - Level 3  to Category class (TO BE FILLED IN)

** Documentation:
*** Documented new statistics features in User Guide (TO BE FILLED IN)
*** Added the implementation of Statistics in Developer’s Guide (TO BE FILLED IN)


== Contributions to the User Guide


|===
|We had to update the original AddressBook - Level 3 with instruction for the enhancement that we have added.
The following is an excerpt from our MooLah User Guide, showing additions that I have made for
the Statistics features.

|===

include::../UserGuide.adoc[tag=statsug]

== Contributions to the Developer Guide

|===
|The following section shows my additions to the MooLah Developer Guide for the Statistics features.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project.

|===

include::../DeveloperGuide.adoc[tag=statsdg]

== PROJECT: MooLah


