= Quek Wei Ping - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MooLah

---

== Overview

This portfolio aims to document the contributions made by Quek Wei Ping to MooLah

My team of 4 Computer Science students and I were tasked with enhancing a basic Command
Line Interface desktop application AddressBook - Level 3 for our Software Engineering project.
Over 6 weeks, we chose to morph it into a finance tracker application called MooLah. This enhanced application
allows the typical NUS student to manage past expenses with the use of budgets, be reminded of
future and recurring expenses, with added convenience coming from user-friendly input formats, aliases
and helpful statistics. It is written in Java, and has about 17 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to generate statistics* in MooLah
** What it does: allows the user to view statistics concerning his expenses either by summarising them,
or providing a deeper analysis such as comparisons and trends. Integrated to work with undo/redo and budget commands.
** Justification: This feature improves the product significantly because users can now analyse
their spending habits with these tools at a varying level of depth.
** Highlights: This feature allows users to manage different use cases such as various number of periods,
and reflects the different changes simultaneously across categories. It requires adjustments with the existing
model, logic, UI components and complements the current implementation of other core features such as budgets.

* *Code contributed*: TO BE FILLED IN

* *Other contributions*:

** Project management:
*** Initiated the renaming of the product to MooLah
*** Reviewed pull requests of team mates
*** In charge of statistics features in every component
*** In charge of Scheduling and tracking of tasks, including defining milestone tasks, consolidating discussion minutes.
*** In charge of Deliverables and deadlines, including facilitated meetings every Wednesday and Friday, to ensure
that project deliverables are done on time and in the right format.

** Enhancements to existing features:
*** Refactored Tag classes from AddressBook - Level 3  to Category class (TO BE FILLED IN)

** Documentation:
*** Documented new statistics features in User Guide (TO BE FILLED IN)
*** Added the implementation of Statistics in Developer’s Guide (TO BE FILLED IN)


== Contributions to the User Guide


|===
|_We had to update the original AddressBook - Level 3 with instruction for the enhancement that we have added.
THe following is an excerpt from our MooLah User Guide, showing additions that I have made for
the Statistics features. [Work in Progress]

|===

include::../UserGuide.adoc[tag=statsug]

== Contributions to the Developer Guide

|===

|_The following section shows my additions to the MooLah Developer Guide for the Statistics features.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project.

_
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: MooLah


