= Quek Wei Ping - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MooLah

---

== Overview

This portfolio aims to document the contributions my contributions to MooLah

My team of 4 Computer Science students and I were tasked with enhancing a basic Command
Line Interface desktop application AddressBook - Level 3 for our Software Engineering project.
Over 6 weeks, we chose to morph it into a finance tracker application called MooLah. This enhanced application
allows the typical NUS student to manage past expenses with the use of budgets, be reminded of
future and recurring expenses, with added convenience coming from user-friendly input formats, aliases
and helpful statistics. It is written in Java, and has about XXX kLoC(TO BE CONFIRMED).
My main developer responsibility in the team consists of the statistics features across every component.


== Summary of contributions

* *Big feature*: I have added *the ability to generate statistics* in MooLah
** What it does: This features consists of a basic summary of expenses, a side-to-side comparison
as well as a trend analysis across different periods of time.
** Justification: This feature improves the product significantly because the problem
of untracked expenditure is greatly solved by allowing users to monitor their spending habits,
with the added flexibility of choosing their visual representation as well as varying levels of depth.
** Highlights: As the feature is closely coupled to the budget component and requires to support other dependencies such as
undo/redo, constant coordination with other developers is required.



* *Code contributed*: TO BE FILLED IN

* *Other contributions*:

** Project management:
*** Initiated the renaming of the product to MooLah
*** Reviewed pull requests of team mates
*** Facilitated meetings every Wednesday and Friday and consolidated discussion minutes,
*** Scheduled milestone tasks and ensure that project deliverables are completed on time in the right format.


** Enhancements to existing features:
*** Refactored Tag classes from AddressBook - Level 3  to Category class (TO BE FILLED IN)

** Documentation:
*** Documented new statistics features in User Guide (TO BE FILLED IN)
*** Added the implementation of Statistics in Developer’s Guide (TO BE FILLED IN)


== Contributions to the User Guide


|===
|_We had to update the original AddressBook - Level 3 with instruction for the enhancement that we have added.
THe following is an excerpt from our MooLah User Guide, showing additions that I have made for
the Statistics features. [Work in Progress]

|===

include::../UserGuide.adoc[tag=statsug]

== Contributions to the Developer Guide

|===

|_The following section shows my additions to the MooLah Developer Guide for the Statistics features.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project.

_
|===

include::../DeveloperGuide.adoc[tag=undoredo]

== PROJECT: MooLah


