= *Roby Tanama - Project Portfolio for $aveNUS*
:site-section: AboutUs
:icons: font
:imagesDir: ../images
:stylesDir: ../stylesheets

== Overview

$aveNUS is a command line interface (CLI) financial planning application that my team and I designed for
CS2103T (Software Engineering) module in School of Computing, National University of Singapore (NUS).

In this project, we morphed the sample address book application into $aveNUS, an application that allows NUS students
to track their financial spending with regards to food purchases. Additionally, the application provides them with
the best food recommendations within their current budget as well as a savings feature to track their savings.

The table below provides a quick summary of the symbols and formatting used in this portfolio.

[width="70%",cols="^15%,85%"]
|===
a| `code` | Command that can be typed into the command box
ifndef::env-github[]
a| icon:check[role="green", size="2x"] | Success execution of command
a| icon:lightbulb-o[role="icon-tip", size="2x"] | Tips that might be useful
a| icon:info-circle[role="icon-note", size="2x"] | Additional information that is good to know
a| icon:exclamation-circle[role="icon-important", size="2x"] | Important pointers to take note
endif::[]
|===

== Summary of contributions

This section provides a summary of the contributions that I have made to the team project.

=== Major enhancement: UI

I have updated the UI and added numerous front end functions to improve the look and quality of the app.

==== What it entails

Firstly, I updated the look of the app to give it a more professional look and much more fitting to the purpose
of the application.

For example, I added a Wallet section which shows the user's current amount of money available
to be used for purchases.

Another one would be the addition of the statistics tab which allows user to tab through
their spending data to get a better understanding of their own spending habits and plan their future spending
accordingly.

The font of the application has been carefully selected based on the list of TypeFaces available. This is to allow all
users to be able to read the application easily, even those with reading difficulties.

The overall color scheme of the application is a result of hours and hours of brainstorming in which I have managed to
successfully come up with color schemes for any theme selected by the user that is not only easy on the eyes, but also
stylish in design.

I also added buttons on the menu pane that functions as the single-word commands such as `recommend` and `default`.
These buttons function just like typing the commands on the Command Text Box and the icon for each button has been
carefully selected from online database of icons to perfectly match its function.

==== Justification

The look of the app is the first thing that users see when starting up the application. By having an expertly
designed UI, the user will feel more at ease when using the app as it gives a sense of overall professionalism.

The reasoning behind adding enhancements to the UI components such as statistics tab and wallet section is to make
the app more convenient to the user. By adding such displays, the user will no longer have to type on the command line
just to get the statistics that they desire. Even the most experienced of keyboard users will definitely not want to
constantly type commands just for a bunch of information that could have been easily displayed on the screen.

The themes are added so that the users are able to easily modify how the app look to their likings. Due to our team's
foresight and forward-thinking nature, we thought that it would be much more accommodating to the user. Imagine having
to stare at the same application for hours on end without being able to change the look of the application at all,
which is why it is important to have themes.

The buttons are added to improve the user's convenience as most single-word commands like `recommend` are done by
typing the command word into the Command Text Box. By being able to use the command just by clicking the button, it
would greatly save the user's time. This also allows the app to accommodate the different type of users, where some
might prefer mouse over keyboard, and vice versa.

==== Highlights

The UI features such as `theme` has been implemented to work with Command Line Interface. For example, `theme dark` will
change the application's theme to Dark theme. This is to enhance the clickable theme button and also to give users the
freedom of choice.

A menu tab has been created on the left side of the application with a variety of buttons available such as help menu,
and theme button with tooltip that appears when user hovers over the button. This is to give a brief outline to the
users on what the application is capable of doing.

The `MainWindow` has been meticulously modified and tweaked to make the application look more professional and
numerous bug fixes were done to allow most laptop to open the application without any problems. The application used
to have problems with smaller laptop screens due to the size of the UI but I have managed to tweak the UI to suit
reasonably small screens.

=== Minor enhancement: Information Features

I have added a command called `info` command, and improved the already implemented `help` command.

==== What it does

The `info` command allows users to view more information about a particular command.

For example, by typing `info add`, new window will be opened displaying everything that the user needs to know about
the command `add` such as usage example, and even expected output.

The `help` command initially only allow the user to copy the user guide's url and paste it onto the browser which
is not very helpful in my opinion. As such, I have decided to include the list of commands available and also
enable the `HelpWindow` to automatically open up the user guide using the system's default browser.

==== Justification

Firstly, the `info` command is implemented to give users a better understanding of how the application works. The
information listed for the commands are written as detailed as possible without over-using technical terms. This works
like an in-built user-guide, hence improving convenience.

The `info` command does not require internet connection as everything is manually typed by the developers and is
integrated into the application. This is so help those users who do not have internet connection but would still want
to know more about various commands.

Secondly, the enhanced `help` command is done so as to provide users with more convenience. The list of commands is to
allow users to easily find out the features that the app can provide without having to look through the entire user
guide. The clickable user guide is done so that the users will not have to manually copy paste the links onto their
browsers which saves a lot of time.

==== Highlights

While implementing both commands, my main train of thought was on user's convenience and ease of usage. While
implementing the `info` command, I had to decide between displaying it on the `ResultDisplay` section or just open
up a new window which I have decided that would be much more detailed and convenient.

The improved `help` command causes the app to require internet connection in order to open the user guide which was
a point of discussion for our group at a certain point. I have decided to go through with it as copying URL would still
require internet connection to open up the user guide nevertheless. The ability to automatically open the system's
default browser would definitely make it much more convenient for the user.

=== Code contributions

https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=robytanama&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&until=2019-11-05[Project Code Dashboard]
| https://github.com/AY1920S1-CS2103T-F13-2/main/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Arobytanama+is%3Aclosed[Pull Request]

=== Other contributions

* Project Management:

** Added user stories as issues on GitHub

** Initialized all the major milestones

** Created appropriate labels for better documentation.

** Improved the documentation for some PRs [Example: https://github.com/AY1920S1-CS2103T-F13-2/main/pull/189[#189]]

** Reviewed pull requests by team members [Example: https://github.com/AY1920S1-CS2103T-F13-2/main/pull/223[#223],
https://github.com/AY1920S1-CS2103T-F13-2/main/pull/177[#177]]

** Organized mini project milestones [Examples: https://github.com/AY1920S1-CS2103T-F13-2/main/issues/228[#228]]

** Fixed bugs after they were found [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/317[#317]]

* Documentation:

** Updated the User Guide [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/315[#315]]

** Updated the Developer Guide

*** Updated UI section of the Developer Guide [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/198[#198]]

*** Updated Info feature of the Developer Guide [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/323[#323]]

*** Updated Theme feature of the Developer Guide [PR https://github.com/AY1920S1-CS2103T-F13-2/main/pull/333[#333]]

== Contributions to the User Guide

This section shows the contributions that I have made to the general feature of the User Guide.

include::../UserGuide.adoc[tag=roby1]

This section was done to enable users to find out the optimal screen resolution to use the application. This is due
to the fact that the application might not work as intended on very small screen resolution, especially on the older
generation laptops.

Smaller screen resolution might result in truncation in details in some section of the application
such as the `info` command.

The scaling setting reminder is done as our app is optimized to work in 100% scaling. Any higher and some section of
the application might fall out of the monitor's boundaries. This reminder is important as some laptops' default scaling
setting is usually higher than 100%.

The following is my contribution to the general commands that the app can offer in the User Guide.

include::../UserGuide.adoc[tag=roby2]

== Contributions to the Developer Guide

This section shows the additions that I have made to the various features of the Developer Guide.

=== This section includes my contribution on the UI component.
include::../DeveloperGuide.adoc[tag=UI]

=== This section includes my contribution on the Info feature of the Developer Guide.
include::../DeveloperGuide.adoc[tag=info]

=== This section includes my contribution on the Theme feature of the Developer Guide.
include::../DeveloperGuide.adoc[tag=theme]
