
= Seah Lynn - Project Portfolio
:site-section: AboutUs
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets

== Introduction
=== About The Team
We are a group of 5 Year 2 NUS Computer Science students
grpup of 4, second year computing students (brief description of team)

=== About The Project
+Work is a project management tool aimed at NUS project leaders who are in charge of a small project group. It allows project leaders to successfully achieve the objectives of their project, by helping them manage their members, meeting times, task allocations as well as personal claims for equipment purchased. A user can use +Work to find the most popular meeting time among his project members, when calling for a meeting. He can add project tasks, and members that are assigned under these tasks, into +Work to better manage the project manpower. Additionally, he can add inventory items into +Work to keep track of the purchases made over the course of the project. 


== Summary of Contributions
=== Enhancements 
* *Major enhancement*: Added *the ability to retrieve the overall statistics of tasks and members in +Work*
** What it does: This feature allows the user to retrieve statistics relating to tasks and members in +Work. For project members, the number of tasks and inventory items allocated to each member is retrieved. For project tasks, the proportion of tasks that are undone, in progress and completed, as well as the time spent on each task inputted into +Work, is retrieved.
** Justification: This feature improves the product significantly because it gives the user a broad overview of the project's progress and members' responsibility allocation at a glance. This makes it easier for the user to plan out future tasks and allocate them accordingly to members so that everyone has close to equal responsibility, which is one of the main goals of effective project management.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Major enhancement*: Added *the ability for users to work with (add, delete, list) project members on +Work*
** What it does: This feature allows the user to retrieve statistics relating to tasks and members in +Work. For project members, the number of tasks and inventory items allocated to each member is retrieved. For project tasks, the proportion of tasks that are undone, in progress and completed, as well as the time spent on each task inputted into +Work, is retrieved.
** Justification: This feature improves the product significantly because it gives the user a broad overview of the project's progress and members' responsibility allocation at a glance. This makes it easier for the user to plan out future tasks and allocate them accordingly to members so that everyone has close to equal responsibility, which is one of the main goals of effective project management.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Major enhancement*: Added *the ability for users to add profile pictures for each project member in +Work*
** What it does: This feature allows the user to retrieve statistics relating to tasks and members in +Work. For project members, the number of tasks and inventory items allocated to each member is retrieved. For project tasks, the proportion of tasks that are undone, in progress and completed, as well as the time spent on each task inputted into +Work, is retrieved.
** Justification: This feature improves the product significantly because it gives the user a broad overview of the project's progress and members' responsibility allocation at a glance. This makes it easier for the user to plan out future tasks and allocate them accordingly to members so that everyone has close to equal responsibility, which is one of the main goals of effective project management.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Minor enhancement*: 
** Enhanced the UI of Members to include the uploading of members' profile photos, as well as listing of tasks allocated to each member under individual member cards.
** Enhanced the UI of statistics calculated in easy-to-read format.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

=== Other Significant Contribution to Project 
** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a new Github plugin (CircleCI) to the team repo


== Contributions to the User Guide
=== Current Enhancement
=== Proposed Enhancement for Version 2.0

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]



== Contribution to the Developer Guide
=== Current Enhancement
=== Proposed Enhancement for Version 2.0

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]







