= Yu Chenghui - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AlgoBase

== Overview

AlgoBase is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 20 kLoC.

== Summary of contributions

* *Major enhancement*: added *the training plan feature*
** What it does: allows users to create customized training plans with specific starting date and end date and that consist of selected problems in AlgoBase. Each problem is wrapped up as a task in the plan. Users can record their progress by marking problems in plans as done or undone, and they can edit, delete or search for plans.
** Justification: This feature improves the product significantly because it would be inconvenient for a hard-working user to manage a large number of problems without a higher-level component that categorize selected problems.
** Highlights: This feature enables users to set specific duration for a training plan, which provides the possibility of various potential enhancements in the future, such as alarming for deadlines, and thus will make AlgoBase more attractive to users.

* *Minor enhancement to existing project*: refactored part of *command and parsers*

* *Code contributed*:
https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=seris370[Code contributed]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (3 releases) on GitHub
** Enhancements to project prototype:
*** Add basic plan commands and Ui for plans (Pull requests https://github.com/AY1920S1-CS2103T-W11-1/main/pull/65[#65], https://github.com/AY1920S1-CS2103T-W11-1/main/pull/72[#72])
*** Enable plan finding (Pull requests https://github.com/AY1920S1-CS2103T-W11-1/main/pull/117[#117], https://github.com/AY1920S1-CS2103T-W11-1/main/pull/148[#148])
*** Write tests for plans (Pull requests https://github.com/AY1920S1-CS2103T-W11-1/main/pull/65[#212])
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/105[#105]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/108[#108]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/125[#125]
*** Reported bugs and suggestions for other teams in the class:
https://github.com/Seris370/ped[PE Dry Run]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
include::../UserGuide.adoc[tag=plan]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

https://github.com/AY1920S1-CS2103T-W11-1/main/blob/master/docs/DeveloperGuide.adoc#training-plan-feature[Design - Plan] +
https://github.com/AY1920S1-CS2103T-W11-1/main/blob/master/docs/DeveloperGuide.adoc#adding-a-plan[Manual Testing - Plan]
include::../DeveloperGuide.adoc[tag=plan]
