= Shaun Ng - Project Portfolio for CS2103 - Revision Tool
:site-section: AboutUs
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: full
:experimental:
:contributedCodeUrl: https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=shaunngtx
:ab3Url: https://github.com/nus-cs2103-AY1920S1/addressbook-level3
:pullUrl: https://github.com/AY1920S1-CS2103-F10-3/main/pull
:restoreCommand: https://github.com/AY1920S1-CS2103-F10-3/main/blob/master/src/main/java/seedu/revision/logic/commands/main/RestoreCommand.java
:AutoComplete: https://github.com/AY1920S1-CS2103-F10-3/main/blob/master/src/main/java/seedu/revision/ui/AutoComplete.java
:ab3ForumUrl: https://github.com/nus-cs2103-AY1920S1/forum/issues

By: `Team F10-3`      Since: `Aug 2019`      Licence: `MIT`

---

== Overview

RevisionTool is a Desktop application used as a personal tool for revisions and self-quizzes.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java and
has about 14 kLoC.

== Summary of contributions

* *Major enhancement*: added *the Restore Command function*
** What it does: allows the user to restore their current Question Bank to the default question bank.
** Justification: This feature improves the product rather significantly as users tend to over-add questions and this would allow them to revert their Question Bank to the default bank
as a form of "Restart", as most of our default questions are taken from the weekly lecture quiz questions, and hence deemed as important by the professor.
** Highlights: This enhancement required changes to the existing models and command classes as a warning alert would pop up to seek confirmation from the users before performing the restore command. Hence the implementation was challenging as it required UI, and model changes.

* *Major enhancement*: added *the Auto Complete function*
** What it does: shows the user a list of possible AutoComplete commands while they are typing, in which they can select, in order to simplify the user's journey.
** Justification: This feature improves the product significantly because for a CLI, users have to do a lot of typing and this greatly eases the amount of work they have to do, and hence allow them to reap the maximum benefits from the application.
** Highlights: This enhancement required in-depth analysis of design alternatives as the implementation required changes to the commandBox which was used in almost every file which had a textBox in it. A significant amount of thought was placed into the implementation as well as I had to formulate what sort of AutoComplete would be most intuitive and value-add to users.
** Credits: _Took references and suggestions from 2 different sources:_
 [https://github.com/AY1920S1-CS2103-F10-3/main/blob/master/src/main/java/seedu/revision/logic/commands/main/RestoreCommand.java[JavaFX AutoComplete]]
 [https://stackoverflow.com/questions/36861056/javafx-textfield-auto-suggestions[Stackoverflow JavaFX Auto-Suggestions]]

* *Minor enhancement*:
** Created the initial UI interface for the startCommand that users use to start the quiz. The different modes such as "start mode/normal", "start mode/arcade", "start mode/custom" were built upon this.

* *Code contributed*:

** link:{restoreCommand}/[Restore Command]

** link:{AutoComplete}/[Auto Complete]

** link:{contributedCodeUtl}/[Tp Dashboard]

* *Other contributions*:

** Enhancements to existing features:
*** Name refactoring from AB3 to Revision Tool (Pull requests link:{pullUrl}/154[#154])
*** Wrote additional tests for existing features. (Pull requests link:{pullUrl}/154[#154])

** Documentation:
*** Did minor changes in diagrams and content for User Guide: link:{pullUrl}/4[#4], link:{pullUrl}/165[#165]
** Community:
*** PRs reviewed (with non-trivial review comments): link:{pullUrl}/99[#99], link:{pullUrl}/101[#101],link:{pullUrl}/149[#149], link:{pullUrl}/153[#153],link:{pullUrl}/155[#155],link:{pullUrl}/158[#158], link:{pullUrl}/163[#163]
*** Provided suggestions and comments for other teams in the class as seen from this link:{ab3ForumUrl}/52[feedback].

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=shaun-autocomplete]
include::../UserGuide.adoc[tag=shaun-restore]
include::../UserGuide.adoc[tag=shaun-AcTip]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=shaun-logic]
include::../DeveloperGuide.adoc[tag=shaun-designmodel]
include::../DeveloperGuide.adoc[tag=shaun-storage]
include::../DeveloperGuide.adoc[tag=shaun-add]

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
