= Shawn Lee Shi Jie - Project Portfolio for Athletick
:site-section: AboutUs
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-T12-3/main

== Introduction
This document details my contribution to the team project, **Athletick**.

=== About the team

**Athletick** was completed by 4 other students and myself. We are second-year computer science undergraduates from the National University of Singapore (NUS).

=== About the project

**Athletick** is a team management desktop application for coaches and team captains of
timing-based performance sports. **Athletick** provides them with athlete
information managing, attendance tracking and performance monitoring. This enables them to better manage their team, plan for trainings and prepare for upcoming competitions.

**Athletick** was developed as part of a requirement for our second-year software engineering
module, https://nusmods.com/modules/CS2103T/software-engineering[CS2103T]. The project was
completed over a period of  six weeks. We were tasked to morph an https://se-education.org/addressbook-level3/[address book application] that manages contacts into an application that
manages something else. As part of the project constraints, the input to **Athletick** needs to be primarily Command-Line Interface (CLI), where the user interacts with **Athletick** by issuing lines of commands.

Note the following symbols and formatting used in this document:

NOTE: This symbol indicates important information

[horizontal]

`command`:: A grey highlight (called a mark-up) indicates that this is a command that can be typed into the command
line and executed by the application.

`[green]#component#`:: Green text with grey highlight indicates a component, class, object or method in the architecture of the application.

== Summary of contributions

This section contains a summary of my coding, documentation, and other helpful contributions to the team project.

**Enhancement Added**: I added the ability to display training and performance records in a calendar.

* What it does
** The `view calendar` and `calendar MMYYYY` commands allow users display a monthly calendar indicating which days contain training and performance records.
** The `calendar DDMMYYYY` command allows users to display training and performance records recorded on a specific date in the form of tables. The overall team attendance rate is displayed in the form of a pie chart as well.
* Justification
** The ability to keep track of when training and performance records were recorded is important
for coaches and captains as it allows them to find out what happened on a specific date.
** The use of a calendar to display this information is neat and easy to navigate, which makes the feature more user-friendly.
* Highlights
** This enhancement provides a platform for further development of date-related features, such as
the planning of training programmes in advance.
** The implementation was also challenging because it required the `[green]#Training#` and
`[green]#Performance#` features to incorporate a date for the calendar to utilise and the construction of a calendar is complex.

*Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=shawnlsj97&tabRepo=AY1920S1-CS2103T-T12-3%2Fmain%5Bmaster%5D[RepoSense]] [https://github.com/AY1920S1-CS2103T-T12-3/main/commits?author=shawnlsj97[GitHub repository]]

*Other contributions*

* Project management
** Managed releases https://github.com/AY1920S1-CS2103T-T12-3/main/releases/tag/v1.1[v1.1], https://github.com/AY1920S1-CS2103T-T12-3/main/releases/tag/v1.2[v1.2], https://github.com/AY1920S1-CS2103T-T12-3/main/releases/tag/v1.2.5[v1.2.5], https://github.com/AY1920S1-CS2103T-T12-3/main/releases/tag/v1.3.1[v1.3.1] and https://github.com/AY1920S1-CS2103T-T12-3/main/releases/tag/v1.3.2[v1.3.2] (5 releases) on GitHub.
** Served as the team's Integration Engineer, ensuring all features are integrated together smoothly
for each project milestone submission.
* Enhancements to existing features
** Implemented sorting of the team list. (Pull request https://github.com/AY1920S1-CS2103T-T12-3/main/pull/62[#62])

** Updated the GUI layout and color scheme. (Pull request https://github.com/AY1920S1-CS2103T-T12-3/main/pull/68[#68], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/87[#87], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/201[#201])
* Documentation
** Added documentation for the `calendar`, `sort` and `view` commands in the User Guide. (Pull requests https://github.com/AY1920S1-CS2103T-T12-3/main/pull/124[#123], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/138[#138], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/214[#214])
** Added documentation for the `calendar`, `sort` and `view` commands in the Developer Guide. (Pull requests https://github.com/AY1920S1-CS2103T-T12-3/main/pull/111[#111], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/220[#220])
** Created style guide for diagrams for the team to adhere to. (https://docs.google.com/presentation/d/1JprrBR5HnnOQio1M9YEgheEYldplHqL18q4IQCGqyMk/edit#slide=id.p[Link])
* Community:
** Reviewed PRs by peers by providing feedback and suggestions. (Pull requests
https://github.com/AY1920S1-CS2103T-T12-3/main/pull/63[#63],
https://github.com/AY1920S1-CS2103T-T12-3/main/pull/64[#64], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/65[#65], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/81[#81], https://github.com/AY1920S1-CS2103T-T12-3/main/pull/91[#91])
** Reported bugs and suggestions for other teams in the module.
(https://github.com/shawnlsj97/ped/issues?q=is%3Aopen+is%3Aissue+label%3Atype.FunctionalityBug[Bug reports], https://github.com/shawnlsj97/ped/issues?q=is%3Aopen+is%3Aissue+-label%3Atype.FunctionalityBug[Suggestions])

== Contributions to the User Guide

|===
|_This section displays my contributions to the User Guide for the calendar feature. They showcase
my ability to write documentation targeting end-users of our application. The full User Guide can
be found https://ay1920s1-cs2103t-t12-3.github.io/main/UserGuide.html[here]._
|===

[blue]#_Start of extract from User Guide_#

include::../UserGuide.adoc[tag=calendar1]

include::../UserGuide.adoc[tag=calendar2]

include::../UserGuide.adoc[tag=calendar3]

[blue]#_End of extract from User Guide_#

== Contributions to the Developer Guide

|===
|_This section displays my contributions to the Developer Guide for the calendar feature. They
showcase my ability to write technical documentation and the technical depth of my contributions
to the project. The full Developer Guide can be found
https://ay1920s1-cs2103t-t12-3.github.io/main/DeveloperGuide.html[here]._
|===

[blue]#_Start of extract from Developer Guide_#

include::../DeveloperGuide.adoc[tag=calendar1]

include::../DeveloperGuide.adoc[tag=calendar2]

include::../DeveloperGuide.adoc[tag=calendar3]

[blue]#_End of extract from Developer Guide_#
