= Shui Yao - Project Portfolio for NUStudy
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Introduction
'''

This portfolio is to document my contributions to project NUStudy, which is a software engineering project under Module
CS2103T at National University of Singapore. Our team consists of five students majoring in Computer Science. We decided
to morph an existing Java application https://github.com/nus-cs2103-AY1920S1/addressbook-level3[Address Book 3] into
NUStudy, which is a desktop application with command line for user input and a JavaFX GUI for display. NUStudy supports
notes management, quiz practice, revision task records, and usage statistics to help with revision.

NOTE: You may take note of the following symbols and formatting used in this portfolio *unless otherwise specified*: +
`overdue` - The monospaced text indicates that it is a user input. +
_Task_ - An italicised word indicates that it is a class name. +
#11 - A number with # sign indicates the Pull Request or Issue number. +
PR - Abbreviation for "Pull Request".

== Summary of Contributions
'''
This section is to summarise my contributions to the project, including feature enhancements, documentation and project
management.

* Major Enhancement: I implemented revision tasks, which have attributes of a heading, a starting date and time
(starting from PR https://github.com/AY1920S1-CS2103T-F11-4/main/pull/37[#37]).
** What it does: This feature supports tasks for revision of a note or a question at a particular point of time. It is
implemented as _Task_ class stored in a revision list which is implemented as _TaskList_ class. I also implemented
commands (_AddTaskForNoteCommand_, _DoneTaskCommand_ etc.) to support operations on tasks.
** Justification: This feature allows users to set their revision plans and goals. It makes the revision more structured
and organised. It helps to stop procrastination to some extent. In the future release *v2.0*, this feature will also
support desktop push notification to remind the users to start their revision.
** Highlights: This enhancement is dependent on _Note_ and _Question_ classes implemented by my teammates. There might
be regressions of my task features if my teammates decide to change their implementations of _Note_ or _Question_.
Therefore, I did a thorough analysis of the design pattern and the project architecture to use as least information as
possible from their classes in order to reduce coupling.

* Minor Enhancement

* Code Contributed: You may feel free to check my code https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=shuiyao-sg&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=shuiyao-sg&tabRepo=AY1920S1-CS2103T-F11-4%2Fmain%5Bmaster%5D[here]

* Other Contributions

== Contributions to the User Guide
'''

*This section summarises my contributions to the User Guide.*

include::../UserGuide.adoc[tag=task]

'''

*I also envisioned more advanced features that will come in v2.0 of NUStudy as shown below.*

include::../UserGuide.adoc[tag=task_2.0]

'''

*Apart from addition to my individual work, I also helped the team by adding a command summary of everyone's feature. This
is shown in the following paragraphs.*

include::../UserGuide.adoc[tag=command_summary]

== Contributions to the Developer Guide
'''
This section summarises my contributions to the Developer Guide. My individual section of the Developer Guide illustrates
the implementation of the command for adding a task to the revision task list. Implementations of other commands such as
deletion, searching, marking done etc. are omitted from the Developer Guide.

NOTE: Notations for this section is slightly different from the rest of the PPP. In the Developer Guide, a `monospaced`
text has various meanings depending on its format. If the text is a word or a group of words in *PascalCase* ie. first letter
of each word is capitalized without any space in between each word, then the `monospaced` text refers to a class or interface name. If
the text comes with a bracket () at the end, then the text refers to a method name. Otherwise, the text refers to user command.

include::../DeveloperGuide.adoc[tag=task]

include::../DeveloperGuide.adoc[tag=task_usecase]

'''

*Apart from addition to my individual features, I also modified the diagrams of the UI and Model components as shown below.*

include::../DeveloperGuide.adoc[tag=UIClassDiagram]

include::../DeveloperGuide.adoc[tag=ModelClassDiagram]
