= Chong Guang Jun - Project Portfolio
:site-section: AboutUs
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets
:siteURL: https://ay1920s1-cs2103t-w13-4.github.io/main

== PROJECT: Budget Buddy

This portfolio serves to provide a breakdown of what I have contributed as a student in the software engineering project,
*Budget Buddy*.

== About Budget Buddy

Budget Buddy is a desktop-based expense tracking application made for students, NUS School of Computing students in particular,
to keep track of and manage their finances better. The user interacts with it using a Command Line Interface (CLI),
and it has a Graphical User Interface (GUI) created with JavaFX. The application is written in Java, and has about 15 kLoC.

This is a software engineering project in which groups are tasked to enhance or morph a simple CLI-based address book application.
The end result is a expense tracking application with focus on programmers, to make customisation that much easier.

Budget Buddy is able to maintain separate accounts, handle a multitude of transactions within an account, and even track any
loans that the user might have made. Rules can be added to make repetitive tasks automated, and scripts can even allow the user
to create mass changes to data in their own way by themselves.

== Project Role

My task in this project is the Rule Engine feature, which allows for the automation in the application, executing certain tasks
automatically upon the addition of a new transaction. The following sections will elaborate on this feature, which includes the additions I have made to both the user and developer guides.

'''

Take note of the following formatting used in the rest of this portfolio.

[cols="<1a,<5a", frame=none, grid=none]
|===
|`command word`
|Monospace text like this indicates that this is a command word that can be entered as part of a command to be executed by the application.

|*_filename.txt_*
|Bold italicized text like this indicates that this is a filename that can be found within the application.

|`*component*`
|Bold monospace text like this indicates that this is a component that can be found within the application.
|===


== Summary of contributions

|===
|This section provides an overview of my contribution to this application.
|===

=== Major enhancement:
Added the ability to add/list/edit/remove rules, as well as executing them.

* *What it does*: Allows the user to define a set of rules in the rule engine which will be executed by the rule engine upon
adding/editing a transaction. A rule may carry out an action depending on whether the transaction satisfies the rule's condition,
or "predicate".
* *Justification*: This feature improves the application significantly because for day-to-day transactions, there may be many
repetitions in what the user types. The app can therefore help users save time by automating such repetitive processes, or even
more, depending on how the user uses it.
* *Highlights*: Setting up rules was a challenge, as it created an additional source of "logic" besides commands, which required a new structure
from the bottom up. A method to process rules had to be made, and considering that both expressions and scripts can be used for rules, a unified
way to process them was required.

=== Minor enhancement:
Set up panel management within the GUI.

* *What it does*: Allow easy switching between panels within the same frame.
* *Highlights*: Different panels were required based on the currently active tab, hence managing panels properly allowed
for switching between them to be much easier.

=== Code contributed:
I have contributed over 30 pull requests to the repository as of 11 November 2019.

All of my contributions can be found here: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=tcgj[RepoSense Analysis]]

=== Other contributions:

* GUI Enhancements:
** Updated the GUI layout and colour scheme: Pull requests https://github.com/AY1920S1-CS2103T-W13-4/main/pull/60[#60], https://github.com/AY1920S1-CS2103T-W13-4/main/pull/95[#95], https://github.com/AY1920S1-CS2103T-W13-4/main/pull/185[#185]
* Bug fixes:
** Fix bugs noted during PE dry run: Pull request https://github.com/AY1920S1-CS2103T-W13-4/main/pull/153[#153]
* Documentation:
** Contributed to the User Guide and Developer Guide. See Section 5 and 6 below for detailed breakdown.
* Community:
** Project-wide refactoring on package naming to remove existing references to AB3: Pull request https://github.com/AY1920S1-CS2103T-W13-4/main/pull/52[#52]
** Reviewed https://github.com/AY1920S1-CS2103T-W13-4/main/issues?q=reviewed-by%3Atcgj[50+] pull requests by the team

== Contributions to the User Guide

|===
|_This section shows what I have contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

You can refer to the full User Guide link:{siteURL}/UserGuide.html[here].

=== Overview of Contributions

Below is an overview of my contributions to the User Guide.

==== Improve user experience

I added multiple sections and introductory paragraphs, which include the _Introduction, Quick Start, Getting Started, Features, and FAQ_,
that provide clarification and support in usage for the users who are using the application for the first time, or need help with troubleshooting.

==== Add main content into the User Guide

I wrote detailed sections about the usage of commands that are in the Budget Buddy application, to guide users in the format and
specifications required for those commands. An extract from the User Guide that were written by me is shown in section 5.2 below.

include::../UserGuide.adoc[tag=rules]

== Contributions to the Developer Guide

|===
|_This section shows what I have contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

You can refer to the full Developer Guide link:{siteURL}/DeveloperGuide.html[here].

=== Overview of Contributions

Below is an overview of my contributions to the Developer Guide.

==== Add main content into the Developer Guide

I wrote detailed sections about the implementations of functionality in the Budget Buddy application, drawn UML diagrams, and documented some use cases
for the Developer Guide. A few extracts of the Developer Guide that were written by me are shown in section 6.2 and 6.3 below.

include::../DeveloperGuide.adoc[tag=ruleMgmt]

include::../DeveloperGuide.adoc[tag=ruleExec]
