= Tie Ying Kathleen - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: iFridge

---

== Overview

iFridge is a desktop grocery management application to encourage home cooks to manage their food waste. The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has a about 20kLoC.

== Summary of contributions

* *Major enhancement*: adding *the ability to add a template to the shopping list*
** What it does: allows the user to add items in a specified template that are not currently in their grocery list. The feature
is able to deal with duplicate items as well as exclude expired items when checking the grocery list.
** Justification: This feature improves the product significantly by making it easy for the user to generate shopping lists without having to
check the fridge. In addition, the feature makes it easy for the user to generate shopping lists involving regular grocery items instead of having to add them one by one.
Users can also use it to store the ingredients list of recipes.
** Highlights: This feature is able to subtract the amount of each item already in the grocery list from the template item to be added into the shopping list.
In the case that the item to be added is already in the shopping list, the item amount is updated with the sum of needed amount and the previous amount recorded.
To complement this function, a UnitDictionary class was added in order to enable cross-unit calculations as long as the units were of the same unit type.

* *Minor enhancement*: added template list that allows the user to create and manage templates
** For templates: Add, Edit, Delete, Clear, and List templates in the template list
** For individual template: Add, Edit, Delete, and List items in a template

* *Minor enhancement*: added unit dictionary that keeps tracks of the unit types of items with the same name (note: non case-sensitive)
** Supports the ability of the app to carry out arithmetic functions on similar items with different units by checking that all items with the same name
have the same unit type. E.g. Volume unit type: ml, L or Weight unit type: g, kg, oz, lbs

* *Code contributed*: The samples of my functional and test code can be viewed https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=teika97[here].

* *Other contributions*:

** Project management:
//*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the Food class to include an Amount field https://github.com/AY1920S1-CS2103-F10-2/main/pull/34[#34]
//*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
//*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Updated ContactUs, AboutUs: https://github.com/AY1920S1-CS2103-F10-2/main/pull/14[#30]
*** Updated Class diagram for Logic component
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/teika97/ped/issues/1[1], https://github.com/teika97/ped/issues/3[3], https://github.com/teika97/ped/issues/4[4])
*** Contributed to forum discussions (examples: https://nus-cs2103-ay1920s1.slack.com/archives/CM4H41AN9/p1568817306026000[1])

== Contributions to the User Guide
|===
|_Below are some notable sections I contributed to the User Guide which showcase my ability to write documentation targeting our target end-users._
|===

include::../UserGuide.adoc[tag=templatelistfeatures]
include::../UserGuide.adoc[tag=addTempfeature]

== Contributions to the Developer Guide

|===
|_Below are some notable sections I contributed to the Developer Guide that showcase my ability to write technical documentation and the technical depth of my contributions to the project_
|===

include::../DeveloperGuide.adoc[tag=logicClassDiagram]
include::../DeveloperGuide.adoc[tag=addTemplateListfeature]
include::../DeveloperGuide.adoc[tag=manualTestingTemplate]




