= Wang Xinman - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT:  Incident Management System

== Overview

The Incident Management System is a desktop application used for managing incidents and dispatching vehicles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement* : Implemented *Vehicle Assignment Command*
** What it does: Dispatches nearby vehicles to newly created incidents.
** Justification: Whenever new incidents are reported, vehicles in the area need to be dispatched to respond to the emergency.
** Highlights: This enhancement supports both automatic and manual vehicle dispatchment to incident sites, resulting in a multitude of considerations in the algorithm design for both vehicle assignment command and its associated new command. It required an in-depth analysis of the nature of vehicle dispatchment and design alternatives. The implementation too was challenging as many validity checks have to be conducted to handle a range of exceptions.

* *Medium enhancement*: Implemented *Find Vehicles Command*
** What it does: Searches for vehicles by district number, vehicle type or vehicle number in the existing list of vehicles.
** Justification: This feature helps operators check the status of vehicles present in a given district, both available and already dispatched. Searching by vehicle type also shows operators the vehicles of a specific type that are present, for them to make relevant judgements and decisions. Searching for vehicles by their vehicle numbers allows operators to locate a vehicle even if they only remember one character in its vehicle number.
** Highlights: This enhancement significantly increases flexibility in vehicle searching beyond exact matches, which added complexity in the implementation.

* *Minor enhancement*: Implemented the *Vehicle Model* and *New Command*, allowing for new incident creation and vehicle actions.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=tirameshu[View on RepoSense]]

* *Other contributions*:

** Enhancements to existing features:
*** Detects irrelevant prefixes in user input (Pull request https://github.com/AY1920S1-CS2103-T11-1/main/pull/270[#270])
*** Allow for case insensitivity of vehicle searches (Pull request https://github.com/AY1920S1-CS2103-T11-1/main/pull/260[#260])
*** Removed repetitive prefixes (Pull request https://github.com/AY1920S1-CS2103-T11-1/main/pull/286[#286])
*** Wrote tests for existing features to increase coverage (Pull requests https://github.com/AY1920S1-CS2103-T11-1/main/pull/178[#178], https://github.com/AY1920S1-CS2103-T11-1/main/pull/292[#292])
** Documentation:
*** Peer-reviewed and standardised formatting for Developer Guide and User Guide (Pull requests https://github.com/AY1920S1-CS2103-T11-1/main/pull/280[#280], https://github.com/AY1920S1-CS2103-T11-1/main/pull/281[#281])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=new]

include::../UserGuide.adoc[tag=list-v]

include::../UserGuide.adoc[tag=find-v]

include::../UserGuide.adoc[tag=newincidentwithoutvehicle]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=incidentdraftcreation]

include::../DeveloperGuide.adoc[tag=vehiclesearch]
