= Kartike Khandelwal - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:

This document is a portfolio of the ichifund software engineering project I have been a part of and it is a means of highlighting my contributions to this project, and to my potential as a software engineer.

== PROJECT:IchiFUnd

---

== Overview

For our software engineering project, my team of five software engineering students, including myself, were tasked with either improving on or modifying the existing addressbook project into a new application. We decided to opt for the latter of the two options and morph the addressbook codebase into a command-line based finance management tool which we named `"*Ichifund*"`. Ichifund is a desktop application targeted towards students who need to manage their finances over a desktop application and intends to aid them with several money accounting needs, such as tracking budgets, loans, keeping track of transactions over time, and generating data and analysis on all of these factors. All of this intends to package the various complex tools required to manege personal finances into a single application.

== Summary of contributions

* *Major enhancement*: added *Application support for the Loans feature*
** What it does: allows the user to add Loans, remove Loans and edit them on the fly.
** Justification: This feature improves the product significantly because a user can can keep track of Credit and Debit, contrary to just active transactions. Static budgets and transactions don't keep track of money that is owed to a different party.
** Highlights: This enhancement affects the use case of the Application and adds to the value the user can potentially receive from the product.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
***
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag = loanpaid]

include::../UserGuide.adoc[tag=loanadd]

include::../UserGuide.adoc[tag=loanedit]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=loans]

include::../DeveloperGuide.adoc[tag=LoanManual]
