= Yan Wei Liang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Seller Manager Lite Junior

== Overview

Seller Manager Lite is a desktop application, written in Java, for managing phone sales.
The user interacts with it using a Command Line Interface, and views data using a Graphical
User Interface, where data is displayed in the form of lists. As the database was designed
specifically to support phone sales, database objects such as Customers, Phones and Orders
have predefined relationships between them.

== Summary of contributions

* *Major enhancement*: Added the ability to autocomplete commands.
** What it does: allows the user to input commands with ease. As the user types into the
command line, suggestions will be shown.
** Justification: This feature improves the product significantly because a user does not need
to remember what commands are available or constantly refer to the user guide. It also allows
the user to determine if he is entering duplicated data in real time, instead of waiting for
feedback after entering the command.
** Highlights: This enhancement supports all existing commands of varying formats and was
designed to be easily extensible to commands added in future.
** Credits: UI code for displaying a dropdown menu was inspired by this StackOverflow post:
https://stackoverflow.com/questions/36861056/javafx-textfield-auto-suggestions

* *Minor enhancement*: Refactored the Model to use generic DataBook and UniqueList that
store Identifiable objects.

* *Minor enhancement*: Implemented the Phone class.

* *Minor enhancement*: Implemented "cascading" effects for edit and delete for database objects.

* *Code contributed*:

** Autocomplete:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/122[#122]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/143[#143]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/155[#155]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/277[#277]

** Refactor:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/137[#137]

** Phone:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/62[#62]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/77[#77]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/101[#101]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/111[#111]

** Cascading:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/117[#117]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

//include::../UserGuide.adoc[tag=delete]

//include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]
