= Yan Wei Liang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Seller Manager Lite Junior

== Overview

Seller Manager Lite is a desktop application, written in Java, for managing phone sales.
The user interacts with it using a Command Line Interface, and views data using a Graphical
User Interface, where data is displayed in the form of lists. As the database was designed
specifically to support phone sales, database objects such as Customers, Phones and Orders
have predefined relationships between them.

== Summary of contributions

* *Major enhancement*: Added the ability to autocomplete commands.
** What it does: allows the user to input commands with ease. As the user types into the
command line, suggestions will be shown.
** Justification: This feature improves the product significantly because a user does not need
to remember what commands are available or constantly refer to the user guide. It also allows
the user to determine if he is entering duplicated data in real time, instead of waiting for
feedback after entering the command.
** Highlights: This enhancement supports all existing commands of varying formats and was
designed to be easily extensible to commands added in future. The autocomplete system is
contextually aware, by suggesting values catered to each command and prefix
specifically. The possible values will also automatically update according to changes in the database.
** Credits: UI code for displaying a dropdown menu was inspired by this StackOverflow post:
https://stackoverflow.com/questions/36861056/javafx-textfield-auto-suggestions

* *Minor enhancement*: Refactored the Model to use generic DataBook and UniqueList that
store Identifiable objects.

* *Minor enhancement*: Implemented the Phone class.

* *Minor enhancement*: Implemented "cascading" effects for edit and delete for database objects.

* *Code contributed*:

** Autocomplete:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/122[#122]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/143[#143]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/155[#155]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/277[#277]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/262[#262]

** Refactor:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/137[#137]

** Phone:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/62[#62]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/77[#77]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/101[#101]
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/111[#111]

** Cascading:
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/117[#117]

* *Other contributions*:

** Project management:
*** Released `v1.2` on GitHub
** Enhancements to existing features:
*** Removed unwanted AB3 code related to Person
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/141[#141],
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/83[#83],
https://github.com/AY1920S1-CS2103T-T09-4/main/pull/106[#106]
*** Reported bugs and suggestions for other teams in the class (
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/203[ExerHealth #203],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/204[ExerHealth #204],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/205[ExerHealth #205],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/206[ExerHealth #206],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/209[ExerHealth #209],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/210[ExerHealth #210],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/219[ExerHealth #219],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/220[ExerHealth #220],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/221[ExerHealth #221],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/222[ExerHealth #222],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/223[ExerHealth #223],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/226[ExerHealth #226],
https://github.com/AY1920S1-CS2103T-T09-2/main/issues/227[ExerHealth #227]
)

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=autocomplete]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=autocomplete]
