= Victor Varian - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 3

== Overview

_Modulo_ - a java application that enable students to keep track of their studies
by enabling them to create modules, plans, quizzes and managing their finances. The code is written in Java and
the user interacts with it using a CLI, and it has a GUI created with JavaFX.

== Summary of contributions

* *Major enhancement*: added *the ability to switch application for different features*
** What it does: allows the user to switch logic, model, storage, and UI from one feature to another.
** Justification: This feature is the first step for the user to switch and use several features that Modulo offers. It also make sure that switching from one feature to another is smooth enough.
** Highlights: This enhancement can be extended further if the next developer decides to add a big feature to Modulo.
It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
Furthermore it will also reduce coupling in our code.

* *Major enhancement*: added *the ability to compromise for typo and categorical search*
** What it does: allows the user to search for questions in multiple ways based on the result of the filter that the user keys in. It also substantially helps the user
who often type carelessly to capture for typo if the user enable it.
** Justification: This feature helps the user search for related questions faster and flexible. The feature can therefore help users save more time from linear searching
and retyping the keyword they want to search.
** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _addressbook3_

* *Minor enhancement*: added *the ability to hide the answer when the user is in the studyMode and vice versa*
* *Minor enhancement*: added *the ability to split screen to reveal the full details of the question and add explanation to the question*

* *Code contributed*:
https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=victorvic54&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[RepoSense Report]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
