= Victor Varian - Project Portfolio (Modulo)
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Overview

_Modulo_ - a java application that enable students to keep track of their studies
by enabling them to create modules, plans, quizzes and managing their finances. The code is written in Java and
the user interacts with it using a CLI, and it has a GUI created with JavaFX.

== Summary of contributions

* *Major enhancement*: added *the ability to switch application for different features*
** What it does: allows user to switch logic, model, storage, UI from one feature to another.
** Justification: This feature is the first step for the user to switch and use several features that Modulo offers. Switching from one feature to another is maintained to smooth.
** Highlights: This enhancement can be extended further if the next developer decides to add a big feature to Modulo.
It required an in-depth analysis of design alternatives. The implementation too was challenging as it required a depth understanding on how to make sure each feature
care for their own implementation without others interfering it. Furthermore it will also reduce coupling in our code.

* *Major enhancement*: added *the ability to compromise for typo and categorical search*
** What it does: allows the user to search for questions in multiple ways based on the result of the filter that the user keys in. It also substantially helps the user
who often type carelessly to capture for typo if the user enable it.
** Justification: This feature helps the user search for related questions faster and flexible. The feature can help users save more time from linear searching
and retyping the keyword they want to search.
** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _addressbook3_

* *Minor enhancement*: added *the ability to hide the answer when the user is in the studyMode and vice versa*
* *Minor enhancement*: added *the ability to split screen to reveal the full details of the question and add explanation to the question*

* *Code contributed*:
https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=victorvic54&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[RepoSense Report]

* *Other contributions*:

** Project management: +
Managed releases `v1.1` - `v1.2.1` (3 releases) on GitHub

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S1-CS2103-T16-2/main/pull/104[#104]
*** Parts of the switch feature I added was adopted by several other class mates (https://github.com/AY1920S1-CS2103-T16-2/main/pull/63/files[63])

** Tools:
*** Setting up the GitHub, Travis, Coveralls.
*** Integrated a new Github plugin (Travis and Coveralls) to the team repo
*** Maintaining the issue tracker every week

== Contributions to the User Guide

include::../UserGuide.adoc[tag=quizsection1]

== Contributions to the Developer Guide

include::../DeveloperGuide.adoc[tag=createquestion1]
include::../DeveloperGuide.adoc[tag=createquestion2]
include::../DeveloperGuide.adoc[tag=undoredo1]
include::../DeveloperGuide.adoc[tag=undoredo2]
include::../DeveloperGuide.adoc[tag=undoredo3]
include::../DeveloperGuide.adoc[tag=undoredo4]

