= Huang Weijie - _Billboard Project Portfolio Page_
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: <Billboard>

== Purpose
The purpose of this page is to consolidate the various contributions that I have made in the process of working on this software engineering project and building Billboard,
from code and documentation to team tasks and project management, in the hopes that it will serve as a useful reference and proof of work in the future.

== Overview
For CS2103T, a Software Engineering module, my team of 4 others and I were tasked with enhancing a pre-existing application called AddressBook 3.
It was a desktop Address Book application of considerable size. Through the various cycles of ideation and development, we eventually settled on the idea for Billboard.

Billboard is a financial management application with emphasis on speed and simplicity. Among the unique traits of Billboard is that
it is a desktop Command Line Interface (CLI) application, with most of its functionality accessed via typing commands into a console. Billboard supports all the basic operations
that are needed to effective manage your finances. You can:

* Add new expenses to the list
* Edit past expenses
* Delete past expenses
* View your expenses so you are able to keep track of them

Additionally, Billboard sports several enhanced features that make it stand out. These features include tagging expenses,
archiving past expenses, filtering the current list of expenses, and dynamically displaying statistics based on the current expense.
All these features aim to ease the process of managing and organizing your finances.

== Legend
The below styles of formatting are used to demarcate certain sections of text with special meaning:

NOTE: Additional information that the reader should take note of.

`text`: Indicates that text should be treated as a command or code.


== Summary of contributions

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=statistics]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=statistics]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_