= Tan Wei Yang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:

== PROJECT: IchiFund

'''

== Overview

This portfolio documents my contributions towards the project, IchiFund, which is part of an introductory software
engineering module, CS2103T. My team of 5 was tasked to morph or enhance an existing address book software.
Our resulting product, IchiFund, is a desktop finance management application for students to manage transactions, budgets and loans.
It is optimised for students that prefer using a CLI.
My role was to develop the https://ay1920s1-cs2103t-w12-4.github.io/main/UserGuide.html#transactions[Transactions] component of the application.

== Summary of contributions
* *Major enhancement*: Developed the `Model`, `Logic`, `Storage`, and `Ui` infrastructure for transactions.
** Functionality: Provides the foundation on which features related to transactions, such as `add`, `filter`, `edit` and `delete`, are built.
** Justification: The ability to easily create, read, update and delete transactions on the GUI of the application depends on properly
establishing the infrastructure for transaction.
** Highlights: This enhancement demonstrates a deep understanding of the underlying MVC design pattern of the existing code.
The modifications to the GUI (addition of a filter title and reorganizing information in cells) also demonstrate an understanding of how to work with JavaFX.

* *Major enhancement*: Added the ability to *add and filter transactions* with *optional arguments based on the current filter* (enhancement with greatest depth)
** Functionality: The `filter` command changes the existing filter for the list of transactions. The `add` command adds a transaction to the list of transactions.
If left unfilled, the values taken by the optional arguments are inferred from the current filter.
** Justification: The add and filter features on their own are basic functionalities of the software. The
implementation of optional arguments filled in based on the current filter allows user to provide minimal information to add
a transaction, which significantly improves user experience.
** Highlights: This enhancement required the implementation of an intermediate between `Model` and `Logic`, `TransactionContext` for `Logic` to easily
access information about the current filter used in the list of transactions. Moving forward, this can be generalized to a `Context` component
that stores read-only information about the state of `Model` that is vital to the function of `Logic`.

* *Minor enhancement*: Added the ability to edit and delete transactions (PR https://github.com/AY1920S1-CS2103T-W12-4/main/pull/175[#175])

* *Code contributed*: Click https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=weiyang13[here] to view the code I have contributed.

* *Other contributions*:

** Project management:
*** Managed https://github.com/AY1920S1-CS2103T-W12-4/main/pulls[pull requests (PRs)],
https://github.com/AY1920S1-CS2103T-W12-4/main/issues[issue tracker] and
https://github.com/AY1920S1-CS2103T-W12-4/main/milestones[project milestones]
*** Refactored existing code of Address Book 3 to IchiFund (PR https://github.com/AY1920S1-CS2103T-W12-4/main/pull/252[#252])

** Enhancements to existing features:
*** Restructured architecture of code to enable separate parsing for features in different tabs using the same command line
(PR https://github.com/AY1920S1-CS2103T-W12-4/main/pull/137[#137])
*** Modified sample data for initialization of IchiFund (PR https://github.com/AY1920S1-CS2103T-W12-4/main/pull/239[#239])
*** Modified documentation on
https://github.com/AY1920S1-CS2103T-W12-4/main/blob/master/docs/UserGuide.adoc#ichifund-basics[existing features]
to be more reader-friendly

** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/AY1920S1-CS2103T-T09-1/main/issues/196[196], https://github.com/AY1920S1-CS2103T-T09-1/main/issues/197[197],
https://github.com/AY1920S1-CS2103T-T09-1/main/issues/198[198], https://github.com/AY1920S1-CS2103T-T09-1/main/issues/200[200],
https://github.com/AY1920S1-CS2103T-T09-1/main/issues/201[201])

== Contributions to the User Guide


|===
|_Given below is a sample of what I have contributed to the User Guide. It showcases my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addtx]

|===
|_For more sample user guide contributions, refer to the https://ay1920s1-cs2103t-w12-4.github.io/main/UserGuide.html#Navigation[Navigation]
and https://ay1920s1-cs2103t-w12-4.github.io/main/UserGuide.html#transactions[Transactions] sections of the User Guide._
|===

<<<

== Contributions to the Developer Guide

|===
|_Given below is a sample of what I have contributed to the Developer Guide. It showcases my ability to write technical
documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=overviewtx]

include::../DeveloperGuide.adoc[tag=transfilter]

include::../DeveloperGuide.adoc[tag=transadd]

|===
|_For more sample developer guide contributions, refer to the https://ay1920s1-cs2103t-w12-4.github.io/main/DeveloperGuide.html#separate-parsing-and-tab-switching[Separate Parsing and Tab Switching]
and https://ay1920s1-cs2103t-w12-4.github.io/main/DeveloperGuide.html#transactions[Transactions] sections of the User Guide._
|===
