= Cheryl Ng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Incident Management System

'''

== Overview

Incident Management System is a desktop incident Manager application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Implemented *Incident Search and Listing*
** What it does: allows the user to list a filtered or unfiltered list of incidents dependent on commands and parameters used.
** Justification: This feature improves the product significantly because a user can handle large sets of data efficiently through searching for relevant incident reports based on the parameters, to prepare these incidents for filling and submission, or for reviewing.
** Highlights: This enhancement is easily extendable to various data within the Incident model, and has been designed to easily accommodate additional parameters. It required an in-depth analysis of design alternatives, as the implementation was challenging, requiring a good understanding of how to parse multiple parameters with multiple words for each parameter, and consideration of the abstraction of said parameters.
** Credits: _Extended from the FindPerson command in the initial AB3_

* *Major enhancement*: Implemented *initial Incident GUI layout* [https://github.com/AY1920S1-CS2103-T11-1/main/pull/59[#59]]
** Summary: Modified the GUI for a new panel for displaying Incidents and the relevant information in the initial implementation.
** Highlights: This enhancement required an in-depth understanding of the GUI design and the JavaFX library, as well as great familiarity with the initial Incident class. Further abstraction of the Incident class was also executed to ensure SLAP principlese were adhered to.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#=undefined&search=yoshi275[View on RepoSense]]

* *Other contributions*:
** Add Netlify bot to repo and add badge to README [https://github.com/AY1920S1-CS2103-T11-1/main/pull/18[#18]]
** Remove irrelevant Developer Guide sections [https://github.com/AY1920S1-CS2103-T11-1/main/pull/128[#128]]
** Make minor aesthetic and usability edits to the GUI [https://github.com/AY1920S1-CS2103-T11-1/main/pull/289[#289]]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=listi]

include::../UserGuide.adoc[tag=findi]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=incidentsearch]
