@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Finance <<Rectangle>> {
    Class FinanceTracker
    Class MonthlyLimit
    Class PurchaseList
    Class InstallmentList
    Class Purchase
    Class PurchaseDescription
    Class PurchaseMoneySpent
    Class Installment
    Class InstallmentDescription
    Class InstallmentMoneyPaid
    Class MonthlyLimit
}

FinanceTracker *-down-> "0...1" MonthlyLimit
FinanceTracker *-down-> "1" PurchaseList
FinanceTracker *-down-> "1" InstallmentList

PurchaseList o-down-> "*" Purchase
Purchase *-down-> "1" PurchaseDescription
Purchase *-down-> "1" PurchaseMoneySpent

InstallmentList o-down-> "*" Installment
Installment *-down-> "1" InstallmentDescription
Installment *-down-> "1" InstallmentMoneyPaid

@enduml
