@startuml
!include ../style.puml

box UiLogic UI_LOGIC_COLOR_T1
participant ":UiLogicManager" as UiLogicManager UI_LOGIC_COLOR
participant ":AlgoBaseUiActionParser" as AlgoBaseUiActionParser UI_LOGIC_COLOR
participant ":EditProblemUiActionParser" as EditProblemUiActionParser UI_LOGIC_COLOR
participant "d:EditProblemUiAction" as EditProblemUiAction UI_LOGIC_COLOR
participant ":UiActionResult" as UiActionResult UI_LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> UiLogicManager : execute(uiActionDetails)
activate UiLogicManager

UiLogicManager -> AlgoBaseUiActionParser : parseUiAction(uiActionDetails)
activate AlgoBaseUiActionParser

create EditProblemUiActionParser
AlgoBaseUiActionParser -> EditProblemUiActionParser
activate EditProblemUiActionParser

EditProblemUiActionParser --> AlgoBaseUiActionParser
deactivate EditProblemUiActionParser

AlgoBaseUiActionParser -> EditProblemUiActionParser : parse(uiActionDetails)
activate EditProblemUiActionParser

create EditProblemUiAction
EditProblemUiActionParser -> EditProblemUiAction
activate EditProblemUiAction

EditProblemUiAction --> EditProblemUiActionParser : d
deactivate EditProblemUiAction

EditProblemUiActionParser --> AlgoBaseUiActionParser : d
deactivate EditProblemUiActionParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditProblemUiActionParser -[hidden]-> AlgoBaseUiActionParser
destroy EditProblemUiActionParser

AlgoBaseUiActionParser --> UiLogicManager : d
deactivate AlgoBaseUiActionParser

UiLogicManager -> EditProblemUiAction : execute(model)
activate EditProblemUiAction

EditProblemUiAction -> Model : editProblem(Id.generateId("11b"))
activate Model

Model --> EditProblemUiAction
deactivate Model

create UiActionResult
EditProblemUiAction -> UiActionResult
activate UiActionResult

UiActionResult --> EditProblemUiAction
deactivate UiActionResult

EditProblemUiAction --> UiLogicManager : result
deactivate EditProblemUiAction

[<--UiLogicManager
deactivate UiLogicManager
@enduml
