@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class ExpenditureList
class Expenditure
class Name
class Budget
class DayNumber

Trip *-right-> ExpenditureList
ExpenditureList *-down-> "*" Expenditure

Expenditure *---> "1" Name
Expenditure *---> "1" Budget
Expenditure *---> "0...1" DayNumber
Expenditure *---> "1" boolean

@enduml
