@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI.expenditure <<Rectangle>> {
Class ExpensesListPage
Class ExpenditureCard
Class DailyExpenditurePage
Class DailyExpendituresPanel {
    lineTextLabel : Label
}
Class EditExpenditurePage
Class "{abstract}\nExpensesPage" as ExpensesPage

}


package UI <<Rectangle>> {
    Class MainWindow
}

package Ui.template <<Rectangle>> {
    Class "{abstract}\nPageWithSidebar" as PageWithSidebar
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> MainWindow
MainWindow *--> ExpensesPage

ExpensesListPage -up-|> ExpensesPage
DailyExpenditurePage -up-|> ExpensesPage
ExpensesListPage *--> EditExpenditurePage
DailyExpenditurePage *--> EditExpenditurePage
ExpensesPage -up-> HiddenModel
ExpensesPage -up-> HiddenLogic

ExpensesListPage *--> "*" ExpenditureCard

DailyExpendituresPanel *--> "*" ExpenditureCard

DailyExpenditurePage *--> "*" DailyExpendituresPanel

ExpensesPage -|> PageWithSidebar
@enduml
