@startuml
!include ../style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package ModelHistory{
    package PastChanges {}
    package FutureChanges {}
}

@end
