@startuml
start
:User executes addfood command;

if () then ([food info is all correct])
    :Update UI of food recommendations;
    :Save new food list into Storage;
else ([else])
endif
stop
@enduml
