@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

note "Since parsers are omitted,\nthe translation from user\ninputs to Flag is not shown." as N1

class ModelManager as "__:ModelManager__"
class FoodTypeIsWantedPredicate as "__:FoodTypeIsWantedPredicate__" {
    foodTypes = {FoodType.PROTEIN}
}
class FoodNameContainsKeywordsPredicate as "__:FoodNameContainsKeywordsPredicate__" {
    keyWords = {"Cherry"}
}
class FilteredList as "__filteredFoodList:FilteredList__" {
    source = foodList.getUnmodifiableObservableList
}
class UniqueFoodList as "__foodList:UniqueFoodList__"
class Predicate as "__:Predicate__"
class FoodComparator as "__:FoodComparator__" {
    sortOrderString = "gi"
}


FilteredList "1" -l-o ModelManager: < updates
(ModelManager, FilteredList) .. Predicate
ModelManager o--right "1" UniqueFoodList: sorts >
(ModelManager, UniqueFoodList) .. FoodComparator
Predicate ^-- FoodTypeIsWantedPredicate
Predicate ^-- FoodNameContainsKeywordsPredicate

show FilteredList fields
show FoodComparator fields
show FoodNameContainsKeywordsPredicate fields
show FoodTypeIsWantedPredicate fields
@enduml
