== Advanced Patient Features
====
*Advanced Patient Features*

On top of managing your patient data, you may need to assign other items to patients e.g. medical conditions or medication prescriptions. This section pertains to that.
====

=== Adding a Medical Condition to a Patient `patient add medcon`

You can add a medical condition to a patient using `patient add medcon`.

Format `patient add medcon i/PATIENT_INDEX m/MEDCON_INDEX`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* MEDCON_INDEX refers to the index of a medical condition (obtained using `medcon list` or `medcon find`).
* If the medical condition can be found in the patient's list of medical conditions, then it will not be added.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient add medcon i/1 m/2` +
Adds the medical condition at index no. 2 (in the list of medical conditions) to the patient that was assigned index no. 1 in the list of patients

=== Removing a Medical Condition from a Patient `patient rm medcon`

You can remove a medical condition from a patient using `patient rm medcon`.

Format: `patient rm medcon i/PATIENT_INDEX m/MEDCON_INDEX`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* MEDCON_INDEX refers to the index of a medical condition (obtained using `medcon list` or `medcon find`).
* If the medical condition can be found in the patient's list of medical conditions, then it will be removed.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient rm medcon i/1 m/2` +
Removes the medical condition at of index no. 2 (in the list of medical conditions) from the patient that was assigned index no. 1 in the list of patients

=== Adding a Prescription to a Patient `patient add presc`

You can add a prescription to a patient using `patient add presc`.

You can view the list of prescriptions you have added to a patient using `patient view`.

Format `patient add presc i/PATIENT_INDEX m/MED_INDEX d/DOSAGE`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* MED_INDEX refers to the index of a medicine (obtained using `med list` or `med find`).
* If the prescription can be found in the patient's list of prescriptions, then it will not be added.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient add presc i/1 m/2 d/20mg 3 times a day` +
Adds prescription of the medicine of index 2 (in the list of medicines) with a dosage of 20mg 3 times a day to the patient at index 1 in list of patients.

=== Editing a Patient's Prescription `patient edit presc`

You can edit a patient's prescription using `patient add presc`.

You can view a patient's list of prescriptions using `patient view`.

Format `patient edit presc i/PATIENT_INDEX pr/PRESCRIPTION_INDEX [m/MED_INDEX] [d/DOSAGE]`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* MED_INDEX refers to the index of a medicine (obtained using `med list` or `med find`).
* The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to input values.
****

Examples:

* `patient edit presc i/1 pr/3 d/10mg 2 times a day` +
Edits the prescription with index 3 of the patient at index 1 in list of patients, changing the dosage to "10mg 2 times a day"

=== Removing an Prescription from a Patient `patient rm presc`

You can remove a prescription to a patient using `patient rm presc`.

You can view the list of prescriptions of a patient using `patient view`.

Format `patient rm presc i/PATIENT_INDEX pr/PRESCRIPTION_INDEX`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* PRESCRIPTION_INDEX refers to the index of a prescription (obtained using `patient view`).
* If the prescription can be found in the patient's list of prescriptions, then it will be removed.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient rm presc i/1 pr/2` +
Removes the 2nd prescription of the patient of index 1.

=== Adding an Appointment to a Patient `patient add appt` [INCOMPLETE UG]
//Can be based off adding & removing of prescriptions
=== Removing an Appointment from a Patient `patient rm appt` [INCOMPLETE UG]
//Can be based off adding & removing of prescriptions

=== Assigning a Todo Template to a Patient `patient set todoform` [INCOMPLETE UG]
//Can be based off adding & removing of medcon, but this is setting because a patient can only have 0..1 todo templates
=== Unassigning a Todo Template from a Patient `patient unset todoform` [INCOMPLETE UG]
//Can be based off adding & removing of medcon, but this is unsetting because a patient can only have 0..1 todo templates

=== Adding an extra Todo to a Patient `patient add todo`

You can add an extra todo item to the patient's visit todo list using `patient add todo`. This extra todo item will be added to the patient's list of extra todos.

For more information on the differences between a patient's todo list template and extra todos, Refer to <<Visits>> for more elaboration.

Format: `patient add todo i/PATIENT_INDEX t/TODO`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient add todo t/Check fridge for spoiled items` +
Adds a todo item "Check fridge for spoiled items" to the extra todo items list.

=== Removing an extra Todo from a Patient `patient rm todo`

You can remove an extra todo item from the patient's visit todo list using `patient rm todo`.

Format: `patient rm todo i/PATIENT_INDEX t/TODO_INDEX`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* TODO_INDEX refers to the index of a todo item (obtained using `patient view`).
* If the todo item can be found in the patient's list of todo items, then it will be removed.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient rm todo i/1 t/2` +
Removes the 2nd todo item of the patient of index 1.

=== Adding a note to a Patient `patient add note`

You can add a note to the patient's list of notes using `patient add note`.

These notes are for you to take general notes on a patient. If you want to take notes on a specific visit / while you are visiting the patient, you will want to make an appointment with `patient add appt`, begin the appointment using `appt begin` and add details to the visit.

Format: `patient add note i/PATIENT_INDEX t/NOTE`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient add note t/Check fridge for spoiled items` +
Adds a todo item "Check fridge for spoiled items" to the notes list.

=== Removing a note from a Patient `patient rm note`

You can remove a note from the patient's list of notes using `patient rm note`.

Format: `patient rm note i/PATIENT_INDEX t/NOTE_INDEX`

****
* PATIENT_INDEX refers to the index of a patient (obtained using `patient list` or `patient find`).
* NOTE_INDEX refers to the index of a note (obtained using `patient view`).
* If the note can be found in the patient's list of notes, then it will be removed.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `patient rm note i/1 t/2` +
Removes the 2nd note of the patient of index 1.
