[[Visits]]
== Visit Management
====
*Visit Management*

As a community nurse, you will often make home visits to your patients. When you are visiting a patient, there is often a todo list that you will have to do as well as information that you will have to record. You can use the application to mark the items you have done in a visit and add further details and notes about a visit (e.g. about a patient's symptoms). This section describes the features that will allow you to keep track of what you have to do during a visit and manage previous visits.

====

=== Mark a Todo Item of current Visit as done: `visit now todo done`[INCOMPLETE UG]
//By index

=== Updating the current Visit: `visit now add note`

=== Finishing a Visit: `visit finish`

If you have just finished your home visit to a patient, you can mark the visit as finished using `visit finish`.

Format: `visit finish`.

=== How to Listing All Visits
You can see a list of all visits in the app by typing `visit list`.

In the list displayed, each visit will have an *index* number which can then be used for other features that require you to select a visit by *index* e.g. `visit delete`. Take note that a visit will be given the same *index* regardless of other display commands such as `visit find`.

Format: `visit list`

=== Finding Visit(s): `visit find`

You can find visits that fit the parameters given using `visit find`.

In the list displayed, each visit will have an *index* number which can then be used for other features that require you to select a visit by *index* e.g. `visit delete`. Take note that a visit will be given the same *index* regardless of other display commands such as `visit list` or if different parameters are used.


Format: `visit find [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* If the parameter is text (e.g. `n/NAME`), partial words will be matched (e.g. `n/John` will return `John Smith` and `John Kim`.
****

Examples:

* `visit find n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague` +
Finds all visits with this patient

=== Viewing a Visit: `visit view`

You can see a visit's full details using `visit view`. The visit is selected by their *index*.

Format: `visit view INDEX`

****
* View the visit at the specified `INDEX`.
* The index refers to the index number shown in the list of visits displayed by `visit list` or `visit find`.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `visit list` +
`visit view 1`
View the item with index number 1. This index can be found from the full list of visits.

* `visit view 2`
View the item with the index number 2.

=== Viewing the current Visit: `visit now`

If you are currently visiting a patient, you can see the current visit's full details using `visit now`.

Format: `visit now`
