== Todo Templates [Parameters not updated]
====
*Todo Templates*

As a community nurse, you will often use a todo list to keep track of things that you have (and have not) done during a visit. It is tedious, however, to add multiple things to do / take note of for every patient; in fact, there may be many duplicated items.

To simplify the process, you can create a reusable checklist that you can then assign to your patients. We call this reusable checklist a "todo template" This section describes the features that will allow you to streamline the management of todo templates of your patients.
====

=== Listing All Todo Templates: `todoform list`
You can see a list of all todo templates in the app by typing `todoform list`.

In the list displayed, each todo template will have an *index* number which can then be used for other features that require you to select a todo template by *index* e.g. `todoform delete`. Take note that a todo template will be given the same *index* regardless of other display commands such as `todoform find`.

Format: `todoform list`

=== Finding Todo Template(s): `todoform find`

You can find todo templates that fit the parameters given using `todoform find`.

In the list displayed, each todo template will have an *index* number which can then be used for other features that require you to select a todo template by *index* e.g. `todoform delete`. Take note that a todo template will be given the same *index* regardless of other display commands such as `todoform list` or if different parameters are used.


Format: `todoform find [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]` e.g. `todoform find n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* If the parameter is text (e.g. `n/NAME`), partial words will be matched (e.g. `n/John` will return `John Smith` and `John Kim`.
****

Examples:


* Returns `john` and `John Doe`

=== Viewing a Todo Template: `todoform view`

You can see a todo template's full details using `todoform view`. The todo template is selected by their *index*.

Format: `todoform view INDEX`

****
* View the todo template at the specified `INDEX`.
* The index refers to the index number shown in the list of todo templates displayed by `todoform list` or `todoform find`.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `todoform list` +
`todoform view 1`
View the item with index number 1. This index can be found from the full list of todo templates.

* `todoform view 2`
View the item with the index number 2.

=== Adding a Todo Template: `todoform add`

You can add a todo template to the list of all templates by using `todoform add`.

Format: `todoform add pn/PRESCRIPTION_NAME pi/PRESCRIPTION_IC p/PHONE_NUMBER a/ADDRESS [e/EMAIL] [t/TAG]…​ [kn/NOK_NAME] [kp/NOK_PHONE_NUMBER] [ka/NOK_ADDRESS] [ke/NOK_EMAIL] [imp/PRIORITY]`

****
 * a todo template can have any number of tags.
 * a todo template can have next-of-kin contact details.
 * Every todo template is uniquely identified by their IC.
 * Priority can take values from 0 to 10.
****

Examples:

 * `todoform add n/John Doe pi/S7012255C p/98765432 a/John street, block 123, #01-01`

 * `todoform add n/Choong Siew Hwang pi/S7015376D p/91239876 a/22 College Avenue East; Singapore 138608 e/cho0ng@email.com t/Big kn/Choong Tee Ling kp/85639274 ka/10 Buangkok View, Singapore 534194 ke/ch1ng@email.com`

 * `todoform add n/Betsy Crowe pi/S0011239X t/friend e/betsycrowe@example.com a/Newgate Prison p/12345678 t/criminal imp/4`

=== Editing a Todo Template: `todoform edit`

You can edit an existing todo template in the app using `todoform edit`.

Format: `todoform edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]...`

****
* Edits the person at the specified `INDEX`.
* The index refers to the index number shown in the list of todo templates displayed by `todoform list` or `todoform find`.
* The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the person will be removed i.e adding of tags is not cumulative.
* You can remove all the person's tags by typing `t/` without specifying any tags after it.
****

Examples:

* `todoform list` +
 `edit 1 p/91234567 e/johndoe@example.com` +
Edits the phone number and email address of the 1st person in the entire todo template's list to be `91234567` and `johndoe@example.com` respectively.


* `edit 2 n/Betsy Crower t/` +
Edits the name of the 2nd person with the index 1.`Betsy Crower` and clears all existing tags.


// tag::delete[]
=== Deleting a Todo Template: `todoform delete`

You can delete a todo template by *index* using `todoform delete`.

Format: `todoform delete INDEX`

****
* Deletes the todo template at the specified `INDEX`.
* The index refers to the index number shown in the list of todo templates displayed by `todoform list` or `todoform find`.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `todoform list` +
`todoform delete 2` +
Deletes the 2nd todo template in the todo template list.

* `todoform delete 1` +
Deletes the todo template which had been assigned the index 1.

// end::delete[]

=== Deleting multiple Todo Templates: `todoform delete` `[coming in V2.0]`

You can delete a todo template by *indexes* using `todoform delete`.

Format: `todoform delete INDEX_1 [INDEX_2] [INDEX_3]...`

****
* Deletes the todo template at the specified `INDEX` es. You can put in as many indexes to delete as many todo templates as you wish.
* The index refers to the index number shown in the list of todo templates displayed by `todoform list` or `todoform find`.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `todoform list` +
`todoform delete 2` +
Deletes the 2nd todo template in the todo template list.

* `todoform delete 1 2` +
Deletes the and 2nd todo templates with which had been assigned the 1.command.

== Autocomplete
====
*Autocomplete*

As a community nurse, you will be performing several commands through the Command Line Interface (CLI). In order to speed up the process, the application includes an autocomplete feature that allows you to more quickly and conveniently input your commands and parameters. This section describes the feature in further detail.
====
