==== Overview Of Implementation
The auto-complete mechanism extends NurseTraverse with 3 functionalities +

- Completing word in command box
- Suggesting of words that are compatible with previous sub-commands
- Guide for user to select from the various sub-commands +

Given below is an example usage scenario

Step 1:
When the user launches the application, an instance of the object, command and prefix autocomplete word list will be initialised in `AutoCompleteStorage`, which implements the following operations:

* `AutoCompleteWordStorage#getOListAllCommandWord()` — returns the observable list of command words stored
* `AutoCompleteWordStorage#getOListAllPrefixWord()` — returns the observable list of prefix words stored
* `AutoCompleteWordStorage#getOListAllObjectWord()` — returns the observable list of object words stored
* `AutoCompleteWordStorage#generateOListAllIndexWord(String objectName)` — generate an observable list of index words corresponding to previous object word when called

The auto-complete panel will be set to object list when user first start the application.

Step 2: Whenever user types a key in the command line, `CommandBox` will notify `AutoCompletePanel` to perform changes based on userinput

This will update the number of matched words with the current list and 3 sets of algorithms will be run +

- `AutoCompletePanel#resetList()` -> switch the current list based on what is typed.

- `AutoCompleteListFilter#filterList()` -> filter the chosen list to only words that are compatible with previous correctly typed full words. Eg: prefix list will be filtered to only be compatible with “pat-add” user command, the words that come before prefix.

- `AutoCompleteListUpdater#updateSuggestedWordsInList()` -> update the chosen list which was filtered to fit the key that is partially typed. Eg: User typed “ad”. “add” and “add-medcon” which are both in the current list will be suggested.

The following sequence diagram illustrates what happens when user inputs a letter into the command box: +
-sample-

==== Design Considerations
===== Aspect: Method to suggest auto-complete words

* **Alternative 1:** Have several lists. First word list, Second word list, etc
** Pros: Minimal effort in parsing of command line input.
** Cons: Auto-complete panel will be unorganised. Eg: both index 1 and prefix may be suggested instead of just all index or all prefix suggested.

* **Alternative 2:** Suggest full commands such as pat-edit 2 n/ t/ .. and omit any list
** Pros: Easy to implement. No parsing required.
** Cons: Auto-complete panel will be chunky as all commands are suggested at the same time. User will not be guided in selecting which command to choose.

* **Alternative 3(current choice):** Have several lists. Object/Command/Index/Prefix lists.
** Pros: User will be guided. Very user friendly. Panel will be more organised as words are suggested in sets of the same type.
** Cons: Parsing of command line input can be tedious.

==== Logic Design Considerations

==== UI Design Considerations
