This set of functionality consists of one GUI component and two commands,
each of which rely on the same core components:

1. `HistoryPane` - GUI component that displays a numbered list of previous
data-modifying commands that can be reverted by `app-undo`.
2. `app-undo` - Command that reverts until a specified data-modifying command
in the history, or the previous data-modifying command if no argument is specified.
3. `app-redo` - Command that reverts the previous command if and only if it was an `app-undo`.

==== Implementation Overview

For undo/redo/history to function, there must be the following:

* A way to mark which `Command` s are data-modifying commands so that
non-data-modifying commands can be ignored.
* A mechanism to clearly demarcate the model state before and after the execution
of each data-modifying command.
* A way to record the state of the model before (or after) each command, together
with the `Command` object responsible.
* Methods to switch the state of the model back and forth from the states stored
in the history.

To achieve this, the following classes are introduced:

* `MutatorCommand` - An empty subclass of `Command` to indicate that a `Command` is a
data-modifying command and should be considered for undo/redo/history.
* `HistoryRecord` - Record of the command and data of one atomic commit in the command history. It consists of the
`MutatorCommand` responsible for the commit and the state of the model either before or after the commit. All recorded
states are deep copies decoupled from their original references.
* `HistoryManager` - Represents the history of the application. Maintains data structures containing `HistoryRecord` s
of each data state change.

Additionally, `LogicManager` and `Model` are modified to accommodate this functionality.

==== Model

The following methods are added to the `Model` interface:

* `Model#commit(MutatorCommand)` - Commits the changes made to the address book since the last call to this method,
making them permanent and updating the UI data. The committing `MutatorCommand` is stored for history record purposes.
* `Model#getHistory()` - Returns an unmodifiable view of the history.
* `Model#undoTo(HistoryRecord)` - Reverts current model state to the that contained in the specified `HistoryRecord`
(i.e. the state before the command was executed).
* `Model#redo()` - Redoes the previous `MutatorCommand` if it was an undo.

==== Model Design Considerations

===== Aspect: How to record the PatientBook and AppointmentBook states in the history

* Alternative 1: Simply store references to `PatientBook` and `AppointmentBook`.
** Pros: Easier to implement.
** Cons: Relies on the assumption that the objects in `PatientBook` and `AddressBook`
are immutable; if they are not truly immutable, changes to the current model's
`PatientBook` and `AddressBook` state may leak and affect the states stored in
the history.

* **Alternative 2 (current choice):** Defensively store deep copies of the `PatientBook` and `AppointmentBook`.
** Pros: Prevents improperly coded `Patient` or `Appointment` (or their
associated classes) from breaking undo/redo/history functionality. Can reuse
JSON serialization code for persistent storage of `PatientBook` and `AppointmentBook`
to perform deep copies by serializing then immediately deserializing them.
** Cons: Consumes more memory and CPU time. More difficult to implement as
MVC pattern between UI view and models is broken in two, due to the
`ObservableList` observed by the UI being part of `ModelManager` as `ModelManager`
has to modify the `ObservableList` each time the the current state is swapped with
a state in the history.

===== Aspect: Which class to place the HistoryManager in

* **Alternative 1 (current choice):** Make `HistoryManager` a field of `ModelManager`.
** Pros: Ensures atomicity of the records in the history as pushing a transaction
to the `HistoryManager` can only be (and is always) done by `Model#commit()`
itself - records in the history are guaranteed to be products of complete command
execution rather than intermediate states.
** Cons: More difficult to test `ModelManager` as two `ModelManager` objects may have
the same current state but differing `HistoryManager` objects. May violate Single
Responsibility Principle as `ModelManager` now has to manage both its current
state and its previous states.

* Alternative 2: Make `HistoryManager` a field of `LogicManager`.
** Pros: Higher cohesion as `ModelManager` only represents the model's current state.
Easier to test `ModelManager` as only its current state matters.
** Cons: It is possible for intermediate model states to be pushed to the `HistoryManager` -
trusts `LogicManager` to push the transaction to history after (and only
after) calling `Model#commit()`. Requires `Command#execute()` to accept
`HistoryManager` as a parameter just so `UndoCommand` and `RedoCommand` can
work even though the vast majority of commands do not require it.

==== UI

The command history is constantly displayed in a panel on the right side of
the app. This `HistoryPanel` uses `HistoryRecordCard` s to display the
user-input text that invoked each command.

==== UI Design Considerations

===== Aspect: Where to display the history

* **Alternative 1 (current choice):** Permanently display it in a dedicated panel.
** Pros: User does not have to execute a 'history' command to view the history,
making it much easier to use the multiple undo function.
** Cons: Takes up more space in the UI.

* Alternative 2: Display it as a tab in the `TabPane`.
** Pros: Saves space in the UI.
** Cons: User has to switch to the history tab to view it. Less intuitive
UX as the other tabs in the `TabPane` all display actual data such as
`Patient`, `Visit`, and `Appointment` info, whereas history is app metadata.
