This set of functionality consists of one GUI component and two commands,
each of which rely on the same core components:

1. `HistoryPane` - GUI component that displays a numbered list of previous
data-modifying commands that can be reverted by `undo`.
2. `app-undo` - Command that reverts until a specified data-modifying command
in the `history`, or the previous data-modifying command if no argument is specified.
3. `app-redo` - Command that Reverts the previous command if and only if it was an `undo`.

==== Implementation Overview

For undo/redo/history to function, there must be the following:

* A way to mark which `Command` s are data-modifying commands.
* A mechanism to clearly demarcate the model state before and after the execution
of each data-modifying command.
* A way to record the state of the model before (or after) each command, together
with the `Command` object responsible.
* Methods to switch the state of the model back and forth from the states stored
in the history.

To achieve this, the following classes are introduced:

* `MutatorCommand` - An empty subclass of `Command` to indicate that a `Command` is a
data-modifying command and should be considered for undo/redo/history.
* `HistoryRecord` - Record of the command and data of one atomic commit in the command history. It consists of the
`MutatorCommand` responsible for the commit and the state of the model before (or after) the commit. All recorded
states are deep copies decoupled from their original references.
* `HistoryManager` - Represents the history of the application. Maintains data structures containing `HistoryRecord` s
of each data state change.

Additionally, `LogicManager` and `Model` are modified to accommodate this functionality.

==== Model

The following methods are added to the `Model` interface:

* `Model#commit(MutatorCommand)` - Commits the changes made to the address book since the last call to this method,
making them permanent and updating the UI data. The committing `MutatorCommand` is stored for history record purposes.
* `Model#getHistory()` - Returns an unmodifiable view of the history.
* `Model#undoTo(HistoryRecord)` - Reverts current model state to the that contained in the specified `HistoryRecord`
(i.e. the state before the command was executed).
* `Model#redo()` - Redoes the previous `MutatorCommand` if it was an undo.
