@startuml
!include ../style2.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
    Interface Model <<interface>>
    Interface UserPrefsModel <<interface>>
    Interface HistoryModel <<interface>>
    Interface FinanceTrackerModel <<interface>>
    Interface CcaTrackerModel <<interface>>
    Interface PlannerModel <<interface>>
    Interface CoursePlannerModel <<interface>>
    Class ModelManager
}

ModelManager .up.|> Model
Model -up-|> UserPrefsModel
Model -up-|> HistoryModel
Model -up-|> FinanceTrackerModel
Model -up-|> CcaTrackerModel
Model -up-|> PlannerModel
Model -up-|> CoursePlannerModel
@enduml
