= SugarMummy - User Guide
:site-section: UserGuide
:toc:
:toclevels: 5
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103-T16-1/main

By: `Team CS2103-T16-1`      Since: `September 2019`      Licence: `MIT`

== Introduction
Do you feel it difficult to keep the right diets for type II diabetes? Do you want to manage your hectic schedule? Do you want to have a better overview of your health data? Do you want to move to a healthier lifestyle? If your answer is yes, then SugarMummy is perfect  for you! SugarMummy is a lifestyle tracker and planner that aims to combat Type II diabetes by encouraging users to keep a healthy lifestyle. Moreover, being a computer app with Command Line Interface, SugarMummy is optimized for fast typers who has access to a computer most of the time.

Hope following features will benefit you and enjoy!

✔ Data tracker for various data types (blood sugar levels,  diets,
exercise, clinic appointments, medical finance and so on!)

✔ Easy-to-use reminder and calendar

✔ Personalized user experience and bio encouragements

✔ Weekly and Monthly summary for your activities and health level

✔ Customized recommendations for food and fun quizzes about
healthy dieting

Interested? Jump to the <<Quick Start>> to get started. Enjoy!

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `SugarMummy.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your Address Book.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== DATA LOG

==== Add a data entry to the diabetes tracker app: `add`

Format: `add r/RECORD_TYPE v/VALUE t/TIME [t/TIME_END]`

==== Show a list of all data entries in the diabetes tracker app: `list`

Format: `list [r/RECORD_TYPE] ...`

If a specific RECORD_TYPE is provided, it will list the data entries that are of RECORD_TYPE. If more than 1 RECORD_TYPE is provided, it will list all data entries of the requested types. Otherwise, it lists all types of recent data entries.

==== Edit an existing entry in the diabetes tracker app: `edit`

Format: `edit INDEX [v/VALUE] [t/TIME] [t/TIME_END]`

Edits the entry at the specified INDEX. The index refers to the index number shown in the displayed entries list. The index must be a positive integer. At least one of the optional fields must be provided. Existing values will be updated to the input values.

==== Deletes a specified data entry from the diabetes tracker app: `delete`

Format: `delete INDEX`

Index must be a positive integer

The index refers to the index number shown in the displayed entries list

=== CALENDAR AND REMINDER

==== Add a reminder: `reminder`

Format: `reminder DESCRIPTION t/TIME [t/TIME]... [rp/repetition] [v/venue] [p/people]`

Add a reminder at a specific time with possible detail information of other time, repetition, venue(e.g. hospital) ,people(e.g. doctor) and sound.

==== Add an event: `event`

Format: `event TITLE [DESCRIPTION] t/TIME [t/END_TIME] [tp/TIME_PERIOD]  [v/venue] [p/people]`

Add an event with starting time and optional ending time. Set a reminder some time before the event with possible detail information of venue(e.g. hospital) ,people(e.g. doctor) and sound.

==== Add a task: `task`

Format: `task TITLE [DESCRIPTION] t/TIME [t/END_TIME] [tp/TIME_PERIOD] [tg/TARGET]`

Add a task with starting time and optional ending time. Set a reminder some time before the task begins and a target for the task.

==== Snooze reminder: `snooze`

Format: `snooze [tp/TIME_PERIOD]`

Silence the current reminder and activate it after a time period.

==== Complete a task: `complete`

Format: `complete [INDEX]... [t/TIME]`

Mark all the reminders before now as completed if no argument provided. Otherwise, mark only those tasks with indices provided or before the specific time as completed.

==== Set time zone: `timezone`

Format: `timezone tz/TIME_ZONE [t/TIME] [t/TIME_END]`

Set the time zone of the application permanently or in any time interval(e.g. For travelling).

==== Search for entries in calendar: `search`

Format: `search [KEYWORD] [t/TIME] [t/END_TIME] [tp/TYPE] [v/VENUE] [p/PEOPLE]`

Search for all entries by providing keyword, time interval, type, venue or people.

==== Delete an entry in calendar `[coming in v2.0]`

Delete an event that you do not want to keep track anymore.

=== PERSONALISED USER EXPERIENCE

==== Show a list of all achievements the user has attained: `achievement`

Format: `achievement`

Display the current ranking of the user (i.e. Bronze III, Bronze II, Bronze I, Silver III, Silver II, Silver I, Gold...Platinum...Diamond) followed by milestone achievements acquired by the user.

==== Shows a page displaying the user profile of the user: `bio`

Format: `bio`

Display a page containing user information such as the user’s profile picture, name, nric, gender, date of birth, contact number, address and other biography information that the user would like to include. Includes an icon used to represent the user based on his/ her BMI.

==== Adds a biography for the user using specified fields: `addbio`

Format: `addbio n/NAME [nric/NRIC] [g/GENDER] [dob/DATE_OF_BIRTH] p/CONTACT_NUMBER e/EMERGENCY_CONTACT m/MEDICAL_CONDITION [a/ADDRESS] [dp/PROFILE_PICTURE_PATH] [o/OTHERS]`

Profile picture of the user is set using a given file path. If the file that is given is invalid, the user is shown an error message. Name, contact number, emergency contact number and medical condition are compulsory fields. (if a user of this app happens to have no medical condition, he / she may input NIL)

==== Delete biography `[coming in v2.0]`

==== Edit a biography for the user using specified fields: `editbio`

Format: `editbio [n/NAME] [nric/NRIC] [g/GENDER] [dob/DATE_OF_BIRTH] [p/CONTACT_NUMBER] [e/EMERGENCY_CONTACT] [m/MEDICAL_CONDITION] [a/ADDRESS] [dp/PROFILE_PICTURE_PATH] [o/OTHERS]`

Profile picture of the user is set using a given file path. If the file that is given is invalid, the user is shown an error message. If no parameters are set, the program displays a message suggesting the user to set biography information using the specified fields.

==== Sets the background picture using a specified file path: `bg`

Format: `bg p/PATH`

If the file that is given is invalid, the user is shown an error message.

==== Sets the font color of the text: `fontcolor`

Format: `fontcolor c/COLOUR`

Sets the font to a colour specified by the user (eg. yellow, blue 00FF00)

==== Displays the daily motivation message of the day: `dailymsg`

Format: `dailymsg`

==== Personalized avatar `[coming in v2.0]`

User can customize his or her own avatar and the avatar will have body shapes according to user BMI.
This helps to motivate them to have a healthy BMI.

=== DATA ANALYSIS

==== Display the daily/weekly/monthly average in a graph: `average`

Format: `average a/AVERAGE_TYPE r/Record_TYPE [n/COUNT]`

AVERAGE_TYPE is either day/week/month. Displays a graph of the AVERAGE_TYPE average value of a particular RECORD_TYPE. COUNT is an integer value. If COUNT is given, show only the latest COUNT number of average values. Else, show only latest 3 average values.

==== Display interesting statistics: `summary`

Examples of statistics: minimum, maximum, average, number of dangerously high blood sugar level, weekly quiz points etc in suitable graph

Format: `summary r/RECORD_TYPE [d/START_DATE]`

If START_DATE is given, statistics from START_DATE to the current date will be retrieved. Else, statistics will be based on all data.

==== Export summary of all medical records into pdf: `export`

Format: `export [d/START_DATE]`

If START_DATE is given, summary from START_DATE to the current date will be exported. Else, summary of all data will be exported.

=== Autocomplete Command

SugarMummy will recommend list of possible commands that can be add on to user current input.

=== EDUCATION AND QUIZ

==== Recommending food: `recmf`

Recommends a list of medically suggested foods for type II diabetes
patients. The user can specify flags:

`-b`: breakfast recommendations

`-l`: lunch recommendations

`-d`: dinner recommendations

`-f`: fruit recommendations

`-v`: vegetable recommendations

With specified one or more FOOD_ITEM, the user will only view recommendations match at least one item. However, if any food item is considered dangerous for type II diabetes patients, a warning will be shown. (case-insensitive)

Format: `recmf [-b] [-l] [-d] [-f] [-v] [FOOD]...`

Examples:

`recm -b strawberries`

`recm -b -l -d`

==== Recommending exercise: `recme`

Format: `recme`

==== Adding new food items : `put`

Adds a new food time into certain category. Calorie and glycemic can
be attached followed by -i flag. Otherwise, another prompt will be
shown to ask for these two values.

Format: `put FOOD[, FOOD]...[-i CALORIE GI] in CATEGORY`

Example:

`put guava -i 68 20, green apple -i 52 38 in fruits`

`put guava in fruits`

==== Disliking certain foods: `dislike`

Dislikes certain foods so that those foods will no longer be shown on
the recommendations. (case-insensitive)

Format: `dislike FOOD[, FOOD]...`

Example: `dislike watermelon, chicken`

==== Playing flash cards: `game`

Shows an interactive page for user to play the flash card game. The
user will win certain points if answering a question correctly.

Format: `game`

During the game session, the user is able to:

. Selecting the correct answer: `<alphabet>`

* Answers the multiple-choice question. If the answer is correct,
the user will be awarded a few points. If the answer is wrong,
multiple, or not within the choice range, a few points will be deducted and the correct answer will be revealed.

* Format: `<alphabet>`


. Skipping a certain question: `skip`

* Skips a certain question and moves to the next question.

* Format: `skip`


. Exiting the game: `exit`

* Exits the game and go back to normal page
* Format: `exit`

=== Clearing all entries: `[coming in v2.0]`

Clears all entries in SugarMummy.

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

SugarMummy data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

=== Encrypting data files `[coming in v2.0]`

Users cannot retrieve data by opening data files directly.

=== Detailed workout schedule `[coming in v2.0]`

User can enter details of a workout schedule. +
For example: Do exercise A for 10 minutes then switch to exercise B for 5 minutes.

=== Workout timer `[coming in v2.0]`

Displays workout instructions and a timer on screen.
Screen instruction changes when the time for that particular exercise is up.
Time required for each exercise is dictated by stored workout schedule.

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *achievement* `achievement`
* *add* `add r/RECORD_TYPE v/VALUE t/TIME [t/TIME_END]` +
e.g `add r/bloodsugar v/10 t/now`
* *addbio* `addbio n/NAME [nric/NRIC] [g/GENDER] [dob/DATE_OF_BIRTH] p/CONTACT_NUMBER e/EMERGENCY_CONTACT m/MEDICAL_CONDITION [a/ADDRESS] [dp/PROFILE_PICTURE_PATH] [o/OTHERS]` +
e.g. `addbio n/Bob p/98765432 e/91234567 m/Type II Diabetes`
* *average* `average a/AVERAGE_TYPE r/Record_TYPE [n/COUNT]` +
e.g. `average a/weekly r/bloodsugar n/3`
* *bio* `bio`
* *bg* `bg p/PATH` +
e.g. `bg p//Users/Bob/Pictures/bg.jpg`
* *complete* `complete [INDEX]... [t/TIME]` +
e.g. `complete t/today`
* *dailymsg* `dailymsg`
* *delete* `delete INDEX` +
e.g. `delete 2`
* *edit* `edit INDEX [v/VALUE] [t/TIME] [t/TIME_END]` +
e.g. `edit 1 v/15 t/now`
* *export* `export [d/START_DATE]` +
e.g `export d/01.09.2019`
* *event* `event TITLE [DESCRIPTION] t/TIME [t/END_TIME] [tp/TIME_PERIOD]  [v/venue] [p/people] [s/sound]`
* *editbio* `edit [n/NAME] [nric/NRIC] [g/GENDER] [dob/DATE_OF_BIRTH] [p/CONTACT_NUMBER] [e/EMERGENCY_CONTACT] [m/MEDICAL_CONDITION] [a/ADDRESS] [dp/PROFILE_PICTURE_PATH] [o/OTHERS]` +
e.g. `g/Male dp//Users/Bob/Pictures/dp.jpg` +
e.g. `dp/C:\\Users\\Bob\\Pictures\\dp.jpg`
* *fontcolor* `fontcolor c/COLOUR` +
e.g. `fontcolor yellow` +
e.g. `fontcolor 00FF00`
* *list* `list [r/RECORD_TYPE] ...` +
e.g. `list r/bloodsugar r/sleep r/food`
* *reminder* `reminder DESCRIPTION t/TIME [t/TIME]... [rp/repetition] [v/venue] [p/people] [s/sound]` +
e.g  `reminder insulin injection t/13:00 rp/daily`
* *search* `search [KEYWORD] [t/TIME] [t/END_TIME] [tp/TYPE] [v/VENUE] [p/PEOPLE]` +
e.g. `search tp/event v/NUH`
* *snooze* `snooze [tp/TIME_PERIOD]` +
e.g `snooze 30 min`
* *summary* `summary r/RECORD_TYPE [d/START_DATE]` +
e.g `summary r/bloodsugar d/01.09.2019`
* *task* `task TITLE [DESCRIPTION] t/TIME [t/END_TIME] [tp/TIME_PERIOD] [tg/TARGET]` +
e.g `task Running running for 40 minutes t/15:00 tp/10 min tg/200 calories`
* *timezone* `timezone tz/TIME_ZONE [t/TIME] [t/TIME_END]` +
e.g `timezone tz/GMT+8`
