= ModBuddy - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `AY1920S1-CS2103-F09-3`      Since: `Aug 2019`      Licence: `MIT`

== Introduction

ModBuddy is a module planning desktop application aimed towards *Computer Science (B.Comp) students* studying in the National University of Singapore (NUS). ModBuddy allows the student to build study plans by *facilitating module planning* across different semesters, such as by ensuring that the prerequisites of a module are met in previous semesters, and core modules are completed upon graduation. Interested? Jump to Section 2, <<Quick Start>> to get started! 

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `addressbook.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your Address Book.
.  Double-click the file to start the app. The GUI should appear in a few seconds. If it is your first time using the application, a default study plan will be loaded. 
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add NAME`, `NAME` is a parameter which can be used as `add John Doe`.
* Items in square brackets are optional e.g `NAME [TAG]` can be used as `John Doe friend` or as `John Doe`.
* Items with `…`​ after them can be used multiple times including zero times
====

=== Viewing help : `help`

Format: `help`

=== Command Line Interface

==== Assigning a module to a given semester: `addmodule`
Assigns the specified module to a given semester of the current study plan. +
Format:  `add SEMESTER MODULE ...` +
Examples:

* `add y1s1 CS1101s`
* `add y2s2 CS3244 CS3245 CS3233`
* `add y1s1 ue`
* `add y1s2 ue:GER1000`

==== Removing a module from a given semester. `remove`
Removes the specified module to a given semester of the current study plan. +
Format: `remove SEMESTER MODULE ...` +
Examples:

* `remove y1s1 CS1101S`
* `remove y2s2 CS3244`

==== Naming a UE from a semester. `nameue`
Names a UE from the given semester with the given module name. This feature is purely for aesthetic purposes and has no functional implications. + 
Format: `nameue SEMESTER NAME` +
Examples:

* `nameue y1s1 GER1000`

==== Moving a module from one semester to another. `move`
Moves a given module from a source semester to a destination semester, as specified. +
Format: `move MODULE SEMESTER_SRC SEMESTER_DEST` +
Examples:

* `move CS3243 y2s1 y2s2`

==== Setting the current semester. `setcurrent`
Sets the given semester as the current one. Semesters before the specified semester will be locked and therefore modules cannot be added or removed from them. +
Format: `setcurrent SEMESTER` +
Examples:

* `setcurrent y1s2`

==== Blocking off the given semester: `block`
Block off the given semester, for reasons such as exchange, LOA, etc. +
Format:  `block SEMESTER [REASON]`

==== Undo-ing the previous command: `undo`
Undo the previous command. The state of the application will revert back to that before the previous command. This command cannot undo itself. +
Format: `undo`

==== Redo-ing the previous undone command: `redo`
Redo the previous undone command. The state of the application will revert back to that before the undo. This command cannot redo itself. +
Format:  `redo`

==== Declaring a focus area: `declarefocusarea`
Declares the given focus area as one of the focus areas of the study plan. This means that the requirements of the focus area has to be met to be eligible for graduation. +
Format: `declarefocusarea FOCUS_AREA`

==== Chaining commands
Chain commands together for greater efficiency. The commands, if different, are separated by a ‘&&’. ‘&&’ is not needed if the command is the same. +
Format: `COMMAND_1 && COMMAND_2 && …` +
Examples: 

* `addmodule y1s1 CS1101S CS1231 MA1521`
* `movemodule CS2105 y2s1 y2s2 && addmodule CS2106 y2s2`

== FAQ

== Command Summary
