= Budget Buddy - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W13-4/main
:jarName: budgetbuddy.jar

By: `CS2103T W13-4`

== Introduction

Budget Buddy is an all-in-one expense tracking application for computing students who prefer to use a desktop app
to manage their expenses. More importantly, Budget Buddy is *optimized for those who prefer to work with a Command
Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).
If you type fast, Budget Buddy can get your expense management tasks done faster than traditional GUI apps.
Furthermore, Budget Buddy allows computing students to add their own functions through customized JavaScript files,
as well as a set of rules to simplify expense tracking through automation.

This user guide provides in-depth documentation of the current as well as upcoming features, including the setup
process, as well as some commonly asked questions. For the hands-on person, check out the _Quick Start_ section right
below.

== Quick Start

_Ensure that Java 11 is installed on your system._

Download the latest version of Budget Buddy link:{repoURL}/releases[here].

Place the _{jarName}_ file in your desired home folder. This folder will contain all data saved into Budget Buddy.

Double click the _{jarName}_ file to launch Budget Buddy.

====
*Launching for the first time*

* A default account will created.
* Type `txn dn/out x/100 d/This is my first transaction!` to add a new spending.
* To view your accounts, type `account list`
* To view available commands, type `help`
====

If the application does not run, follow the instructions below based on your operating system:

* Mac/Linux:
** Launch _Terminal_
** Navigate to the home folder where _{jarName}_ is, using the `cd` command, e.g. `cd ~/Documents/BudgetBuddy`
** Execute the jar file using `java -jar budgetbuddy.jar`

* Windows:
** Launch _Cmd_, or Windows' Command Prompt
** Navigate to the home folder where _{jarName}_ is, using the `cd` command, e.g. `cd Documents\BudgetBuddy`
** Execute the jar file using `java -jar budgetbuddy.jar`

== Getting Started

Welcome to the Budget Buddy User Guide! You can scroll down to start looking at the in-depth features of Budget Buddy,
or select a topic from the _Table of Contents_ right above.

[[Features]]
== Features

Budget Buddy comes with many tools to help you manage your expenses better! You can create multiple accounts,
add and remove transactions that you have made, and even track any outstanding loans that you may have.

What's more? Automate processes by using rules. Typing repetitive descriptions? Set the description of a transaction
automatically by using a keyword! Set a Food category automatically each time you make a food
transaction! Automate everything!

If you know how to code in JavaScript, great news for you too. Write and evaluate your own scripts within the application,
do complicated things in a snap. And even use your script in rules!

====
*Command Format*

* Commands start with a category, and a command type usually follows, e.g. `rule add`
* Words written using `<>` brackets are parameters to be supplied by the user.
* Parameters within `[]` brackets are optional and can be omitted.
* `|` indicates that a choice must be made between two parameters.
* `...` indicates a variable number (at least 1) of the specified parameter.
====

=== Viewing help: `help`

Provides a link to this user guide.

Format: `help`

=== Managing defaults: `default` (coming in v2.0)

==== Set default account: `default account` (coming in v2.0)

Sets the default account.

Format: `default account <id>`

=== Managing the main transaction view: `view`

==== Filter transactions: `view filter` (Coming in v2.0)

Filters the main transaction view. If no arguments are provided, all transactions are shown.
Otherwise, only transactions meeting all the criteria are shown.

Format: `view filter [a/<account>] [c/<category>] [f/<from date>] [t/<to date>]`

==== Sort transactions: `view sort` (Coming in v2.0)

Sorts transactions by (a)ccount, (c)ategory, (d)ate or (x)amount.
Specify `o/a` to sort in ascending order, or `o/d` to sort in descending order.
If omitted, sort in ascending order.

Format: `view sort s/<a|c|d|x> [o/<a|d>]`

=== Managing transactions: `transaction`

==== Add a transaction: `txn out|in`

Adds a new transaction of the specified amount and with the given description.

Format: `txn dn/out|in x/<amount> d/<description> [a/<account>] [c/<category>] [w/<date>] [r/<d|w|m|y>]`
****
* If the account is not given, the transaction is inserted into the active account.
* If the category is not given, the transaction is not categorized.
* If the date is not given, the date is set to the current date.
* If the argument ‘r’ is added, the transition is marked as recurring;
identical entries will be added either daily, weekly, monthly, or yearly.
****

==== Edit a transaction: `txn edit`

Edits the specified transaction, setting the specified fields.
If the ‘recurring’ field is modified, the app will ask if all previous recurring entries should be deleted.

Format: `txn edit <id> dn/out|in [x/<amount>] [d/<description>] [a/<account>] [c/<category>] [w/<date>] [r/<d|w|m|y>]`

==== Delete transaction(s): `txn delete`

Deletes the transaction with the specified ID.

Format: `txn delete <id>`

// tag::accounts[]
=== Managing accounts: `account`

==== Add an account: `account add`

You can create a new account. Each account has a unique ID and name. The user can choose to customise a description to describe the use of the account.

Format: `account add [n/<name>] [d/<description>]`

Examples:

* `account add n/Japan trip`
You have created an account with name of 'Japan trip'.
* `account add n/Japan trip d/expense spent in Japan`
You have created an account with name of 'Japan trip' and description of 'expense spent in Japan'.

==== List accounts: `account list`

If you want to see the full list of accounts you currently own, you can enter command and a list of all accounts will be displayed.

Format: `account list`

==== Edit an account: `account edit`

You can edit the account you think that needs modified. You can choose to edit either the name or the description of the account, or both.

Format: `account edit <id> [n/<name>] [d/<description>]`

****
* Edits the account with the specified index. The index refers to the index number shown in the displayed account list. The index must be a positive integer 1, 2, 3...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

Examples:

*`account edit 1 n/food`
The name of your first account will be changed to 'food'.
*`account edit 1 d/money spent on food`
The name of your first account will be changed to 'money spent on food'.
*`account edit 1 n/food d/money spent on food`
The name of your first account will be changed to 'food', at the same time the description of the same account will be changed to 'money spent on food'.

==== Delete account: `account delete`

You can delete the account with the specified ID, as in `account list`.
Note: you cannot delete an account if there are transactions associated with the account.

Format: `account delete <id>`

****
* Deletes the account with the specified index. The index refers to the index number shown in the displayed account list. The index must be a positive integer 1, 2, 3...
****

Examples:

* `account delete 2`
You have deleted the second account in your account list.

==== Find account: `account find`

If you want to see a specific type of accounts you have, or find a specific account, you can find the account(s) with a specified keyword.
A list of account(s) contain the keyword in their names will be displayed.

Format: `account find <keyword>`

Examples:

*`account find trip`
You can see a list of accounts with the word 'trip' contained in their names.
// end::accounts[]

=== Managing categories: `category` (Coming in v2.0)

==== Add a category (Coming in v2.0)

Categories do not need to be added; you can simply use the category name and a new category will be created if no such one exists.

==== List categories: `category list` (Coming in v2.0)

Lists all categories.

==== Rename a category: `category rename` (Coming in v2.0)

Renames the specified category.
Note that this is the same as setting the category of all transactions of category `old name` to `new name`.

Format: `category rename o/<old name> n/<new name>`

==== Delete a category: `category delete` (Coming in v2.0)

Deletes the specified category.
Note that this is the same as un-categorising all transactions under the specified category.

Format: `category delete n/<name>`

// tag::loans[]
=== Tracking loans: `loan`

==== Add a new loan: `loan out|in`

Adds a new loan out/in entry.
Each loan has a unique ID.
If a date is not given, it is set to the current date. The description is also optional.

Format: `loan out|in p/<person> x/<amount> [w/<date>] [d/<description>]`

Examples:

* `loan out p/John Doe x/50 w/23/04/2018`
* `loan in p/Jane Doe x/100 d/Lent me some money for booze.`

==== List loans: `loan list`

Displays a list of all loans, sorted alphabetically by person first, then by newest for each person's loans.

Format: `loan list [out|in|unpaid|paid ...] [p/<person> ...] [x/<amount> ...] [w/<date> ...] [d/<description> ...] [s/w|x|p]`
****
* Filter loans using one or more of the `out`, `in`, `unpaid`, `paid` filters.
* Filter loans persons, amounts, dates and descriptions by adding one or more of the `p/<person>`, `x/<amount>`, `w/<date>`, `d/<description>` filters.
* Sort loans by date, amount, or persons' names using `s/w`, `s/x`, or `s/p` respectively.
** Sorting the list using the same method when it is already sorted will reverse the order of sorting (e.g. descending to ascending).
****

Examples:

* `loan list out unpaid p/John Doe` +
Lists all unpaid loans out to the person named "John Doe".
* `loan list s/p` +
`loan list s/p`
Lists all loans sorted by persons in alphabetical order. Then lists all loans again, but sorted by persons in reverse alphabetical order.

==== Edit loan: `loan edit`

Edits the specified field of the loan entry with the specified index.

Format: `loan edit <index> [<p/person>] [x/<amount>] [d/<description>] [w/<date>]`

****
* Edits the loan with the specified index. The index refers to the index number shown in the displayed loan list. The index must be a positive integer 1, 2, 3...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

Examples:

* `loan list` +
`loan edit 1 x/500 d/Dude owes me so much money I can't even.` +
Lists all loans, then edits the amount and description of the first person in the list to the given values.

==== Mark loan(s) as paid: `loan paid`

Marks the specified loan(s) as paid.
If a person's name is specified, all their loans are also marked as paid.

Format: `loan paid <index ...> [<p/person ...>]`

Examples:

* `loan list` +
`loan paid 1 2 3` +
Lists all loans, then marks the first three loans in the list as *paid*.
* `loan paid p/John p/Adam` +
Marks all loans in from and out to John and Adam as *paid*.

==== Mark loan(s) as unpaid: `loan unpaid`

Marks the specified loan(s) as unpaid.
If a person's name is specified, all their loans are marked as unpaid.
This feature works identically to `loan paid`, except the command word is `unpaid` instead of `paid`.

Format: `loan unpaid <index ...> <p/person ...>`

==== Delete loan(s): `loan delete`

Deletes the loan(s) with the specified loan index/indices.
If a person's name is specified, all of that person's loans are deleted.

Format: `loan delete <index ...> <p/person ...>`

Example:

* `loan list` +
`loan delete 1` +
Lists all loans, then deletes the first loan in the list.
* `loan delete p/John` +
Deletes all loans in from and out to John.

==== Calculate loans: `loan split`

Splits a joint payment equally among group members, then displays a list of who owes who how much.

Format: `loan split p/<person> x/<amount paid> ... [me/<your name> w/<date> d/<description>]`
****
* Each `<person>` corresponds to an `<amount paid>`, representing how much the `person` paid for the group initially. +
The order of all `person`s should match the order of `amount paid`.
* Adding the optional `me/` will add all debts from the resulting list to your loan list.
+
`<your name>` must match one of the persons among the other `p/<person>` names.
* Adding `w/` will set the `<date>` of the loans added to your list.
* Adding `d/` will set the `<description>` of the loans added to your list.
****

Examples:

* `loan split p/John p/Mary p/Peter x/0 x/40 x/60` +
Calculates the money owed between `John`, `Mary` and `Peter` for a scenario where (initially) `Mary` paid `40` and `Peter` paid `60`. +
The resulting display should show that `John` owes `Mary` *$6.66* and also owes `Peter` *$26.67*.
* `loan split p/John p/Mary p/Peter x/0 x/10 x/90 me/Mary d/Dinner.` +
In this scenario, `Mary` paid `10` and `Peter` paid `90`.
Furthermore, `me/Mary` marks `Mary` as the user (you), so any debts `Mary` owes/is owed will be added to the normal loan list with the description `Dinner`. +
The resulting display should show that `John` owes `Peter` *$33.33* and `You` owe `Peter` *$23.33*.
The latter debt will also have been added to your loan list, which can be checked using the command `loan list`.
// end::loans[]

// tag::rules[]
=== Automating with rules: `rule`

// TODO: Some information here to show users perspective

==== Add a new rule: `rule add`

Adds a new rule to the rule engine.
A rule can be formed using either expressions or scripts, or both.

NOTE: Rules with conflicting actions are allowed.
All rules will be executed in the order they were added.

Format: `rule add pred/<expression | script name> act/<expression | script name>`

Refer to <<Scripting>> for script usage.
****
*Expression Formatting Guide:*

* **Predicate**: In the order of `<attribute> <predicate operator> <value>`
** An attribute can be one of the following:
*** `inamt` : Transaction amount inwards
*** `outamt` : Transaction amount outwards
*** `desc` : Transaction description
** A predicate operator can be one of the following:
*** `=` : equality operator
*** `<` , `\<=`  , `>=` , `>` : inequality operators
*** `contains` : string comparison operator
** A value can be a number or a string of length not more than 180 characters

* **Action**: In the order of `<action operator> <value>`
** An action operator can be one of the following:
*** `set_cat` : Adds a category to the transaction
*** `remove_cat` : Removes a category from the transaction
*** `set_desc` : Sets the description of the transaction
*** `app_desc` : Appends a value to the description
*** `prep_desc` : Prepends a value to the description
*** `set_in` : Sets the direction of the transaction to be inwards
*** `set_out` : Sets the direction of the transaction to be outwards
*** `switch_direct` : Switches the current direction of the transaction
** A value is as described in a predicate expression
****

==== List rules: `rule list`

Displays the list of all existing rules, sorted by the order in which a rule was added.

Format: `rule list`

==== Edit a rule: `rule edit`

Edits the specified fields in the rule with the specified ID.
Both the predicate and action can be modified.

Format: `rule edit <rule ID> [pred/<expression | script>] [act/<expression | script>]`

==== Delete a rule: `rule delete`

Deletes a rule with the specified rule ID.

Format: `rule delete <rule ID>`
// end::rules[]

// tag::scripting[]
[[Scripting]]
=== Scripting: `script`

The scripting engine allows you to evaluate arbitrary scripts to perform complex operations on your transaction data,
as well as extend the application and add commands and features of your own.

WARNING: Scripts have full access to the application's internals, as well as all Java standard library classes and APIs.
It is possible to corrupt the application state by execution of a malicious or buggy script. There are no guarantees on
application behaviour if scripts are used.

==== Evaluate a script: `script eval`

Evaluates a script and displays the result.

Format: `script eval <script>`

****
* The scripting language is JavaScript (specifically, ECMAScript 5.1).
****

==== Add a stored script: `script add`

Stores a script for future invocation.

Format: `script add <script name> [p/<file path> | s/<script>]`

****
* The script name may contain only alphanumeric characters, underscores, and dashes.
* If neither a file path nor the script code is given, a file browser is opened for you to
select the script file.
****

WARNING: The script is not checked for correctness before it is stored. Any syntax errors
will be reported only when the script is run.

==== Delete a stored script: `script delete`

Deletes a previously-stored script.

Format: `script delete <script name>`

==== Run a stored script: `script run`

Runs a previously-stored script.

Format: `script run <script name> [<argument>]`

****
* The argument is the rest of the command line after the script name, and is passed to the script as a single string.
****

==== List stored scripts: `script list`

Lists stored scripts.

Format: `script list`

==== Reset the scripting environment: `script reset`

Resets the scripting environment.

Format: `script reset`
// end::scripting[]

// tag::importexport[]
=== Import and export *(Coming in v1.4)* : `import`, `export`

==== Import a file: `import`

Imports transactions from the file at the given path.

Format: `import [f/<format>] [p/<file path>]`
****
* The file path can be relative to where you launched Budget Buddy from, or absolute.
If the path is omitted, a file browser is opened for you to select the file.
* Format is one of dbs (DBS Bank/POSB), ocbc (OCBC Bank), sc (Standard Chartered), csv (generic comma-separated values file).
If the format is omitted, automatic detection is attempted.
****

==== Export transactions: `export`

Exports all transactions to the given path.

Format: `export [p/<file path>]`
****
* The file path can be relative to where you launched Budget Buddy from, or absolute.
If the path is omitted, a file browser is opened for you to select where to save the file.
* The file is a comma-separated values file.
****
// end::importexport[]

// tag::aliases[]
=== Aliases *(Coming in v1.4)* : `alias`

==== Add an alias: `alias add`

Adds an alias.

Format: `alias add <alias name> c/<alias replacement>`

****
* When executed, the alias name will be replaced by the replacement, and the resulting command line executed.
** For example, suppose you add an alias named `abcd efgh 7890`, with replacement `script run x`.
** Executing `abcd efgh 7890 abcd` is equivalent to executing `script run x abcd`.
* The alias name must appear at the start of a command line, followed by a space, for it to be recognised.
* There is no restriction on the characters in the alias name. However, leading and trailing whitespace will be trimmed.
* Aliases can expand to other aliases.
****

WARNING: Built-in commands take precedence. If you add an alias with the same name as a built-in command, it will have no effect.

==== Delete an alias: `alias delete`

Deletes an alias.

Format: `alias delete <alias name>`
// end::aliases[]

// tag::budget[]
=== Managing budgets *(Coming in v2.0)* : `budget`

Displays or sets the budget for the specified period.
// TODO: give purpose of this command for user

==== View budgets: `budget list`

Views the list of budgets currently stored.

==== Add budgets: `budget add`

This command sets a budget. Note that budgets cannot overlap.

==== Remove budgets: `budget delete`

This command removes a budget from the list.
// end::budget[]

=== Goal setting *(Coming in v2.0)* : `goal`

==== Add a goal: `goal add`

Adds a goal on the specified account to reach the specified amount by the target date or at the end of the specified period.

==== View goals: `goal list`

List all goals.

==== Delete goal(s): `goal delete`

Deletes the goal with the specified goal ID.


=== Viewing reports *(Coming in v2.0)*: `report`

Displays a report.

Format: `report [[f/<from date>] [t/<to date>] | [p/<this month|last month|this week|last week|today|yesterday>]] [total|category]`
****
* You can specify either the start and end date range, inclusive, or name a period.
If no period is specified, it defaults to the current month-to-date.
* You can see a total report that shows your total income and expenditure and budget information,
if a budget has been set up,  or a report that breaks your income and expenditure down into categories.
If the type is omitted, it defaults to a total report.
* Your goal progress will also be shown in both reports.
****

=== Getting help with specific commands *(Coming in v2.0)*: `help`

Displays detailed help for a specific command.

Format: `help <command word>`

== Scripting API

The Nashorn scripting engine is used. All features and Java class access of the Nashorn engine are available. See the https://docs.oracle.com/en/java/javase/11/nashorn/nashorn-java-api.html[Nashorn documentation] for more details.

Currently, the only exposed interface to the Budget Buddy model is `bb`, which exposes the full application model to scripts.

Convenience functions as well as access to the UI will be added in v1.4.

== FAQ

*Q:* Which version of Java do I require to run this application?

*A:* Java 11

'''

*Q:* How do I switch between the different tabs without clicking on them?

*A:* Simply execute the `list` command for that category, e.g. `rule list`.
On the other hand, executing any command from that category will switch you over as well.

'''

*Q:* How do I reset the application data?

*A:* All data is stored within the same folder as your execution path, under the "data/" folder.
Deleting that folder will reset the application data.

== Command Summary

=== Rules

* `rule add` - Add a new rule
* `rule list` - List rules
* `rule edit` - Edit a rule
* `rule delete` - Delete a rule


