# DeliveryMANS – User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-T12-2/main

By: `Team AY1920S1-CS2103-T12-2`   Since: `Sept 2019`  Licence: `NUS`

== Introduction

*DeliveryMANs* is a command-line application designed specifically for delivery centre administrators who are in charge of food delivery service. It encompasses a well-structured system for users to keep track and manage the entire delivery process. It facilitates food delivery service by coaliasing the delivery men, customers and restaurant menu. From auto-assigning deliverymen for deliveries when orders are made, to viewing statistics of the most popular dish of restaurants as well as customer ordering trends for further promotions, financial and business management decisions, *DeliveryMANs* is everything you need to help improve managing deliveries. With just a few simple commands, this delivery manager can help to kickstart your delivery service.

Get started with <<Quick Start>> and begin managing your deliveries today!

== Quick start

Ensure you have Java 11 or above installed on your computer.

Click https://github.com/AY1920S1-CS2103T-T12-2/main/releases[here] to download the JAR file for *DeliveryMANs*.

Open the application to begin. Refer to <<Features>> for details of each command.

// tag::features[]

[[Features]]
== Features

In *DeliveryMANs*, there are 2 types of commands: universal commands and context-specific commands.

Universal commands can be used anywhere throughout the application. You can identify universal commands by its "-" convention followed by a keyword e.g. `-help`.

Context-specific commands are commands which are only applicable for a specific context. Commands such as viewing a customer ordering history can only be accessed in the customer context.

**Command Format**

* Words in curly brackets are parameters to be supplied by the user e.g. in `add_order c/CUSTOMER r/RESTAURANT f/FOOD q/QUANTITY`, `CUSTOMER`, `RESTAURANT`, `FOOD` and `QUANTITY` are parameters to be replaced. `add_order c/Donald Trump r/KFC f/Chicken Bucket q/100`
* Items with square brackets are optional such as `[t/TAG]` e.g. `n/John Doe t/Japanese` or `n/John Doe`.
* Items with `…` after them can be used multiple times e.g. `[f/FOOD]...` can be used 1 or more: `f/3 Piece Chicken Meal`, `f/Pepperoni Pizza f/Char Kway Teow` etc.
// end::features[]

// tag::universalCommand[]
=== Universal commands

These are general commands to assist you in controlling the app, which are not directly related to the customer, restaurant and delivery men.

==== Viewing help `-help`

Generates a list of commands and tips for you.

Format: `-help`

- Context specific: -help {context}
- Example: -help customer
- Context specific commands: -help -cxt {context} -cmd {command}
- Example: -help -cxt customer -cmd sort

==== Switching context

Switches to a specific context for targeted commands

Format: -{context}

Example: -switch restaurant

==== Viewing order summary

Views the current order summary

Format: -summary

==== Exiting program

Exits the program

Format: -exit

// end::universalCommand[]
// tag::customerCommand[]

=== Customer commands

These are commands pertaining to customer context of *DeliveryMANs*. The screenshot below shows how the customer context will look like in *DeliveryMANs*.

 screenshot of finalised DeliveryMANs showing customer list goes here

This is a customer and its information.

 screenshot of finalised CustomerCard

==== Adding a customer: `add`

This command allows you to add a new customer to the customer list. Name and phone number are necessary to a customer. Tags in customers are optional to include. They are used to specify the customer's favourite cuisine. Multiple tags can be added to one customer.

Format: `add n/NAME p/PHONE [t/TAG]...`

Example: `add n/John Doe p/91234567 t/Japanese t/Noodles`

==== Editing a customer: `edit`

This command allows you to edit an existing customer in the customer list. The index of a customer needs to be provided while the information to edit are optional. For example, you can edit the customer's name without editing the phone number.

Format: `edit INDEX [n/NAME] [p/PHONE] [t/TAGS]...`

Example: `edit 1 n/John Hoe p/97654321 t/Indian`

==== Deleting a customer: `delete`

This command allows you to delete an existing customer in the customer list. The index of a customer needs to be provided.

Format: `delete INDEX`

Example: `delete 1`

==== Viewing a customer's order history: `history`

This command allows you to view a customer's order history. The index of a customer needs to be provided.

Format: `history INDEX`

Example: `history 1`

// end::customerCommand[]
// tag::restaurantCommand[]
=== Restaurant commands

Commands in the restaurant context

==== Listing all restaurants

Lists all available restaurants

Format: -list

==== Entering specific restaurant

Enters a specific restaurant

Format: -enter {restaurant}

Example: -enter muthu&#39;s curry

==== Adding food item

Adds a food item for a specific restaurant

Format: -add {item}

Example: -add chicken rice

==== Removing food item

Removes a food item for a specific restaurant

Format: -remove {item}

Example: -remove laksa

==== Adding rating

Adds a rating (out of 5) for the restaurant

Format: -rate {rating}

Example: -rate 5

==== ChefHat food item

Marks a food item as Chef&#39;s recommendation

Format: -chefhat {item}

Example: -chefhat nasi lemak

// end::restaurantCommand[]
// tag::deliverymenCommand[]

=== Deliverymen commands

Commands in the delivery men context

==== Listing all deliverymen

Lists all deliverymen

Format: -list

==== Listing available deliverymen

Lists all available deliverymen

Format: -lista

==== Entering a specific deliveryman

Shows a deliveryman&#39;s basic info

Format: -list {name}

Example: -list Stanley Tay

==== Assigning order to a deliveryman

Assigns an order to an available deliveryman

Format: -assn {name}{#orderIndex}

Example: -assn Stanley Tay #12

==== Viewing delivery status of a deliveryman

Shows delivery status of an assigned deliveryman

Format: status {name}

Example: -status Stanley Tay


== Command summary

**Command:** format

* Universal commands
- View help: -help
- View order summary: -summary
- Switch to restaurant context: -restaurant
- Switch to customer context: -customer
- Switch to deliverymen context: -deliverymen
- Exit application: -exit

* Customer commands
- Adding a customer: `add n/NAME p/PHONE [t/TAG]...`
- Editing a customer: `edit INDEX [n/NAME] [p/PHONE] [t/TAGS]...`
- Deleting a customer: `delete INDEX`
- Viewing a customer's order history: `history INDEX`

* Restaurant commands
- List restaurants: -list
- Enter specific restaurant: -enter {restaurant}
- Add food item: -add {item}
- Remove food item: -remove {item}
- View order: -orders
- Add Rating from Customer: -rate {rating}
- ChefHat Food Item: -chefhat {item}

* Deliverymen commands
- List deliverymen: -list
- List available deliverymen: -lista
- List specific deliveryman info: -list {name}
- Assign order to deliveryman: -assn {name} {order}
- Show delivery status of deliveryman: -status {name}
