= CaloFit - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W11-4/main

By: `Team AY1920S1-CS2103T-W11-4`      Since: `Sep 2019`      Licence: `MIT`

== Introduction

CaloFit is suitable for those who prefer to track their calories gained from day-to-day meals. CaloFit is primarily uses a Command Line Interface(CLI) while still displaying the results through a Graphical User Interface(GUI). You can set your daily calorie target and CaloFit will do its best to help you stay on track.

== Quick Start

Coming in v1.4 when the first jar file will be released.

Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add MEAL_NAME`, `MEAL_NAME` is a parameter which can be used as `add carbonara`.
* Items in square brackets are optional e.g `add MEAL_NAME [cal/CALORIES]` can be used as `add carbonara cal/430` or as `add carbonara`.
====

=== Adding a meal: `add`

Adds a meal that the user ate to be tracked by CaloFit. +
Inputting calories of the meal is optional. +
If the meal is a dish stored in CaloFit, the calories will be taken from CaloFit. If not, the default value is 700. +
Tags are completely optional and there is no default tag. +
Format: `add n/MEAL_NAME [c/CALORIES] [t/TAGS]`

Examples:

* `add n/spaghetti c/480 t/tasty`
* `add n/chicken rice c/500`
* `add n/mushroom soup`

=== Editing previous meal entry : `edit`

Edits a meal that the user previously ate today. +
Format: `edit MEAL_NUMBER [n/NAME] [c/CALORIES]`

Examples:

* `edit 1 n/wanton noodle c/1000`
* `edit 2 n/chicken rice`
* `edit 3 c/500`
* `edit 4`

=== Deleting previous meal entry : `delete`

Deletes a meal that the user previously ate today. +
Format: `delete MEAL_NUMBER`

Examples:

* `delete 1`

=== Suggesting Meal options: `suggest`

Suggest possible meals based on user calorie intake budget and number  of meals left for today. +
Format: `suggest`

=== Setting calorie intake budget: `set`

Set user calorie intake budget for today. +
Format: `set CALORIES`

Examples:

* `set 2500`

=== Generating a Report: `report`

Creates a report for the user. +
Includes Maximum, Minimum and Average calorie intake per day of the current month, +
Number of days where calorie intake exceeded per month, +
Most consumed food of the month. +
Format: `report`

=== Reminder that a meal is missed

A reminder will display when the user starts up the CaloFit if he or she has missed a meal after a default time.

=== Shows an overview of commands usable in CaloFit: `help`

Displays all the commands that are usable in CaloFit, including examples of how to use them. +
Format: `help`

== Command Summary

* *Add* `add n/MEAL_NAME [c/CALORIES]` +
e.g. `add n/duck rice c/360`
* *Edit* : `edit MEAL_NUMBER [n/MEAL_NAME] [c/CALORIES]` +
e.g. `edit 1 n/duck noodle c/250`
* *Delete* : `delete MEAL_NUMBER` +
e.g. `delete 3`
* *Suggest* : `suggest`
* *Set* : `set CALORIES` +
e.g. `set 2600`
* *Report* : `report`
* *Help* : `help`
