= Billboard - User guide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:repoURL: https://github.com/AY1920S1-CS2103T-F12-4/main
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

By: `CS2103T-F12-4`      Since: `Sep 2019`      Licence: `MIT`

== Introduction

_Billboard_ is for those who prefer to use desktop applications to manage and keep track of their expenses.
_Billboard_ is optimized for those who prefer to work with a Command Line Interface (CLI)
while still enjoying all the benefits of having a fully fledged Graphical User Interface (GUI).
If you can type fast, _Billboard_ can help you manage your expenses faster than traditional
GUI apps!

== Quick Start

. Ensure you have Java 11 or above installed on your machine.
. Download the latest version of _Billboard_ https://github.com/AY1920S1-CS2103T-F12-4/main/releases/tag/v1.1[here].
. Copy the file to the folder you want to use as the Home folder for _Billboard_
. Double-click the file to open the application
. Refer to <<Features>> for the details of each command

[[Features]]
== Features

{nbsp} +
====
*Command Format*

* Words in `[SQUARE BRACKETS]` are the mandatory parameters to be supplied by the user e.g. in `expense add [DESCRIPTION] [AMOUNT]`, `DESCRIPTION` and `AMOUNT` are parameters which can be used as `expense add “buy a book” 10`.
* The mandatory parameters must be supplied in the order specified.
* Default values can be specified in the square brackets, e.g `[NUM_ENTRIES, DEFAULT = 10]`. If the user does not provide a value for that parameter, it will default to the default value stated.
* Some commands may have optional parameters denoted under options. These can be included by specifying a flag, usually of the format `--flag` or `-f`. E.g `--description` can be used as `expense edit 2 --description "changed description"`.
* Flags can be in any order.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[TAG]...` can be used as `{nbsp}` (i.e. 0 times), `bills`, `bills fees` etc.

====


=== Managing expenses: `expense`

. _Add a new expense: expense add_ +
Adds an expense to records. +
Usage:

 expense add [DESCRIPTION] [AMOUNT]
+
Example:  +
`expense add “buy a book” 10` +
Adds an expense to record where the description is “buy a book” and the amount is 10. +
{nbsp} +

. _Edit an existing expense: expense edit_ +
Edits an existing expense that is being displayed on the GUI. Either description or amount must be supplied. +
{nbsp} +
Usage:

 expense edit [INDEX] [OPTIONS]
+
Options: +

* `--description`, `-d`: Specify new description to update expense with. +
* `--amount`, `-a`: Specify new amount to update expense with. +
{nbsp} +

+
Example: +
`expense edit 2 -d “buy a math book”` +
Edit the expense at index 2  with new description of: “buy a math book” +

{nbsp} +

. _Delete an existing expense: expense rm_ +
Deletes an existing expense that is being displayed on the GUI. +
{nbsp} +
Usage:

 expense rm [INDEX]
+
Example: +
`expense rm 3` +
Deletes the expense with index 3. +
{nbsp} +

. _List all expenses: expense list_ +
Lists all the expenses in the record list. +
{nbsp} +
Usage:

 expense list
+
Example: +
`expense list` +
Displays below expenses (for example) in the GUI: +

* buy a book / amount: $10 +
 * pay for dinner / amount: $5 +
{nbsp} +

=== Tagging expenses: `tag`

. _Adding a tag: tag add_ +
Adds your input tag/s to the expense at the index you have specified. +
{nbsp} +
Usage:

 tag add [INDEX] [TAG] [TAG…]

+
Options: +

* t/ : Specifies the name of the tag/s you want to add to the expense.(REQUIRED) +
{nbsp} +

+
Example: +
`tag add 2 t/monthlybills t/electricity` +
Adds the tags “monthly bills” and "electricity" to the expense at index 2. +
{nbsp} +


. _Removing a tag: tag rm_ +
Deletes your input tag/s from the expense at the index you have specified. +
{nbsp} +
Usage:

 tag rm [INDEX] [TAG] [TAG…]

* t/ : Specifies the name of the tag/s you want to remove from the expense.(REQUIRED) +
{nbsp} +

+
Example: +
`tag rm 2 t/monthly bills t/electricity` +
Removes the tags “monthly bills” and "electricity" from the expense at index 2. +
{nbsp} +

. _Filtering by tag: tag filter_ +
Filters expenses by your input tag/s. +
{nbsp} +
Usage:

 tag filter [TAG] [TAG…]

* t/ : Specifies name of the tag/s you want to filter expenses with.(REQUIRED) +
{nbsp} +

+
Example: +
`tag filter t/home t/monthly bills` +
Lists out all the expenses that contains the tags “home” or “monthly bills” +
{nbsp} +

. _Listing out all the tags: tag list_ +
Lists out all existing tags. +
{nbsp} +
Usage:

 tag list

{nbsp} +

=== Finding expenses by attributes: `find`

. _Find : find_ +
Find expenses that satisfies conditions specified in the arguments. +
{nbsp} +
Usage:

 find [d/KEYWORD[ KEYWORD…]] [a/LOWER AMOUNT LIMIT] [al/UPPER AMOUNT LIMIT] [sd/START DATE] [ed/END DATE]
+
Example: +
`find d/lunch book a/2 al/20 sd/1/1/2019 ed/1/10/2019` +
Finds all expenses that contain the keyword ‘lunch’ or 'book' and amount between 2 and 20 dollars
and date between 1 Jan 2019 to 1 Oct 2019 in any of its attributes. +
{nbsp} +

=== Sorting expenses by attributes: `[Coming in v1.3]`

. _Sort by name:_ +
Sort expenses by name in alphabetical order. +
{nbsp} +
Usage:

 sort name

. _Sort by date:_ +
Sort expenses by date from newest to oldest +
{nbsp} +
Usage:

 sort date

. _Sort by amount_ +
Sort expenses by amount of expense in from largest to smallest. +
{nbsp} +
Usage:

 sort amt

{nbsp} +

=== Archiving past expenses: `archive`

. _Adding a record to an archive: archive add_ +
Transfers the expense at the specified index to your specified archive. +
If archive you entered does not exist, then the new archive is created before the expense is added. +
{nbsp} +
Usage:

 archive add [INDEX] [OPTIONS]
+
Options:

* `/arc`: Specifies the name of the archive to add the expense to. (REQUIRED) +
{nbsp} +

+
Example: +
`archive add 3 arc/MBS casino winnings` +
Archives the record at the 3rd index into an archive named “MBS casino winnings” +
{nbsp} +

. _Listing out all archives: archive listall_ +
Displays the list of all archive names. +
{nbsp} +
Usage:

 archive listall

+
{nbsp} +
. _Listing records in a particular archive: archive list_ +
Displays the list of records in your specified archive +
{nbsp} +
Usage:

 archive list [NAME]
+
Example: +
`archive list 2018 expenses` +
Lists out all the records in the “2018 expenses” archive +
{nbsp} +

. _Deleting an archived record: archive delete_ +
Deletes the record at the specified index from your specified archive. +
If the archive record deleted was the last record in the archive, the empty archive will be deleted. +
{nbsp} +
Usage:

 archive delete [INDEX] [OPTIONS]
+
Options:

* `arc/`: Specifies the name of the archive to delete the expense from. (REQUIRED) +
{nbsp} +

+
Example: +
`archive delete 5 arc/2018 expenses` +
Deletes the record at the 5th index in the “2018 expenses” archive +
{nbsp} +

. _Revert/unarchive an archived record: archive revert_ +
Unarchives the record at the specified index from your specified archive, transferring it back to your current list of expenses. +
If the archive record reverted was the last record in the archive, the empty archive will be deleted. +
{nbsp} +
Usage:

 archive revert [INDEX] [OPTIONS]
+
Options:

* `arc/`: Specifies the name of the archive to revert the expense from. (REQUIRED) +
{nbsp} +

+
Example: +
`archive revert 5 arc/2018 expenses` +
Unarchives the record at the 5th index in the “2018 expenses” archive +
{nbsp} +

=== Displaying of statistics: `display-stats`

. _Display timeline overview of expenses: display-stats timeline_ +
Displays a timeline overview of the currently displayed expenses. The expenses over a
specified time period are aggregated and added as a data point on the timeline. +
{nbsp} +
Usage:

 show-stats timeline [OPTIONS]
+
Options:

* `interval/`: Specifies the date interval to be used to split the expenses into groups by.
Supported date intervals include 'day', 'week', 'month' and 'year'.
{nbsp} +

+
Example: +
`show-stats timeline interval/week` +
Displays a timeline overview of the displayed expenses with the expenses being grouped into weeks. +
{nbsp} +

. _Display breakdown of expenses: show-stats breakdown_ +
Displays a breakdown of expenses by tag for the currently displayed expenses. The total
expenses per tag are totalled and displayed in a pie chart. +
{nbsp} +
Usage:

 show-stats breakdown
+

{nbsp} +

+
Example: +
`show-stats breakdown` +
Shows a pie chart breakdown by tag of all currently displayed expenses. +
{nbsp} +

// tag::undoredo[]

=== Undo and Redo: `undo/redo`

. _Undo the previous action: undo_ +
Undo will restore the previous billboard state from state history. Undo will ignore all arguments. +
{nbsp} +
Usage:

 undo
+
{nbsp} +
. _Redo the previous undo action: redo_ +
Redo will restore a previously undone billboard state from state history. Redo will ignore all arguments. +
{nbsp} +
Usage:

 redo
+
{nbsp} +

// end::undoredo[]

// tag::history[]
=== Viewing History: `history`

. _View the past command history: history_ +
History will show all previous command histories. History will ignore all arguments. +
{nbsp} +
Usage:

 history
+
{nbsp} +

// end::history[]

// tag::updownkey[]
=== Up and down key: `&uarr;/&darr;`

. _Get the previous entered command: &uarr;_ +
Up arrow key(&uarr;) will get the previous command entered in the command history on the text field. +
{nbsp} +
. _Get the sequential entered command: &darr;_ +
Down arrow key(&darr;) will get the sequential command entered in the command history on the text field. +
{nbsp} +

// end::updownkey[]

=== Viewing help: `help`

. _Help list of complete set of commands: help_ +
Shows the complete list of commands and instructions/description on how to use them. +
{nbsp} +
Usage:

 help
+
{nbsp} +
. _Help list of a specific command: help_ +
Shows the description and instructions on how to use the specified command. +
{nbsp} +
Usage:

 help [COMMAND]
+
Example: +
`help archive` +
Shows the help message for the archive commands. +
{nbsp} +

=== Exporting data: `[Coming in v2.0]`

_{explain how the user can enable/disable data encryption}_



== FAQ
{nbsp} +
Coming soon!





