= PalPay - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `AY1920S1-CS2103T-W12-3`      Since: `SEPT 2019`      Licence: `MIT`

== Introduction

PalPay is for those who *prefer to use a desktop app for managing personal finances*. More importantly, PalPay is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, PalPay can get your finance management tasks done faster than traditional GUI apps. Ready to start your journey to financial freedom? Jump to the <<Quick Start>> to get started. Enjoy!

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `palpay.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your finance manager.
.  Double-click the file to start the app. The GUI should appear within a few seconds.
+
+
.  Type your command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`view`* : shows statistics of your current finances
* **`in`**`100 n/mother t/allowance` : adds an income to your personal finance of *100* dollars under the catergory *mother* and the item type *allowance*.
* **`out`**`3 n/pie t/food` : adds an expenditure to your personal finance of *3* dollars under the category *food* and the item type *pie*.
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `in AMOUNT n/ITEM`, `AMOUNT` and 'ITEM' are parameters which can be used as `in 300 n/concert`.
* Items in square brackets are optional e.g `n/ITEM [t/CATEGORY]` can be used as `n/coke t/drinks` or as `n/coke`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[n/NAME]...` can be used as `{nbsp}` (i.e. 0 times), `n/Amy`, `n/Amy n/Betty` etc.
* Parameters can be in any order e.g. if the command specifies `AMOUNT n/ITEM`, `n/ITEM AMOUNT` is also acceptable.
====

=== Viewing help : `help`

Opens help page for list of usable commands +
Format: `help`

=== Splitting expense with multiple people: `split`

Split expenses with you friends +
Format: `split AMOUNT [FLAG] n/NAME1 [n/NAME2]...`


* [FLAG] defines how the bill is split
** `--even` splits the amount evenly.
** `--shares` splits the amount by ration (default = 0)

Examples:

* `split 1000 n/Amy n/Betty n/Catherine n/Dan`
* `split 100 --share n/Albert n/Bernard n/Clement`

=== Finance output: `out`

Adds an expenditure of personal finance +
Format: `out AMOUNT n/ITEM [t/CATEGORY]`

Examples:
* `out 100 n/milk t/food`
* `out 29 n/taxi t/transport`
* `out 12 n/burger`

=== Finance input: `in`

Adds an income of personal finance +
Format: `in AMOUNT n/ITEM [t/CATEGORY]`

Examples:
* `in 100 n/errand t/work`
* `in 200 n/mom t/family`
* `in 120 n/work`

=== Display view: `view`

Shows all possible views (spending, projection and loan). +
Format: `view KEYWORD [TIMEFRAME]`

****
* `KEYWORD` input only accepts `spending`, `projection` and `loan`.
* `[TIMEFRAME]` input defines the number of days prior to this command for the called projection. (default=30)
* `view spending` shows a breakdown of your categories of spending
* `view projection` shows a personal finance projection for a given period of time
* `view loan` shows the amount of money owed and lent to others
****

Examples:

* `view loan`
* `view projection`
* `view spending`

// tag::delete[]
=== Deleting Finance: `delete`

Deletes the specified income or expenditure from the finance manager. +
Format: `delete --TYPE AMOUNT n/ITEM [t/CATEGORY]`

****
* `TYPE` only accepts `in` or `out`. (e.g. `delete --out ...` refers to deleting an *expenditure*)
* Deletes the item from the given category with it's given amount.
* If there is no given category, it will only search for given type with it's corresponding amount.
* If AMOUNT/ITEM/CATEGORY or a combination of any of the 3 does not match, no operation will be performed
* example `delete --in 200 n/mom t/allowance` will delete income of *200* from type: *mom* and category: *allowance*.
****

Examples:

* `delete --out 20 n/sprite t/drinks`
* `delete --out 10 n/car`
* `delete --in 50 n/mom`

=== Updating Finance: `update`

Updates the specified income or expenditure from the finance manager. +
Format: `update --TYPE AMOUNT1 AMOUNT2 n/ITEM [t/CATEGORY]`

****
* `TYPE` only accepts `in` or `out`. (e.g. `update --out ...` refers to deleting an *expenditure*)
*`AMOUNT1` is the new amount you want to update the current in/out with.
* Updates the item from the given category with it's given amount.
* If there is no given category, it will only search for given type with it's corresponding amount.
* If AMOUNT/ITEM/CATEGORY or a combination of any of the 3 does not match, no operation will be performed
* example `update --in 100 200 n/mom t/allowance` will update income of *200* to *100* from type: *mom* and category: *allowance*.
****

Examples:

* `update --out 10 20 n/coke t/drinks`
* `update --out 100 300 n/transport`
* `update --in 60 70 n/dad`

// end::delete[]
=== Clearing all entries : `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

PalPay data is saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *In* `in AMOUNT n/ITEM [t/CATEGORY]` +
e.g. `in 100 n/allowance`
* *Out* : `out AMOUNT n/ITEM [t/CATEGORY]` +
e.g. `out 20 n/coke t/drink`
* *Update* : `update --TYPE AMOUNT1 AMOUNT2 n/ITEM [t/CATEGORY]` +
e.g. `update --out 100 300 n/transport`
* *Delete* : `delete --TYPE AMOUNT n/ITEM [t/CATEGORY]` +
e.g. `delete --in 200 n/waiter t/work`
* *Split* : `split AMOUNT [FLAG] n/NAME1 [n/NAME2]...` +
e.g. `split 100 --share n/Albert n/Bernard n/Clement`
* *View* : `view KEYWORD [TIMEFRAME]` +
e.g. `view loan`, `view projection`, `view spending`
* *Help* : `help`
