= Budget Buddy - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W13-4/main

By: `CS2103T W13-4`

== Introduction

Budget Buddy is for computing students who prefer to use a desktop app to manage their expenses.
More importantly, Budget Buddy is *optimized for those who prefer to work with a Command Line Interface* (CLI)
while still having the benefits of a Graphical User Interface (GUI).
If you can type fast, Budget Buddy can get your expense management tasks done faster than traditional GUI apps.
Furthermore, computing students can take full advantage of Budget Buddy by adding their own functions through custom JavaScript files.

== Quick Start

Nothing to see here.

[[Features]]
== Features

====
*Command Format*

* Words within `<>` brackets are parameters to be supplied by the user.
* Parameters within `[]` brackets are optional and can be omitted.
* `|` indicates that a choice must be made between two parameters.
* `...` indicates a variable number (at least 1) of the specified parameter.
====

=== Viewing help : `help`

Displays help. If `command` is specified, view detailed help for that command.

Format: `help [<command]>`

=== Manage defaults : `default`

==== Set default account : `default account`

Sets the default account.

Format: `default account <id>`

=== Tracking loans : `loan`

==== Add a new loan : `loan out|in`

Adds a new loan out/in entry.
Each entry has a unique ID (across both out and in entries).
If date is not given, it is set to the default date.

Format: `loan out|in x/<amount> d/<description> [w/<date>]`

==== List loans : `loan list`

Displays a list of all loans, sorted by newest first.

Format: `loan list [o|i] [s/a]`
****
* Adding ‘o’ argument filters list to out loans only.
* Adding ‘i’ argument filters list to in loans only.
* Add `s/a` to sort the list by amount.
****

==== Edit loan : `loan edit`

Edits the specified field of the loan entry with the specified ID.

Format: `loan edit <id> [x/<amount>] [d/<description>] [w/<date>]`

==== Mark loan(s) as paid : `loan paid`

Marks the specified loan(s) as paid.

Format: `loan paid <id ...>`

==== Delete loan(s) : `loan delete`

Deletes the loan(s) with the specified loan ID(s).

Format: `loan delete <id ...>`

==== Calculate loans : `loan split`

Splits and calculates a group payment, then prints a list of who owes who.

Format: `loan split n/<name> a/<amount paid> ...`

== FAQ

== Command Summary
