= THRIFT - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W12-2/main

By: `Team THRIFT`      Since: `Sept 2019`      Licence: `MIT`

== Introduction
THRIFT is for money-conscious NUS students who wish to track their spending, in order to make better informed decisions when it comes to saving money. Maintain records of your daily incoming and outgoing transactions and constantly keep track of your spending and income! THRIFT is optimized for those who prefer to work with a Command Line Interface (CLI) while still enjoying the benefits of having a Graphical User Interface (GUI). If you want a simple, no-frills finance tracker, look no further than THRIFT!



== Quick Start
1. Ensure that you have Java `11` or above installed in your Computer.
2. Download the latest THRIFT.jar https://github.com/AY1920S1-CS2103T-W12-2/main/releases[here].
3. Copy the file to the folder you want to use as the home folder for your THRIFT application.
4. Double-click the file to start the app, the GUI should appear in a few seconds.
5. Type the command in the command box and press `Enter` to execute it. e.g. typing `help` and pressing `Enter` will open the help window.
6. Some example commands you can try:
*   `add expense n/Apple Airpods c/200`: adds an expense called `Apple Airpods` which cost $`200`.
*   `add income n/Bursary Award c/350`: adds an income called `Bursary Award` which incremented your budget by $`350`.
*   `delete i/1`: deletes the 1st transaction in the current list shown in the UI.


== Features:

Command format:

*   Words in `UPPER_CASE` are parameters to be supplied by the user e.g. `expense n/EXPENSE_NAME c/COST`.
*   Items in square brackets `[ ]` are optional e.g. `n/EXPENSE_NAME [t/TAG]` can be used as `n/Laksa t/Food`.
*   Items in round brackets `( )` with `|` are mandatory parameters where a selection is needed e.g. `tag (add | delete)` means you need to input either `tag add` or `tag delete`.
*   Items with `...` after them can be used multiple times including zero times e.g. `[t/TAG] …` can be used as ` ` (i.e. 0 times), `t/Food t/Dinner` etc.
*   Parameters can be in any order e.g. if the command specifies `n/EXPENSE_NAME c/COST`, `c/COST n/EXPENSE_NAME` will achieve the same outcome.


=== Adding an expense: `add expense`

Format: `add expense n/EXPENSE_NAME c/COST [t/TAG]...`

TIP: The default currency is in Singapore Dollars (SGD). You are recommended to `convert` foreign currencies to SGD before adding the value as the COST.

Examples:

*   `add expense n/Laksa c/10.50 t/Lunch t/Food`
*   `add expense n/Travel c/53 t/Travel`

Expected output:

*   `New entry added: 1. [-] Laksa ($10.50) [Lunch][Food]`
*   `New entry added: 2. [-] Travel ($53) [Travel]`


=== Adding an income: `add income`

Format: `add income n/INCOME_NAME c/COST [t/TAG]...`

Examples:

*   `add income n/Allowance c/1000 t/Monthly`

Expected output:

*   `New entry added: 3. [+] Allowance ($1000) [Monthly]`

=== Deleting a Transaction: `delete`

Format: `delete i/INDEX`

****
* Deletes the transaction at the specified `INDEX`.
* `INDEX` refers to the index number currently shown in the UI (after filtering, if any).
* `INDEX` *must be a positive integer* 1, 2, 3, ...
****

Examples:

*   `delete i/1`

Expected output:

*   `Entry deleted: 1. Laksa ($10.50) [Lunch][Food]`


=== Generate an external report `[coming in v2.0]`

With this feature, you will be able to save your monthly budget report into an external file for your record purposes. The report will clearly state your expenditure, income and remaining budget for the month.


=== Recommend dining options based on budget `[coming in v2.0]`

Depending on your remaining budget and the remaining days to the end of the month, THRIFT will recommend you dining places in NUS which will suit your budget. For example, if you are running low on funds, you might get recommended to travel to the Arts canteen to eat since there are really cheap options there.


=== Encryption of THRIFT data `[coming in v2.0]`

If you are especially conscious about having your data spied on, this function will definitely ease your worries. With encryption enabled, your data will not be known to the intruder should they steal your THRIFT application data.

== FAQ

*Q*: How do I transfer my data to another Computer?

*A*: Install the application in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous THRIFT installation.

== Command summary
* *Expense*:  `add expense n/EXPENSE_NAME c/COST [t/TAG]...` +
Example: `add expense n/Laksa c/10.50 t/Lunch t/Food`
* *Income*: `add income n/INCOME_NAME c/COST [t/TAG]...` +
Example: `add income n/Allowance c/1000 t/Monthly`
* *Delete*: `delete i/INDEX` +
Example: `delete i/1`
