= THRIFT - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W12-2/main

By: `Team THRIFT`      Since: `Sept 2019`      Licence: `MIT`

== Introduction
THRIFT is for money-conscious NUS students who wish to track their spending, in order to make better informed decisions when it comes to saving money. Maintain records of your daily incoming and outgoing transactions and constantly keep track of your spending and income! THRIFT is optimized for those who prefer to work with a Command Line Interface (CLI) while still enjoying the benefits of having a Graphical User Interface (GUI). If you want a simple, no-frills finance tracker, look no further than THRIFT!



== Quick Start
1. Ensure that you have Java `11` or above installed in your Computer.
2. Download the latest THRIFT.jar https://github.com/AY1920S1-CS2103T-W12-2/main/releases[here].
3. Copy the file to the folder you want to use as the home folder for your THRIFT application.
4. Double-click the file to start the app, the GUI should appear in a few seconds.
5. Type the command in the command box and press `Enter` to execute it. e.g. typing `help` and pressing `Enter` will open the help window.
6. Some example commands you can try:
*   `add expense n/Apple Airpods c/200`: adds an expense called `Apple Airpods` which cost $`200`.
*   `add income n/Bursary Award c/350`: adds an income called `Bursary Award` which incremented your budget by $`350`.
*   `delete i/1`: deletes the 1st transaction in the current list shown in the UI.


== Features:

Command format:

*   Words in `UPPER_CASE` are parameters to be supplied by the user e.g. `expense n/EXPENSE_NAME c/COST`.
*   Items in square brackets `[ ]` are optional e.g. `n/EXPENSE_NAME [t/TAG]` can be used as `n/Laksa t/Food`.
*   Items in round brackets `( )` with `|` are mandatory parameters where a selection is needed e.g. `tag (add | delete)` means you need to input either `tag add` or `tag delete`.
*   Items with `...` after them can be used multiple times including zero times e.g. `[t/TAG] …` can be used as ` ` (i.e. 0 times), `t/Food t/Dinner` etc.
*   Parameters can be in any order e.g. if the command specifies `n/EXPENSE_NAME c/COST`, `c/COST n/EXPENSE_NAME` will achieve the same outcome.

[[ExpenseTag]]
=== Adding an expense: `add expense`

Format: `add expense n/EXPENSE_NAME c/COST [t/TAG]...`

TIP: The default currency is in Singapore Dollars (SGD). You are recommended to `convert` foreign currencies to SGD before adding the value as the COST.

Examples:

*   `add expense n/Laksa c/10.50 t/Lunch t/Food`
*   `add expense n/Travel c/53 t/Travel`

Expected output:

*   `New entry added: 1. [-] Laksa ($10.50) [Lunch][Food]`
*   `New entry added: 2. [-] Travel ($53) [Travel]`

[[IncomeTag]]
=== Adding an income: `add income`

Format: `add income n/INCOME_NAME c/COST [t/TAG]...`

Examples:

*   `add income n/Allowance c/1000 t/Monthly`

Expected output:

*   `New entry added: 3. [+] Allowance ($1000) [Monthly]`

[[DeleteTag]]
=== Deleting a Transaction: `delete`

Format: `delete i/INDEX`

****
* Deletes the transaction at the specified `INDEX`.
* `INDEX` refers to the index number currently shown in the UI (after filtering, if any).
* `INDEX` *must be a positive integer* 1, 2, 3, ...
****

Examples:

*   `delete i/1`

Expected output:

*   `Entry deleted: 1. Laksa ($10.50) [Lunch][Food]`

// tag::update[]
[[UpdateTag]]
=== Updating a Transaction’s details: `update`

Format: `update i/INDEX | PREFIX_LETTER/UPDATED_DETAILS`

****
* Updates the Transaction's details at the specified `INDEX`.
** `INDEX` refers to the index number currently shown in the UI, and must be a *positive integer*.
* `PREFIX_LETTER` specifies type of detail to be updated, e.g. `n/` for name.
* `UPDATED_DETAILS` are the new details of type corresponding to `PREFIX_LETTER` that the Transaction is to be updated with.
****

Examples:

*   `update i/1 | n/Curry Laksa`
*   `update i/1 | c/11`

Expected output: +

NOTE: Assume 2nd command occurs after 1st

*   `Entry name updated: 1. [-] Curry Laksa ($10.50) [Lunch][Food] +
Original name was: Laksa`
*   `Entry cost updated: 1. [-] Curry Laksa ($11) [Lunch][Food] +
Original cost was: $10.50`
// end::update[]

// tag::clone[]
[[CloneTag]]
=== Cloning a Transaction: `clone`

Format: `clone i/INDEX`

****
* Clones (creates a duplicate of) a Transaction.
* Clone produced is added to a new index at the bottom of the list.
****

Examples:

*   `clone i/1`

Expected output: +

NOTE: Assume entry at index 1 is `1. [-] Laksa ($10.50) [Lunch][Food]` and there are no other entries.

*   `New entry added: 2. [-] Laksa ($10.50) [Lunch][Food]`
// end::clone[]

[[UndoTag]]
=== Undoing the previous undoable command: `undo`

Format: `undo`

NOTE: Undoable commands are commands that modify the data of THRIFT application.

.List of undoable commands[[Undoable]]:
* <<Adding an expense: `add expense`, add expense>>
* <<Adding an income: `add income`, add income>>
* <<Deleting a Transaction: `delete`, delete>>
* update
* clone
* tag

Examples:

* `add expense n/Laksa c/10.50 t/Lunch t/Food` +
  `undo`

* `add income n/Allowance c/1000 t/Monthly` +
  `list` +
  `undo`

Expected output:

* Deletes the expense spent on Laksa from THRIFT.
* Deletes the allowance income from THRIFT.

[[RedoTag]]
=== Redoing the undone command: `redo`

Redo the <<Undoable, undoable command>> that was previously undone by the user.

Format: `redo`

Examples:

* `add expense n/Laksa c/10.50 t/Lunch t/Food` +
  `undo` +
  `redo`

Expected output:

* Adds the expense spent on Laksa back to THRIFT.

[[ListTag]]
=== List expenses for the month: `list`

Format: `list [m/MONTH] [t/TAG]`

Examples:

*  `list`
*  `list m/Jan t/Food`

Expected output:

* Returns a list of all expenses for the current month.
* Returns a list of all food expenses for the specified month.

[[HelpTag]]
=== Displaying help page: `help`

Format: `help [COMMAND]`

Examples:

* `help`
* `help delete`

Expected output:

* Displays a detailed list of information regarding all the THRIFT commands.
* Returns syntax of `delete` command.

[[ExitTag]]
=== Exiting THRIFT application: `exit`

Format: `exit`

=== Generating an external report `[coming in v2.0]`

With this feature, you will be able to save your monthly budget report into an external file for your record purposes. The report will clearly state your expenditure, income and remaining budget for the month.


=== Recommending dining options based on budget `[coming in v2.0]`

Depending on your remaining budget and the remaining days to the end of the month, THRIFT will recommend you dining places in NUS which will suit your budget. For example, if you are running low on funds, you might get recommended to travel to the Arts canteen to eat since there are really cheap options there.


=== Encrypting THRIFT data `[coming in v2.0]`

If you are especially conscious about having your data spied on, this function will definitely ease your worries. With encryption enabled, your data will not be known to the intruder should they steal your THRIFT application data.

== FAQ

*Q*: How do I transfer my data to another Computer?

*A*: Runs the application in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous THRIFT application.

== Command summary
* <<ExpenseTag, *Expense*>>:  `add expense n/EXPENSE_NAME c/COST [t/TAG]...` +
Example: `add expense n/Laksa c/10.50 t/Lunch t/Food`
* <<IncomeTag, *Income*>>: `add income n/INCOME_NAME c/COST [t/TAG]...` +
Example: `add income n/Allowance c/1000 t/Monthly`
* <<DeleteTag, *Delete*>>: `delete i/INDEX` +
Example: `delete i/1`
* <<UpdateTag, *Update*>>: `update i/INDEX | PREFIX_LETTER/UPDATED_DETAILS` +
Example: `update i/1 | n/Curry Laksa`
* <<CloneTag, *Clone*>>: `clone i/INDEX` +
Example: `clone i/1`
* <<UndoTag, *Undo*>>: `undo`
* <<RedoTag, *Redo*>>: `redo`
* <<ListTag, *List*>>: `list [m/MONTH] [t/TAG]` +
Example: `list m/Jan t/Food`
* <<HelpTag, *Help*>>: `help [COMMAND]` +
Example: `help delete`
* <<ExitTag, *Exit*>>: `exit`
