= PowerLifting Competition Coordinator- User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103-T11-3/main

By: `Team CS2103-T11`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

A powerlifting competition/meet consists of 3 lifts, the Squat, Bench and Deadlift. With 3 attempts, athletes will try to outdo and challenge themselves and lift as heavy as they can. 

This software is for organisers who organise powerlifting competitions. To facilitate the ease of data-entry, we have provided a command line interface that is augmented with a Graphical User Interface to help them better administer powerlifting competitions.


== Quick Start

Download the software from our git repo.
Ensure Java 11 is downloaded into your machine.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== Competitions
The commands listed below in 3.2, 3.3, … are based on the context of a competition.

==== Context: No Competition
*Commands*

* Save: this changes the context to `Creating a competition`
* Select: changes the context of a `Competition`

==== Context: Creating a Competition
*Parameters*

* name
* date
* Type

*Commands*

* Save

==== Context: On a Competition
*Commands*

* Athletes
* List

*Prints a list of competitions*

* Finalise

*Parameters*

* Id
* name

*Marks the competition as completed and prevents further edits*

* Switch

*Parameters*

* id
* name

*Switch context to a different competition*

* Delete

*Parameters*

* Id
* name

=== Getting Competitors’ Data

==== Sorting Athletes: `sort`

Groups and sorts all athletes into their respective weight classes or attempted weights for an event.

Format: `sort wc/WEIGHTCLASS`

Format: `sort aw/EVENT`

Example(s):

* `sort wc/90kg`
* `sort aw/Squat`

==== Getting top scorers: `score`
Gets and displays leading athletes and their scores for individual events or for their total scores.

Format: `score e/EVENT t`

Examples:

* to get scores for individual events only:
  `score e/Squat`

* to get total scores only
  `score t`

==== Getting rank of an athlete: `rank`
Gets current position of an athlete relative to other relatives for the entire competition.

Format: `rank n/NAME`

Examples:

* `rank n/John`

==== Affiliation of an athlete: `aff`
Gets the name of an organisation and a country, an athlete is associated with.

Format: `aff n/NAME`

Examples:

* `aff n/John`

==== Edit data of an athlete: `edit`
Edits field(s) of information belonging to an athlete

Format: `edit n/CURRENTNAME newN/NEWNAME bw/BODYWEIGHT wc/WEIGHTCLASS aff/AFFILIATION s/SCORE`

Examples:

* To edit name only:
  `edit n/John newN/Johnny`
  
* To edit bodyweight only:
  `edit n/John bw/100kg`
  
* To edit subset of fields:
  `edit n/John newN/Johnny wc/100kg aff/Singapore`
  
* To edit all fields:
  `edit n/John newN/Johnny bw/90 wc/90 aff/Singapore s/1000`

==== Get top 3 athletes: `top3`
Gets top 3 athletes (currently in 1st, 2nd and 3rd) for each weight class.

Format: `top3 wc/WEIGHTCLASS`

Examples:
`top3 wc/100kg`

=== Participation
This feature handles the entire flow of each session during Meet Day. It allows event organisers to submit Athlete’s Squat, Bench, Deadlift attempts, as well as the success of their lifts. It will show the relevant information to prepare for the athletes lift (displaying name, weight, rack height, etc). 


=== Listing all persons : `list`

Shows a list of all persons in the address book. +
Format: `list`

=== Editing a person : `edit`

Edits an existing person in the address book. +
Format: `edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]...`

****
* Edits the person at the specified `INDEX`. The index refers to the index number shown in the displayed person list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the person will be removed i.e adding of tags is not cumulative.
* You can remove all the person's tags by typing `t/` without specifying any tags after it.
****

Examples:

* `edit 1 p/91234567 e/johndoe@example.com` +
Edits the phone number and email address of the 1st person to be `91234567` and `johndoe@example.com` respectively.
* `edit 2 n/Betsy Crower t/` +
Edits the name of the 2nd person to be `Betsy Crower` and clears all existing tags.

=== Locating persons by name: `find`

Finds persons whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Persons matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `find John` +
Returns `john` and `John Doe`
* `find Betsy Tim John` +
Returns any person having names `Betsy`, `Tim`, or `John`

// tag::delete[]
=== Deleting a person : `delete`

Deletes the specified person from the address book. +
Format: `delete INDEX`

****
* Deletes the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd person in the address book.
* `find Betsy` +
`delete 1` +
Deletes the 1st person in the results of the `find` command.

// end::delete[]
=== Clearing all entries : `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...` +
e.g. `edit 2 n/James Lee e/jameslee@example.com`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
* *Help* : `help`
