= NJoy - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W13-2/main

By: `Team AY1920S1-CS2103T-W13-2`      Since: `September 2019`      Licence: `MIT`

== Introduction

*Creating and managing your students and classes have never been easier.* Njoy assistant aims to enable teachers to easily manage their students and activities right from their keyboard. With just a few commands, you will be able to *manage your classes, create questions, generate quizzes and much more!*

== Features

. *Manage your classes* easily with just a few strokes of your keyboard.
.. Attendance taking
//.. Note taking
.. Record student scores
. *Creating questions* is simple. Simply type a topic and an answer and it is done.
.. Easy input
.. Repeatable
. *Generate quizzes* for your students.
.. Type once, generate anytime
.. Randomised
.. Distribute
. *Timetable Manager* for scheduling your classes.
.. Create and manage
.. Schedule classes
.. Class Reminders
.. Repeatable daily/monthly and even yearly
. *Statistics* provide a comprehensive view of your students' performance.
.. View underperforming students
.. Trends of the academic year

== Getting Started

=== Running .jar file
. Download the njoy.jar file
. Double click on ‘njoy.jar’ file to run the application

_If you are not able to run the application using the method above, use the following:_ +
. Open Terminal(Mac)/Command Prompt(Windows)
. Type cd [path to directory containing jar file]
. Type ‘java -jar njoy.jar’ to run the application.

== Commands

*Command Format*
====
All commands start with a forward slash “/” followed by the command name. Certain commands may include additional options and will be specified in the description. An optional field will be marked ​(optional) b​ eside the field.
====

=== Student ​- `/student`

Create and edit students.

. *Create student* - `/student create [name] [birthdate in DD/MM/YYYY format]​(optional)` +
e.g. `/student create “John” “20/09/2006”` +
*Return*: student no.
. *Edit student* ​- `/student edit [student no.]` +
e.g. `/student edit 1` +
*Return*:​ Options to edit name or birthdate
. *Delete student* ​- `/student delete [student no.]`  +
e.g. `/student delete 1`
. *Find student* ​- `/student find [name]` +
e.g. `/student find “John”` +
*Return*:​ student no.


=== Class​ - `​/class`

Manage classes and manage students within the class.

. *Create class*​ - `/class create [class id] [description]​(optional)` +
e.g. `/class create unity “My First Class”`
. *Edit class description* ​- `/class edit [class id] [description]​(optional)` +
e.g. `/class edit unity “My Second Class”`
. *Delete class* ​- `/class delete [class id]` +
e.g. `/class delete unity`
. *Add student to class* ​ - `/class add [class id] [student no.]` +
e.g. `/class add unity 1`
. *Remove student from class* ​ - `/class remove [class id] [student no.]` +
e.g. `/class remove unity 1`

=== Timetable​ - `​/timetable`

Manage timetable and schedule class timings

. *Schedule class time* ​- `/timetable schedule [class id] [date & time in DD/MM/YYYY HH:mm format] [description]​(optional)` +
e.g. `/timetable schedule unity “18/11/2019 11:00” “Math class”` +
*Return*: ​schedule id.
. *View schedule for all classes​* - `/timetable view all` +
e.g. `/timetable view all` +
*Return*: ​schedule id, class id, class name, date time, description
. *View schedule for specific class​* - `/timetable view [class id]` +
e.g. `/timetable view unity` +
*Return*: ​schedule id, class id, class name, date time, description
. *Delete scheduled class time* ​- `/timetable delete [schedule id]` +
e.g. `/timetable delete 1`

=== Attendance ​-​ `/attendance`

View and mark student’s attendance.

. *View attendance* ​- `/attendance show` +
e.g. `/attendance show`
. *Mark attendance* ​- `/attendance check [class id] [student no.]` +
e.g. `/attendance check unity 1`

////
=== Notes ​- ​`/notes`

Notes can be specified under general or class. Specifying a class note will allow you to view
notes specific to a class.

. *View all notes* ​- `/note view all` +
e.g. `/note view all`
. *View general note* ​- `/note view general` +
e.g. `/note view general`
. *View class note* ​- `/note view class [class id]` +
e.g. `/note view class unity`
. *Create general note​* - `/note create general “[description]”` +
e.g. `/note create general “Remember to attend cca briefing”`
. *Create class note* ​- `/note create class “[class id]” “[description]”` +
e.g. `/note create class unity “Remember to meet john after class”`
////

=== Generating Questions ​-​ `/question`

Create and store questions according to the type specified.

. *Open ended questions* ​- `/question open “[topic]” “[answer]”` +
e.g. `/question open “Which year did Singapore gain independence?” “1965”`
. *MCQs* ​- `/question mcq “[topic]” “[answer]” “[option1]” “[option2]” “[option3]” “[option 4]”` +
e.g `​/question mcq “Which year did Singapore gain independence?” “1965” “1963” “2019” “1926” “1965”`

=== Quizzes ​-​ `/quiz`

Create and store quizzes using questions specified. Users are also able to edit the quizzes after creation.

. *Creating quizzes manually* ​- `/quiz manual/ quizID/[quizName] questionNumbers/[questionNumbers]` +
e.g. `/quiz manual/ quizID/CS2103T_Quiz questionNumbers/1 2 3`
This creates a quiz named "CS2103T_Quiz" and adds question numbers 1, 2 and 3 from the question bank to the quiz.
. *Creating quizzes automatically* ​- `/quiz auto/ quizID/[quizName] numQuestions/[numberOfQuestions] type/[typeOfQuestion]` +
e.g. `/quiz auto/ quizID/CS2103T_Quiz numQuestions/3 type/open`
This creates a quiz named "CS2103T_Quiz" and adds 3 questions from the question bank to the quiz, ensuring there are no duplicates.
. *Adding questions to quizzes* ​- `/quiz add quizID/[quizName] questionNumber/[questionNumber] quizQuestionNumber/[quizQuestionNumber]` +
e.g. `/quiz add quizID/CS2103T_Quiz questionNumber/1 quizQuestionNumber/3`
This adds the question number 1 from the question bank to the quiz "CS2103T_Quiz"'s question number 3, shifting questions previously at or after question 3, down by 1 question. I.e question 3 becomes question 4, question 4 becomes question 5 to accomodate for the added question.
. *Removing questions from quizzes* ​- `/quiz remove quizID/[quizName] quizQuestionNumber/[quizQuestionNumber]` +
e.g. `/quiz remove quizID/CS2103T_Quiz quizQuestionNumber/3`
This removes the question number 3 from the quiz "CS2103T_Quiz", shifting questions previously after question 3, up by 1 question. I.e question 4 becomes question 3, question 5 becomes question 4 to acoomodate for the removed question.
. *List all questions and answers in a readable format* ​- `/quiz list quizID/[quizName]` +
e.g. `/quiz list quizID/CS2103T_Quiz`
This fetches the quiz named "CS2103T_Quiz" and displays all the questions followed by answers of the quiz.

=== Help ​-​ `/help`

Show all available commands usable in the application.

== FAQ

*Q*: Typing a command result in “Invalid command entered.” +
*A*: Please ensure that the command is entered as specified in the format above. Note that all fields all mandatory except those marked as ​(optional).​
