= Budget Buddy - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W13-4/main

By: `CS2103T W13-4`

== Introduction

Budget Buddy is for computing students who prefer to use a desktop app to manage their expenses.
More importantly, Budget Buddy is *optimized for those who prefer to work with a Command Line Interface* (CLI)
while still having the benefits of a Graphical User Interface (GUI).
If you can type fast, Budget Buddy can get your expense management tasks done faster than traditional GUI apps.
Furthermore, Budget Buddy allows computing students to add their own functions through customized JavaScript files,
as well as a set of rules to simplify expense tracking.

== Quick Start

Nothing to see here.

[[Features]]
== Features

====
*Command Format*

* Words within `<>` brackets are parameters to be supplied by the user.
* Parameters within `[]` brackets are optional and can be omitted.
* `|` indicates that a choice must be made between two parameters.
* `...` indicates a variable number (at least 1) of the specified parameter.
====

=== Viewing help : `help`

Displays help. If `command` is specified, view detailed help for that command.

Format: `help [<command]>`

=== Manage defaults : `default`

==== Set default account : `default account`

Sets the default account.

Format: `default account <id>`

=== Manage the main transaction view : `view`

==== Filter transactions : `view filter`

Filters the main transaction view. If no arguments are provided, all transactions are shown.
Otherwise, only transactions meeting all the criteria are shown.

Format: `view filter [a/<account>] [c/<category>] [f/<from date>] [t/<to date>]`

==== Sort transactions : `view sort`

Sorts transactions by (a)ccount, (c)ategory, (d)ate or (x)amount.
Specify `o/a` to sort in ascending order, or `o/d` to sort in descending order.
If omitted, sort in ascending order.

Format: `view sort s/<a|c|d|x> [o/<a|d>]`

=== Managing transactions : `transaction`

==== Add a transaction : `transaction add`

Adds a new transaction of the specified amount and with the given description.

Format: `transaction out|in x/<amount> d/<description> [a/<account>] [c/<category>] [w/<date>] [r/<d|w|m|y>]`
****
* If the account is not given, the transaction is inserted into the default account.
* If the category is not given, the transaction is not categorised.
* If the date is not given, the date is set to the current date.
* If the argument ‘r’ is added, the transition is marked as recurring;
identical entries will be added either daily, weekly, monthly, or yearly.
****

==== Edit a transaction : `transaction edit`

Edits the specified transaction, setting the specified fields.
If the ‘recurring’ field is modified, the app will ask if all previous recurring entries should be deleted.

Format: `transaction edit <id> out|in [x/<amount>] [d/<description>] [a/<account>] [c/<category>] [w/<date>] [r/<d|w|m|y>]`

==== Delete transaction(s) : `transaction delete`

Deletes the transactions with the specified IDs.

Format: `transaction delete <id ...>`

=== Managing accounts : `account`

==== Add an account : `account add`

Creates a new account with the given name. If the currency symbol is not specified, “$” is used.

Format: `account add n/<name> [c/<currency symbol>]`

==== List accounts : `account list`

Lists all accounts.

==== Edit an account : `account edit`

Edits the specified account, setting the specified fields.

Format: `account edit <id> [n/<name>] [c/<currency symbol>]`

==== Delete account(s) : `account delete`

Deletes the accounts with the specified IDs, as in `account list`.
Note: you cannot delete an account if there are transactions associated with the account.

Format: `account delete <id ...>`

=== Managing categories : `category`

==== Adding a category

Categories do not need to be added; you can simply use the category name and a new category will be created if no such one exists.

==== List categories : `category list`

Lists all categories.

==== Rename a category : `category rename`

Renames the specified category.
Note that this is the same as setting the category of all transactions of category `old name` to `new name`.

Format: `category rename o/<old name> n/<new name>`

==== Delete a category : `category delete`

Deletes the specified category.
Note that this is the same as un-categorising all transactions under the specified category.

Format: `category delete n/<name>`

=== Viewing reports : `report`

Displays a report.

Format: `report [[f/<from date>] [t/<to date>] | [p/<this month|last month|this week|last week|today|yesterday>]] [total|category]`
****
* You can specify either the start and end date range, inclusive, or name a period.
If no period is specified, it defaults to the current month-to-date.
* You can see a total report that shows your total income and expenditure and budget information,
if a budget has been set up,  or a report that breaks your income and expenditure down into categories.
If the type is omitted, it defaults to a total report.
* Your goal progress will also be shown in both reports.
****

=== Managing budgets : `budget`

Displays or sets the budget for the specified period.
If the period is omitted, it defaults to the entire current month.

Format: `budget [[f/<from date>] [t/<to date>] | [p/<this month|last month|this week|last week|today|yesterday>]] [<amount>|unset]`

==== Viewing budgets

To view budgets, omit `[<amount>|unset]` from the command.
All budgets overlapping the period specified will be displayed.

==== Setting budgets

To set a budget, specify the `[<amount>]`. Note that budgets cannot overlap.

==== Removing budgets

To unset a budget, specify `[unset]`.

=== Goal setting : `goal`

==== Adding a goal : `goal add`

Adds a goal on the specified account to reach the specified amount by the target date or at the end of the specified period.

Format: `goal add [a/<account>] [[d/<target date>] | [p/<this week|this month|next month|this year>]] x/[+]<amount>`
****
* If the account is omitted, the default account is set.
* If the period is omitted, the target date is set to the last day of the current month.
* If + is specified before amount, then the target amount is set as amount more than the current balance in the target account.
****

==== View goals : `goal list`

List all goals.

==== Delete goal(s) : `goal delete`

Deletes the goals with the specified goal IDs. Goal IDs can be retrieved from `goal list`.

Format: `goal delete <id ...>`
=== Tracking loans : `loan`

==== Add a new loan : `loan out|in`

Adds a new loan out/in entry.
Each entry has a unique ID (across both out and in entries).
If date is not given, it is set to the default date.

Format: `loan out|in x/<amount> d/<description> [w/<date>]`

==== List loans : `loan list`

Displays a list of all loans, sorted by newest first.

Format: `loan list [o|i] [s/a]`
****
* Adding ‘o’ argument filters list to out loans only.
* Adding ‘i’ argument filters list to in loans only.
* Add `s/a` to sort the list by amount.
****

==== Edit loan : `loan edit`

Edits the specified field of the loan entry with the specified ID.

Format: `loan edit <id> [x/<amount>] [d/<description>] [w/<date>]`

==== Mark loan(s) as paid : `loan paid`

Marks the specified loan(s) as paid.

Format: `loan paid <id ...>`

==== Delete loan(s) : `loan delete`

Deletes the loan(s) with the specified loan ID(s).

Format: `loan delete <id ...>`

==== Calculate loans : `loan split`

Splits and calculates a group payment, then prints a list of who owes who.

Format: `loan split n/<name> a/<amount paid> ...`

=== Import and export : `import, export`

==== Import a file : `import`

Imports transactions from the file at the given path.

Format: `import [f/<format>] [p/<file path>]`
****
* The file path can be relative to where you launched Budget Buddy from, or absolute.
If the path is omitted, a file browser is opened for you to select the file.
* Format is one of dbs (DBS Bank/POSB), ocbc (OCBC Bank), sc (Standard Chartered), csv (generic comma-separated values file).
If the format is omitted, automatic detection is attempted.
****

==== Export transactions : `export`

Exports all transactions to the given path.

Format: `export [p/<file path>]`
****
* The file path can be relative to where you launched Budget Buddy from, or absolute.
If the path is omitted, a file browser is opened for you to select where to save the file.
* The file is a comma-separated values file.
****

== FAQ

== Command Summary
