= Jarvis - User Guide
:nus-grades: http://www.nus.edu.sg/registrar/education-at-nus/modular-system.html
:nusmods-modules: https://nusmods.com/modules
:cs-focus-areas:  https://www.comp.nus.edu.sg/programmes/ug/focus/
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-T10-1/main

By: `Team T10-1`      Since: `Sep 2019`      Licence: `MIT`

== Introduction

Ensure you have https://www.java.com/en/download/[Java 11] or above installed
on your PC.

Jarvis is your personal student assistant. She is able to manage your
schoolwork and finances. Jarvis offers four main features to bolster your
productivity, he is able to track your:

1. **Tasks**
2. **CCA Life**
3. **Finances**
4. **Courses Taken**

Jarvis also supports undo and redo functionality, allowing you easily
undo and redo any mistakes that you may make in your application.

== Quick Start

Ensure you have https://www.java.com/en/download/[Java 11] or above installed
on your PC.

Download the latest `Jarvis` https://www.google.com/[here].

Copy the downloaded file to the folder that you would like to use as the
home folder for `Jarvis`.

Double-click `jarvis.jar` to start the app. The GUI will appear in a few
seconds.

== Features

=== Command Format

1. Words in `UPPER CASE` are the parameters supplied by the user, while those
in `lower case` are **key-words** used by the program.
+
For example:
+
`add-task t/TASK-TYPE des/TASK-DESCRIPTION`
+
In this case, `TASK-TYPE` and `TASK-DESCRIPTION` are parameters supplied by
the user, and `add-task` is a key-word.

2. Items in square brackets `[]` are optional fields with the command.
+
For example:
+
`add-task t/TASK-TYPE des/TASK-DESCRIPTION [p/PRIORITY]`
+
Can be used
+
With a priority level:: `add-task t/todo des/assignment p/high`
Without a priority level:: `add-task t/todo des/assignment`

3. Parameters with `...` can be used 0, or any number of items
+
For example:
+
`[#TAG]...` is an optional parameter that can be used 0 or any number of times.
+
Without optional parameter:: `add-task t/todo des/assignment`
With optional parameter:: `add-task t/todo des/assignment #cs2103t #urgent`

4. Jarvis can parse parameters to commands in *any order*.

5. Commands that can take different parameters are represented with a pipe `|`,
surrounded by curly braces, e.g `{param1 | param2}`.
+
For example:
+
`export {csv | txt | xlsx} f/FILENAME`
+
As a .csv file:: `export csv f/MyFile`
With a.txt file:: `export txt f/MyFile`

6. Dates `d/DATE` follow the following format: `DD/MM/YYYY`.
+
For example:
+
`add-task t/todo des/assignment d/01/01/1970`

////
Task Scheduler

Feature by
-> Anisha Nicole Joseph
////
=== Task Scheduler

==== List all tasks: `list-tasks`
Lists all the tasks in the planner.

Format: `list-tasks`

==== Adding a task: `add-task`
Adds a task to the planner.

A task must have a:

* `TASK-TYPE`: `todo`, `event` or `deadline`
* `TASK-DESCRIPTION`: a short description of the task

A task *can* have the following *attributes*:

* `DATE`
* `TAG`: any number of tags, such as `#school` or `#cca`
* `PRIORITY` level: `high`, `medium` or `low`
* `FREQ` frequency: `daily`, `weekly`, `monthly` or `yearly`

|===
| Task Type | Format

|`Todo`
|`add-task t/todo des/TASK-DESCRIPTION [#TAG]... [p/PRIORITY r/FREQ]`

|`Event`
|`add-task t/event des/TASK-DESCRIPTION d/START-DATE//END-DATE [#TAG]... [p/PRIORITY r/FREQ]`

|`Deadline`
|`add-task t/deadline des/TASK-DESCRIPTION d/DUE-DATE [#TAG]... [p/PRIORITY r/FREQ]`
|===

NOTE: Duplicate tasks are not allowed in the Planner!

===== Example
----
add-task t/event des/workshop r/weekly d/25/12/2019//26/12/2019
add-task t/deadline des/cs2101 assignment d/20/09/2019 p/high
----

==== Deleting a task: `delete-task`
Deletes a task from the planner.

Format: `delete-task INDEX`

where `INDEX` is the **one-based** index of the task list.

===== Example
----
delete-task 3
----

==== Finding a task: `find-task`
Locates a task by task description from a given `KEYWORD`

Format: `find-task KEYWORD...`

===== Example
----
find-task assignment
find-task homework cs ma1101r
----

==== Editing a task: `edit-task` [v1.4]
Edits the task at the specified index.

Format: `edit-task INDEX//NEW-DESCRIPTION...`

`NEW-DESCRIPTION` can be a new task description or any of the other attributes (refer to 3.2.2 Adding a Task)
used to create a task. You can also edit any number of attributes at the same time, each separated with a space.
However, only one instance of each attribute is allowed per command.

NOTE: `NEW-DESCRIPTION` must be tagged with the attribute prefix. For example, if you want to edit the task description
and priority level of a task: `edit-task INDEX//des/NEW-TASK-DESCRIPTION p/NEW-PRIORITY-LEVEL`.

===== Example
----
edit-task 1//des/project part 2
edit-task 2//des/project part 2 d/18/09/2019
edit-task 3//r/weekly
----

==== Updating a task's status: `done-task`
Updates the status of a task. By default on `add-task`, all tasks are marked
as undone, represented by a `[✗]`. Upon finishing the task, the task will be
represented with a `[✓]`.

Format: `done-task INDEX`

where `INDEX` is the **one-based** index of the task list.


==== Clearing entries: `clear-task` [v1.4]
Clears tasks from the planner. Tasks can be cleared by `#TAG` or `d/DATE`.
The command `clear-task` with no parameters succeeding it will result in all tasks
being cleared.

Format: `clear-task [#TAG]... [d/DATE]`

===== Example
----
clear-task #school
clear-task d/12/09/2019
----

////
Finance Tracker

Feature by
-> Goh Si Ning
////
=== Where did all my money go?
Introducing the **Finance Tracker** feature of Jarvis, which is responsible for keeping track of all your purchases,
monthly subscriptions and debts owed. Upon switching to the Finance tab, you will be able to see a list of purchases on
the left and a list of your monthly subscriptions on the right. The circle in the middle indicates how much you have
spent in relation to the spending limit set and you can see your "monthly expenses" right below that. How neat!

//todo: add a ui ss

As students, we often forget what we have spent on so far, which makes it hard for us to save since we do not know how
much we are spending. But do not worry, as here's what the Finance Tracker can
do for you:

==== Add a single-use purchase: `add-paid`
So you bought another cup of GongCha at UTown? Let's put that in.

This command adds a single purchase (with a description and a price) to the finance tracker.
Don't worry about remembering __when__ you made your purchase, as Jarvis will automatically store it to today's date!
Jarvis will then also update your monthly expenses accordingly.

Format: `add-paid d/PURCHASE-DESCRIPTION a/AMOUNT`

===== Example
----
add-paid d/GongCha a/2.8
add-paid d/GongCha a/2.89
----


==== Delete a single-use purchase: `delete-paid`
Did you return something you bought on Zalora recently? Welp, I guess that's one less purchase you made this month.

This command tells Jarvis to remove the purchase at the given index on the list of purchases shown on the Finance tab.
Jarvis will also update your monthly expenses accordingly, which also means you have more remaining budget left!

Format: `delete-paid INDEX`

NOTE: `INDEX` corresponds to index shown on the list "What I bought this month..." under the Finance tab. This also
means that the index must exist within this list!


==== Searching for a purchase: `find-purchases`
Ever wondered how many cups of GongCha you bought over the past month? Brace yourself for the truth.

Jarvis can help you search for your purchases that match whatever keyword you give it!

Format: `find-purchases KEYWORD`

===== Example
----
find-purchases GongCha
----


==== Add a monthly subscription: `add-install`
Who can resist the plethora of shows to watch on Netflix? So you decided to jump on the bandwagon and subscribe to it
as well.

Let's tell Jarvis to store this new installment. Don't forget to key in the description and the amount you
have to pay monthly so Jarvis can automatically keep track of this every month from now on!

Format: `add-install d/INSTALLMENT-DESCRIPTION a/AMOUNT`

===== Example
----
add-install n/Netflix a/13.0
add-install n/Spotify a/9.50
----


==== Delete a monthly subscription: `delete-install`
But alas, finals are approaching, and you decided to remove all distractions to help you better study. Unfortunately,
this means deleting your Netflix account.

This command will tell Jarvis to remove the installment at the given index on the list of installments shown on the
Finance tab. Jarvis will also update your monthly expenses accordingly.

Format: `delete-install INDEX`

NOTE: `INDEX` corresponds to index shown on the list "What I spend on monthly..." under the Finance tab. This also
means that the index must exist within this list!


==== Edit an installment: `edit-install`
Spotify just released a new student plan? Great, that means a lower subscription fee every month!

Let's inform Jarvis of the changes using the index of the installment on the list "What I spend on monthly..." under
the Finance tab. You can either change the description or the amount or both.

Format: `edit-install INDEX {d/INSTALLMENT-DESCRIPTION | a/AMOUNT}`

===== Example
----
edit-install 1 a/10
edit-install 2 d/Spotify student plan
edit-install 2 d/Spotify student plan a/7.50
----


==== Setting a monthly spending limit: `set-limit`
It's the season to stop spending so much!

Let Jarvis keep track of how much you have limited yourself to spend this month. Simply set the limit to the
Finance Tracker.

Format: `set-limit a/AMOUNT`

===== Example
----
set-limit a/300
set-limit a/500.90
----

If no monthly limit has been specified, the program will show:

`Oops, there does not seem to be a monthly limit.`

==== Listing finances: `list-finances`
Jarvis will switch you onto the Finance tab if you are not already there. If you have previously searched through your
purchases for something, then Jarvis returns you to the original list of purchases.

Format: `list-finances`


==== Export to File: `export`
A feature coming to you in v2.0!

Want to keep a record of your finances for this month? Simple export your current expenditures to a file, either
as a `.txt`, `.csv` or `xlsx` format.

Format: `export {csv | txt | xlsx} f/FILENAME`

===== Example
----
export csv f/expenditures
----

NOTE: Jarvis will create a file called `expenditures.csv` in the current directory, containing all expenditures.


////
Module Lookup

Feature by
-> Ryan Tan Yu
////
=== Course Planner

==== Add a course: `add-course`
Adds the specified course(s) to your list.

Format: `add-course c/COURSE-CODE [c/COURSE-CODE]...`

`COURSE-CODE` may be the code of any {nusmods-modules}[NUS course] and you
are able to specify multiple courses to add.

===== Example
----
add-course c/CS1010
add-course c/CS1010 c/CS2030 c/CS2040
----

==== Delete a course: `delete-course`
Deletes the specified course from your list. You may also delete a course
by its **id** within the list.

Format: `delete-course {c/COURSECODE | INDEX}`

===== Example
----
delete-course c/CS1010
delete-course 2
----

==== Lookup a course's information: `lookup`
Retrieves information about the specified course - such as name, course code,
number of credits and its prerequisites - and displays it on the screen.

Format: `lookup c/COURSECODE`

===== Example
----
lookup c/CS1010
----

==== Check a course: `check`
Checks if you can take the specified course. The result is dependent on the
courses you have added to your list. Jarvis will display a very helpful
tree to show you what requirements you need for each course.

Format: `check c/COURSECODE`

===== Example
----
check c/CS1010
----

////
CCA tracker

Feature by
-> Tan Ye Kai
////
=== CCA tracker

==== Add a CCA: `add-cca`
Add a CCA to your list. You need to to specify the name of the course and the
type of CCA. The types of the CCA will be limited to the following:

. `performingArt`
. `sport`
. `club`
. `uniformedGroup`

Format: `add-cca n/NAME t/TYPE e/EQUIPMENT`

===== Example
----
add-cca n/Swimming t/sport e/swimming trunks e/goggles
add-cca n/Canoeing t/sport e/Boat e/Paddle
add-cca n/Guitar Ensemble t/performingArt e/guitar
----

==== Delete a CCA: `delete-cca`
Deletes the specified CCA by index from your list.

Format: `delete-cca INDEX`

===== Example
----
delete-cca 1
----


==== Edit a CCA: `edit-cca`
Edits the CCA. Note that the keywords in square brackets are optional.

Format: `edit-cca INDEX [n/NAME] [t/TYPE] [e/EQUIPMENT]`

===== Example
----
edit-cca 1 t/sport e/tennis racket
edit-cca 1 t/performingArt
edit-cca 1 n/Running e/shoes e/water bottle
----


==== List a CCA: `list-cca`
List the CCAs that the user is participating in. If user does not participate
in any CCAs, an empty list will be shown.

Format: `list-cca`


==== Find a CCA: `find-cca`
Find a CCA based on keyword. If no such CCA can be found, an empty list will
be shown. Note that you can use any number of keywords.

Format: `find-cca KEYWORD`

===== Example
----
find-cca swimming
find-cca canoeing guitar
----


==== Add progress levels for a CCA: `add-progress`
Adds the progress milestones for the CCA.

Format: `add-progress INDEX p/MILESTONE `

===== Example
----
add-progress 1 p/bronze p/silver p/gold p/gold star
add-progress 2 p/Beginner boat p/Intermediate boat p/Racing boat
add-progress n/Guitar Ensemble l/8
----

==== Increment progress level: `increment-progress`
Increments the progress for a CCA at the specified index.

Format: `increment-progress INDEX`

===== Example
----
increment-progress 1
----

////
Undo/Redo

Feature by
-> Marc Fong Yung Kit
////
=== App History

==== undo
Undo action(s) on the application. This will allow you to roll back certain
actions that you may have accidentally or erroneously done on the application.
Keep in mind that only commands that change the data on the application
are undoable. Commands that render and display information cannot be undone.

The limit of the number of undoable actions you can make in the application is
currently **20** actions.

Format: `undo [r/NUMBER]`

===== Example
----
undo        (undoes the latest action)
undo r/3    (undoes the last three actions)
----


==== redo
Redo action(s) on the application. This will allow you to redo certain
actions, or any accidental or erroneous undo actions. Keep in mind that
only commands that can be undone can be redone. Therefore, only commands
that change the data on the application can be redone as they can be undone.
Commands that render and display information are not actions that can be
undone and hence will not be able to be redone.

The limit of the number of available redo actions you can make in the
application is currently **20** actions.

Take note that if you have undone a certain amount of actions and from that
point, you type in a new command that is not `redo`, the actions available to
be redone will be cleared as of that point, similar to a browser navigation on
a single tab.

Format: `redo [r/NUMBER]`

===== Example
----
redo        (redoes the latest undo)
redo r/3    (redoes the last three undos)
----

== FAQ

'''

**Q:** How is the budget for monthly limit calculated?

**A:** Budget is calculated from the 1st to the last day of every month. The budget is split evenly across all days.

'''

**Q:** What if I am still learning this application and I make a mistake on the application and I do not know how to revert the changes made in my latest command?

**A:** Simple undo the command, the application will revert your changes automatically.

'''

**Q:** How do I know what I am undo-ing?

**A:** enter history into the command line, which will display where you are relative to what you can undo and redo.

'''

**Q:** If I accidentally undo something, can i revert this mistake?

**A:** enter redo to undo your undo mistake, if you made multiple undo mistakes, you can redo <number> to redo those mistakes quickly.

'''

== Command Summary

=== Task Scheduler

* `list {d/DATE | #TAG...}`
* `add-task t/TASK-TYPE/TASK-DESCRIPTION [d/DATE] [#TAG]... [p/PRIORITY] [r/FREQ]`
* `delete-task {INDEX | t/TASK-DESCRIPTION}`
* `find-task k/KEYWORD`
* `edit-task {t/TASK-DESCRIPTION/NEW-DESCRIPTION | INDEX/NEW-DESCRIPTION}`
* `create #TAG...`
* `done-task INDEX`
* `clear-task [#TAG]... [d/DATE]`

=== Finance Tracker

* `add-paid d/PURCHASE-DESCRIPTION a/AMOUNT`
* `delete-paid INDEX`
* `add-install d/INSTALLMENT-DESCRIPTION a/AMOUNT`
* `edit-install INDEX {d/INSTALLMENT-DESCRIPTION | a/AMOUNT}`
* `delete-install INDEX`
* `set-monthly a/AMOUNT`
* `find-purchases k/KEYWORD`
* `list-finances`
* `export {csv | txt | xlsx} f/FILENAME`

=== Cca Tracker

* `add-cca n/NAME t/TYPE`
* `delete-cca n/NAME`
* `edit-cca n/NAME`
* `list-cca`
* `find-cca k/KEYWORD`
* `increment-progress INDEX`

=== Course Planner

* `add-course c/COURSECODE [g/GRADE]`
* `delete-course c/COURSECODE`
* `lookup c/COURSECODE`
* `check c/COURSECODE`
* `cap`
* `focus n/FOCUS-AREA`

=== App History

* `undo [r/NUMBER]`
* `redo [r/NUMBER]`
