= MoneyGoWhere - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-F13-3/main

By: `Team CS2103T-F13-3`      Since: `Sep 2019`      Licence: `MIT`

== Introduction

*MoneyGoWhere* is a budgeting application which helps tech-savvy finance-oriented users to store and track their personal finances. It enables users to track their spending, set their financial goals and budgets as well as export their data to a .csv file. +

*MoneyGoWhere* is optimised for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). Tech-savvy users who love to type fast will be able to complete tasks faster than traditional GUI apps.  +

What are you waiting for? Start tracking your finances now!

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/apple`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/apple t/fruit` or as `n/apple`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `add n/NAME [t/TAG]...` can be used as `t/vegetable`, `t/fruit` etc.
* Parameters can be in any order e.g. if the command specifies `add n/NAME c/COST`, `add c/COST n/NAME` is also acceptable.
====

=== Viewing help : `help`

Shows a list of available commands and their usages. +
Format: `help`

=== Flexible Date Format

Whenever a particular command requires a `DATE` field, you can choose either of the following formats.

* Formal Dates
** 1978-01-28
** 1984/04/02
** 1/02/1980
** 2/28/79
* Relaxed Dates
** The 31st of April in the year 2008
** Fri, 21 Nov 1997
** Jan 21,'97
** jan 1st
** february twenty-eight
* Relative Dates
** next thursday/ last wednesday
** today/ tomorrow/ yesterday
** next week/ next month / next year
** 3 days from now
** three weeks ago
* Date Alternatives
** next wed or thurs
** oct 3rd or 4th
* Prefixes
** day after/ the day before
** the monday after/ the monday before
** 2 fridays before/ 4 tuesdays after

=== Adding a Spending: `add`

Adds a spending to the list +
Format: `add n/NAME c/COST [t/TAG]... [r/REMARKS]`

[TIP]
A spending can have any number of tags (including 0)

Examples: +
* `add n/apple c/2.50 d/yesterday t/fruits r/Expensive apple` +
* `add n/chicken breast c/1.80 t/meat` +
* `add n/coffee c/1.20 d/today` +
* `add n/milo c/1.50 r/I love milo` +

=== Updating a Spending : `update`

Updates a spending in the specified index in the list. +
Format: `update i/INDEX [n/NAME] [c/COST] [d/DATE] [t/TAG]... [r/REMARKS]`

****
* Updates the spending at the specified `INDEX`. The index refers to the index number shown in the displayed spending list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the spending will be removed i.e adding of tags is not cumulative.
* You can remove all the spending's tags by typing `t/` without specifying any tags after it.
****

Examples:

* `update 1 c/100` +
Updates the cost of the first spending to `100`.
* `edit 2 n/chicken rice` +
Updates the name of the third spending to `chicken rice`.
* `update 5 c/500 n/flight tickets` +
Updates both the cost of the fifth spending to `500` and its name to `flight tickets`.
* `update 10 t/vegetable` +
Overwrites existing tags of the tenth spending to `vegetable`.

=== Deleting a person : `delete`

Deletes a spending in the specified index from the list. +
Format: `delete INDEX`

****
* Deletes the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Example:

* `delete 2` +
Deletes the second spending in the list based on the current results shown.

=== Listing All Spending : `list`

Displays a list of all spending. +
Format: `list [r/DATE_RANGE] [t/TAG] [c/COST_RANGE] [o/SORT_ORDER]`

Examples:

* `list` +
Displays the list of all spending sorted by date in descending order (most recent on top).
* `list r/01/09/2019-30/09/2019 t/groceries c/20-100` +
Displays the list of all spending with date range between `01/09/2019 and 30/09/2019`, tagged `groceries` and cost ranging from `20 to 100`.
* `list t/groceries o/ASC` +
Displays the list of spending tagged with `groceries` in `ascending order by date`.
* `list t/groceries o/DESC` +
Displays the list of spending tagged with `groceries` in `descending order by date`.

=== Find by Keyword `find`

Searches for spending based on a given keyword. +
Format: `find KEYWORD [MORE_KEYWORDS] [c/COST_RANGE] [r/DATE_RANGE]`

Example:

* `find book Java c/100-150 r/01/09/2019-30/09/2019` +
Returns a list of spending with `book` and `Java` keywords within the cost range `100-150` and date range within `01/09/2019-30/09/2019`.

=== Setting Monthly Budget: `budget`
Sets a monthly budget in Singapore dollars. +
Format: `budget m/MONTHLY_BUDGET` +

Example:

* `budget m/500000` +
Sets a budget of `$500,000` for this month

=== Generating Statistics: `stats`
Returns an overview of all spending such as total spending. +
Format: `stats`

=== Listing All Tags: `ltags`
Displays a list of all available tags. +
Format: `ltags`

=== Importing Data: `import`
Imports data from a CSV file specified by file path. +
Format: `import p/FILE_PATH` +

Examples: +

* `import p/data.csv`
* `import p/C:\Users\User\Documents\importfile.csv`
* `import p/~/data.csv`

=== Exporting Data: `export`
Exports data to a CSV file specified by file path. +
Format: export `p/FILE_PATH` +

Examples: +

* `export p/data.csv`
* `export p/C:\data.csv`
* `export p/~/data.csv`

=== Undoing Previous Command: `undo`
Restores the list of spending to the state before the previous undoable command was executed. +
Format: `undo` +

Examples: +

* `delete 1` +
`list` +
`undo` (reverses the delete 1 command)
* `list` +
`stats` +
`undo` (command fails as there are no undoable commands executed previously)
* `delete 1` +
`add n/textbook c/100` +
`undo` (reverses the add n/textbook c/100 command) +
`undo` (reverses the delete 1 command)

=== Redoing The Previously Undone Command: `redo`
Reverses the most recent undo command. +
Format: `redo` +

Examples:

* `delete 1` +
`undo` (reverses the delete 1 command) +
`redo` (reapplies the delete 1 command)
* `list` +
`redo` (command fails as there are no undo commands executed previously)
* `delete` 1 +
`add n/textbook c/100` +
`undo` (reverses the add n/textbook c/100 command) +
`undo` (reverses the delete 1 command) +
`redo` (reapplies the delete 1 command) +
`redo` (reapplies the add n/textbook c/100 command)

=== Graphing The Data: `graph`
Shows all spending in the form of a graph. +
Format: `graph`

=== Clear All Data: `clear`
Clears all entries from the application. +
Format: `clear`


=== Exiting the program : `exit`

Exits the program. +
Format: `exit`


== Command Summary

* *Add* `add n/NAME c/COST [d/DATE] [t/TAG]... [r/REMARKS]` +
e.g. `add n/apple c/2.50 d/yesterday t/fruits r/expensive apple`
* *Update* : `update i/INDEX [n/NAME] [c/COST] [n/NAME] [t/TAG]... [r/REMARKS]` +
e.g. `update i/123 n/apple c/2.50 d/yesterday t/fruits r/expensive apple`
* *Delete* : `delete INDEX` +
e.g. `delete 123`
* *Find* : `find KEYWORD [MORE_KEYWORDS] [c/COST_RANGE] [r/DATE_RANGE]` +
e.g. `find apple orange c/1.00-200 r/19/09/2019-20/09/2019`
* *List* : `list [r/DATE_RANGE] [t/TAG] [c/COST_RANGE] [o/SORT_ORDER]` +
e.g. `list r/01/09/2019-30/09/2019 t/groceries c/20-100 o/ASC`
* *Budget* : `budget m/MONTHLY_BUDGET` +
e.g. `goal m/1800`
* *Import data*: `import p/FILE_PATH` +
e.g. `import p/C:\Users\User\Documents\importfile.csv`
* *Export data*: `export p/FILE_PATH` +
e.g. `export p/C:\Users\User\Documents\importfile.csv`
* *Generate statistics*: `stats`
* *List all tags*: `ltags`
* *Undo*: `undo`
* *Redo*: `redo`
* *Graph*: `graph`
* *Clear*: `clear`
* *Exit*: `exit`
* *Help* : `help`
