# DeliveryMANS – User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-T12-2/main

By: `Team AY1920S1-CS2103-T12-2`   Since: `Sept 2019`  Licence: `NUS`

== Introduction

*DeliveryMANs* is a command-line application designed specifically for delivery centre administrators who are in charge of food delivery service. It encompasses a well-structured system for users to keep track and manage the entire delivery process. It facilitates food delivery service by coaliasing the delivery men, customers and restaurant menu. From auto-assigning deliverymen for deliveries when orders are made, to viewing statistics of the most popular dish of restaurants as well as customer ordering trends for further promotions, financial and business management decisions, *DeliveryMANs* is everything you need to help improve managing deliveries. With just a few simple commands, this delivery manager can help to kickstart your delivery service.

Get started with <<Quick Start>> and begin managing your deliveries today!

== Quick start

Ensure you have Java 11 or above installed on your computer.

Click https://github.com/AY1920S1-CS2103T-T12-2/main/releases[here] to download the JAR file for *DeliveryMANs*.

Open the application to begin. Refer to <<Features>> for details of each command.

// tag::features[]

[[Features]]
== Features

In *DeliveryMANs*, there are 2 types of commands: universal commands and context-specific commands.

Universal commands can be used anywhere throughout the application. You can identify universal commands by its "-" convention followed by a keyword e.g. `-help`.

Context-specific commands are commands which are only applicable for a specific context. Commands such as viewing a customer ordering history can only be accessed in the customer context.

**Command Format**

* Words in `UPPER_CASE` are parameters to be supplied by the user e.g. in `add_order c/CUSTOMER r/RESTAURANT f/FOOD q/QUANTITY`, `CUSTOMER`, `RESTAURANT`, `FOOD` and `QUANTITY` are parameters to be replaced.

> `add_order c/Donald Trump r/KFC f/Chicken Bucket q/100`

* Items with `…` after them can be used multiple times e.g. `f/FOOD...` can be used 1 or more: `f/3 Piece Chicken Meal`, `f/Pepperoni Pizza f/Char Kway Teow` etc.

* Items with `[]` are optional and can be ommitted e.g. `[t/TAG]...`

// end::features[]

// tag::universalCommand[]
=== Universal commands

These are general commands to assist you in controlling the app, which are not directly related to the customer, restaurant and delivery men.

==== Viewing help `-help`

This generates a list of commands and tips for you.

Format: `-help`

- Help with a specific context: `-help CONTEXT`

> `-help customer`

- Help with a specific context command: `-help cxt/CONTEXT cmd/COMMAND`

> `-help -cxt customer -cmd sort`

==== Switching context

This command switches to a specific context for you to enter targeted commands. The list of contexts include: customer, deliveryman and restaurant. By default, the application will be in the universal context upon startup.

===== Switching to customer context `-customer`
This command switches to the customer context for you to enter customer-specific commands.

Format: `-customer`

===== Switching to restaurant context `-restaurant`
This command switches to the restaurant context for you to enter restaurant-specific commands.

Format: `-restaurant`

===== Switching to deliveryman context `-deliveryman`
This command switches to the deliveryman context for you to enter deliveryman-specific commands.

Format: `-deliveryman`

==== Adding of orders `-add_order`
This command adds a new order to the database to be processed. The deliveryman to deliver the order will be allocated automatically based on the internal algorithms.

Format: `-add c/CUSTOMER r/RESTAURANT f/FOOD... q/QUANTITY...`

> `add_order c/Donald Trump r/KFC f/Chicken Bucket q/100`

Requirements:

* A valid customer `c/CUSTOMER`, restaurant `r/RESTAURANT` and restaurant menu item `f/FOOD` must be provided and exists currently in the database.

* The quantity of food to be delivered also be provided and be greater than 0.

==== Editing of orders `-edit_order`
This enables you to edit an order. The order to edit will have to be specified by its index when you are entering the command.

You can change:

* The customer who made the order

* The restaurant and/or food ordered

* The quantity of the food ordered

* The deliveryman to deliver the order

* The delivery status of the order

Format: `-edit_order i/INDEX [c/CUSTOMER] [r/RESTAURANT] [d/DELIVERYMAN] [f/FOOD]... [q/QUANTITY]... [completed/DELIVERY_STATUS]`

> `-edit_order i/1337 d/John Doe completed/true`

Requirements:

* The index `i/INDEX` provided must be within the order list size and be greater than or equals to 0.

* A customer `c/CUSTOMER`, restaurant `r/RESTAURANT` or restaurant menu item `f/FOOD` provided must be valid and exists currently in the database.

* Optional items with '[]' tags may be ommitted e.g. `[r/RESTAURANT]`. However at least 1 tag has to be present for the order to be edited.

* Delivery status `completed/DELIVERY_STATUS` must be true or false, if present.

==== Deleting of orders `-delete_order`
This command enables you to delete an unwanted/cancelled order in the database by its index.

Format: `-delete_order INDEX`

> `-delete_order 3`

==== Viewing order summary `-order_summary`
This command brings up the current order summary for your viewing.

Format: `-order_summary`

==== Exiting program `-exit`
This comamnd exits the program.

Format: `-exit`

// end::universalCommand[]
// tag::customerCommand[]

=== Customer commands

These are commands pertaining to customer context of *DeliveryMANs*. The screenshot below shows how the customer context will look like in *DeliveryMANs*.

 screenshot of finalised DeliveryMANs showing customer list goes here

This is a customer and its information.

 screenshot of finalised CustomerCard

==== Adding a customer: `add`

This command allows you to add a new customer to the customer list. Name and phone number are necessary to a customer. Tags in customers are optional to include. They are used to specify the customer's favourite cuisine. Multiple tags can be added to one customer.

Format: `add n/NAME p/PHONE [t/TAG]...`

> `add n/John Doe p/91234567 t/Japanese t/Noodles`

==== Editing a customer: `edit`

This command allows you to edit an existing customer in the customer list. The index of a customer needs to be provided while the information to edit are optional. For example, you can edit the customer's name without editing the phone number.

Format: `edit INDEX [n/NAME] [p/PHONE] [t/TAGS]...`

> `edit 1 n/John Hoe p/97654321 t/Indian`

==== Deleting a customer: `delete`

This command allows you to delete an existing customer in the customer list. The index of a customer needs to be provided.

Format: `delete INDEX`

> `delete 1`

==== Viewing a customer's order history: `history`

This command allows you to view a customer's order history. The index of a customer needs to be provided.

Format: `history INDEX`

> `history 1`

// end::customerCommand[]
// tag::restaurantCommand[]
=== Restaurant commands

Commands in the restaurant context

==== Listing all restaurants

Lists all available restaurants

Format: -list

==== Entering specific restaurant

Enters a specific restaurant

Format: -enter {restaurant}

Example: -enter muthu&#39;s curry

==== Adding food item

Adds a food item for a specific restaurant

Format: -add {item}

Example: -add chicken rice

==== Removing food item

Removes a food item for a specific restaurant

Format: -remove {item}

Example: -remove laksa

==== Adding rating

Adds a rating (out of 5) for the restaurant

Format: -rate {rating}

Example: -rate 5

==== ChefHat food item

Marks a food item as Chef&#39;s recommendation

Format: -chefhat {item}

Example: -chefhat nasi lemak

// end::restaurantCommand[]
// tag::deliverymenCommand[]

=== Deliverymen commands

Commands in the delivery men context

==== Adding a deliveryman: `add`

This command adds a new deliveryman to the deliverymen database. Name and phone number are necessary to a deliveryman.

Format: `add n/NAME p/PHONE [t/TAG]...`

> `add n/John Doe p/91234567  `

==== Editing a deliveryman: `edit`

This command edits an existing deliveryman in the deliverymen database.
Format: `edit INDEX [n/NAME] [p/PHONE] [t/TAGS]...`

> `edit 1 n/John Hoe p/97654321 t/Indian`

==== Deleting a deliveryman: `delete`

This command deletes an existing deliveryman in the deliverymen database. The index of a deliveryman needs to be provided.

Format: `delete INDEX`

> `delete 1`

==== Listing available deliverymen

This command lists all available deliverymen

Format: `lista`

==== Entering a specific deliveryman

This command shows a deliveryman's basic info

Format: `list NAME`

Example: `list Stanley Tay`

==== Assigning order to a deliveryman

This command assigns an order to an available deliveryman

Format: `assn NAME #ORDERINDEX`

Example: `assn Stanley Tay #12`

====  Obtains a list of deliverymen eligible for pay rise

This command displays a list of deliverymen who met the pre-determined requirements for a pay rise.

Format: `payrise`

Example: `payrise`


== Command summary

**Command:** format

* Universal commands
- View help: `-help`
- View order summary: `-order_summary`
- Add order: `-add c/CUSTOMER r/RESTAURANT f/FOOD... q/QUANTITY...`
- Edit order: `-edit_order i/INDEX [c/CUSTOMER] [r/RESTAURANT] [d/DELIVERYMAN] [f/FOOD]... [q/QUANTITY]... [completed/DELIVERY_STATUS]`
- Delete order: `-delete_order INDEX`
- Switch to restaurant context: `-restaurant`
- Switch to customer context: `-customer`
- Switch to deliverymen context: `-deliverymen`
- Exit application: `-exit`

* Customer commands
- Add a customer: `add n/NAME p/PHONE [t/TAG]...`
- Edit a customer: `edit INDEX [n/NAME] [p/PHONE] [t/TAGS]...`
- Delete a customer: `delete INDEX`
- View a customer's order history: `history INDEX`

* Restaurant commands
- List restaurants: -list
- Enter specific restaurant: -enter {restaurant}
- Add food item: -add {item}
- Remove food item: -remove {item}
- Add Rating from Customer: -rate {rating}
- ChefHat Food Item: -chefhat {item}

* Deliverymen commands
- Add a deliveryman: `add n/NAME p/PHONE`
- Delete a deliveryman: `delete INDEX`
- Edit a deliveryman: `edit INDEX [n/NAME] [p/PHONE]`
- List available deliverymen: `lista`
- List specific deliveryman info: `list NAME`
- Assign order to deliveryman: `assn NAME #orderINDEX`
- List deliverymen eligible for pay rise: `payrise`
