= Scheduler - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `Team AY1920S1-CS2103-F09-1`      Since: `Oct 2019`      Licence: `MIT`

== Introduction
Scheduler is an app that can automate the scheduling of interviews for secretaries in NUS CCAs. It is optimised for
people who **prefer typing in a Command Line Interface (CLI)** to quickly access the functionalities of an app. +

Click on <<Quick Start, Quick Start>> to get started!

== Quick Start

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user, e.g. in `add interviewee name:"NAME" slot:"SLOT"`,
`NAME` and `slot` are parameters that need to be provided by the user, e.g. "John Doe" and "20/09/2019 1800 - 20/09/2019 21:00".

====

=== Scheduling `generate`
==== Generating timetable of all available time slots
Generate the timetable of all available interview time slots based on the availability of interviewers. +
Format: `generate timetable`

==== Generating full interview schedule
Schedule and allocate interviewees to the available interview slots based on the availability of interviewees and
the timetable of all available interview time slots. +
Format: `generate schedule` +

**Note:** This command requires the timetable of all available time slots to be generated first!

=== Recording of additional statuses: `record` `[Coming in v2.0]`
==== Recording of interviewee’s attendance
Bring up the window to record the attendance of interviewees. You can navigate through the table in the window (GUI)
using the directions key to record the attendance of the interviewees. Hit Enter at the target cell to record the
attendance. +
Format: `record attendance`

====  Recording of interview result
Bring up the window to record the interview result. The way to record the result is the same as 2.12.1. +
Format: `record result`

==== Ranking of interviewees
Bring up the window to rank the interviewees. The way to record the result is the same as 2.12.1. +
Format: `record rank`

== FAQ

== Command Summary
.Table Command Summary
|===
|Command Description |Command Syntax

|Help
|`help` +

|Import existing availabilities
|`import interviewer PATH_TO_FILE` +
  `import interviewee PATH_TO_FILE`

|Add interviewers/interviewees
|`add interviewer name:"NAME" slot:SLOT...` +
 `add interviewee name:"NAME" slot:SLOT...`

|Display interview schedule
|`display` +

|Get interview schedule for interviewer/interviewee
|`get NAME` +

|Delete interviewer/interviewee
|`delete interviewer NAME` +
 `delete interviewee NAME`

|Tag interview slot
|`tag TAG_NAME` +

|Filter
|`filter tag TAG_NAME` +

|Schedule
|`generate timetable` +
 `generate schedule`

|Export
|`export` +

|Email blast
|`email timeslots` +
 `email results` +
 `email status` +

|Record
|`record attendance` +
 `record result` +
 `record rank` +

|===
