
= Teacher’s Notebook - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103-T14-1/main
By: 'Team CS2103-T14-1'     Since: 'Sep 2019'

== Introduction

Teacher’s Notebook is for teachers who prefer to make use of an application to keep track of the deliverables, tasks and students’ information. It is optimized for teachers who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). If you are a teacher who wants to manage your students and your tasks efficiently, and can type fast, Teacher’s Notebook can get your work done much faster than traditional applications! Jump to Section 2, “Quick Start” to get started! Enjoy!

== Quick Start

.  Ensure you have Java 11 or above installed in your Computer.
.  Download the latest teachersnotebook.jar {repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your Teacher’s Notebook.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Type in the commands and press enter to execute them. Refer to Section 3: Features for more details on the commands.

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format* +
* Words in UPPER_CASE are the parameters supplied by the user e.g. in `addclass c/CLASS`, CLASS is a parameter which can be used as `addclass c/4C`. +
* Items in square brackets are optional e.g. `n/NAME [m/MEDICAL_CONDITIONS]` can be used as `n/John Doe m/Sinus` or `n/John Doe`. +
* Items with … after them can be used multiple times including zero times e.g. `[t/TAGS]...` can be used as (i.e. 0 times), `t/Math REP`, `t/MATH REP t/Bully` etc. +
* Parameters can be in any order e.g. if the command specifies `n/NAME a/ADDRESS`, `a/ADDRESS, n/NAME` is also acceptable
====

// tag::classes[]
=== Classes
// end::classes[]

// tag::lessons[]
=== Lessons
// end::lessons[]

// tag::students[]
=== Students
Students are contained within each class. There are several fields in each student as shown below:

* Name - Prefix: n/
** Names must be alphanumerical, and cannot be empty.
* Email - Prefix: e/
** Emails must be in the format alphanumeric@example.com e.g. amanda@example.com, ilovebubbletea@gmail.com
* Phone - Prefix: p/
** Phone numbers must be at least 3 digits, and must only contain digits.
* Address - Prefix: a/
** Address must be alphanumerical, and cannot be empty.
* Parent Phone - Prefix: pp/
** Parent phone numbers must be at least 3 digits, and must only contain digits.
* Medical Conditions - Prefix: m/
** Medical conditions must be alphanumerical. This is an optional field.
* Tags - Prefix: t/
** Tags must be alphanumerical. This is an optional field that can be used multiple times.
* DisplayPicture - Prefix: none
** Display pictures must be in PNG file format. A default display picture is set for each student.

====
*CONDITIONS* +
* Students in the class must not have the same name. Other fields can be the same as we expect that there might be
siblings sharing the same fields (e.g. share the same phone and email, stay in the same house etc.)
* Phone and parent phone must not be the same. We expect that the students now have a phone.
====

==== Adding: addstudent

Adds a student to the student list of the current class. +
Format: `addstudent n/NAME e/EMAIL p/PHONE a/ADDRESS pp/PARENT_PHONE [m/MEDICAL_CONDITIONS]... [t/TAG]...`

Examples:

* `addstudent n/John Doe e/johndoe@gmail.com p/81930042 a/Jurong East Avenue 3 Blk 639 #12-02 pp/84295512 m/Sinus`
* `addstudent n/Jane Doe e/janedoe@hotmail.com p/91823051 a/Tampinese Avenue 5 Blk 772 #02-84 pp/99811241 t/PE Rep t/Naughty`

==== Editing: editstudent

Edits a student at the specified index in the student list of the current class. +
Format: `editstudent STUDENT_INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [pp/PARENT_PHONE] [m/MEDICAL_CONDITIONS], [t/TAG]...`

Examples:

* `editstudent 2 p/98510293 e/jonathan@example.com`
* `editstudent 4 n/Xavier Lim`

[NOTE]
The index provided must be valid and at least one field must be edited.

==== Deleting: deletestudent

Deletes a student at the specified index in the student list of the current class. +
Format: `deletestudent STUDENT_INDEX`

Example:

* `deletestudent 5`

[NOTE]
The index provided must be valid.

==== Uploading: upload

Uploads a PNG file to set as the display picture of the student at the specified index in the student list of the current class. +
This will prompt the user to select a PNG file from their computer to set as the new display picture of the student. +
Format: `upload STUDENT_INDEX`

Example:

* `upload 3`

[NOTE]
The index provided must be valid and the directory of the image uploaded is assumed to not change.

==== Finding: findstudent

Find students whose name matches a given keyword in the current classroom. +
Format: `findstudent STUDENT_NAME`

Examples:

* `findstudent John Doe`
* `findstudent Jane Doe`

// end::students[]


// tag::assignments[]
=== Assignments
// end::assignments[]


== Additional Features Coming in V2.0

//tag::reminders_for_assignments[]

=== Reminders for Assignments [coming in v2.0]

Assignments can be added to the reminders for the notebook, where users will be alerted when the deadline is up for assignments. +
Once the deadline is over, the assignments will be removed from the reminder panel, but will remain in the assignment list for future reference. +
This will give teachers a clearer idea of what they need to do in the reminder panel beyond just lessons.

//end::reminders_for_assignments[]

//tag::statistics[]

=== Statistics for Assignments [coming in v2.0]

Calculates the statistics for the chosen assignment for each class - Average, Median, 25th / 75th percentile etc. +
This will give teachers a clearer idea of how each class as a whole is doing. +
Format: `getstats ASSIGNMENT_INDEX`

//end::statistics[]

== FAQ

[qanda]
How do I transfer my data from the current notebook to another computer?::
    Copy the teachernotebook.json file from your current computer, and paste it in a /data folder in your other computer's directory where teachernotebook.jar is at.

== Command Summary

* Add Student: `addstudent n/NAME e/EMAIL p/PHONE a/ADDRESS pp/PARENT_PHONE [m/MEDICAL_CONDITIONS]... [t/TAG]...` +
e.g. `addstudent n/John Doe e/johndoe@gmail.com p/81930042 a/Jurong East Avenue 3 Blk 639 #12-02 pp/84295512 m/Sinus`
* Edit Student: `editstudent STUDENT_INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [pp/PARENT_PHONE] [m/MEDICAL_CONDITIONS], [t/TAG]...` +
e.g. `editstudent 2 p/98510293`
* Delete Student: `deletestudent STUDENT_INDEX` +
e.g. `deletestudent 3`
* Upload: `upload STUDENT_INDEX` +
e.g. `upload 2`
* Find Student: `findstudent STUDENT_NAME` +
e.g. `findstudent John Doe`

