= Mark - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

Mark is for those who prefer to use a *desktop app for managing
bookmarks.* More importantly, it is optimized for those who prefer to
work with a *Command Line Interface (CLI)* while still having the
benefits of a Graphical User Interface (GUI). If you can type fast, Mark
can get your bookmark organisation and note-taking done faster than
traditional GUI apps. Interested? Jump to
link:#quick-start[[.underline]#Section 2, “Quick Start”#] to get
started. Enjoy!

== Quick Start

[arabic]
. Ensure you have Java 11 or above installed in your Computer.
. Download the latest mark.jar here.
. Copy the file to the folder you want to use as the home folder for your Bookmark Manager.
. Double-click the file to start the app. The GUI should appear in a few
seconds.
 . Type the command in the command box and press Enter to execute it.

* e.g. typing help and pressing Enter will open the help window.
. Some example commands you can try:

* *list* : lists all bookmarks
 * *add u/git-scm.com/book/en/v2 n/Pro Git f/Tutorials* : adds a bookmark
named Pro Git to the Bookmark Manager.
 * *delete 3* : deletes the 3rd bookmark shown in the current list
 * *exit* : exits the app

. Refer to <<Features>> for details
of each command.

[[Features]]
== Features

*Command Format*

* Words in UPPER_CASE are the parameters to be supplied by the user e.g.
in add u/URL, URL is a parameter which can be used as add
u/luminus.nus.edu.sg.
 * Items in square brackets are optional e.g u/URL [t/TAG] can be used as
u/luminus.nus.edu.sg t/NUS or as u/luminus.nus.edu.sg.
 ** Default values for optional items are specified with an = symbol. E.g.
u/URL [t/TAG=CS2103T]the default value for the tag is CS2103T if not
specified.
 * Items with …​ after them can be used multiple times including zero times
e.g. [t/TAG]…​ can be used as (i.e. 0 times), t/module, t/module
t/read-later etc.
 * Parameters can be in any order e.g. if the command specifies n/NAME
u/URL, u/URL n/NAME is also acceptable.

=== Viewing help: `help`

Format: `help`

=== Adding a bookmark: `add`

Adds a bookmark to the bookmark manager.

Format: `add u/URL n/NAME [f/FOLDER] [t/TAG]…​`

****
* A bookmark can have any number of tags (including 0).
* Use the keyword `this` in place of URL to bookmark the current page,
e.g.
****

Examples:
* `add u/this n/Homepage` +
Bookmarks the current place and names it Homepage.
Only valid if a web-page is currently being viewed.
* `add u/nus-cs2103-ay1920s1.github.io n/Module Website f/CS2103T`
* `add u/www.youtube.com/watch?v=9AMcN-wkspU n/IntelliJ Tips and Tricks t/video t/watch-later`

=== Listing all bookmarks: `list`

Shows a list of all bookmarks in the bookmark manager.

Format: `list`

=== Editing a bookmark: `edit`

Edits an existing bookmark in the bookmark manager.

Format: `edit INDEX [u/URL] [n/NAME] [f/FOLDER] [t/TAG]…​ [r/REMARK]`

****
* Edits the bookmark at the specified `INDEX`. The index refers to the index
number shown in the displayed bookmark list. The index must be a
positive integer 1, 2, 3, …​
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the bookmark will be removed i.e
adding of tags is not cumulative.
* You can remove all the bookmark’s tags by typing `t/` without specifying
any tags after it.
****

Examples:

* `edit 1 n/CS2103T Website f/AY1920-S1` +
Edits the name and folder of the 1st bookmark to be CS2103T Website and AY1920-S1 respectively.

* `edit 2 t/` +
Clears all existing tags from the 2nd bookmark.

=== Locating bookmarks by name, URL, or tag: `find`

Finds bookmarks that contain any of the given keywords in their name or
URL, or that are tagged with the given tag(s).

Format: `find [KEYWORD]... [t/TAG]...`

****
* At least one keyword or tag must be provided.
* Keyword search is case insensitive. e.g video will match Video.
* The order of the keywords does not matter. e.g. `Website Video` will match `Video Website`.
* Keywords are only searched in the URL and name.
* Words will be partially matched e.g. `Video` will match `Videos`.
* Bookmarks matching at least one search criteria will be returned (i.e. OR search).
****

Examples:

* `find Website Video t/Fun will` +
Returns CS2103T Website, Video Streaming, and all bookmarks tagged with Fun.

* `find Luminus` +
Returns luminus website and GER1000 LumiNUS

* `find CS2103T CS2101 CS2105` +
Returns any bookmark with CS2103T, CS2101, or CS2105 in its name or in its url

* `find GitHub t/CS2103T` +
Returns any bookmark with the tag CS2103T or that contains github in either name or URL.

=== Deleting a bookmark: `delete`

Deletes the specified bookmark from the bookmark manager.

Format: `delete INDEX`

****
* Deletes the bookmark at the specified INDEX.
* The index refers to the index number shown in the displayed bookmark list.
* The index must be a positive integer 1, 2, 3, …​
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd bookmark in the bookmark manager.

* `find luminus` +
`delete 1` +
Deletes the 1st bookmark in the results of the find command.

=== Opening a bookmark: `goto`

Opens the specified version of the bookmark from the bookmark manager.

Fomat: *goto INDEX [v/VERSION]*

* If the flag v/ is not present, go to the online version
 * v/ with no VERSION: Go to the most current version

Examples:

* Goto 1

=== Opening a bookmark from a reminder: `goto reminder`

Opens the specified version of the bookmark from the bookmark manager.

Fomat: *goto reminder INDEX*

* INDEX is the index of the reminder as viewed on the dashboard

Examples:

* *goto reminder 1* +
If reminder 1 points to bookmark 5, this command is equivalent to *goto
5*. I.e. opens bookmark 5.

=== Clearing all entries: `clear`

Clears all entries from the bookmark manager.

Format: *clear*

=== Undoing previous command: `undo`

Restores the list to the state before the previous undoable command was
executed.

Undoable commands include commands that modify the bookmark list or
reminders (add, edit, delete, clear, reminder, reminder edit, reminder
delete etc).

Format: *undo*

=== Redoing the previously undone command: `redo`

Reverses the most recent ‘undo’ command.

Format: *redo*

=== Exiting the program: `exit`

Exits the program.

Format: *exit*

=== Saving the data

Bookmark manager data are saved in the hard disk automatically after any
command that changes the data.

There is no need to save manually. However, it is possible to save with
a different file name or to save specific bookmarks only, by using the
command export.

=== Exporting bookmarks: `export`

Exports the displayed list of bookmarks to the hard disk.

Format: *export [FILENAME]*

* {blank}
+
FILENAME should not include the file extension. E.g. myBookmarks and not
myBookmarks.json
 * If no file name is specified, the default file name is the name of the
first bookmark and “AndOtherBookmarks”. E.g.
CS2103TWebsiteAndOtherBookmarks
 * FILENAME is overwritten if it already exists.
 * Bookmarks are exported to the folder with relative path data/bookmarks/.

Examples:

* *list* +
*export myBookmarks* +
Exports all bookmarks in the bookmark manager to a file named
myBookmarks.json.

* *find luminus* +
(result of find command: cs2101Luminus, cs2103TLuminus, cs2105Luminus) +
*export* +
Exports the results of the find command to a file named
cs2101LuminusAndOtherBookmarks.json.

* *find t/favorite* +
 *export favorites* +
Exports all bookmarks tagged with favorite to a file named
favorites.json

=== Importing bookmarks: `import`

Imports bookmarks from files on the hard disk.

Format: *import FILENAME [MORE_FILENAMES]...*

* FILENAME should not include the file extension. E.g. myBookmarks and not
myBookmarks.json
 * FILENAME is case sensitive.
 * FILENAME should be a file stored in the folder data/bookmarks/ (relative
to the application directory).
 * The file corresponding to FILENAME should have a valid format, identical
to the JSON files produced by *export*.

Examples:

* *import myBookmarks* +
Imports bookmarks from the file
[applicationHome]/data/bookmarks/myBookmarks.json

* *import myBookmarks nusBookmarks youtubeBookmarks* +
Imports bookmarks from the files myBookmarks.json, nusBookmarks.json,
and youtubeBookmarks.json.

=== Creating automatic tags: `autotag`

Creates a tag that will be automatically applied to bookmarks that match
the given conditions.

Format: *autotag NAME [u/PARTIAL_URL] [nu/NOT_PARTIAL_URL] [f/FOLDER]
[nf/NOT_FOLDER]... [t/TAG]... [nt/NOT_TAG]...*

* If an autotag with name NAME already exists, the user is prompted
whether the conditions for NAME should be overwritten.
 * An autotag is applied when a bookmark matches all of its conditions (u/,
nu/, f/, nf/, t/, and nt/). Hence, if conditions contradict each other,
this autotag will not be automatically applied to any bookmark. E.g.
u/github.com/bookmarker nu/github.com/bookmarker
 * PARTIAL_URL and NOT_PARTIAL_URL can be any part of a URL. E.g. youtube,
.nus.edu.sg, or github.com/bookmarker.
 * NOT_PARTIAL_URL, NOT_FOLDER, and NOT_TAG are partial URLs, folders, or
tags that bookmarks to be tagged should _not_ match.
 * Bookmarks can also be tagged with NAME using regular tags, i.e. if an
autotag YouTube matches bookmarks with URL youtube.com, it is possible
for the user to tag bookmarks with URLs not containing youtube.com with
the tag YouTube.
 * If none of the optional fields are specified, the given tag will not be
automatically applied to any bookmark. However, NAME can still be used
as a regular tag.

Examples:

* *autotag Miscellaneous f/NUS nt/academic nt/admin* +
 Creates an autotag named Miscellaneous that tags all bookmarks in the
folder _NUS_ but not tagged as _academic_ or _admin_.

* *autotag Luminus u/luminus* +
 Creates an autotag that adds the tag Luminus to all bookmarks with URLs
containing _luminus_.

=== Saving offline Readable copies of bookmarked website: `cache`

Saves the bookmarked website locally for offline viewing.

Format: `cache INDEX [s/SAVE_NOW] [u/AUTO_UPDATE] [d/VERSION]`

****
* `INDEX` is the bookmark that you want to save a local copy of
* `SHOULD_AUTOUPDATE` (default false) if true, it will check daily for any
updates. Any old versions will be archived and users will be able to see
the different versions and delete them / name them
* If `AUTO_UPDATE` is missing, will not auto update.
* `VERSION` is the version number to be deleted.
****

Examples:

* `cache 1 s/true u/true` +
Saves the bookmark at index 1 locally, and updates it daily.

* `cache 1` +
Show the list of cached copies.

* `cache 1 d/2` +
Deletes the cached version at the second index.

* `cache 1 u/true` +
Manually save a new copy of the site.

=== Making annotations on offline copy of bookmarked website: `annotate`

Makes annotations on locally saved, offline version of the bookmarked
website. You can have various options, including:

[arabic]
. Highlight paragraph on local copy and attach a note to said paragraph. +
When a paragraph is chosen to be highlighted, it is optional to add a
supplementary note (Notes can be added to justify the highlight or as
content-relevant notes for future reference to bookmark).

. Modify and update notes of paragraph by changing note content. +
If a highlight is removed but had a note attached to it, the note will
be moved to a “lost notes” section of the copy.

. Delete notes or clear annotations +
Notes of a certain paragraph, “lost notes” section, or entire document
can be wiped out. If you choose to clear annotations, all notes and
highlights will be removed and the offline copy will be reverted to
clean slate.

Format: *annotate INDEX p/P_NUM [n/NOTES] [h/HIGHLIGHT_COLOUR=yellow]*

* INDEX is the bookmark that you want to annotate offline version of
 * DELETE is either *all*, *lost* or *one*. If *one*, then a/*P_NUM* must
be present.
 * P_NUM is the number of the paragraph to be marked or deleted.
 * NOTES is the content of notes to add. If this field is included
alongside the delete field, then the notes of the paragraph will be
removed.
 * HCOLOUR is either *orange*, *pink*, *green* or *yellow*. This selects
the highlight colour to mark out paragraphs. If no colour is specified,
yellow is the default colour. If this field is included alongside the
delete field, then highlight of the paragraph will be removed.

Format: *annotate edit P_NUM [p/NEW_P_NUM] [n/NOTES]
[h/HIGHLIGHT_COLOUR]*

* If HIGHLIGHT_COLOUR is specified with a lost note index, nothing
happens.

Examples:

* Annotate edit 1 p/2 - Move notes from para 1 to para 2
 * Annotate edit 1 n/new notes - Edit the notes for para 1
 * Annotate edit 1 h/yellow - Change the highlight color for para 1
 * Annotate edit L1 p/1 - Move lost notes L1 to para 1


Format: *annotate delete P_NUM *

Deletes notes associated with the specified paragraphs.

Examples:

* *Annotate delete 1*
 * *Annotate delete L1*

Examples:

* *annotate 1 a/2 n/summary of paragraph h/yellow* +
In offline copy of bookmark 1, highlights paragraph 2 yellow and
attaches note with content “summary of paragraph” to the paragraph.

* *annotate 1 a/2 h/pink* +
In offline copy of bookmark 1, overwrites any existing highlight and
highlights paragraph 2 with pink. Any notes attached remain attached.

* *annotate 1 a/2 n/change note content* +
In offline copy of bookmark 1, changes note attached to paragraph 2 to
note with content “change note content”.

* *annotate 1 d/one a/2 n/ h/* +
In offline copy of bookmark 1, delete all annotations on paragraph 2.
Highlights and notes are removed altogether for paragraph 2.

* *annotate 1 d/one a/2 n/* +
In offline copy of bookmark 1, removes the note on paragraph 2 but
leaves the highlight on paragraph 2.

* *annotate 1 d/one a/2 h/* +
In offline copy of bookmark 1, removes the highlight on paragraph 2.
Notes on paragraph 2 are moved to “lost notes” section.

* *annotate 1 d/lost* +
In offline copy of bookmark 1, deletes all notes in the “lost notes”
section.

* *annotate 1 d/all* +
Removes all annotations in the offline copy of bookmark 1.

=== Viewing annotated bookmarked website: `offline`

Shows offline copy of a selected bookmark. The offline view tab will
show the latest offline copy with annotations by default.

Format: *offline INDEX [v/VERSION = current]*

* INDEX is the bookmark that you want to view notes of
 * VERSION is the version of the cached version to show. Default is the
current version

Examples:

* *offline 1* +
Shows annotated offline copy of bookmark 1.

* *offline 1 v/2* +
Shows the 2nd version of offline copy of bookmark 1. If it is annotated,
then annotations are shown as well.

=== Adding reminder: `reminder`

Adds a reminder to visit a bookmark. You can set the deadline (when you
want the reminder remind you) and the start time is optional. The app
will inform you at that time before the start time and the deadline.

Format: *reminder INDEX t/TIME_DATE [n/NOTE=Open]*

* INDEX is the index of the bookmark that you want to add with a reminder.
 * TIME_DATE follows HHMM dd/mm/yyyy format.

Examples:

* *reminder 1 2359 02/07/2019* +
Adds a reminder for bookmark 1, and set the deadline at 02/07/2019. The
reminder will remind you at 23:59 on 2nd July, 2019.

* *reminder 1 2359 02/07/2019 1200 29/06/2019* +
Adds a reminder for bookmark 1, and set the start time at 12:00 of
29/06/2019, the deadline at 23:59 of 02/07/2019. The reminder will
remind you at these two timings.

=== Editing reminder: `reminder edit`

Format: *reminder edit INDEX [t/TIME_DATE] [n/NOTE]*

=== Deleting reminder: `reminder delete`

Deletes the the specified reminder.

Format: *reminder delete INDEX*

=== Sorting bookmarks: `sort`

Sorts the displayed bookmarks according to different criteria (name,
order added) and displays them as a list.

Format: *sort [CRITERIA]*

* CRITERIA is the field you use to sort. Acceptable values of CRITERIA
are: *name* and *default*.
 * CRITERIA is case insensitive, e.g. both URL and url are acceptable
criteria.

Examples:

* *sort name* +
Lists all the bookmarks based on name/alphabetical order.

* *sort default* +
Sort all the bookmarks based on the order they were added.

=== Expanding folder hierarchy: `expand`

Expands the folder hierarchy by the specified number of levels.

Format: *expand [LEVEL]*

* LEVEL should be an integer. If it is more than zero, folder hierarchy
will expand by LEVEL number of levels. If LEVEL is less than zero,
folder hierarchy will collapse by the given number of levels. If LEVEL
is zero, nothing happens.
 * Current level of display + LEVEL must be positive and less than or equal
to the maximum number of levels
 * If LEVEL is negative, the folder hierarchy will be collapsed by the
specified number of levels
 * If LEVEL is not specified, expand to the maximum number of levels.

Examples

* *expand 3*

=== Collapsing folder hierarchy: `collapse`

Collapses the folder hierarchy by the specified number of levels.

Format: *collapse [LEVEL]*

* LEVEL should be an integer. If it is more than zero, folder hierarchy
will collapse by LEVEL number of levels. If LEVEL is less than zero,
folder hierarchy will expand by the given number of levels. If LEVEL is
zero, nothing happens.
 * Current level of display + LEVEL must be positive and less than or equal
to the maximum number of levels of the folder hierarchy
 * If LEVEL is negative, the folder hierarchy will be collapsed by the
specified number of levels
 * If LEVEL is not specified, collapse to show only one level of folders.

Examples

* *collapse 1*

=== Switching link:#faq[[.underline]#tabs#]: `tab`

Switches the current app view to the tab that corresponds to the given
index.

Format: *tab INDEX*

* INDEX is 1, 2 or 3, which correspond to the
link:#faq[[.underline]#Dashboard#], Online, and Offline tabs
respectively.

Examples

* *tab 1* +
Goes to the Dashboard tab

* *tab 2* +
Goes to the Online tab which is a web view

* *tab 3* +
Goes to the Offline tab which shows the offline copy of bookmarks

== FAQ

*What are Tabs?*

 Different user displays. There are three tabs: dashboard, online view
(web browser), and offline view (caches and notes).

*What is the Dashboard?*

 The default tab in view when the application starts. The dashboard
contains a help section (command summary), favorite tags, current
reminders, and a view of the folder hierarchy for bookmarks.

<more coming soon>

== Command Summary

<coming soon>
