= Budget Buddy - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W13-4/main

By: `CS2103T W13-4`

== Introduction

Budget Buddy is for computing students who prefer to use a desktop app to manage their expenses.
More importantly, Budget Buddy is *optimized for those who prefer to work with a Command Line Interface* (CLI)
while still having the benefits of a Graphical User Interface (GUI).
If you can type fast, Budget Buddy can get your expense management tasks done faster than traditional GUI apps.
Furthermore, computing students can take full advantage of Budget Buddy by adding their own functions through custom JavaScript files.

== Quick Start

Nothing to see here.

[[Features]]
== Features

====
*Command Format*

* Words within `<>` brackets are parameters to be supplied by the user.
* Parameters within `[]` brackets are optional and can be omitted.
* `|` indicates that a choice must be made between two parameters.
* `...` indicates a variable number (at least 1) of the specified parameter.
====

=== Viewing help : `help`

Displays help. If `command` is specified, view detailed help for that command.

Format: `help [<command]>`

== FAQ

== Command Summary
