= PalPay - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2103T-W12-3/main

By: `AY1920S1-CS2103T-W12-3`      Since: `SEPT 2019`      Licence: `MIT`

== Introduction

PalPay is for those who *prefer to use a desktop app for managing personal finances*.
More importantly, PalPay is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).
If you can type fast, PalPay can get your finance management tasks done faster than traditional GUI apps.
This User Guide as written for the users of PalPay as an introductory document of the application.
You are strongly encouraged to read this document before using the application top enjoy the full functionality of the application.
Ready to start your journey to financial freedom?
Jump to the <<Quick Start>> to get started.
Enjoy!

== Quick Start

. Ensure you have Java `11` or above installed in your Computer.
. Download the latest `palpay.jar` link:{repoURL}/releases[here].
. Copy the file to the folder you want to use as the home folder for your finance manager.
. Double-click the file to start the app.
The GUI should appear within a few seconds.
+
+
. Type your command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
. Some example commands you can try:

* *`view`* : shows statistics of your current finances
* **`in`**`100 n/mother c/allowance` : adds an income to your personal finance of *100* dollars under the catergory *mother* and the item type *allowance*.
* **`out`**`3 n/pie c/food` : adds an expenditure to your personal finance of *3* dollars under the category *food* and the item type *pie*.
* *`exit`* : exits the app

. Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `in AMOUNT n/ITEM`, `AMOUNT` and 'ITEM' are parameters which can be used as `in 300 n/concert`.
* Items in square brackets are optional e.g `n/ITEM [c/CATEGORY]` can be used as `n/coke t/drinks` or as `n/coke`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[n/NAME]...` can be used as `{nbsp}` (i.e. 0 times), `n/Amy`, `n/Amy n/Betty` etc.
* Parameters can be in any order e.g. if the command specifies `AMOUNT n/ITEM`, `n/ITEM AMOUNT` is also acceptable.
====

=== Splitting a Bill with Friends : `split`

Split a bill with your friends +
Format: `split [f/FLAG] $/AMOUNT n/NAME1 [n/NAME2]... [s/SHARE]`


* `[FLAG]` defines how the bill is split:
** `dutch` user is included in the split (default)
** `loan` user is not included in the split
* `[SHARE]` defines portion of bill to be paid by each person
*** number of rations must match number of names for `loan` splits
*** number of rations must be 1 more than number of names for `dutch` splits

Examples:

* `split $/1000 n/Amy n/Betty n/Catherine n/Dan`
* `split $/100 f/loan n/Albert n/Bernard n/Clement s/2 s/1 s/7`

=== Settling Up with a Friend : `pay`

Sends money to 1 friend +
Format: `pay $/AMOUNT n/NAME1`

Examples:

* `pay $/2.5 n/Albert`

=== Logging Expense : `out`

Adds an expenditure of your personal finance +
Format: `out $/AMOUNT n/ITEM d/DATE [c/CATEGORY]`

****
* `AMOUNT` input accepts the value of the expenditure
* `ITEM` input accepts the description of the expenditure
* `DATE` accepts the date of this transaction
* `CATEGORY` accepts the CATEGORY for this expenditure
* `in` will update the Bank Account with a net **negative** amount (e.g. `out n/milk $/2 d/10102019` will **decrease** Bank Acount balance by $2)
****

Examples:
* `out $/100 n/milk c/food`
* `out $/29 n/taxi c/transport`
* `out $/12 n/burger`

=== Logging Income : `in`

Adds an income of your personal finance +
Format: `in $/AMOUNT n/ITEM d/DATE [c/CATEGORY]`

****
* `AMOUNT` input accepts the value of the income
* `ITEM` input accepts the description of the income
* `DATE` input accepts accepts the date of this transaction
* `CATEGORY` input accepts the CATEGORY for this income
* `in` updates the Bank Account with a net positive amount (e.g. `in n/work $/1000 d/10102019` will **increase** Bank Acount balance by $1000)
****

Examples:

* `in $/100 n/errand c/work`
* `in $/200 n/mom c/family`
* `in $/120 n/work`

=== Setting a Budget : `set`

Sets a budget for a particular category until a certain date +
You cannot have duplicate budgets (bugets with the same `AMOUNT` and `DATE` and `CATEGORY`).
If you attempt to do so, you will receive an erorr message: `This budget already exists in the bank account`. +
Format: `set $/AMOUNT d/DATE c/CATEGORY`

****
* `AMOUNT` input accepts the new budget amount to be set.
* `DATE` input accepts the deadline to be set.
* `CATEGORY` accepts the CATEGORY for the budget
****

Examples:

* `set $/100 c/shopping`
* `set $/50 c/food`

=== Display View : `view`

Shows all possible views (spending, projection and loan) +
Format: `view KEYWORD [TIMEFRAME]`

****
* `KEYWORD` input only accepts `spending`, `projection` and `loan`.
* `[TIMEFRAME]` input defines the number of days prior to this command for the called projection. (default=30)
* `view spending` shows a breakdown of your categories of spending
* `view projection` shows a personal finance projection for a given period of time
* `view loan` shows the amount of money owed and lent to others
****

Examples:

* `view loan`
* `view projection`
* `view spending`

// tag::delete[]
=== Deleting Finance : `delete`

Deletes the specified Transaction or Budget from the finance manager. +
Format: `delete TYPE+INDEX`

****
* `INDEX` refers to the target item number. (Items are sorted starting from the **latest** input added)
* `TYPE` only accepts `t` (Transaction) or `b` (Budget). (e.g. `delete --b1` refers to deleting an *Budget* of index 1)
* `TYPE+INDEX` requires the TYPE and INDEX to be placed in sequential order (e.g. `delete --b 1` or `delete --1` or `delete --1b` will not work)
* You can only delete an existing transaction or budget. Nothing will be deleted if the transaction or budget with `INDEX` does not exists.
* Example: `delete --t1` will delete the first transaction from the list of transactions.
****

Examples:

* `delete t1`
* `delete b3`

=== Updating Finance : `update`

Updates the specified income or expenditure from the finance manager. +
Format: `update TYPE+INDEX [$/AMOUNT] [d/date] [n/ITEM] [c/CATEGORY]`


****
* `INDEX` refers to the target item number. (Items are sorted starting from the **latest** input added)
* `TYPE` only accepts `t` (Transaction) or `b` (Budget). (e.g. `update --b1 ...` refers to updating a *Budget* of index 1)
* `TYPE+INDEX` requires the TYPE and INDEX to be placed in sequential order (e.g. `update --b 1 ..` or `update --1 ..` or `update --1b ..` will not work)
* `update` requires at least one field to be updated but also allows more than one field to be updated (e.g. `update t1 $/20 d/10102019 n/milk` and `update t1 $/10` will both be accepted but `update t1` will not be accepted)
* You can only update an existing transaction or budget. Nothing will be updated if the transaction or budget with `INDEX` does not exists.
* Example: `update --t1 $/3000 d/10102019` will update the first transaction from the list of transactions by changing it's *Amount* to $1000 and *Date* to 10/10/2019.
****

Examples:

* `update t1 $/20 n/coke c/drinks d/12122019`
* `update b2 $/300`
* `update t4 $/30 d/12102019`

=== Sorting Transactions : `sort`

Sorts all transactions with given `PREDICATE` +
Format: `sort PREDICATE`

****
* You are only able to `sort` by `date` and `amount` in v1.3.
****

Examples:

* `sort amount`
* `sort date`

=== Filtering Transactions : `filter`

Shows all relevant transactions with given `CATEGORY` +
Format: `filter CATEGORY...`

****
* `CATEGORY` input accepts `CATEGORY` you have used in In or Out transactions before.
****

Examples:

* `filter food`
* `filter transport allowance`

=== Projecting Balance : `project`

Projects future balance based on past In or Out transactions +
Format: `project d/DATE`

****
* `DATE` only accepts date in format DDMMYYYY.
****

Examples:

* `project d/10012019`

=== Redoing the Last Command : `redo`

Redo the last command +
Format: `redo`

=== Undoing the Last Command : `undo`

Undo the last command. +
Format: `undo`

=== Clearing All Entries : `clear`

Clears all entries from your Bank Account. +
Format: `clear`

=== Listing All Entries : `list`

Lists all entries from your Bank Account. +
Format: `list`

=== Viewing Help : `help`

Opens help page for the list of usable commands +
Format: `help`

=== Exiting the Application : `exit`

Exits the program. +
Format: `exit`

=== Saving the Data

PalPay data is saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Bank Account folder.

== Command Summary

* *Split* `split [f/FLAG] $/AMOUNT n/NAME1 [n/NAME2]... [s/SHARE]` +
Example: `split $/100 f/loan n/Albert n/Bernard n/Clement s/2 s/1 s/7`
* *Out* : `out $/AMOUNT n/ITEM d/DATE [c/CATEGORY]` +
Example: `out $/20 n/coke d/19112019 c/drink c/lunch`
* *In* `in $/AMOUNT n/ITEM d/DATE [c/CATEGORY]` +
Example: `in $/100 n/allowance d/11112019 c/income`
* *Set* : `set $/AMOUNT d/DATE c/CATEGORY` +
Example: `set $/100 d/10102019 c/food`
* *View* : `view TAB` +
Example: `view transaction`
* *Delete* : `delete TYPE+INDEX` +
Example: `delete t1 $/200 n/waiter c/work`
* *Update* : `update TYPE+INDEX [$/AMOUNT] [d/date] [n/ITEM] [c/CATEGORY]` +
Example: `update b1 $/100 c/transport`
* *Sort* : `sort PREDICATE` +
Example: `sort amount`
* *Filter* : `filter CATEGORY...` +
Example: `filter food`
* *Project* : `project DURATION` +
Example: `project 10`
* *Redo* : `redo`
* *Undo* : `undo`
* *Clear* : `clear`
* *List* : `list`
* *Help* : `help`
* *Exit* : `exit`
