= MyProject User Guide:

== Introduction:

MyProject (MP) is for team leaders who prefer to use a desktop app for managing their projects.
MP is optimized for those who prefer to work with a Command Line Interface (CLI)
while still having the benefits of a Graphical User Interface (GUI).
With MP it is a one-stop app to store and manage your projects and their relevant information,
this is especially useful if you are always managing multiple projects across different teams.
Interested? Jump to the Section 2, “QuickStart” to get started. Enjoy!

== Quick Start:

. Ensure you have Java 11 or above installed in your Computer.
. Download the latest myproject.jar here.
. Copy the file to the folder you want to use as the home folder for your Address Book.
. Type the command in the command box and press Enter to execute it. e.g. typing help and pressing Enter will open the help window.
. Some example commands you can try:
.. list : lists all contacts
.. exit : exits the app
. Refer to Section 3, “Features” for details of each command.

== Features

=== Viewing help: `help`

Shows a list of commands. +
Format: `help` +

=== Listing Information

==== List your contacts: `list`

Shows you the list of contacts you have currently along with their respective information. +
Format: `list`

=== Checkout a project: `checkout`

Checkout a project to begin working on the project immediately.

    Commands which require a project to be checked out first will be tagged using [Checkout].

Format: `checkout INDEX`

`INDEX` is the number used to identify the project in the project list.

Example:

* `checkout 1`

=== Adding Items

This section deals with adding information to the application.

==== 1. Add a project: `addProject`

Adds a new project into your list of projects. +
Format: `addProject n/PROJECT_TITLE s/PROJECT_DESCRIPTION`

Example:

* `addProject n/CS2103 project s/Software engineering project`

==== 2. Add a person: `add`

Adds a person to your contacts.
When you add a person to your contacts, it will automatically change to displaying your list of contacts. +
Format: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...`

[TIP]
A person can have any number of tags (including 0)

Examples:

* `add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01`
* `add n/Betsy Crowe t/friend e/betsycrowe@example.com a/Newgate Prison p/1234567 t/criminal`


==== 3. Add a member to your project

Adding a member can be done in 2 ways, you can either add a new person to your contacts and to your current project,
or you can simply add an existing person from your contacts to your current project.

==== 3.1 Add a new member: `addMember` [Checkout]

This command is similar to adding a person to your contacts shown previously, except that you have to be
checked out into a project. +
Format: `addMember n/NAME [p/PHONE_NUMBER] [e/EMAIL] [a/address] [t/tag]...`

[TIP]
Adding a member only requires his/her name!

However it will be good to add as much information as possible.

Example:

* `addMember n/John Doe a/John street, block 123, #01-01`

* `addMember n/Betsy Crowe e/betsycrowe@example.com t/friend t/criminal`


==== 3.2 Add from your contacts: `addFromContacts` [Checkout]


This command helps to add a person you already saved in your contacts into your project, reducing the need
to type his information all over again. All you need to do is enter the index he is listed at. +
Format: `addFromContacts INDEX`


`INDEX` is the number which the person is listed at, and it should be a positive integer eg. 1, 2, 3, ....


Example:

* `addFromContacts 1`

==== 4. Add a timetable: `addTimetable`

Need to keep track of your team members' schedule? Use this command to record down their timetable easily!

[TIP]
Timetable added can be used to generate avaiable meeting timeslots using the command `generate`

Format:

`addTimetable INDEX [n/NUSMODS_SHARE_URL] [f/FILEPATH_TO_TIMETABLE]`

Example:

* `addTimetable 3 f//home/john/Desktop/aliceTimetable.txt` +
Add Alice's timetable to Alice, who has index 3 in the list of persons.

[NOTE]
File should be formatted as a newline separated list of time ranges, e.g: +
MONDAY 1000 MONDAY 1200 +
MONDAY 1400 MONDAY 1600 +
TUESDAY 1100 TUESDAY 1500

* `addTimetable 2 n/https://nusmods.com/timetable/sem-1/share?CS2100=LAB:05,TUT:02,LEC:1&CS2101=&CS2103T=LEC:G13&CS2105=TUT:03,LEC:1&CS3241=TUT:05,LEC:1&CS3243=TUT:01,LEC:1&GEQ1000=TUT:D27` +
Add timetable to the person with index 2 on the list of persons.


==== 5. Add a task: `addTask` [Checkout]


Adds an unchecked task to the list of tasks of your current working project. +
Format: `addTask s/DESCRIPTION c/dd/MM/yyyy HHmm`

Example:

* `addTask s/Finish GUI c/06/10/2019 1600`

[TIP]
Whenever you add a time with the prefix c/, the format should be dd/MM/yyyy HHmm,
whereby the year must be between 1900 to 2100 and the time must be between 0000 to 2359.

[CAUTION]
MyProject does not check for invalid days such as 30th February so do ensure you input
your dates correctly!

==== 6. Add a project meeting: `addProjectMeeting`

Adds a new project meeting to the current working project.  +
Format: `Format: addProjectMeeting [c/ dd/MM/yyyy HHmm] [s/MEETING_DESCRIPTION]`

Example:

* `addProjectMeeting c/29/09/2019 1900 s/milestone discussion`

=== Editing

This section deals with editing information shown on the application.


==== 1. Edit a person : `edit`


Edits an existing person in the address book. +
Format: `edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]...`

****
* Edits the person at the specified `INDEX`. The index refers to the index number shown in the displayed person list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the person will be removed i.e adding of tags is not cumulative.
* You can remove all the person's tags by typing `t/` without specifying any tags after it.
****

Examples:

* `edit 1 p/91234567 e/johndoe@example.com` +
Edits the phone number and email address of the 1st person to be `91234567` and `johndoe@example.com` respectively.
* `edit 2 n/Betsy Crower t/` +
Edits the name of the 2nd person to be `Betsy Crower` and clears all existing tags.

==== 2. Edit a task : `editTask`

Edits an existing task in the task list of the current project. +
Format: `editTask INDEX [s/DESCRIPTION] [c/dd/MM/yyyy HHmm] [d/]` +

****
* Edits the task at the specified `INDEX`. The index refers to the index number shown in the displayed task list. The index *must be a positive integer* 1, 2, 3, ...
* If `d/` is not provided in the input, the task will automatically be unchecked.
* Existing values will be updated to the input values.
****

Examples:

* `editTask 1 c/05/05/2019 1600 d/` +
Edits the date and time to `05/05/2019 1600` and checks the task.
* `editTask 2` +
Unchecks the task.

=== Deleting

This section deals with removing information within the application.


==== 1. Deleting a person: `delete`


Deletes the specified person from your contacts. +
Format: `delete INDEX`

****
* Deletes the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd person in the address book.
* `find Betsy` +
`delete 1` +
Deletes the 1st person in the results of the `find` command.

==== 2. Remove a member: `removeMember` [Checkout]


Removes the specified person from the current working project. +
Format: `removeMember NAME`

`NAME` refers to the full name of the member displayed in the project.

Example:

* `removeMember John Doe`


==== 3. Delete a task: `deleteTask` [Checkout]


Deletes the specified task from the current working project.  +
Format: `deleteTask INDEX`

`INDEX` is the number used to identify this task in the task list.

Example:

* `deleteTask 1`


==== 4. Delete a meeting: `deleteMeeting` [Checkout]


Deletes the specified meeting from the current working project.  +
Format: `deleteMeeting INDEX`

`INDEX` is the number used to identify this meeting in the meeting list.

Example:

* `deleteMeeting 1`

=== Finding


==== 1. Find a person by name: `find`


Finds persons whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Persons matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `find John` +
Returns `john` and `John Doe`
* `find Betsy Tim John` +
Returns any person having names `Betsy`, `Tim`, or `John`

=== Meeting
For every project, you can add meetings to it, and below you will be able to find more useful commands
associated with this functionality.

==== 1. Generate meeting timing: `generate` [Checkout]

Generates possible meeting timeslots for which everyone is available.
=======
Need to decide on a meeting timing, but having trouble finding a time where all members are free? This command can help suggest meeting timings!

* Prerequisite: Timetables have been assigned to the members with the command `addTimetable`

[NOTE]
`generate` would still work even if some members do not have timetable assigned to them. Make sure that you have done `addTimetable` for each of the members  in the project.

Format: `generate d/DURATION [r/TIMERANGE]`

Example:

* `generate d/2 r/MONDAY 0900 MONDAY 1800` +
Generates all possible meeting timeslots that lasts at least 2 hours, within the time frame of Monday 9am to Monday 6pm.

=======


=== Email
Tired of switching between applications? We got you covered, below you will find some commands which support sending
emails right here within the application.

Do keep in mind that only the user Account in our current version is only compatible with Gmail Account and please ensure that the Access to less secure app in the security setting is enabled before signing in! 

==== 1. Sign in to your account: `signIn`
Signs in to the your email account. +
Format: `signIn ac/ACCOUNT_EMAIL_ADDRESS pa/PASSWORD`

==== 2. Log out from your account: `logOut`
Logs out from your email account. +
Format: `logOut`

==== 3. Send an email: `sendMail`
Sends an email to the specified person in your contacts. +
Format: `sendMail r/RECIPIENT_OF_EMAIL su/SUBJECT me/MESSAGE_BODY`

==== 4. Broadcast an email: `broadcastMail`
Sends an email to all members in the current working project. +
Format: `broadcastMail su/SUBJECT me/MESSAGE_BODY`

==== 2. Send reminder: `sendReminder`

Sends a reminder to all members of the upcoming Meeting and Task that is due from the current working project. +
Format: `sendReminder`d/DURATION

`DURATION` is the number of days from the current time within which the Tasks are due and The Meetings are held.

Example:

* `sendReminder d/3`

=== Sorting

The following section provides a set of commands which help with sorting the information inside the
application.

****
All commands in this section follow this set of index/order pairing, where applicable:

. Alphabetical order
. Increasing order of time
. Whether tasks are done
. Whether tasks are done and then by increasing order of time
. Increasing price
****

==== 1. Sort tasks: `sortTask`

Sorts the tasks in the task list of the current working project based on given specification. +
Format: `sortTask INDEX`

`INDEX` in this case refers to which type of sorting you want to do. In this case, only integers between 1 and 4 are applicable.(Refer to the highlighted section above)

Example:

* `sortTask 4` (Sorts the tasks whether they are done and then by increasing date/time)

==== 2. Sort spending: `sortSpending`

Sorts the spending in the budget list of the current working project based on given specification. +
Format: `sortSpending INDEX`

`INDEX` in this case refers to which type of sorting you want to do. In this case, only integers 1, 2 and 5 are applicable.(Refer to the highlighted section above)

Example:

* `sortSpending 5` (Sorts the spending by increasing prices)

=== Finance
Isn't it always a pain to keep track of all the finances and checking with the treasurer everytime? You can do it easily with MyProject!

==== Add a budget
Add multiple budgets available to the current project. +
Format: `addBudget [b/NAME_OF_BUDGET AMOUNT NAME_OF_BUDGET AMOUNT...]`

==== Add an expense
Whenever an expenditure is made under a budget, add it to record. +
Format: `addExpense [INDEX_OF_BUDGET] [s/DESCRIPTION] [ex/AMOUNT SPEND] [c/dd/MM/yyyy HHmm]`

==== View budgets
See the summary of all budget which shows how much money is left with that budget and where is this budget used. +
Format: `listBudget`
