@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class HiddenOutside #FFFFFF

namespace Model {
Class Model
Model --> "1" FinancialTracker
namespace Expense {
Class Expense
Expense *-down-> Amount
Expense *-down-> Description
Expense *-down-> Type
Expense *-down-> Country
Expense *-down-> Date
Expense *-down-> Time
}
FinancialTracker -left-> "*" ExpenseList
FinancialTracker .left.> ObservableList
ExpenseList -down---> "*" Model.Expense.Expense
ExpenseList -left-> "1" Model.ObservableList
}

@enduml
