@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include <office/Users/administrator>
!include ../style.puml

Package " "<<Rectangle>>{
    Class GUI UI_COLOR
    Class TextUI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class FinancialTracker MODEL_COLOR_T1
    Class Commons LOGIC_COLOR_T2
    Class "Log Center" as Logs UI_COLOR_T1
    Class "Test Driver\nJunit Test" as Test MODEL_COLOR_T4
}

Class "<$user>\nUser" as User MODEL_COLOR_T2
Class "<$administrator>\nDeveloper" as Developer MODEL_COLOR_T2
Class "<$documents>\nJson File" as File UI_COLOR_T1

GUI -right-> Logic
Model -up-> GUI

Logic -down-> Model
Logic --> Storage

TextUI -up-> GUI
TextUI .up.> Commons
Logic .up.> Commons
Storage .up.> Commons

Logs -right- Commons
Storage .right.>File
User -right-> GUI
User <--> TextUI
Test -up-> TextUI
Developer -up[hidden]-> User
Developer <-right-> Test

Model -down-> FinancialTracker

@enduml
