@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package CcaTracker {
    Class CcaTracker
    Class CcaList
    Class Cca
    Class CcaName
    Class CcaType
    Class EquipmentList
    Class Equipment
    Class CcaProgress
    Class CcaCurrentProgress
    Class CcaMilestoneList
    Class CcaMilestone
}

CcaTracker *--> "1" CcaList
CcaList o--> "*" Cca
Cca *--> "1" CcaName
Cca *--> "1" CcaType
Cca *--> "1" EquipmentList
EquipmentList o--> "*" Equipment
Cca *--> "1" CcaProgress
CcaProgress *--> "1" CcaCurrentProgress
CcaProgress *--> "1" CcaMilestoneList
CcaMilestoneList *--> "*" CcaMilestone

@enduml
