@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package AddressBook <<Rectangle>> {
    Class AddressBook
    Interface ReadOnlyAddressBook <<interface>>
    Class UniquePersonList
    Class Person
    Class Name
    Class Phone
    Class Address
    Class Email
    Class Tag
}

AddressBook ..|> ReadOnlyAddressBook
AddressBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Person
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Address
Person *--> "*" Tag
Person *--> "1" Email
@enduml
