@startuml
!include ../../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
left to right direction

interface Predicate {
	+ boolean test(Plan plan)
	+ boolean equals(Object other)
}

package PlanSearchRule {

    class FindPlanDescriptor
    class PlanNameContainsKeywordsPredicate
    class PlanDescriptionContainsKeywordsPredicate
    class TimeRangePredicate

    class TimeRange
    class Keyword

    note right of Keyword
    An abstraction used in
    PlanNameContainsKeywordsPredicate and
    PlanDescriptionContainsKeywordsPredicate
    to make sure every keyword is a valid String.
    end note
}

Predicate <|.. PlanNameContainsKeywordsPredicate
Predicate <|.. PlanDescriptionContainsKeywordsPredicate
Predicate <|.. TimeRangePredicate

PlanNameContainsKeywordsPredicate "1" <--* FindPlanDescriptor
PlanDescriptionContainsKeywordsPredicate "1" <--* FindPlanDescriptor
TimeRangePredicate "1" <--* FindPlanDescriptor
TimeRange *--> "1" LocalDate : startDate
TimeRange *--> "1" LocalDate : endDate


TimeRange "1" <-down- TimeRangePredicate

@enduml
