@startuml
!include ../../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
left to right direction

interface Predicate {
	+ boolean test(Problem problem)
	+ boolean equals(Object other)
}

package ProblemSearchRule {

    class Name

    class ProblemSearchRule
    class UniqueFindRuleList


    class FindProblemDescriptor
    class NameContainsKeywordsPredicate
    class AuthorMatchesKeywordPredicate
    class DescriptionContainsKeywordsPredicate
    class SourceMatchesKeywordPredicate
    class DifficultyIsInRangePredicate
    class TagIncludesKeywordsPredicate

    class Keyword
    note left of Keyword
    An abstraction used
    in xxxPredicate to make sure
    every keyword is a valid String.
    end note
}

UniqueFindRuleList o--> "*" ProblemSearchRule

Predicate <|.. NameContainsKeywordsPredicate
Predicate <|.. AuthorMatchesKeywordPredicate
Predicate <|.. DescriptionContainsKeywordsPredicate
Predicate <|.. SourceMatchesKeywordPredicate
Predicate <|.. DifficultyIsInRangePredicate
Predicate <|.. TagIncludesKeywordsPredicate

NameContainsKeywordsPredicate "1" <--* FindProblemDescriptor
AuthorMatchesKeywordPredicate "1" <--* FindProblemDescriptor
DescriptionContainsKeywordsPredicate "1" <--* FindProblemDescriptor
SourceMatchesKeywordPredicate "1" <--* FindProblemDescriptor
DifficultyIsInRangePredicate "1" <--* FindProblemDescriptor
TagIncludesKeywordsPredicate "1" <--* FindProblemDescriptor

ProblemSearchRule -u|> FindProblemDescriptor
ProblemSearchRule *--u> "1" Name

@enduml
